### ISSUE TITLE
AccessibilityServiceAlreadyRegisteredError

### ISSUE THREAD

**Issue by huan1936** [openatx/uiautomator2#1013]
- 手机型号 一加7Pro
- uiautomator2的版本号(`pip show uiautomator2`) 3.2.0

服务已启动的情况下无法初始化
不知道为啥 出现服务没有关闭 导致现在无法初始化

```python
Traceback (most recent call last):
  File "D:\pyCode\other\ttts.py", line 3, in <module>
    d = u2.connect()
  File "D:\pyCode\other\venv\lib\site-packages\uiautomator2\__init__.py", line 1073, in connect
    return connect_usb(serial)
  File "D:\pyCode\other\venv\lib\site-packages\uiautomator2\__init__.py", line 1089, in connect_usb
    return Device(serial)
  File "D:\pyCode\other\venv\lib\site-packages\uiautomator2\__init__.py", line 69, in __init__
    BasicUiautomatorServer.__init__(self, self._dev)
  File "D:\pyCode\other\venv\lib\site-packages\uiautomator2\core.py", line 169, in __init__
    self.start_uiautomator()
  File "D:\pyCode\other\venv\lib\site-packages\uiautomator2\core.py", line 194, in start_uiautomator
    self._wait_ready()
  File "D:\pyCode\other\venv\lib\site-packages\uiautomator2\core.py", line 218, in _wait_ready
    self._wait_app_process_ready(launch_timeout)
  File "D:\pyCode\other\venv\lib\site-packages\uiautomator2\core.py", line 238, in _wait_app_process_ready
    raise AccessibilityServiceAlreadyRegisteredError(output)
uiautomator2.exceptions.AccessibilityServiceAlreadyRegisteredError: [server] INFO: [UiAutomator2Server] Starting Server
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@4fe2ce7already registered!
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2381)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:739)
	at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:456)
	at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:106)
	at android.app.UiAutomation.connect(UiAutomation.java:243)
	at java.lang.reflect.Method.invoke(Native Method)
	at mirror.RefMethod.call(RefMethod.java:63)
	at uiautomator.InstrumentShellWrapper.getUiAutomation(InstrumentShellWrapper.java:97)
	at androidx.test.uiautomator.UiDevice$Api24Impl.getUiAutomationWithRetry(UiDevice.java:1545)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1468)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:115)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:296)
	at com.wetest.uia2.Main.runServer(Main.java:40)
	at com.wetest.uia2.Main.main(Main.java:29)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:438)
java.lang.IllegalStateException: UiAutomation not connected, UiAutomation@ddd9c79[id=-1, flags=0]
	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1239)
	at android.app.UiAutomation.getServiceInfo(UiAutomation.java:497)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1482)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:115)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:296)
	at com.wetest.uia2.Main.runServer(Main.java:40)
	at com.wetest.uia2.Main.main(Main.java:29)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:438)

```

**Comment by codeskyblue** [comment]
是否有别的服务也在运行，比如appium？

**Comment by huan1936** [comment]
没有别的服务  就是uiautomator2的服务已经启动了
我试了 重新拔插一下设备让uiautomator2的服务连接断开后  就能重新完成初始化了

**Comment by shaping520** [comment]
用ps -ef命令查看到新版本使用的是sh -c CLASSPATH=/data/local/tmp/u2.jar app_process / com.wetest.uia2.Main 服务进程，实在不行就在初始化前先检查下这个进程是否存在。
@codeskyblue 大佬，这个u2.jar包的项目是否开源了呢？

**Comment by huan1936** [comment]
> 是否有别的服务也在运行，比如appium？

就是服务已运行
![image](https://github.com/user-attachments/assets/6282d0eb-b201-43a6-974d-51be4c7fd721)

**Comment by Yan0789** [comment]
> 是否有别的服务也在运行，比如appium？

![微信截图_20240812171744](https://github.com/user-attachments/assets/5812800f-2aea-4150-9eb1-444a9afb142b)
大神这是什么情况呢

**Comment by luck-zhou** [comment]
uiautomator2的服务先启动就会报这个，@codeskyblue 这个问题还有在新版本规避了吗

**Comment by tired0408** [comment]
我的是3.2.6版本，经常出现这个问题，每次都要通过重启模拟器解决，有没有啥解决办法

**Comment by luck-zhou** [comment]
我的是3.2.6版本，也会遇到这个问题，中途跑着跑着会出现，有没有什么规避的

**Comment by luck-zhou** [comment]
我的是3.2.6版本，也会遇到这个问题，中途跑着跑着会出现，有没有什么规避的 @codeskyblue
