### ISSUE TITLE
使用python在真机运行，突然Uiautomator started failed.

### ISSUE THREAD

**Issue by MrSmailWhitle** [openatx/uiautomator2#102]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```
Your code or log here
```
> "C:\Python27\python.exe"  "E:\pythonscript\PUF\Untitled 1.py" 
C:\Python27\lib\site-packages\uiautomator2\__init__.py:354: RuntimeWarning: uiautomator2 is not reponding, restart uiautomator2 automatically
  stacklevel=1)
Traceback (most recent call last):
  File "E:\pythonscript\PUF\Untitled 1.py", line 4, in <module>
    print d.info
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 913, in __getattr__
    return getattr(self._default_session, attr)
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 1349, in info
    return self.jsonrpc.deviceInfo()
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 342, in __call__
    params, http_timeout)
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 356, in jsonrpc_retry_call
    self.healthcheck(unlock=False)
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 505, in healthcheck
    raise RuntimeError("Uiautomator started failed.")
RuntimeError: Uiautomator started failed.

## Versions (版本)
通过`pip show uiautomator2`可以获取到

## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快

- 手机型号?华为nova青春版
- 错误日志?
- 出错的代码片段?

## Additional Details （其他信息）

**Comment by codeskyblue** [comment]
因为系统资源不足也可能会引起uiautomator被杀掉

**Comment by MrSmailWhitle** [comment]
有什么解决方法没有

**Comment by MrSmailWhitle** [comment]
我把uiautomator2库和apk全部删除，重新安装了，然后就好了。但是不能每次都重装吧。那就太不友好了

**Comment by codeskyblue** [comment]
调用  `d.healthcheck()` 函数也可以恢复
