### ISSUE TITLE
文件缺失

### ISSUE THREAD

**Issue by csdaa** [openatx/uiautomator2#1025]
uiautomator2 总是要下载文件，但是这几个文件的地址已经失效了，作者能否提供一下文件，感谢

![image](https://github.com/user-attachments/assets/237f81d8-5dc7-4088-8c5d-22b473216644)

异常日志
```shell

python -m uiautomator2 init
[I 240813 17:40:06 init:156] uiautomator2 version: 2.16.23
[I 240813 17:40:06 init:373] Install minicap, minitouch
[D 240813 17:40:06 init:62] Download https://tool.appetizer.io/openatx/stf-binaries/raw/0.3.0/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch
[D 240813 17:40:08 init:111] download error from mirror(HTTPSConnectionPool(host='tool.appetizer.io', port=443): Max retries exceeded with url: /openatx/stf-binaries/raw/0.3.0/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03A8B610>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))), use origin source
[D 240813 17:40:08 init:62] Download https://github.com/openatx/stf-binaries/raw/0.3.0/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch
[W 240813 17:40:10 api:40] HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /openatx/stf-binaries/raw/0.3.0/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03A9C1F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极 拒绝，无法连接。'))), retrying in 0 seconds...
[D 240813 17:40:10 init:62] Download https://tool.appetizer.io/openatx/stf-binaries/raw/0.3.0/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch
[D 240813 17:40:12 init:111] download error from mirror(HTTPSConnectionPool(host='tool.appetizer.io', port=443): Max retries exceeded with url: /openatx/stf-binaries/raw/0.3.0/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03A9C650>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))), use origin source
[D 240813 17:40:12 init:62] Download https://github.com/openatx/stf-binaries/raw/0.3.0/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch
Traceback (most recent call last):
  File "D:\python\lib\site-packages\urllib3\connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "D:\python\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "D:\python\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:
```

site-packages/uiautomator2 /init.py
![image](https://github.com/user-attachments/assets/2a8abd5e-e19e-4ecf-b83b-4c243e9eb9dd)

**Comment by codeskyblue** [comment]
已移除
