### ISSUE TITLE
set_text中的内容长度超过140个字符后，报网络超时

### ISSUE THREAD

**Issue by peidachang** [openatx/uiautomator2#1037]
手机型号:HONOR 50 android:14
uiautomator2的版本号:3.2.4

具体代码：

    import uiautomator2 as u2
    d = u2.connect('192.168.2.101:39863')
    d.debug = True
    message = ""
    d(resourceId="com.tencent.mm:id/bkk").click()
    d.set_input_ime(True)

    d(resourceId="com.tencent.mm:id/bkk").set_text(message, 30)

错误信息：

Traceback (most recent call last):
  File "/Users/zhuchang/pythoncode/mp/main.py", line 26, in <module>
    print_hi('PyCharm')
  File "/Users/zhuchang/pythoncode/mp/main.py", line 21, in print_hi
    d(resourceId="com.tencent.mm:id/bkk").set_text(message, 30)
  File "/usr/local/lib/python3.10/site-packages/uiautomator2/_selector.py", line 350, in set_text
    self.must_wait(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/uiautomator2/_selector.py", line 343, in must_wait
    raise UiObjectNotFoundError({'code': -32002, 'data': str(self.selector), 'method': 'wait'})
uiautomator2.exceptions.UiObjectNotFoundError: {'code': -32002, 'data': "Selector [resourceId='com.tencent.mm:id/bkk']", 'method': 'wait'}

**Comment by codeskyblue** [comment]
- Google Nexus 4测试未发现异常
