### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory \uiautomator2\\assets\\u2.jar

### ISSUE THREAD

**Issue by Congdanh1997** [openatx/uiautomator2#1038]
Traceback (most recent call last):
  File "C:\Users\Danh\AppData\Local\Temp\ONEFIL~3\Auto_Pee_XPro.py", line 1123, in run
  File "C:\Users\Danh\AppData\Local\Temp\ONEFIL~3\uiautomator2\__init__.py", line 1096, in connect
  File "C:\Users\Danh\AppData\Local\Temp\ONEFIL~3\uiautomator2\__init__.py", line 1112, in connect_usb
  File "C:\Users\Danh\AppData\Local\Temp\ONEFIL~3\uiautomator2\__init__.py", line 69, in __init__
  File "C:\Users\Danh\AppData\Local\Temp\ONEFIL~3\uiautomator2\core.py", line 170, in __init__
  File "C:\Users\Danh\AppData\Local\Temp\ONEFIL~3\uiautomator2\core.py", line 189, in start_uiautomator
  File "C:\Users\Danh\AppData\Local\Temp\ONEFIL~3\uiautomator2\core.py", line 201, in _setup_jar
  File "C:\Users\Danh\AppData\Local\Temp\ONEFIL~3\uiautomator2\core.py", line 210, in _check_device_file_hash
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Danh\\AppData\\Local\\Temp\\ONEFIL~3\\uiautomator2\\assets\\u2.jar'
Can you help me to fix this

**Comment by codeskyblue** [comment]
cd assets/; bash sync.sh
