### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.0.3', port=7912): Max retries exceeded with url: /shell (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000039A4710>: Failed to establish a new connection: [Errno 10061] ',))

### ISSUE THREAD

**Issue by MrSmailWhitle** [openatx/uiautomator2#104]
> "C:\Python27\python.exe"  "E:\pythonscript\PUF\ycTest\TestRegister.py" 
[+++]automator connect ok
Traceback (most recent call last):
  File "E:\pythonscript\PUF\ycTest\TestRegister.py", line 3, in <module>
    from register import register
  File "E:\pythonscript\PUF\ycTest\register.py", line 4, in <module>
    from appdriver import pc_phone
  File "E:\pythonscript\PUF\ycTest\appdriver.py", line 99, in <module>
    pp=pc_phone()
  File "E:\pythonscript\PUF\ycTest\appdriver.py", line 19, in __init__
    self.d.app_start(self.app)
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 596, in app_start
    self.adb_shell('monkey', '-p', pkg_name, '-c', 'android.intent.category.LAUNCHER', '1')
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 552, in adb_shell
    ret = self._reqsess.post(self.path2url('/shell'), data={'command': cmdline})
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 210, in request
    resp = super(TimeoutRequestsSession, self).request(method, url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.0.3', port=7912): Max retries exceeded with url: /shell (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000039A4710>: Failed to establish a new connection: [Errno 10061] ',))
怎么解决这个问题呢

**Comment by codeskyblue** [comment]
看文档上的说明，需要init一下才行。
