### ISSUE TITLE
执行python3 -m uiautomator2 init后，模拟器没有出现atx

### ISSUE THREAD

**Issue by AEPzhang** [openatx/uiautomator2#1044]
![屏幕截图 2024-10-09 200703](https://github.com/user-attachments/assets/f61afc84-09c0-4a63-a63f-664427cf1fb0)
![image](https://github.com/user-attachments/assets/563976f9-ee34-4a52-846e-6dcb5a7dbcc5)

**Comment by HQ-random** [comment]
同类问题，真机（一加5T），uiautomator2版本 3.2.5；
![image](https://github.com/user-attachments/assets/a5436616-4824-46f1-903e-4cd3c92fa432)
在终端使用命令：pip uninstall uiautomator2后没有自动安装ATX app，且提示：adbutils.errors.AdbError: unknown host service，此时的adbutils 2.8.0，报错完整日志如下：
[D 2024-10-09 21:12:36,555 core:213 pid:15096] file u2.jar md5: eb05754fdf0e7c69137d42e7db0d2d5e
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\PythonProject\AdbAndroid\.venv\Lib\site-packages\uiautomator2\__main__.py", line 256, in <module>
    main()
  File "D:\PythonProject\AdbAndroid\.venv\Lib\site-packages\uiautomator2\__main__.py", line 248, in main
    actions[args.subparser](args)
  File "D:\PythonProject\AdbAndroid\.venv\Lib\site-packages\uiautomator2\__main__.py", line 29, in cmd_init
    d = u2.connect(dev)
        ^^^^^^^^^^^^^^^
  File "D:\PythonProject\AdbAndroid\.venv\Lib\site-packages\uiautomator2\__init__.py", line 1107, in connect
    return connect_usb(serial)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProject\AdbAndroid\.venv\Lib\site-packages\uiautomator2\__init__.py", line 1123, in connect_usb
    return Device(serial)
           ^^^^^^^^^^^^^^
  File "D:\PythonProject\AdbAndroid\.venv\Lib\site-packages\uiautomator2\__init__.py", line 69, in __init__
    BasicUiautomatorServer.__init__(self, self._dev)
  File "D:\PythonProject\AdbAndroid\.venv\Lib\site-packages\uiautomator2\core.py", line 170, in __init__
    self.start_uiautomator()
  File "D:\PythonProject\AdbAndroid\.venv\Lib\site-packages\uiautomator2\core.py", line 189, in start_uiautomator
    self._setup_jar()
  File "D:\PythonProject\AdbAndroid\.venv\Lib\site-packages\uiautomator2\core.py", line 201, in _setup_jar
    if self._check_device_file_hash(jar_path, target_path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProject\AdbAndroid\.venv\Lib\site-packages\uiautomator2\core.py", line 214, in _check_device_file_hash
    output = self._dev.shell(["toybox", "md5sum", remote_file])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProject\AdbAndroid\.venv\Lib\site-packages\adbutils\_device.py", line 191, in shell
    c = self.open_transport(timeout=timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProject\AdbAndroid\.venv\Lib\site-packages\adbutils\_device.py", line 89, in open_transport
    c.check_okay()
  File "D:\PythonProject\AdbAndroid\.venv\Lib\site-packages\adbutils\_adb.py", line 151, in check_okay
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError: unknown host service
手机、数据线的应该没问题，使用appium后，可以自动安装appium settings的app，这里有个问题不知道对你的修复是否存在启发，启动pc端appium server GUI后，再运行代码：
import uiautomator2 as u2
d = u2.connect()
print(d.info)
此时可以运行成功，但也没有安装ATX app

**Comment by nedsion** [comment]
with newest version lib that ATX app will not show on your screen, that still work

**Comment by jayeliu** [comment]
readme提示了不再安装atx apk了，而是通过u2.jar

**Comment by AEPzhang** [comment]
> readme提示了不再安装ATX apk了，而是通过u2.jar

非常感谢您的回答,这对我非常有帮助!

**Comment by AEPzhang** [comment]
> 非常感谢您的回答,这对我非常有帮助!

非常感谢您的回答,这对我非常有帮助!
