### ISSUE TITLE
OutOfMemoryError 堆栈溢出

### ISSUE THREAD

**Issue by linlaoye** [openatx/uiautomator2#1052]
我使用python写了7条线程，一条负责疯狂随机点击滑动坐标（模拟monkey操作），剩下6条负责查询某个元素是否存在，存在则点击元素（用来点击一些顽固的关闭按钮），6条线程有上线程锁，有序竞争。跑了1天左右就会出现OutOfMemoryError

- 手机型号：Android13 三星A54 
- uiautomator2的版本号：3.2.3
- 手机截图：无
- 相关日志：

Unknown RPC error: -32001 java.lang.OutOfMemoryError
({'mask': 2097152, 'childOrSibling': [], 'childOrSiblingSelector': [], 'resourceId': 'com.adamrocker.android.input.simeji:id/symbol_foot_back'},)

java.lang.OutOfMemoryError: Failed to allocate a 3145712 byte allocation with 1181776 free bytes and 1154KB until OOM,
target footprint 268435456, growth limit 268435456
    at dalvik.system.VMRuntime.newUnpaddedArray(Native Method)
    at com.android.internal.util.ArrayUtils.newUnpaddedLongArray(ArrayUtils.java:75)
    at com.android.internal.util.GrowingArrayUtils.insert(GrowingArrayUtils.java:180)
    at android.util.LongSparseArray.put(LongSparseArray.java:269)
    at android.view.accessibility.AccessibilityInteractionClient.getInstanceForThread(AccessibilityInteractionClient.java:195)
    at android.view.accessibility.AccessibilityInteractionClient.getInstance(AccessibilityInteractionClient.java:179)
    at android.app.UiAutomation.getServiceInfo(UiAutomation.java:806)
    at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1482)
    at androidx.test.uiautomator.QueryController.waitForIdle(QueryController.java:532)
    at androidx.test.uiautomator.QueryController.waitForIdle(QueryController.java:523)
    at androidx.test.uiautomator.UiDevice.waitForIdle(UiDevice.java:676)
    at androidx.test.uiautomator.UiDevice.getWindowRoots(UiDevice.java:1414)
    at androidx.test.uiautomator.UiDevice.findObject(UiDevice.java:156)
    at com.wetest.uia2.stub.AutomatorServiceImpl.exist(AutomatorServiceImpl.java:817)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
    at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
    at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
    at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
    at com.wetest.uia2.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:101)
    at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
    at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
    at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
    at java.lang.Thread.run(Thread.java:1012)

**Comment by atauov** [comment]
same problem

**Comment by huangxiang0828** [comment]
@mingyuan-xia     
麻烦大佬有空帮忙看一下这个问题， 我也出现了， 尤其是在执行压测脚本中容易出现，我跟上面楼主都出现了相同的OutOfMemory

唯一不同的错误就是androidx.test.uiautomator.ByMatcher， 貌似是与递归调用或内存泄漏有关（ByMatcher.findMatches 被多次调用
