### ISSUE TITLE
Mix2 MIUI9.5.6 uiautomator2 init 报错,会影响以往脚本运行

### ISSUE THREAD

**Issue by Archer456** [openatx/uiautomator2#109]
```
(ATX365) cmd@TR:~$ adb devices -l
List of devices attached
myno               device usb:3-1 product:chiron model:MIX_2 device:chiron transport_id:33

(ATX365) cmd@TR:~$ python -m uiautomator2 init
2018-05-22 11:17:35,767 - __main__.py:269 - INFO - Detect pluged devices: ['45806625']
2018-05-22 11:17:35,768 - __main__.py:286 - INFO - Device(45806625) initialing ...
2018-05-22 11:17:35,960 - __main__.py:113 - INFO - install minicap
2018-05-22 11:17:36,057 - __main__.py:120 - INFO - install minitouch
Error output: 
Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.github.uiautomator
	at com.android.server.pm.Settings.isOrphaned(Settings.java:4429)
	at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21922)
	at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:18939)
	at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:913)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:912)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22229)
	at android.os.Binder.shellCommand(Binder.java:576)
	at android.os.Binder.onTransact(Binder.java:476)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2657)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3610)
	at android.os.Binder.execTransact(Binder.java:677)

Error output: 
Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.github.uiautomator.test
	at com.android.server.pm.Settings.isOrphaned(Settings.java:4429)
	at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21922)
	at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:18939)
	at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:913)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:912)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22229)
	at android.os.Binder.shellCommand(Binder.java:576)
	at android.os.Binder.onTransact(Binder.java:476)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2657)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3610)
	at android.os.Binder.execTransact(Binder.java:677)

2018-05-22 11:17:36,403 - __main__.py:143 - INFO - app-uiautomator.apk(1.0.14) installing ...
app-uiautomator.apk |################################| 1.7M / 1.7M
2018-05-22 11:17:57,987 - __main__.py:148 - INFO - app-uiautomator-test.apk installing ...
app-uiautomator-test.apk |################################| 964.7K / 964.7K
2018-05-22 11:18:20,969 - __main__.py:181 - INFO - atx-agent(0.3.0) need to update
2018-05-22 11:18:20,970 - __main__.py:189 - INFO - atx-agent(0.3.2) is installing, please be patient
atx-agent_0.3.2_linux_armv7.tar.gz |################################| 3.3M / 3.3M
2018-05-22 11:19:16,116 - __main__.py:212 - INFO - launch atx-agent daemon
2018-05-22 11:19:17,267 - __main__.py:228 - INFO - atx-agent output: server started, listening on 172.25.0.163:7912
2018-05-22 11:19:17,317 - __main__.py:232 - INFO - success

```

## Versions (版本)
`(ATX365) cmd@TR:~$ pip show uiautomator2
Name: uiautomator2
Version: 0.1.2.dev16
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: /home/cmd/.pyenv/versions/3.6.5/envs/ATX365/lib/python3.6/site-packages
Requires: requests, six, humanize, fire, progress, retry, whichcraft
Required-by: atx
`

## Issue and steps to reproduce (复现步骤)
脚本未变,以往手机系统 和 atx u2 下均可运行通过

- MIX2  MIUI9.5.6
- 脚本端错误:
   
![image](https://user-images.githubusercontent.com/18392901/40341318-1a9dab48-5db7-11e8-999d-d504a8ac9cfd.png)

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）
同样脚本,放到genymotion 一个7.0.0的 镜像下 可执行通过,  u2 init未报错.脚本执行未报错.

**Comment by codeskyblue** [comment]
安装报错可以忽略。脚本端的报错显示的是 UiObjectNotFound。元素没有找到。看下换了系统之后是不是 元素布局是不是也变了。可以用weditor看下

**Comment by Archer456** [comment]
我肯定看过了。重新检查过脚本，和元素识别方法。同脚本在模拟器下是通过的。

**Comment by Archer456** [comment]
@codeskyblue 
哦 发现规律了  凡是8.0  的安卓底层. 都会报上述 init错误  
我又换了 8.0的 genymotion 虚拟器  也是一样的  只有7.1.0 以下也就是API 25 以下的 init u2才正常.

**Comment by codeskyblue** [comment]
那个报错没事的，意思是卸载软件的时候没有找到。代码里面我处理掉了

**Comment by erjinzhi2333** [comment]
可以把界面结构dump放上来看看。

**Comment by codeskyblue** [comment]
fixed

**Comment by Archer456** [comment]
更新后  模拟器 8.0 可通过
但 真机mix2  8.0  不可.
用 weditor  tap 同样元素 也发现 模拟器可以  真机mix2不可以

**Comment by codeskyblue** [comment]
这属于另一个主题了，可以重提个issue
