### ISSUE TITLE
uiautomator server: IllegalStateException: Cannot call disconnect() while connecting!

### ISSUE THREAD

**Issue by GBwuka** [openatx/uiautomator2#111]
processName: com.github.uiautomator
processPid: 1892
shortMsg: java.lang.IllegalStateException
longMsg: java.lang.IllegalStateException: Cannot call disconnect() while connecting!
timeMillis: 1526958778309
stack:
java.lang.IllegalStateException: Cannot call disconnect() while connecting!
at android.app.UiAutomation.disconnect(UiAutomation.java:272)
at android.app.Instrumentation.finish(Instrumentation.java:213)
at android.support.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:277)
at android.support.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:282)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:271)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1977)

**Comment by codeskyblue** [comment]
怎么弄出来这个错误的

**Comment by GBwuka** [comment]
init初始化之后就用uitutomator2测试脚本，有的手机就报这个错了，我也想知道问题出在哪。。。

**Comment by codeskyblue** [comment]
IllegalStateException 这个是正常的确实会出来，只是后面那句 `Cannot call disconnect() while connecting!` 不太熟悉
