### ISSUE TITLE
Init fails

### ISSUE THREAD

**Issue by zgoda-mobica** [openatx/uiautomator2#114]
With `pip install --pre uiautomator2` I got "Successfully installed fire-0.1.3 humanize-0.5.1 progress-1.3 py-1.5.3 retry-0.9.2 uiautomator2-0.1.2.dev20 whichcraft-0.4.1". Additionally installed Pillow and then:

```
python -m uiautomator2 init --verbose
2018-05-25 12:01:55,067 - __main__.py:269 - INFO - Detect pluged devices: ['ddeec0a1']
2018-05-25 12:01:55,068 - __main__.py:286 - INFO - Device(ddeec0a1) initialing ...
2018-05-25 12:01:55,454 - __main__.py:109 - DEBUG - install minicap.so
2018-05-25 12:01:55,455 - __main__.py:70 - DEBUG - file 'minicap.so' cached before
2018-05-25 12:01:55,609 - __main__.py:113 - INFO - install minicap
2018-05-25 12:01:55,610 - __main__.py:70 - DEBUG - file 'minicap' cached before
2018-05-25 12:01:55,977 - __main__.py:120 - INFO - install minitouch
2018-05-25 12:01:55,978 - __main__.py:70 - DEBUG - file 'minitouch' cached before
2018-05-25 12:01:56,523 - __main__.py:137 - INFO - apk(1.0.14) already installed, skip
2018-05-25 12:01:56,637 - __main__.py:175 - INFO - atx-agent(0.3.2) already installed, skip
2018-05-25 12:01:56,891 - __main__.py:212 - INFO - launch atx-agent daemon
2018-05-25 12:01:57,244 - __main__.py:219 - DEBUG - forward device(port:7912) -> 41663
Traceback (most recent call last):
  File "/home/jazg/v/adr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/jazg/v/adr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python-3.6.5/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python-3.6.5/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python-3.6.5/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/python-3.6.5/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jazg/v/adr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/jazg/v/adr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/jazg/v/adr/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/jazg/v/adr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=41663): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python-3.6.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python-3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/uiautomator2/__main__.py", line 356, in <module>
    main()
  File "/home/jazg/v/adr/lib/python3.6/site-packages/uiautomator2/__main__.py", line 352, in main
    fire.Fire(MyFire)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/uiautomator2/__main__.py", line 273, in init
    ignore_apk_check)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/uiautomator2/__main__.py", line 295, in _init_with_serial
    ins.launch_and_check()
  File "/home/jazg/v/adr/lib/python3.6/site-packages/uiautomator2/__main__.py", line 225, in launch_and_check
    'http://localhost:%d/version' % lport, timeout=3)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/jazg/v/adr/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=41663): Read timed out. (read timeout=3)
```

Python is 3.6.5.

**Comment by derekhsieh** [comment]
same error.

**Comment by zhangshifen** [comment]
# init fail too
2018-05-30 20:02:10,153 - __main__.py:212 - INFO - launch atx-agent daemon
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/uiautomator2/__main__.py", line 356, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/uiautomator2/__main__.py", line 352, in main
    fire.Fire(MyFire)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/uiautomator2/__main__.py", line 273, in init
    ignore_apk_check)
  File "/usr/local/lib/python2.7/dist-packages/uiautomator2/__main__.py", line 295, in _init_with_serial
    ins.launch_and_check()
  File "/usr/local/lib/python2.7/dist-packages/uiautomator2/__main__.py", line 225, in launch_and_check
    'http://localhost:%d/version' % lport, timeout=3)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=37858): Read timed out. (read timeout=3)

**Comment by codeskyblue** [comment]
adb forward是不是出啥故障了

**Comment by zgoda-mobica** [comment]
I'm sorry I don't read Chinese.

**Comment by codeskyblue** [comment]
You can find log in path /sdcard/atx-agent.log
Let me see it.

**Comment by cqllang** [comment]
同样的错误，使用 pip install --pre uiautomator2 命令安装
在运行 python -m uiautomator2 init命令之后 ，
执行到 launch atx-agent daemon

报 urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=7912): Read timed out. (read timeout=3)


我的 atx-agent.log为:

2018/06/29 14:46:17 main.go:1333: wait previous server stopped
atx-agent version 0.3.3
Listen on http://192.168.31.108:7912
2018/06/29 14:46:23 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
2018/06/29 14:46:23 cmdctrl.go:27: DEBUG program pid: 12993

**Comment by cqllang** [comment]
i fix this.
find python3.6/site-packages/uiautomator2/__main__.py
modify:
`r = requests.get(
                    'http://localhost:%d/version' % lport, timeout=3)`
to
`r = requests.get(
                    'http://localhost:%d/version' % lport, timeout=10)`

it works.

@zgoda-mobica @derekhsieh @zhangshifen
