### ISSUE TITLE
斷開USB重新連接手機, 再次運行python -m uiautomator2 init fail

### ISSUE THREAD

**Issue by derekhsieh** [openatx/uiautomator2#120]
## Versions (版本)
0.1.1.dev33

## Issue and steps to reproduce (复现步骤)
>1. 第一次運行python -m uiautomator2 init
>2. 運行手機UI自動化測試
>3. 斷開USB後重新接上手機
>4. 嘗試再次運行手機UI自動化測試遇到
d.healthcheck() -('Connection aborted.', ConnectionResetError(10054, '遠端主機已強制關閉一個現存的連線。', None, 10054, None))
>5. 再次運行 python -m uiautomator2 init / python -m uiautomator2 init --reinstall / python -m uiautomator2 init --verbose 都報錯

- 手机型号? Nokia 7
- 错误日志?
```
d.healthcheck() -('Connection aborted.', ConnectionResetError(10054, '遠端主機已強制關閉一個現存的連線。', None, 10054, None))
2018-05-30 08:55:26,817 - __main__.py:109 - DEBUG - install minicap.so
2018-05-30 08:55:26,817 - __main__.py:70 - DEBUG - file 'minicap.so' cached before
2018-05-30 08:55:26,904 - __main__.py:113 - INFO - install minicap
2018-05-30 08:55:26,905 - __main__.py:70 - DEBUG - file 'minicap' cached before
2018-05-30 08:55:27,143 - __main__.py:120 - INFO - install minitouch
2018-05-30 08:55:27,159 - __main__.py:70 - DEBUG - file 'minitouch' cached before
2018-05-30 08:55:27,648 - __main__.py:137 - INFO - apk(1.0.12) already installed, skip
2018-05-30 08:55:27,770 - __main__.py:175 - INFO - atx-agent(0.3.0) already installed, skip
2018-05-30 08:55:28,061 - __main__.py:212 - INFO - launch atx-agent daemon
2018-05-30 08:55:28,447 - __main__.py:219 - DEBUG - forward device(port:7912) -> 62895
Traceback (most recent call last):
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=62895): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uiautomator2\__main__.py", line 352, in <module>
    main()
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uiautomator2\__main__.py", line 348, in main
    fire.Fire(MyFire)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uiautomator2\__main__.py", line 273, in init
    ignore_apk_check)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uiautomator2\__main__.py", line 295, in _init_with_serial
    ins.launch_and_check()
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uiautomator2\__main__.py", line 225, in launch_and_check
    'http://localhost:%d/version' % lport, timeout=3)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=62895): Read timed out. (read timeout=3)
```

- 出错的代码片段?
```
PlugOutUSB()
PlugInUSB()
d = Device.connect(deviceID)
os.popen("python -m uiautomator2 init --reinstall")
```

## Additional Details （其他信息）

**Comment by codeskyblue** [comment]
重新插拔手机之后需要调用connect 另外只要手机没关机，就没必要init

**Comment by derekhsieh** [comment]
已解決 謝謝
