### ISSUE TITLE
install apk fail

### ISSUE THREAD

**Issue by liberty123** [openatx/uiautomator2#122]
## Versions (版本)
Name: uiautomator2
Version: 0.1.2.dev21
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests, six, humanize, fire, progress, retry, whichcraft

- 手机型号: Android 4.2.2
- 错误日志:
>>>   591 KB/s (985448 bytes in 1.628s)
	pkg: /data/local/tmp/app-uiautomator-test.apk
Failure [INSTALL_FAILED_OLDER_SDK]

- 出错的代码片段?
adb install app-uiautomator-test.apk

## Additional Details （其他信息）

run "python -m uiautomator2 init" 
>>> 2018-05-31 15:04:41,553 - __main__.py:269 - INFO - Detect pluged devices: [u'192.168.123.80:5555']
2018-05-31 15:04:41,554 - __main__.py:286 - INFO - Device(192.168.123.80:5555) initialing ...
2018-05-31 15:04:42,189 - __main__.py:113 - INFO - install minicap
2018-05-31 15:04:42,971 - __main__.py:120 - INFO - install minitouch
2018-05-31 15:04:43,464 - __main__.py:143 - INFO - app-uiautomator.apk(1.0.14) installing ...
2018-05-31 15:04:47,706 - __main__.py:148 - INFO - app-uiautomator-test.apk installing ...
2018-05-31 15:04:50,658 - __main__.py:189 - INFO - atx-agent(0.3.2) is installing, please be patient
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/uiautomator2/__main__.py", line 356, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/uiautomator2/__main__.py", line 352, in main
    fire.Fire(MyFire)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/uiautomator2/__main__.py", line 273, in init
    ignore_apk_check)
  File "/usr/local/lib/python2.7/dist-packages/uiautomator2/__main__.py", line 294, in _init_with_serial
    ins.check_apk_installed(apk_version)
  File "/usr/local/lib/python2.7/dist-packages/uiautomator2/__main__.py", line 158, in check_apk_installed
    "package com.github.uiautomator not installed")
EnvironmentError: package com.github.uiautomator not installed

I can't install the two apk "app-uiautomator-test.apk" and "app-uiautomator.apk"

**Comment by codeskyblue** [comment]
4.4之前的版本不支持
