### ISSUE TITLE
多进程编程时碰到个问题，提示方法不存在uiautomator2.JsonRpcError: -32601 Method not found: <method not found> data:

### ISSUE THREAD

**Issue by flyfire100** [openatx/uiautomator2#131]
先上代码
```
   fd_queue = Queue()
    for serial in serial_list:
        print(serial)
        try:
            os.system("python -m uiautomator2 init  --serial %s"%serial)
            d = u2.connect(serial)
            print("A")
            print(d)
            fd_queue.put(d)
            print("C")
        except Exception as e:
            print(e)
            os.system("python -m uiautomator2 init  --serial %s"%serial)
            d = u2.connect(serial)
            if d :
                print("C")
                fd_queue.put(d)
    print("D")
    d = fd_queue.get(True)
    print(d.info)
    fd_queue.put(d)
````

执行时结果如下：
2018-06-07 14:51:09,052 - __main__.py:286 - INFO - Device(9YE0118201000099) initialing ...
2018-06-07 14:51:09,484 - __main__.py:113 - INFO - install minicap
2018-06-07 14:51:09,676 - __main__.py:120 - INFO - install minitouch
2018-06-07 14:51:10,078 - __main__.py:137 - INFO - apk(1.0.14) already installed, skip
2018-06-07 14:51:10,168 - __main__.py:175 - INFO - atx-agent(0.3.2) already installed, skip
2018-06-07 14:51:10,395 - __main__.py:212 - INFO - launch atx-agent daemon
2018-06-07 14:51:12,282 - __main__.py:228 - INFO - atx-agent output: server started, listening on 192.168.3.3:7912
2018-06-07 14:51:12,377 - __main__.py:232 - INFO - success
A
uiautomator2 object for 127.0.0.1:63123
C
D
Traceback (most recent call last):
  File "C:\Users\flyfire\AppData\Local\Programs\Python\Python36\lib\multiprocessing\queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\Users\flyfire\AppData\Local\Programs\Python\Python36\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "C:\Users\flyfire\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 347, in __call__
    params, http_timeout)
  File "C:\Users\flyfire\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 354, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "C:\Users\flyfire\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 422, in jsonrpc_call
    raise err
uiautomator2.JsonRpcError: -32601 Method not found: <method not found> data:
不知道哪里的问题，请帮忙看下

**Comment by codeskyblue** [comment]
不太清楚怎么回事，先更新uiautomator2，刚刚更新了一版

**Comment by flyfire100** [comment]
后面改了下代码，先规避了
