### ISSUE TITLE
JsonRpcError - java.lang.IllegalArgumentException: Illegal character (d83d)

### ISSUE THREAD

**Issue by L-Cool-J** [openatx/uiautomator2#135]
## Versions (版本)
    Version: 0.1.3.dev1

## Issue and steps to reproduce (复现步骤)
    微信6.6.2
    聊天记录界面运行
    xml = d.dump_hierarchy()

- 手机型号
    meizu mx4 pro

- 错误日志
```
JsonRpcError: -32001 Jsonrpc error: <java.lang.IllegalArgumentException> data: java.lang.IllegalArgumentException: Illegal character (d83d)
	at org.kxml2.io.KXmlSerializer.reportInvalidCharacter(KXmlSerializer.java:144)
	at org.kxml2.io.KXmlSerializer.writeEscaped(KXmlSerializer.java:130)
	at org.kxml2.io.KXmlSerializer.attribute(KXmlSerializer.java:465)
```

- 出错的代码片段
    d.dump_hierarchy()

**Comment by codeskyblue** [comment]
应该是界面上有什么uiautomator2解析不了的特殊字符。最好截个图看看

**Comment by mingyuan-xia** [comment]
tracking https://github.com/openatx/uiautomator2/issues/207
