### ISSUE TITLE
android.support.test.uiautomator.StaleObjectException

### ISSUE THREAD

**Issue by xiaowaisheng** [openatx/uiautomator2#138]
## Versions (版本)
Version: 0.1.3.dev4

- 手机型号
华为荣耀10

- 错误日志?

```
C:\Python27\lib\site-packages\uiautomator2\__init__.py:369: RuntimeWarning: uiautomator2 raise exception -32001 Jsonrpc error: <android.support.test.uiautomator.StaleObjectException> data: android.support.test.uiautomator.StaleObjectException
	at android.support.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:647)
	at android.support.test.uiautomator.UiObject2.getApplicationPackage(UiObject2.java:285)
	at com.github.uiautomator.stub.ObjInfo.<init>(ObjInfo.java:77)
	at com.github.uiautomator.stub.ObjInfo.getObjInfo(ObjInfo.java:44)
	at com.github.uiautomator.stub.AutomatorServiceImpl.objInfo(AutomatorServiceImpl.java:770)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
	at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
	at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:784)
, and run code again
  stacklevel=1)
```

- 出错的代码片段?

```python
 def test_offlineMap(self):
        """离线地图测试"""
        try:
            mylogger.info("test_offlineMap:begin")
            self.d(text='我的').click()
            self.d(text='离线地图').click()
            if self.d.exists(text='开始'):
                self.d(text='开始').click_exists(1)
                toast = self.d.toast.get_message(wait_timeout = 1, cache_timeout = 3, default = None)
                # toast = self.d.toast.get_message(2, 5, "开始下载离线地图") #
                print (toast)
                # self.d.toast.reset()
                print "The start button exists"
            elif self.d.exists(text='已完成!'):
                self.d(text="删除").click_exists(2)
                time.sleep(1)
                self.d(text='取消').click()
                self.d(text="删除").click()
                time.sleep(1)
                self.d(text='确定').click()
                toast = self.d.toast.get_message(wait_timeout=3, cache_timeout=3, default=None)
                # toast = self.d.toast.get_message(2, 5, "您已删除离线地图")
                print (toast)
                # self.d.toast.reset()
                self.d(text='开始').click_exists(1)
            else:
                print "Button does not exist"
            time.sleep(1)
            self.d(text='暂停').click_exists(1)
            toast = self.d.toast.get_message(wait_timeout=3, cache_timeout=3, default=None)
            # toast = self.d.toast.get_message(2, 5, "暂停下载离线地图")
            print (toast)
            # self.d.toast.reset()
            self.d(text='继续').click_exists(1)
            toast = self.d.toast.get_message(wait_timeout=3, cache_timeout=3, default=None)
            # toast = self.d.toast.get_message(2, 5, "开始下载离线地图")
            print (toast)
            # self.d.toast.reset()
            time.sleep(5)
            result = self.d.exists(text='已完成!')
            self.assertTrue(result)
            mylogger.info("download Success")
            print "download Success"
            self.d(text="更新").click_exists(2)
            self.d(text='知道了').click_exists(1)
            time.sleep(1)
        except Exception as msg:
            print(u"异常原因%s" % msg)
            mylogger.error("download Failure")
            CutScreenshot.get_screen()
            raise
```

**Comment by xiaowaisheng** [comment]
第一次提，不怎知道描述

**Comment by codeskyblue** [comment]
ObjInfo的时候报错，应该需要改apk了

**Comment by codeskyblue** [comment]
fixed in https://github.com/openatx/android-uiautomator-server/commit/babc434581a1bc1947b5a9cccd0eee9de96196dd
