### ISSUE TITLE
Android P 支持么？

### ISSUE THREAD

**Issue by Master-An** [openatx/uiautomator2#148]
Logs:
127.0.0.1
59567
Mon Jul 02 17:43:55 2018 wait uiautomator is ready.
Mon Jul 02 17:43:56 2018 wait uiautomator is ready.
Mon Jul 02 17:43:57 2018 wait uiautomator is ready.
Mon Jul 02 17:43:58 2018 wait uiautomator is ready.
Mon Jul 02 17:43:59 2018 wait uiautomator is ready.
Mon Jul 02 17:44:00 2018 wait uiautomator is ready.
Mon Jul 02 17:44:01 2018 wait uiautomator is ready.
Mon Jul 02 17:44:02 2018 wait uiautomator is ready.
Mon Jul 02 17:44:03 2018 wait uiautomator is ready.
Mon Jul 02 17:44:04 2018 wait uiautomator is ready.
Traceback (most recent call last):
  File "C:\Automation\PTAS\Plasma\Engine\TestScripts\SLEEPTEST\air.tv.douyu.android\air_tv_douyu_android_login.py", line 118, in <module>
    d = Device.GetDevice()
  File "C:\Automation\PTAS\Plasma\Engine\Library\ptas_software_handler\ATXComModule\device.py", line 28, in GetDevice
    d = atx.connect()
  File "C:\Python27\lib\site-packages\atx\__init__.py", line 83, in connect
    c = cls(connect_url, **kwargs)
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 95, in __init__
    self._uiauto.healthcheck(unlock=False)
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 527, in healthcheck
    raise RuntimeError("Uiautomator started failed.")
RuntimeError: Uiautomator started failed.

**Comment by codeskyblue** [comment]
可能等待的时间不够长，我改了改，你更新下试试

**Comment by Master-An** [comment]
在 uiautomator2 init 的过程中，由于没有SDK28的mincap.so下载目录。我用SDK27的替代，是否会引起以上错误？

**Comment by codeskyblue** [comment]
不会

**Comment by derekhsieh** [comment]
何時會有SDK28的目錄呢?

**Comment by mingyuan-xia** [comment]
tracking
https://github.com/openatx/uiautomator2/issues/204
https://github.com/openatx/uiautomator2/issues/217
