### ISSUE TITLE
uiautomator.apk意外被杀掉

### ISSUE THREAD

**Issue by codeskyblue** [openatx/uiautomator2#15]
锤子M1。运行游戏的时候uiautomator apk被杀

相关logcat日志

```
12-04 18:31:26.158  1371  1404 D UidCpuTracker: mCleanBadBgApp add and mSuspectedUids.remove: 10287
12-04 18:31:26.209  1371  1405 I ActivityManager: Killing 1151:com.github.uiautomator/u0a287 (adj 0): busy background ap
p
12-04 18:31:26.210  1371  1405 I Process : killProcessQuiet pid=1151
12-04 18:31:26.210  1371  1405 I Process : java.lang.RuntimeException
12-04 18:31:26.210  1371  1405 I Process :      at android.os.Process.killProcessQuiet(Process.java:1161)
12-04 18:31:26.210  1371  1405 I Process :      at com.android.server.am.ProcessRecord.kill(ProcessRecord.java:592)
12-04 18:31:26.210  1371  1405 I Process :      at com.android.server.am.ActivityManagerService.removeProcessLocked(Acti
vityManagerService.java:7002)
12-04 18:31:26.210  1371  1405 I Process :      at com.android.server.am.UidCpuTrackerRunner$3.run(UidCpuRunner.java:933
)
12-04 18:31:26.210  1371  1405 I Process :      at android.os.Handler.handleCallback(Handler.java:739)
12-04 18:31:26.210  1371  1405 I Process :      at android.os.Handler.dispatchMessage(Handler.java:95)
12-04 18:31:26.210  1371  1405 I Process :      at android.os.Looper.loop(Looper.java:148)
12-04 18:31:26.210  1371  1405 I Process :      at android.os.HandlerThread.run(HandlerThread.java:61)
12-04 18:31:26.210  1371  1405 I Process :      at com.android.server.ServiceThread.run(ServiceThread.java:46)
12-04 18:31:26.227  1371  2255 W WindowManager: Attempted to remove non-existing token: android.os.Binder@c83af2b
12-04 18:31:26.228  1371  2255 W AccessibilityManagerService: Skipping accessibilty service com.cootek.smartinputv5.smar
tisan/com.cootek.smartinput5.TouchPalAccessibilityService: it does not require the permission android.permission.BIND_AC
CESSIBILITY_SERVICE
12-04 18:31:26.231  1371  1405 D ActivityManager: cleanUpApplicationRecord -- 1151
12-04 18:31:26.232  1371  1405 W ActivityManager: Crash of app com.github.uiautomator running instrumentation ComponentI
nfo{com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}
12-04 18:31:26.236  1371  1405 I ActivityManager:  appId 10287 get for package com.github.uiautomator
12-04 18:31:26.237  1371  1405 I ActivityManager: Force stopping com.github.uiautomator appid=10287 user=0: finished ins
t
12-04 18:31:26.238  1371  1405 I UidCpuTracker: remove busy background app=ProcessRecord{9b2df88 0:com.github.uiautomato
r/u0a287}
12-04 18:31:26.239  1371  2938 W ActivityManager: Spurious death for ProcessRecord{9b2df88 0:com.github.uiautomator/u0a2
87}, curProc for 1151: null
```

**Comment by codeskyblue** [comment]
通过命令`adb shell am startservice -a com.github.uiautomator.ACTION_START`无法实现重新启动Service。
TODO：logcat日志

**Comment by codeskyblue** [comment]
apk中需要去掉启动service的功能
