### ISSUE TITLE
点击拨号盘数字369有BUG

### ISSUE THREAD

**Issue by MacgradyHuang** [openatx/uiautomator2#150]
```
>>> import uiautomator2 as ui
>>> d = ui.connect('10.139.0.xxx')
>>> d(text='1').click()
>>> d(text='3').click()
>>> d(text='6').click()
>>> d(text='9').click()
```

## Versions (版本)
pip show uiautomator2-0.1.3.dev17

## Issue and steps to reproduce (复现步骤)
```
>>> import uiautomator2 as ui
>>> d = ui.connect('10.139.0.xxx')
>>> d(text='1').click()
>>> d(text='3').click()
>>> d(text='6').click()
>>> d(text='9').click()
```

- 手机型号?
华为荣耀 CHE-TL00

- 错误日志?
>>> import uiautomator2 as ui
>>> d = ui.connect('10.139.0.xxx')
>>> d(text='1').click()
>>> d(text='3').click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/huangpengbo/Projects/GridsumProjects/message_channel_center/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 1530, in inner
    'message': E(self.selector.__str__())
uiautomator2.UiObjectNotFoundError: -32002 Server error: <Selector [text='3']> data: 
>>> d(text='6').click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/huangpengbo/Projects/GridsumProjects/message_channel_center/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 1530, in inner
    'message': E(self.selector.__str__())
uiautomator2.UiObjectNotFoundError: -32002 Server error: <Selector [text='6']> data: 
>>> d(text='9').click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/huangpengbo/Projects/GridsumProjects/message_channel_center/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 1530, in inner
    'message': E(self.selector.__str__())
uiautomator2.UiObjectNotFoundError: -32002 Server error: <Selector [text='9']> data: 

## Screenshots （相关截图）
![image](https://user-images.githubusercontent.com/12002500/42198074-930d7b90-7eb8-11e8-9a7c-d4dca4a03892.png)

**Comment by codeskyblue** [comment]
weditor截张图
