### ISSUE TITLE
-32001 Jsonrpc error: <java.lang.IllegalStateException> data: java.lang.IllegalStateException: Cannot perform this action on a sealed instance.

### ISSUE THREAD

**Issue by DevineLiu** [openatx/uiautomator2#156]
```
-32001 Jsonrpc error: <java.lang.IllegalStateException> data: java.lang.IllegalStateException: Cannot perform this action on a sealed instance.
	at android.view.accessibility.AccessibilityNodeInfo.enforceNotSealed(AccessibilityNodeInfo.java:2956)
	at android.view.accessibility.AccessibilityNodeInfo.setConnectionId(AccessibilityNodeInfo.java:2839)
	at android.view.accessibility.AccessibilityInteractionClient.finalizeAndCacheAccessibilityNodeInfo(AccessibilityInteractionClient.java:703)
	at android.view.accessibility.AccessibilityInteractionClient.finalizeAndCacheAccessibilityNodeInfos(AccessibilityInteractionClient.java:721)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:293)
	at android.view.accessibility.AccessibilityInteractionClient.getRootInActiveWindow(AccessibilityInteractionClient.java:160)
	at android.app.UiAutomation.getRootInActiveWindow(UiAutomation.java:479)
	at android.support.test.uiautomator.QueryController.getRootNode(QueryController.java:182)
	at android.support.test.uiautomator.QueryController.findAccessibilityNodeInfo(QueryController.java:161)
	at android.support.test.uiautomator.QueryController.findAccessibilityNodeInfo(QueryController.java:150)
	at android.support.test.uiautomator.UiObject.findAccessibilityNodeInfo(UiObject.java:192)
	at android.support.test.uiautomator.UiObject.getClassName(UiObject.java:580)
	at com.github.uiautomator.stub.ObjInfo.<init>(ObjInfo.java:63)
	at com.github.uiautomator.stub.ObjInfo.getObjInfo(ObjInfo.java:36)
	at com.github.uiautomator.stub.AutomatorServiceImpl.objInfo(AutomatorServiceImpl.java:769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
	at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
	at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:764)

```

## Versions (版本)
Name: uiautomator2
Version: 0.1.2
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: /home/devine/.local/lib/python3.6/site-packages
Requires: six, progress, retry, whichcraft, fire, humanize, requests

## Issue and steps to reproduce (复现步骤)

通过无线链接，在应用(com.android.chrome_339608700)内随机获取可点击组件的点击，在测试时出现err　致使测试中断。

- 手机型号
google pixel

错误日志：
-32001 Jsonrpc error: <java.lang.IllegalStateException> data: java.lang.IllegalStateException: Cannot perform this action on a sealed instance.
	at android.view.accessibility.AccessibilityNodeInfo.enforceNotSealed(AccessibilityNodeInfo.java:2956)
	at android.view.accessibility.AccessibilityNodeInfo.setConnectionId(AccessibilityNodeInfo.java:2839)
	at android.view.accessibility.AccessibilityInteractionClient.finalizeAndCacheAccessibilityNodeInfo(AccessibilityInteractionClient.java:703)
	at android.view.accessibility.AccessibilityInteractionClient.finalizeAndCacheAccessibilityNodeInfos(AccessibilityInteractionClient.java:721)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:293)
	at android.view.accessibility.AccessibilityInteractionClient.getRootInActiveWindow(AccessibilityInteractionClient.java:160)
	at android.app.UiAutomation.getRootInActiveWindow(UiAutomation.java:479)
	at android.support.test.uiautomator.QueryController.getRootNode(QueryController.java:182)
	at android.support.test.uiautomator.QueryController.findAccessibilityNodeInfo(QueryController.java:161)
	at android.support.test.uiautomator.QueryController.findAccessibilityNodeInfo(QueryController.java:150)
	at android.support.test.uiautomator.UiObject.findAccessibilityNodeInfo(UiObject.java:192)
	at android.support.test.uiautomator.UiObject.getClassName(UiObject.java:580)
	at com.github.uiautomator.stub.ObjInfo.<init>(ObjInfo.java:63)
	at com.github.uiautomator.stub.ObjInfo.getObjInfo(ObjInfo.java:36)
	at com.github.uiautomator.stub.AutomatorServiceImpl.objInfo(AutomatorServiceImpl.java:769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
	at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
	at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:764)

代码片段：

```python

old_xml=errcount=0
for i in range(10):
    if errcount >3:
        raise CrashErr('three consecutive failures, raise Crasherr ')
    try:
        self.device(clickable=True)[random.randint(0,2)].click(timeout=5)
        sleep(1)
        print (i)
        newxml=self.device.dump_hierarchy()
        if newxml and not operator.eq(newxml,old_xml):
            old_xml=newxml
            errcount=0
        else:
            raise FindbyClickablexmlErr('raise error eg:no xm_element or same as twice elements')
    except BaseException as e:
        print (e)
        errcount+=1 
```

**Comment by codeskyblue** [comment]
update version to `0.1.3.dev24`
