### ISSUE TITLE
版本0.1.3 Uiautomator started failed

### ISSUE THREAD

**Issue by derekhsieh** [openatx/uiautomator2#158]
```
2018-07-09 15:36:09,655 - __main__.py:295 - INFO - Detect pluged devices: ['xxxxxx']
2018-07-09 15:36:09,655 - __main__.py:312 - INFO - Device(xxxxxx) initialing ...
2018-07-09 15:36:10,555 - __main__.py:129 - INFO - install minicap
2018-07-09 15:36:10,791 - __main__.py:136 - INFO - install minitouch
2018-07-09 15:36:11,650 - __main__.py:149 - INFO - app-uiautomator.apk(1.1.3) downloading ...
2018-07-09 15:36:11,650 - __main__.py:152 - INFO - app-uiautomator-test.apk downloading ...
2018-07-09 15:36:13,510 - __main__.py:212 - INFO - atx-agent(0.3.5) is installing, please be patient
2018-07-09 15:36:14,541 - __main__.py:235 - INFO - launch atx-agent daemon
2018-07-09 15:36:16,947 - __main__.py:253 - INFO - atx-agent output: server started, listening on 127.0.0.1:7912
2018-07-09 15:36:16,947 - __main__.py:257 - INFO - success
>>> d = Device.connect("xxxxxx")
Starting new HTTP connection (1): 127.0.0.1
http://127.0.0.1:53929 "GET /version HTTP/1.1" 200 5
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
http://127.0.0.1:53929 "POST /shell HTTP/1.1" 200 239
http://127.0.0.1:53929 "DELETE /uiautomator HTTP/1.1" 500 16
http://127.0.0.1:53929 "POST /shell HTTP/1.1" 200 136
http://127.0.0.1:53929 "POST /uiautomator HTTP/1.1" 200 7
[2018-07-09 15:36:49] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:36:50] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:36:51] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:36:52] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:36:53] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:36:54] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:36:55] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:36:56] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:36:57] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:36:58] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:36:59] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:37:00] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:37:01] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:37:02] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:37:03] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:37:04] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:37:05] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:37:06] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:37:07] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
[2018-07-09 15:37:08] wait uiautomator is ready ...
http://127.0.0.1:53929 "GET /ping HTTP/1.1" 502 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uiautomator2\__init__.py", line 187, in connect
    return connect_usb(addr)
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uiautomator2\__init__.py", line 234, in connect_usb
    d.healthcheck()
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uiautomator2\__init__.py", line 574, in healthcheck
    raise RuntimeError("Uiautomator started failed.")
RuntimeError: Uiautomator started failed.
```

## Versions (版本)
0.1.3

## Issue and steps to reproduce (复现步骤)
1. python -m uiautomator2 init
2. d = Device.connect("xxxxxx")

- 手机型号? 
Android P
- 错误日志? 
如上
- 出错的代码片段?

## Screenshots （相关截图）
N/A

## Additional Details （其他信息）
我是使用SDK27目錄下的檔案安裝

**Comment by codeskyblue** [comment]
你那个`Device`是啥？ 标准的是这样写的

```python
import uiautomator2 as u2
d = u2.connect("xxxx")
```

**Comment by WeihuaGu** [comment]
我的init 重装后依然是这个错误。手机uiaotomator 已通知

**Comment by WeihuaGu** [comment]
然后我手动在电脑上执行了命令
`curl -X POST -d '{"params": {}, "jsonrpc": "2.0", "id": "40db2a2f323f9b85fc26dea23a12fa3e", "method": "deviceInfo"}' http://192.168.1.103:7912/jsonrpc/0` 返回为空。

然后我在电脑上的浏览器访问了http://192.168.1.103:7912/term,终端倒是能用

然后我又 curl 了http://192.168.1.103:7912/info，倒也是正常返回了json

**Comment by codeskyblue** [comment]
apk都卸载了，重新安装

**Comment by codeskyblue** [comment]
另外最好升级下版本

**Comment by WeihuaGu** [comment]
问题是卸载了重新安装可以管一次用，再用就又是这了。应该是最新的，我用pip install --upgrade --pre 刚升过级

**Comment by codeskyblue** [comment]
你这个手机是 android p的，我这还没有这么高级的

**Comment by WeihuaGu** [comment]
哦，我的手机是安卓8.1 系统是aicp,基于lineago os 的。也就是说这个和手机的安卓版本有关？

**Comment by codeskyblue** [comment]
没多大关系，感觉就是没弄好环境

**Comment by codeskyblue** [comment]
有问题来群里问吧
