### ISSUE TITLE
python -m uiautomator2 init 时报错

### ISSUE THREAD

**Issue by LynnlikeLin** [openatx/uiautomator2#162]
手机型号FRD-AL00
python -m uiautomator2 init 时报下面错误

```
Z:\>python -m uiautomator2 init
* daemon not running; starting now at tcp:5037
* daemon started successfully
2018-07-11 10:21:23,330 - __main__.py:305 - INFO - Detect pluged devices: ['WTKDU16902005623']
2018-07-11 10:21:23,330 - __main__.py:322 - INFO - Device(WTKDU16902005623) initialing ...
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python36-32\lib\site-packages\uiautomator2\adbutils.py", line 44, in execute
    cmdline, stderr=subprocess.STDOUT, shell=True).decode('utf-8')
  File "D:\Program Files (x86)\Python\Python36-32\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "D:\Program Files (x86)\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'C:\Users\linchengxiang\AppData\Local\Android\sdk\platform-tools\adb.EXE -s WTKDU16902005623 shell getprop ro.product.cpu.abi' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files (x86)\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files (x86)\Python\Python36-32\lib\site-packages\uiautomator2\__main__.py", line 395, in <module>
    main()
  File "D:\Program Files (x86)\Python\Python36-32\lib\site-packages\uiautomator2\__main__.py", line 391, in main
    fire.Fire(MyFire)
  File "D:\Program Files (x86)\Python\Python36-32\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "D:\Program Files (x86)\Python\Python36-32\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "D:\Program Files (x86)\Python\Python36-32\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "D:\Program Files (x86)\Python\Python36-32\lib\site-packages\uiautomator2\__main__.py", line 309, in init
    ignore_apk_check)
  File "D:\Program Files (x86)\Python\Python36-32\lib\site-packages\uiautomator2\__main__.py", line 323, in _init_with_serial
    ins = Installer(serial)
  File "D:\Program Files (x86)\Python\Python36-32\lib\site-packages\uiautomator2\__main__.py", line 98, in __init__
    self.abi = self.getprop('ro.product.cpu.abi')
  File "D:\Program Files (x86)\Python\Python36-32\lib\site-packages\uiautomator2\adbutils.py", line 106, in getprop
    return self.execute('shell', 'getprop', prop).strip()
  File "D:\Program Files (x86)\Python\Python36-32\lib\site-packages\uiautomator2\adbutils.py", line 49, in execute
    'utf-8', errors='ignore'))
OSError: [Errno subprocess] C:\Users\linchengxiang\AppData\Local\Android\sdk\platform-tools\adb.EXE -s WTKDU16902005623 shell getprop ro.product.cpu.abi: "error: device 'WTKDU16902005623' not found\r\
n"

Z:\>
```

## Versions (版本)
0.1.3.dev27

**Comment by codeskyblue** [comment]
`adb.EXE -s WTKDU16902005623 shell getprop ro.product.cpu.abi` 返回什么呢?

**Comment by codeskyblue** [comment]
另外试试 `adb devices`输出什么？

**Comment by bravesnail** [comment]
adb shell getprop ro.build.version.release 
p 
发现不支持android p。
ro.product.cpu.abi
arm64-v8a

**Comment by LynnlikeLin** [comment]
@codeskyblue 换了条数据线后安装成功了，应该是之前的那条线有些问题。Thanks♪(･ω･)ﾉ
