### ISSUE TITLE
一加3  android 8.0 启动uiautomator server失败

### ISSUE THREAD

**Issue by santa774** [openatx/uiautomator2#165]
## Versions (版本)
Version: 0.1.3.dev26

## Issue and steps to reproduce (复现步骤)
执行以下代码报错
``` python
phone = u2.connect('192.168.1.100')
print(phone.info)
```

- 手机型号?    一加3   Android 8.0
- 错误日志?
```
D:\Anaconda2\envs\py3\lib\site-packages\uiautomator2\__init__.py:401: RuntimeWarning: uiautomator2 is not reponding, restart uiautomator2 automatically
  stacklevel=1)
[2018-07-13 17:20:09] wait uiautomator is ready ...
[2018-07-13 17:20:10] wait uiautomator is ready ...
[2018-07-13 17:20:11] wait uiautomator is ready ...
[2018-07-13 17:20:13] wait uiautomator is ready ...
[2018-07-13 17:20:14] wait uiautomator is ready ...
[2018-07-13 17:20:15] wait uiautomator is ready ...
[2018-07-13 17:20:16] wait uiautomator is ready ...
[2018-07-13 17:20:17] wait uiautomator is ready ...
[2018-07-13 17:20:18] wait uiautomator is ready ...
[2018-07-13 17:20:20] wait uiautomator is ready ...
[2018-07-13 17:20:21] wait uiautomator is ready ...
[2018-07-13 17:20:22] wait uiautomator is ready ...
[2018-07-13 17:20:23] wait uiautomator is ready ...
[2018-07-13 17:20:24] wait uiautomator is ready ...
[2018-07-13 17:20:25] wait uiautomator is ready ...
[2018-07-13 17:20:26] wait uiautomator is ready ...
[2018-07-13 17:20:27] wait uiautomator is ready ...
[2018-07-13 17:20:28] wait uiautomator is ready ...
Traceback (most recent call last):
  File "D:\Anaconda2\envs\py3\lib\site-packages\uiautomator2\__init__.py", line 396, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "D:\Anaconda2\envs\py3\lib\site-packages\uiautomator2\__init__.py", line 440, in jsonrpc_call
    (time.time() - request_start))
uiautomator2.GatewayError: uiautomator2.GatewayError(gateway error, time used 0.1s)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/python_project/py_project/zaker_intergral_script/zaker_run.py", line 333, in <module>
    print(phone.info)
  File "D:\Anaconda2\envs\py3\lib\site-packages\uiautomator2\__init__.py", line 1025, in __getattr__
    return getattr(self._default_session, attr)
  File "D:\Anaconda2\envs\py3\lib\site-packages\uiautomator2\__init__.py", line 1524, in info
    return self.jsonrpc.deviceInfo()
  File "D:\Anaconda2\envs\py3\lib\site-packages\uiautomator2\__init__.py", line 389, in __call__
    params, http_timeout)
  File "D:\Anaconda2\envs\py3\lib\site-packages\uiautomator2\__init__.py", line 403, in jsonrpc_retry_call
    self.healthcheck(unlock=False)
  File "D:\Anaconda2\envs\py3\lib\site-packages\uiautomator2\__init__.py", line 581, in healthcheck
    raise RuntimeError("Uiautomator started failed.")
RuntimeError: Uiautomator started failed.
```

- 出错的代码片段?

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）

**Comment by mingyuan-xia** [comment]
see: https://github.com/openatx/uiautomator2/issues/151
