### ISSUE TITLE
vivo x7 运行中出错 OSError: atx-agent is not running.

### ISSUE THREAD

**Issue by f0cii** [openatx/uiautomator2#167]
运行一段时间脚本异常退出，atx-agent 退出后没有正常重启，并继续脚本

```
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "C:\ProgramData\Miniconda3\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\ProgramData\Miniconda3\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\ProgramData\Miniconda3\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\ProgramData\Miniconda3\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 671, in urlopen
    release_conn=release_conn, **response_kw)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 671, in urlopen
    release_conn=release_conn, **response_kw)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 671, in urlopen
    release_conn=release_conn, **response_kw)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=39384): Max retries exceeded with url: /jsonrpc/0 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 260, in request
    method, url, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=39384): Max retries exceeded with url: /jsonrpc/0 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强
迫关闭了一个现有的连接。', None, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\alipay.py", line 279, in <module>
    main()
  File ".\alipay.py", line 256, in main
    ok, key = a.bill_list()
  File ".\alipay.py", line 93, in bill_list
    count = listItem.count
  File "C:\ProgramData\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 1769, in count
    return self.jsonrpc.count(self.selector)
  File "C:\ProgramData\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 389, in __call__
    params, http_timeout)
  File "C:\ProgramData\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 396, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 434, in jsonrpc_call
    data=data)
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\uiautomator2\__init__.py", line 263, in request
    "atx-agent is not running. Fix it with following steps.\n1. Plugin device into computer.\n2. Run command \"python -m uiautomator2 init\""
OSError: atx-agent is not running. Fix it with following steps.
1. Plugin device into computer.
2. Run command "python -m uiautomator2 init"
```

## Versions (版本)
0.1.3.dev27

## Issue and steps to reproduce (复现步骤)
连续跑一段时间就会出现

- 手机型号
vivo x7

**Comment by codeskyblue** [comment]
可能是被系统杀掉了

**Comment by Cataglyphis** [comment]
又什么好的方式可以避免被系统杀死么？ @codeskyblue

**Comment by codeskyblue** [comment]
升级下版本，新版基本不会被杀了
