### ISSUE TITLE
页面某些元素无法正常获取到

### ISSUE THREAD

**Issue by edisonyan** [openatx/uiautomator2#169]
## Versions (版本)
Version: 0.1.3.dev27

## Issue and steps to reproduce (复现步骤)
1.weditor中定位到相关元素，
2.weditor中运行相关代码
![image](https://user-images.githubusercontent.com/3954670/42868222-59c9b860-8aa4-11e8-90e7-3439a1701aa4.png)
无法定位相关元素

- 手机型号
华为揽阅m2
- 错误日志
<pre><code>Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\weditor\__main__.py", line 302, in post
    ret = eval(code, {'d': d})
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 1539, in inner
    return fn(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 1575, in click
    x, y = self.center()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 1589, in center
    info = self.info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 1562, in info
    return self.jsonrpc.objInfo(self.selector)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 389, in __call__
    params, http_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 396, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 468, in jsonrpc_call
    raise err
uiautomator2.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[TEXT=9, RESOURCE_ID=com.caijicn.cjpadt:id/tv_evaluation]
[Finished in 0.152s]
</code></pre>
- 出错的代码片段?
如截图所示
## Screenshots （相关截图）
![image](https://user-images.githubusercontent.com/3954670/42868328-98f1c4ba-8aa4-11e8-9f68-2e771198f42a.png)
![image](https://user-images.githubusercontent.com/3954670/42868340-a01cb222-8aa4-11e8-964f-079f1f0f9309.png)

## Additional Details （其他信息）

**Comment by codeskyblue** [comment]
搞不好是个悬浮窗，这个uiautomator2还解析不了

**Comment by DevineLiu** [comment]
这个处理的很恶心 adb shell tap 去点也点不了，发送adb命令 它就默认为不授权 ，目前没找到 方法解决

**Comment by mingyuan-xia** [comment]
sendevent去点击XY，所有popup都无法用hierarchy viewer看到，Google uiautomator设计局限
