### ISSUE TITLE
通过WiFi连接设备，是不是要root手机；运行报错误信息

### ISSUE THREAD

**Issue by holysor** [openatx/uiautomator2#172]
Traceback (most recent call last):
  File "C:\Users\HolyS\.virtualenvs\MMTUiTest_Android-rI6pBAEk\lib\site-packages\uiautomator2\__init__.py", line 260, in request
    method, url, **kwargs)
  File "C:\Users\HolyS\.virtualenvs\MMTUiTest_Android-rI6pBAEk\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\HolyS\.virtualenvs\MMTUiTest_Android-rI6pBAEk\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\HolyS\.virtualenvs\MMTUiTest_Android-rI6pBAEk\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.18.23', port=7912): Max retries exceeded with url: /info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x02E01570>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

**Comment by codeskyblue** [comment]
不需要root，但是需要手机的ip跟电脑同一个网段
