### ISSUE TITLE
在编写case时发现经常有timeout的状况

### ISSUE THREAD

**Issue by DevineLiu** [openatx/uiautomator2#176]
很多时候其实是链接不稳定，或者uiautomator掉了，每次都要写try重连，想说可不可以在框架内封装个修饰器的类去处理掉线的问题，timeout重连很多时候在其实不是测试关心的问题，本身可能是测试工具不稳定造成的，err其实可以不往上抛给case，让框架自身尝试重连，失败再抛出

**Comment by codeskyblue** [comment]
其实已经处理了，把报错贴出来看看

**Comment by DevineLiu** [comment]
[2018-07-30 13:36:52] wait uiautomator is ready ...
[2018-07-30 13:36:53] wait uiautomator is ready ...
[2018-07-30 13:36:54] wait uiautomator is ready ...
[2018-07-30 13:36:55] wait uiautomator is ready ...
[2018-07-30 13:36:56] wait uiautomator is ready ...
[2018-07-30 13:36:57] wait uiautomator is ready ...
[2018-07-30 13:36:58] wait uiautomator is ready ...
[2018-07-30 13:36:59] wait uiautomator is ready ...
[2018-07-30 13:37:00] wait uiautomator is ready ...
[2018-07-30 13:37:01] wait uiautomator is ready ...
[2018-07-30 13:37:02] wait uiautomator is ready ...
[2018-07-30 13:37:03] wait uiautomator is ready ...
[2018-07-30 13:37:04] wait uiautomator is ready ...
[2018-07-30 13:37:05] wait uiautomator is ready ...
[2018-07-30 13:37:06] wait uiautomator is ready ...
[2018-07-30 13:37:07] wait uiautomator is ready ...
[2018-07-30 13:37:08] wait uiautomator is ready ...
[2018-07-30 13:37:09] wait uiautomator is ready ...
[2018-07-30 13:37:10] wait uiautomator is ready ...
[2018-07-30 13:37:12] wait uiautomator is ready ...
Traceback (most recent call last):
  File "/home/devine/PycharmProjects/ATX-Test_LQ/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 396, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "/home/devine/PycharmProjects/ATX-Test_LQ/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 440, in jsonrpc_call
    (time.time() - request_start))
uiautomator2.GatewayError: uiautomator2.GatewayError(gateway error, time used 0.0s)
