### ISSUE TITLE
init fails for Android P due to missing minicap support for P

### ISSUE THREAD

**Issue by gamesguru** [openatx/uiautomator2#185]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```
$ python3 -m uiautomator2 init

2018-08-03 14:50:09,195 - __main__.py:310 - INFO - Detect pluged devices: ['710KPAE0248976']
2018-08-03 14:50:09,196 - __main__.py:321 - INFO - Device(710KPAE0248976) initialing ...
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__main__.py", line 394, in <module>
    main()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__main__.py", line 390, in main
    fire.Fire(MyFire)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__main__.py", line 314, in init
    ignore_apk_check)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__main__.py", line 324, in _init_with_serial
    ins.install_minicap()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__main__.py", line 129, in install_minicap
    path = cache_download(url)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__main__.py", line 78, in cache_download
    raise Exception("status code", r.status_code)
Exception: ('status code', 404)

```

## Versions (版本)
v1.1.4

## Issue and steps to reproduce (复现步骤)
update Google Pixel 2XL to Android P, attempt to use

**Comment by gamesguru** [comment]
issue is with lacking minicap binaries for new Android version
understand the issue am less concerned now.  No pressure to rush delivery

```2018-08-06 16:54:22,897 - __main__.py:127 - DEBUG - install minicap.so
2018-08-06 16:54:23,186 - __main__.py:76 - DEBUG - download from https://github.com/openatx/stf-binaries/raw/master/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-28/minicap.so
```

**Comment by codeskyblue** [comment]
waiting for minicap support android p

**Comment by mingyuan-xia** [comment]
minicap P support has arrived. Please retry.

**Comment by gamesguru** [comment]
marking as fixed on good faith. no longer have access to test phones

**Comment by gamesguru** [comment]
I tested it on an emulator.

Basic commands are working.  No signs of trouble
