### ISSUE TITLE
Unable to unlock or perform any u2 command  when screen off + WiFi on

### ISSUE THREAD

**Issue by gamesguru** [openatx/uiautomator2#189]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

I am running through these steps
```
d.connect()
d.unlock() or d.press('home') or similar 
```
the second command is not very reliable if the phone screen starts in off state

sometimes takes only a couple seconds, but sometimes 20 or 40 seconds, or more than 60 which causes below exception.

Please let me know ways to mitigate this issue.

Regards.

```
currently 2 devices attached, press enter to begin...
getting devices ready...
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.0.4', port=7912): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ocast3.py", line 104, in <module>
    threading.Thread(wifi_devices.append(wifi_device(_wifi_deviceip))).start()
  File "/media/shane/RaptorWS/PythonProjects/ocast3/adb_utils.py", line 96, in __init__
    self.x = self.u2.info['displayWidth'] 
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 1031, in __getattr__
    return getattr(self._default_session, attr)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 1530, in info
    return self.jsonrpc.deviceInfo()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 393, in __call__
    params, http_timeout)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 400, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 438, in jsonrpc_call
    data=data)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 264, in request
    method, url, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.0.4', port=7912): Read timed out. (read timeout=60)

















another example..

currently 2 devices attached, press enter to begin...
getting devices ready...
lge     LGLS770  (6.0.0) [v2.8.0 (572) | v0.0.0 (0)] \\ 1729-61-02583b4 // (LGLS7706fa
samsung SM-G900P (6.0.1) [v2.7.1 (570) | v0.0.0 (0)] \\ G900-PV-PS3CQD1 // (5eda6153)
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.0.2', port=7912): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/media/shane/RaptorWS/PythonProjects/ocast3/adb_utils.py", line 103, in screen_on
    d.u2.unlock()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 864, in unlock
    self.open_identify()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 874, in open_identify
    'com.github.uiautomator/.IdentifyActivity', '-e', 'theme', theme
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 706, in shell
    'timeout': str(timeout)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 264, in request
    method, url, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.0.2', port=7912): Read timed out. (read timeout=60)

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.0.4', port=7912): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/media/shane/RaptorWS/PythonProjects/ocast3/adb_utils.py", line 103, in screen_on
    d.u2.unlock()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 864, in unlock
    self.open_identify()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 874, in open_identify
    'com.github.uiautomator/.IdentifyActivity', '-e', 'theme', theme
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 706, in shell
    'timeout': str(timeout)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 264, in request
    method, url, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.0.4', port=7912): Read timed out. (read timeout=60)

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.0.4', port=7912): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ocast3.py", line 116, in <module>
    activate_pkg(d)
  File "/media/shane/RaptorWS/PythonProjects/ocast3/adb_utils.py", line 106, in activate_pkg
    d.u2.app_start(pkg)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 780, in app_start
    'android.intent.category.LAUNCHER', '1'
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 706, in shell
    'timeout': str(timeout)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__init__.py", line 264, in request
    method, url, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.0.4', port=7912): Read timed out. (read timeout=60)

```

**Comment by codeskyblue** [comment]
yes. unlock is very stable, do you have some idea?

**Comment by gamesguru** [comment]
Are you able to reproduce this at all, by doing different scripts all starting with the screen off? WiFi only, USB is totally reliable here.

thought it was power saving mode on that device, but disabling it didn't work.

I looked at the exceptions, it is not always happening at `unlock()`, my errors are at `u2.app_start()` and `u2.info['displayWidth']`

see, i had thought the phone was good at returning basic information such as `d.info` when the screen is off... but there too it appears unreliable

**Comment by codeskyblue** [comment]
bad spell. I mean not very stable.

**Comment by gamesguru** [comment]
do you think having two more more phones hurts?  I didn't run into this issue today briefly with one phone only
I don't think it is an "unlock" issue, but rather it's a can't send a command 100% of the time "when the screen is off" issue.

I'll look at the logs again and think it over

**Comment by mingyuan-xia** [comment]
newer Android aggressively apply deep-sleep when screen is off for a while, even CPU is in low-frequency mode. The best is to keep device awake during tests.
