### ISSUE TITLE
uiautomator2.UiaError

### ISSUE THREAD

**Issue by youbaowu** [openatx/uiautomator2#19]
```
Traceback (most recent call last):
  File "D:/Django/project/OneKeyTest/Backend/UIAutomator/OpenSDKUIAuto.py", line 128, in <module>
    print d.info
  File "D:\Django\python\lib\site-packages\uiautomator2\__init__.py", line 523, in __getattr__
    return getattr(self._default_session, attr)
  File "D:\Django\python\lib\site-packages\uiautomator2\__init__.py", line 809, in info
    return self.jsonrpc.deviceInfo()
  File "D:\Django\python\lib\site-packages\uiautomator2\__init__.py", line 192, in __call__
    return self.server.jsonrpc_call(self.method, params)
  File "D:\Django\python\lib\site-packages\uiautomator2\__init__.py", line 216, in jsonrpc_call
    raise UiaError(self._server_jsonrpc_url, data, res.status_code, res.text, "HTTP Return code is not 200", res.text)
uiautomator2.UiaError: ('http://127.0.0.1:60334/jsonrpc/0', '{"params": {}, "jsonrpc": "2.0", "id": "c55179c4c0cb2c166427bb3d61963236", "method": "deviceInfo"}', 504.
```

**Comment by youbaowu** [comment]
Do you know how to solve it?

**Comment by codeskyblue** [comment]
format with markdown first, it is too difficult to see your log

**Comment by youbaowu** [comment]
Hi, format with markdown as follows:

Error type 3
Error: Activity class {com.github.uiautomator/com.github.uiautomator.MainActivity} does not exist.
Traceback (most recent call last):
  File "D:/Django/project/OneKeyTest/Backend/UIAutomator/OpenSDKUIAutomator2.py", line 128, in <module>
    print d.info
  File "D:\Django\python\lib\site-packages\uiautomator2\__init__.py", line 523, in __getattr__
    return getattr(self._default_session, attr)
  File "D:\Django\python\lib\site-packages\uiautomator2\__init__.py", line 809, in info
    return self.jsonrpc.deviceInfo()
  File "D:\Django\python\lib\site-packages\uiautomator2\__init__.py", line 192, in __call__
    return self.server.jsonrpc_call(self.method, params)
  File "D:\Django\python\lib\site-packages\uiautomator2\__init__.py", line 216, in jsonrpc_call
    raise UiaError(self._server_jsonrpc_url, data, res.status_code, res.text, "HTTP Return code is not 200", res.text)
uiautomator2.UiaError: ('http://127.0.0.1:20247/jsonrpc/0', '{"params": {}, "jsonrpc": "2.0", "id": "cf841cd3071163f203d7499c1dd10fc4", "method": "deviceInfo"}', 504.

**Comment by codeskyblue** [comment]
重新 `python -muiautomator2 int`一下吧

**Comment by youbaowu** [comment]
已试过重新 python -muiautomator2 int、重新 python -m uiautomator2 init --reinstall、恢复出厂设置等操作，都不行。

**Comment by codeskyblue** [comment]
来点日志截图，什么的

**Comment by laiyuncong8404** [comment]
我也遇到同样的问题
**环境**
python -m atx version
1.1.3.dev36
pip list uiautomator2
0.0.3.dev13
Android--4.4.4
python--2.7
`log如下`
```shell
Shell$ curl -X POST -d '{"params": [{"childOrSiblingSelector": [], "mask": 2, "textContains": "\u624b\u52bf\u5bc6\u7801\u767b\u5f55", "childOrSibling": []}], "jsonrpc": "2.0", "id": "f7219e2f0664e3969ccbadc089df706b", "method": "exist"}' http://192.168.199.108:7912/jsonrpc/0
Output> 
Traceback (most recent call last):
  File "/Users/xiaoxue/Desktop/daKa.py", line 71, in <module>
    test_run()
  File "/Users/xiaoxue/Desktop/daKa.py", line 39, in test_run
    if d(textContains=u'手势密码登录').exists:
  File "/Users/xiaoxue/Library/Python/2.7/lib/python/site-packages/uiautomator2/__init__.py", line 898, in exists
    return self.jsonrpc.exist(self.selector)
  File "/Users/xiaoxue/Library/Python/2.7/lib/python/site-packages/uiautomator2/__init__.py", line 195, in __call__
    return self.server.jsonrpc_call(self.method, params, http_timeout)
  File "/Users/xiaoxue/Library/Python/2.7/lib/python/site-packages/uiautomator2/__init__.py", line 219, in jsonrpc_call
    raise UiaError(self._server_jsonrpc_url, data, res.status_code, res.text, "HTTP Return code is not 200", res.text)
uiautomator2.UiaError: ('http://192.168.199.108:7912/jsonrpc/0', '{"params": [{"childOrSiblingSelector": [], "mask": 2, "textContains": "\\u624b\\u52bf\\u5bc6\\u7801\\u767b\\u5f55", "childOrSibling": []}], "jsonrpc": "2.0", "id": "f7219e2f0664e3969ccbadc089df706b", "method": "exist"}', 502, u'', 'HTTP Return code is not 200', u'')
```

**Comment by codeskyblue** [comment]
不用混用atx和uiautomator2，另外你那个错误感觉是apk没装对

**Comment by laiyuncong8404** [comment]
> 不要混用atx和uiautomator2，另外你那个错误感觉是apk没装对
没懂呢？我应该没有混用atx和uiautomator2，代码都是用uiautomator2的API写的。
APK确认是对的，应为启动成功，只是进行元素定位的时候报错了。我换成resourceId定位，还是报错。
求指导:)

**Comment by codeskyblue** [comment]
更新到最新版重试下

**Comment by mingyuan-xia** [comment]
@laiyuncong8404 @youbaowu 请到手机上卸载uiautomator名字的apk，然后下载最新版本的u2，然后重新`python -m uiautomator2 init` 然后测试连接，如果还有问题，请post log到这里，否则两天后关了
