### ISSUE TITLE
使用pycharm作为IDE，连接usb的时候会报错，如果用wifi的话是正常的。

### ISSUE THREAD

**Issue by xhxt2008** [openatx/uiautomator2#191]
#### 这是我的代码
```
import uiautomator2 as u2

u = u2.connect_usb()
u.make_toast("Hello world", 3)
```
#### 这是报错
```
D:\ProgramData\Anaconda3\python.exe C:/code/PyCharm/test01/1.py
Traceback (most recent call last):
  File "C:/code/PyCharm/test01/1.py", line 3, in <module>
    u = u2.connect_usb()
  File "D:\ProgramData\Anaconda3\lib\site-packages\uiautomator2\__init__.py", line 225, in connect_usb
    lport = adb.forward_port(7912)
  File "D:\ProgramData\Anaconda3\lib\site-packages\uiautomator2\adbutils.py", line 104, in forward_port
    forwards = self.forward_list()
  File "D:\ProgramData\Anaconda3\lib\site-packages\uiautomator2\adbutils.py", line 92, in forward_list
    output = self.execute('forward', '--list')
  File "D:\ProgramData\Anaconda3\lib\site-packages\uiautomator2\adbutils.py", line 49, in execute
    assert adb_path is not None
AssertionError
```

#### Versions (版本)
0.1.4dev3

#### Issue and steps to reproduce (复现步骤)
使用pycharm作为IDE，连接usb的时候会报错，如果用wifi的话是正常的。奇怪的是用anaconda则都是正常的。

- 手机型号?
sony z3

**Comment by codeskyblue** [comment]
PATH中需要有adb的
