### ISSUE TITLE
使用--serial对指定手机安装uiautomator2时老是报错

### ISSUE THREAD

**Issue by cairuichun** [openatx/uiautomator2#192]
服务器连接了两部手机，使用python -m uiautomator2 init两台手机安装正常，但当用--serial指定手机安装时就老是报错
```
C:\Users\Administrator>python -m uiautomator2 init  --mirror --serial $SJxxxxxx
2018-08-15 11:56:58,236 - __main__.py:228 - INFO - atx-server addr --mirror
2018-08-15 11:56:58,368 - __main__.py:243 - INFO - Device(SJE5T17907002202) init
ialing ...
2018-08-15 11:56:59,407 - __main__.py:110 - INFO - install minicap
2018-08-15 11:57:00,006 - __main__.py:117 - INFO - install minitouch
2018-08-15 11:57:03,094 - __main__.py:138 - INFO - app-uiautomator.apk(--serial)
 installing ...
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\uiautomator2\__main__.py", line 305, in <m
odule>
    main()
  File "C:\Python27\lib\site-packages\uiautomator2\__main__.py", line 301, in ma
in
    fire.Fire(MyFire)
  File "C:\Python27\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Python27\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Python27\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "C:\Python27\lib\site-packages\uiautomator2\__main__.py", line 248, in in
it
    ins.install_uiautomator_apk(apk_version, reinstall)
  File "C:\Python27\lib\site-packages\uiautomator2\__main__.py", line 139, in in
stall_uiautomator_apk
    path = cache_download(app_url)
  File "C:\Python27\lib\site-packages\uiautomator2\__main__.py", line 73, in cac
he_download
    raise Exception("status code", r.status_code)
Exception: ('status code', 404)
```

**Comment by codeskyblue** [comment]
感觉好像是版本低，升级下试试

**Comment by cairuichun** [comment]
我拿了一部Android8.1系统的手机试了下，还是报同样的错

**Comment by cairuichun** [comment]
我拿了一部Android8.1系统的手机试了下，还是报同样的错

**Comment by codeskyblue** [comment]
`pip show uiautomator2` 看下版本号

**Comment by cairuichun** [comment]
确实是uiautomator2的版本太低导致的，重新安装后现在已经可以正常用--serial进行安装了，谢谢
