### ISSUE TITLE
init with --serial gives "inf" as serial?

### ISSUE THREAD

**Issue by gamesguru** [openatx/uiautomator2#206]
Affects v0.1.3 and some dev builds at least.  When I have twenty devices plugged in, one or two almost always get left out.

Error message
```
$ adb -s 87681e28689700000000 shell getprop ro.build.version.sdk 
19

$ python3 -m uiautomator2 init --serial 87681e28689700000000
2018-08-29 10:05:49,092 - __main__.py:330 - INFO - Device(inf) initialing ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/adbutils.py", line 55, in execute
    cmdline, stderr=subprocess.STDOUT, shell=True).decode('utf-8')
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/home/android/sdk/platform-tools/adb -s inf shell getprop ro.build.version.sdk' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/__main__.py", line 410, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/__main__.py", line 406, in main
    fire.Fire(MyFire)
  File "/users/shane/.local/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/users/shane/.local/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/users/shane/.local/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/__main__.py", line 326, in init
    reinstall, ignore_apk_check)
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/__main__.py", line 331, in _init_with_serial
    ins = Installer(serial)
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/__main__.py", line 97, in __init__
    self.sdk = self.getprop('ro.build.version.sdk')
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/adbutils.py", line 117, in getprop
    return self.execute('shell', 'getprop', prop).strip()
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/adbutils.py", line 60, in execute
    'utf-8', errors='ignore'))
OSError: [Errno subprocess] /home/android/sdk/platform-tools/adb -s inf shell getprop ro.build.version.sdk: "error: device 'inf' not found\n"

```

## Additional Details （其他信息）
From __main__.py (see comments)
```
class MyFire(object):
    def init(self,
             server=None,
             apk_version=__apk_version__,
             agent_version=__atx_agent_version__,
             verbose=False,
             reinstall=False,
             ignore_apk_check=False,
             proxy=None,
             serial=None,
             mirror=False):
        print(serial) #Issue is already present here, with "inf" reported as a valid serial?
...
...
...
...
        if not serial:
            valid_serials = [
                sn for sn, _ in adbutils.Adb().devices(states=['device'])
            ]
            # output = subprocess.check_output(['adb', 'devices'])
            # pattern = re.compile(
            #     r'(?P<serial>[^\s]+)\t(?P<status>device|offline)')
            # matches = pattern.findall(output.decode())
            # valid_serials = [m[0] for m in matches if m[1] == 'device']
            if len(valid_serials) == 0:
                log.warning("No avaliable android devices detected.")
                return
            log.info("Detect pluged devices: %s", valid_serials)
            for serial in valid_serials:
                self._init_with_serial(serial, server, apk_version,
                                       agent_version, reinstall,
                                       ignore_apk_check)
        else:
            print(serial) #Issue is already present here, with "inf" reported as a valid serial?
            self._init_with_serial(serial, server, apk_version, agent_version,
                                   reinstall, ignore_apk_check)
```

**Comment by codeskyblue** [comment]
Let me see adb devices output

**Comment by gamesguru** [comment]
sir, the output as requested.  I am looking for a speedy solution to this bug. Let me know if I may be of further help.

```
shane@garageStation:/home/testlib/src$ adb devices
List of devices attached
03501ad6d8d500000000	device
86501b36981700000000	device
86509ab6f76700000000	device
86509b37980700000000	device
87281d27675700000000	device
87281d28975700000000	device
87281d58669700000000	device
873c1c86d6b700000000	device
873c1c87a6d700000000	device
873c1c89571700000000	device
873c1ca7a7f700000000	device
873c1cc9885700000000	device
873c9ce8a80700000000	device
873c9d5789a700000000	device
87681e28689700000000	device
87681ec9683700000000	device
87689e28c7a700000000	device
87689ef7d6a700000000	device
87689f36e92700000000	device
87689f7818e700000000	device

shane@garageStation:/home/testlib/src$ adb devices -l
List of devices attached
03501ad6d8d500000000   device usb:1-7.5.7.6 product:astar_uarmmid model:OCTP_7 device:astar-uarmmid transport_id:60
86501b36981700000000   device usb:1-7.7.2 product:astar_uarmmid model:OCTP_7 device:astar-uarmmid transport_id:68
86509ab6f76700000000   device usb:1-7.7.6 product:astar_uarmmid model:OCTP_7 device:astar-uarmmid transport_id:58
86509b37980700000000   device usb:1-7.5.2 product:astar_uarmmid model:OCTP_7 device:astar-uarmmid transport_id:52
87281d27675700000000   device usb:1-7.7.5 product:astar_uarmmid model:OCTP_5 device:astar-uarmmid transport_id:64
87281d28975700000000   device usb:1-7.5.7.5 product:astar_uarmmid model:OCTP_5 device:astar-uarmmid transport_id:65
87281d58669700000000   device usb:1-7.5.7.3 product:astar_uarmmid model:OCTP_5 device:astar-uarmmid transport_id:54
873c1c86d6b700000000   device usb:1-7.7.7 product:astar_uarmmid model:OCTP_7 device:astar-uarmmid transport_id:56
873c1c87a6d700000000   device usb:1-7.5.7.7 product:astar_uarmmid model:OCTP_7 device:astar-uarmmid transport_id:59
873c1c89571700000000   device usb:1-7.5.3 product:astar_uarmmid model:OCTP_7 device:astar-uarmmid transport_id:69
873c1ca7a7f700000000   device usb:1-7.5.4 product:astar_uarmmid model:OCTP_5 device:astar-uarmmid transport_id:66
873c1cc9885700000000   device usb:1-7.5.7.2 product:astar_uarmmid model:OCTP_7 device:astar-uarmmid transport_id:57
873c9ce8a80700000000   device usb:1-7.3 product:astar_uarmmid model:OCTP_7 device:astar-uarmmid transport_id:67
873c9d5789a700000000   device usb:1-7.5.6 product:astar_uarmmid model:OCTP_7 device:astar-uarmmid transport_id:62
87681e28689700000000   device usb:1-7.5.5 product:astar_uarmmid model:OCTP_5 device:astar-uarmmid transport_id:71
87681ec9683700000000   device usb:1-7.7.3 product:astar_uarmmid model:OCTP_5 device:astar-uarmmid transport_id:51
87689e28c7a700000000   device usb:1-7.5.1 product:astar_uarmmid model:OCTP_5 device:astar-uarmmid transport_id:55
87689ef7d6a700000000   device usb:1-7.7.4 product:astar_uarmmid model:OCTP_5 device:astar-uarmmid transport_id:53
87689f36e92700000000   device usb:1-7.5.7.4 product:astar_uarmmid model:OCTP_5 device:astar-uarmmid transport_id:70
87689f7818e700000000   device usb:1-7.4 product:astar_uarmmid model:OCTP_5 device:astar-uarmmid transport_id:61

```

**Comment by codeskyblue** [comment]
Try to update uiautomator2 to latest version, and try again.
`pip install -U --pre uiautomator2`

**Comment by gamesguru** [comment]
thanks but same issue.

where does it store the serials, or does it fetch them each time?

**Comment by codeskyblue** [comment]
![image](https://user-images.githubusercontent.com/3281689/44889991-e8188780-ad0a-11e8-967a-5bee4c114c6d.png)

I guess, there are two version of adb in your computer.

**Comment by gamesguru** [comment]
any way we can set up an experimental branch?  i would like to push in some simpler ideas, for example
```
_devices = []
output = ['test\tdevice','test2\tdevice','test3\tdevice']
for line in output:
    if '\tdevice' in line:
        _devices.append((line.split('\t')[0], 'device'))
print(_devices)

outputs:
[('test', 'device'), ('test2', 'device'), ('test3', 'device')]

then you simply,
return _devices
```
there are more options, but only "devices" concerns us ['connecting', 'unauthorized','unknown',bootloader','recovery']  

and there are not two versions of adb.  there are two versions of your stuff, because windows is behind a version (why? 0.1.2 vs 0.1.3)
```
shane@garageStation:~$ whereis adb
adb: /home/android/sdk/platform-tools/adb

shane@garageStation:~$ adb version
Android Debug Bridge version 1.0.40
Version 4797878
```

**Comment by codeskyblue** [comment]
have you found why inf show up?

**Comment by gamesguru** [comment]
not yet, but if I run init without --serial, it works on all 20. so it seems to parse two different ways!

**Comment by codeskyblue** [comment]
the newest version is 1.0.4.dev.. try to update uiautomator2 and try again

**Comment by gamesguru** [comment]
am not at work but it seems to be working based on this test.  But I am still unsettled by how you prefer import re over string.split, as the former is likelier to break than the latter and also more CPU intensive. 

```
import re

input = b'03501ad6d8d500000000	device\n86501b36981700000000	device\n86509ab6f76700000000	device\n86509b37980700000000	device\n87281d27675700000000	device\n87281d28975700000000	device\n87281d58669700000000	device\n873c1c86d6b700000000	device\n873c1c87a6d700000000	device\n873c1c89571700000000	device\n873c1ca7a7f700000000	device\n873c1cc9885700000000	device\n873c9ce8a80700000000	device\n873c9d5789a700000000	device\n87681e28689700000000	device\n87681ec9683700000000	device\n87689e28c7a700000000	device\n87689ef7d6a700000000	device\n87689f36e92700000000	device\n87689f7818e700000000	device'

pattern = re.compile(r'(?P<serial>[^\s]+)\t(?P<status>device|offline)')
matches = pattern.findall(input.decode())

print(len(matches))
for m in matches:
    print(m)


output:
20
('03501ad6d8d500000000', 'device')
('86501b36981700000000', 'device')
('86509ab6f76700000000', 'device')
('86509b37980700000000', 'device')
('87281d27675700000000', 'device')
('87281d28975700000000', 'device')
('87281d58669700000000', 'device')
('873c1c86d6b700000000', 'device')
('873c1c87a6d700000000', 'device')
('873c1c89571700000000', 'device')
('873c1ca7a7f700000000', 'device')
('873c1cc9885700000000', 'device')
('873c9ce8a80700000000', 'device')
('873c9d5789a700000000', 'device')
('87681e28689700000000', 'device')
('87681ec9683700000000', 'device')
('87689e28c7a700000000', 'device')
('87689ef7d6a700000000', 'device')
('87689f36e92700000000', 'device')
('87689f7818e700000000', 'device')
```

**Comment by gamesguru** [comment]
updating didn't solve it.  Are you sure the serials are coming from only that one place?  If so, I'll test my string.split() changes.  Can you merge that in if it works simply and well?

I would like to continue to receive your updates, but not if they break my setups.  Your work is good but you need to learn to share the responsibilities with others.

```
ids-testers@trusty:~$ pip3 show uiautomator2
Name: uiautomator2
Version: 0.1.3.dev40
```

The issue
```
ids-testers@trusty:/home/testlib/src/ocast3$ python3 -m uiautomator2 init --serial 87681e28689700000000:
^C
ids-testers@trusty:/home/testlib/src/ocast3$ python3 -m uiautomator2 init --serial 87681e28689700000000
2018-09-04 11:56:55,384 - __main__.py:321 - INFO - Device(inf) initialing ...
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/adbutils.py", line 55, in execute
    cmdline, stderr=subprocess.STDOUT, shell=True).decode('utf-8')
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/home/android/sdk/platform-tools/adb -s inf shell getprop ro.build.version.sdk' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__main__.py", line 394, in <module>
    main()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__main__.py", line 390, in main
    fire.Fire(MyFire)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__main__.py", line 317, in init
    reinstall, ignore_apk_check)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__main__.py", line 322, in _init_with_serial
    ins = Installer(serial)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/__main__.py", line 97, in __init__
    self.sdk = self.getprop('ro.build.version.sdk')
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/adbutils.py", line 117, in getprop
    return self.execute('shell', 'getprop', prop).strip()
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/site-packages/uiautomator2/adbutils.py", line 60, in execute
    'utf-8', errors='ignore'))
OSError: [Errno subprocess] /home/android/sdk/platform-tools/adb -s inf shell getprop ro.build.version.sdk: "error: device 'inf' not found\n"
```

adb devices output
```
ids-testers@trusty:~$ adb devices
List of devices attached
03501ad6d8d500000000	device
86501b36981700000000	device
86509ab6f76700000000	device
86509b37980700000000	device
87281d27675700000000	device
87281d28975700000000	device
87281d58669700000000	device
873c1c86d6b700000000	device
873c1c87a6d700000000	device
873c1c89571700000000	device
873c1ca7a7f700000000	device
873c1cc9885700000000	device
873c9ce8a80700000000	device
873c9d5789a700000000	device
87681e28689700000000	device
87681ec9683700000000	device
87689e28c7a700000000	device
87689ef7d6a700000000	device
87689f36e92700000000	device
87689f7818e700000000	device
```

**Comment by codeskyblue** [comment]
The latest version is `0.1.4.dev24`

**Comment by gamesguru** [comment]
I didn't receive that update.  I figured out why Windows PC is behind. Because it has python 3.7 and my Linux has 3.6.  Any reason that 3.7 is not supported anymore?

> $ pip3 install -v -v -v uiautomator2==0.1.4.dev24
> The package https://files.pythonhosted.org/packages/6f/68/fcab652093364b9de8dca47a531e3c7aef390f5780e5a26223bbaa40f32c/uiautomator2-0.1.4.dev25.tar.gz#sha256=d90d4b274397571bf8b2c07f71bc7563518dd7b9b61eab69dc5b224d68752a38 (from https://pypi.org/simple/uiautomator2/) (requires-python:>=2.7,!=3.7.*) is incompatible with the pythonversion in use. Acceptable python versions are:>=2.7,!=3.7.*

**Comment by gamesguru** [comment]
some of my linux guys had version 3.7.0 too.  But with 0.1.4.dev25 I can't connect at all... this is from the atx log, see bottom for full log.

> 1970/01/06 23:51:44 main.go:1431: start uiautomator err: exec: "sh": executable file not found in $PATH

```
$ python3 -m uiautomator2 init --serial 873c9d5789a700000000
2018-09-05 10:56:25,526 - __main__.py:330 - INFO - Device(873c9d5789a700000000) initialing ...
2018-09-05 10:56:25,702 - __main__.py:133 - INFO - install minicap
2018-09-05 10:56:25,845 - __main__.py:140 - INFO - install minitouch
2018-09-05 10:56:26,024 - __main__.py:168 - INFO - apk(1.1.5) already installed, skip
2018-09-05 10:56:26,113 - __main__.py:213 - INFO - atx-agent(0.4.2) already installed, skip
2018-09-05 10:56:26,240 - __main__.py:250 - INFO - launch atx-agent daemon
atx-agent output: 1970/01/07 00:01:35 [INFO][github.com/openatx/atx-agent] main.go:1397: Enter into daemon mode, listening on 127.0.0.1:7912
2018-09-05 10:56:27,871 - __main__.py:272 - INFO - success


$ bpython3
bpython version 0.17.1 on top of Python 3.6.5 /usr/bin/python3
>>> import uiautomator2 as 
>>> d=u2.connect('873c9d5789a700000000')
/usr/local/lib/python3.6/dist-packages/uiautomator2/__init__.py:242: RuntimeWarning: backend uiautomator2 is not alive, start again ...
  RuntimeWarning)
[2018-09-05 10:56:29] wait uiautomator is ready ...
[2018-09-05 10:56:48] wait uiautomator is ready ...
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    d=u2.connect('873c9d5789a700000000')
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/__init__.py", line 194, in connect
    return connect_usb(addr)
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/__init__.py", line 243, in connect_usb
    d.reset_uiautomator()
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/__init__.py", line 594, in reset_uiautomator
    "Uiautomator started failed. Find solutions in https://github.com/openatx/uiautomator2/wiki/Common-issues"
RuntimeError: Uiautomator started failed. Find solutions in https://github.com/openatx/uiautomator2/wiki/Common-issues

```

from atx log
```
$ adb -s 873c9d5789a700000000 shell cat /sdcard/atx-agent.log
1970/01/06 23:51:44 main.go:1377: Ignore SIGHUP
1970/01/06 23:51:44 main.go:1381: Kill server
1970/01/06 23:51:44 main.go:1387: Get http://127.0.0.1:7912/stop: dial tcp 127.0.0.1:7912: connect: connection refused
atx-agent version 0.3.6
Internet is not connected.1970/01/06 23:51:44 getprop.go:58: getgrop exec: "sh": executable file not found in $PATH
1970/01/06 23:51:44 main.go:1431: start uiautomator err: exec: "sh": executable file not found in $PATH
1970/01/06 23:51:44 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
1970/01/06 23:51:44 cmdctrl.go:27: DEBUG program finished
1970/01/06 23:51:44 reverseproxy.go:321: http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
1970/01/06 23:51:44 reverseproxy.go:321: http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
1970/01/06 23:51:48 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
1970/01/06 23:51:48 cmdctrl.go:27: DEBUG program finished
```

**Comment by gamesguru** [comment]
yeah, why am i getting this error in the atx log? I used dev25 by mistake, but am now onto 36 i think?

```
1970/01/09 00:30:04 [INFO][github.com/openatx/atx-agent] main.go:1402: daemon started
atx-agent version 0.4.2
Internet is not connected.1970/01/09 00:30:04 getgrop exec: "sh": executable file not found in $PATH
```

**Comment by codeskyblue** [comment]
looks like the 20 devices have same product and model. And the wiered thing is that there is no sh on you phone.

**Comment by gamesguru** [comment]
wait, apologies.  the issue is resolved after init

can we please spend some time looking at the difference between init and init with serial? because i feel the former is much stabler than the latter while the latter is what i seek use for long-term testing

**Comment by gamesguru** [comment]
hey, if i can make changes in 0.1.3 and get the issue fixed will you take look?

**Comment by gamesguru** [comment]
its fixed by updating and init.  something happened with dev25, not too worried about it

I'm still having the inf serial with 1/20.

You might be right, i noticed this issue after my boss had me flash the same Android on all 20 devices.

If I can fix the problem in 0.1.3 or the commit of your choice and test it on my setups, would you take a look at that?  We could swap emails or ssh keys?
```
$ python3 -m uiautomator2 init --serial 87681e28689700000000
2018-09-10 15:44:37,542 - __main__.py:330 - INFO - Device(inf) initialing ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/adbutils.py", line 55, in execute
    cmdline, stderr=subprocess.STDOUT, shell=True).decode('utf-8')
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/home/android/sdk/platform-tools/adb -s inf shell getprop ro.build.version.sdk' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/__main__.py", line 412, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/__main__.py", line 408, in main
    fire.Fire(MyFire)
  File "/users/shane/.local/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/users/shane/.local/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/users/shane/.local/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/__main__.py", line 326, in init
    reinstall, ignore_apk_check)
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/__main__.py", line 331, in _init_with_serial
    ins = Installer(serial)
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/__main__.py", line 97, in __init__
    self.sdk = self.getprop('ro.build.version.sdk')
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/adbutils.py", line 117, in getprop
    return self.execute('shell', 'getprop', prop).strip()
  File "/usr/local/lib/python3.6/dist-packages/uiautomator2/adbutils.py", line 60, in execute
    'utf-8', errors='ignore'))
OSError: [Errno subprocess] /home/android/sdk/platform-tools/adb -s inf shell getprop ro.build.version.sdk: "error: device 'inf' not found\n"
```

$ pip3 show uiautomator2
Name: uiautomator2
Version: 0.1.4.dev36

**Comment by codeskyblue** [comment]
pr is welcome

**Comment by gamesguru** [comment]
yeah yeah i will try

but do you want me to pull from 0.1.3 or from HEAD??

**Comment by gamesguru** [comment]
i'm getting closer to a solution, i will try to preserver regex (re) where possible.  have a look at these outputs, it's fascinating.

```
$ python3 -m uiautomator2 init --serial 87681e2868
subprocess.CalledProcessError: Command '/home/android/sdk/platform-tools/adb -s inf shell getprop ro.build.version.sdk' returned non-zero exit status 1.

$ python3 -m uiautomator2 init --serial 87681e286
subprocess.CalledProcessError: Command '/home/android/sdk/platform-tools/adb -s 8.7681e+290 shell getprop ro.build.version.sdk' returned non-zero exit status 1.

$ python3 -m uiautomator2 init --serial 87681e2
subprocess.CalledProcessError: Command '/home/android/sdk/platform-tools/adb -s 8768100.0 shell getprop ro.build.version.sdk' returned non-zero exit status 1.

$ python3 -m uiautomator2 init --serial 87681e
subprocess.CalledProcessError: Command '/home/android/sdk/platform-tools/adb -s 87681e shell getprop ro.build.version.sdk' returned non-zero exit status 1.
```

**Comment by gamesguru** [comment]
@codeskyblue 
I tested the above commit.  It is working with normal serials, with or without the str: prefix.  Floating point serials (which should be rare in the wild) now cause a crash, because floats don't have a split() attribute.

A user would hopefully have their attention drawn to this exception and figure out how to properly use the method.

Cheers.

**Comment by codeskyblue** [comment]
maybe I should change googleq fire into other cli parser lib
