### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal character

### ISSUE THREAD

**Issue by dedecn** [openatx/uiautomator2#207]
报错log如下
```
[E 180830 09:46:31 web:1621] Uncaught exception GET /api/v1/devices/db71650b-4680-4056-9332-b0f84e778c68/hierarchy (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/api/v1/devices/db71650b-4680-4056-9332-b0f84e778c68/hierarchy', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\tornado\web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Python27\lib\site-packages\weditor\__main__.py", line 272, in get
        self.write(uidumplib.get_android_hierarchy(d))
      File "C:\Python27\lib\site-packages\weditor\uidumplib.py", line 103, in get_android_hierarchy
        page_xml = d.dump_hierarchy(compressed=False, pretty=False).encode('utf-8')
      File "<decorator-gen-4>", line 2, in dump_hierarchy
      File "C:\Python27\lib\site-packages\retry\api.py", line 74, in retry_decorator
        logger)
      File "C:\Python27\lib\site-packages\retry\api.py", line 33, in __retry_internal
        return f()
      File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 1415, in dump_hierarchy
        content = self.jsonrpc.dumpWindowHierarchy(compressed, None)
      File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 398, in __call__
        params, http_timeout)
      File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 405, in jsonrpc_retry_call
        return self.jsonrpc_call(*args, **kwargs)
      File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 483, in jsonrpc_call
        raise err
    JsonRpcError: -32001 Jsonrpc error: <java.lang.IllegalArgumentException> data: java.lang.IllegalArgumentException: Illegal character (d83d)
        at org.kxml2.io.KXmlSerializer.reportInvalidCharacter(KXmlSerializer.java:144)
        at org.kxml2.io.KXmlSerializer.writeEscaped(KXmlSerializer.java:130)
        at org.kxml2.io.KXmlSerializer.attribute(KXmlSerializer.java:465)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:63)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:86)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:86)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:86)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:86)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:86)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:86)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:86)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:86)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:86)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:86)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:86)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:86)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:86)
        at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpWindowHierarchy(AccessibilityNodeInfoDumper.java:50)
        at android.support.test.uiautomator.UiDevice.dumpWindowHierarchy(UiDevice.java:945)
        at com.github.uiautomator.stub.AutomatorServiceImpl.dumpWindowHierarchy(AutomatorServiceImpl.java:239)
        at com.github.uiautomator.stub.AutomatorServiceImpl.dumpWindowHierarchy(AutomatorServiceImpl.java:225)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
        at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
        at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:841)
    , method: dumpWindowHierarchy
```

## Versions (版本)
0.1.4.dev21

## Issue and steps to reproduce (复现步骤)
在微博app页面，我关注的人，用WEditor获取界面层级，报这个错，应该是jsonrpc序列化/反序列化时不支持某些字符

用的夜神模拟器

**Comment by dedecn** [comment]
应该是android.support.test.uiautomator的版本比较低，可以升一下版本吗？
我看android他们源码已经修了这个问题
https://android.googlesource.com/platform/frameworks/testing/+/2b6d1da16a4e38a9704c2c67b33aadf44a85b1d2

**Comment by codeskyblue** [comment]
![image](https://user-images.githubusercontent.com/3281689/44844728-4cd9d080-ac7e-11e8-9585-6d2b819320d7.png)
2014年改的，现在肯定已经升级过了

**Comment by dedecn** [comment]
![image](https://user-images.githubusercontent.com/3785827/44850146-e9a46a00-ac8e-11e8-8be0-8080a59d98d7.png)

从android源码的diff看，新代码的这个函数是用StringBuilder了，但从以下地址下载的apk反编译后看到的这个函数还是用旧代码的StringBuffer

![image](https://user-images.githubusercontent.com/3785827/44850212-18badb80-ac8f-11e8-9e4c-edbdbea9f053.png)

apk下载地址是
https://github.com/openatx/android-uiautomator-server/releases/download/1.1.5/app-uiautomator-test.apk

会不会是这个apk编译时用的lib还是旧版本的？

**Comment by dedecn** [comment]
appium他们是重写了这个类
![image](https://user-images.githubusercontent.com/3785827/44853652-18bfd900-ac99-11e8-9f3b-eb047258aadb.png)

https://www.javatips.net/api/appium-android-bootstrap-master/bootstrap/src/io/appium/uiautomator/core/AccessibilityNodeInfoDumper.java

**Comment by dedecn** [comment]
上面那个版本的appium也有问题，下面这个版本才没问题。。。
https://github.com/appium/appium-espresso-driver/blob/bda2bc9398731a01bd8a81d13889447a1d802151/espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java

**Comment by codeskyblue** [comment]
android.support.test.uiautomator 已经最新了
<https://github.com/openatx/android-uiautomator-server/blob/master/app/build.gradle#L96>
编译是在trivis上编译的

**Comment by codeskyblue** [comment]
我的java不是很精通，你有什么修改的意见吗？

**Comment by mingyuan-xia** [comment]
欢迎在android-uiautomator-server PR

**Comment by mingyuan-xia** [comment]
目前maven上google发布的最新版本的  https://mvnrepository.com/artifact/com.android.support.test.uiautomator/uiautomator-v18/2.1.3
还是用的StringBuffer这个老版本，说明14年这个没有发布。我看了下最新的代码：
https://android.googlesource.com/platform/frameworks/testing/+/master/uiautomator/library/core-src/com/android/uiautomator/core/AccessibilityNodeInfoDumper.java
自14年这个commit后就没有更新，解决方案可从googlesource弄下来，build出jar来以来，放弃maven的旧版本

**Comment by mingyuan-xia** [comment]
方案是直接拷贝新代码过来去除这个旧依赖  我来弄

**Comment by codeskyblue** [comment]
代码我抠出来了，放到分支里面了 https://github.com/openatx/android-uiautomator-server/tree/fix-dump @mingyuan-xia

**Comment by mingyuan-xia** [comment]
https://github.com/openatx/android-uiautomator-server/pull/19
