### ISSUE TITLE
Android P 設備連接失敗

### ISSUE THREAD

**Issue by derekhsieh** [openatx/uiautomator2#217]
請問是否可以支持Android P?
python -m uiautomator2 init後, Android P Google Pixel 2設備連接過程出現錯誤, atx-agent.log如下

```
INSTRUMENTATION_CODE: -1
2008/12/31 16:18:58 DEBUG cmd wait err: <nil>
2008/12/31 16:18:58 DEBUG idle for 500ms
2008/12/31 16:18:58 http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
2008/12/31 16:18:59 DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
2008/12/31 16:18:59 DEBUG program pid: 8254
2008/12/31 16:18:59 http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.github.uiautomator.stub.Stub:
INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS_CODE: 1
2008/12/31 16:19:01 http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stack=java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.github.uiautomator.ACTION_STOP }
	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1531)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1572)
	at android.app.ContextImpl.startService(ContextImpl.java:1544)
	at com.github.uiautomator.stub.Stub.tearDown(Stub.java:126)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2152)

INSTRUMENTATION_STATUS: stream=
Error in testUIAutomatorStub(com.github.uiautomator.stub.Stub):
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.github.uiautomator.ACTION_STOP }
	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1531)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1572)
	at android.app.ContextImpl.startService(ContextImpl.java:1544)
	at com.github.uiautomator.stub.Stub.tearDown(Stub.java:126)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2152)

INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS_CODE: -2
INSTRUMENTATION_RESULT: stream=

Time: 1.083
There were 2 failures:
1) testUIAutomatorStub(com.github.uiautomator.stub.Stub)
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.github.uiautomator.ACTION_START }
	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1531)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1572)
	at android.app.ContextImpl.startService(ContextImpl.java:1544)
	at com.github.uiautomator.stub.Stub.launchService(Stub.java:119)
	at com.github.uiautomator.stub.Stub.setUp(Stub.java:72)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2152)
2) testUIAutomatorStub(com.github.uiautomator.stub.Stub)
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.github.uiautomator.ACTION_STOP }
	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1531)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1572)
	at android.app.ContextImpl.startService(ContextImpl.java:1544)
	at com.github.uiautomator.stub.Stub.tearDown(Stub.java:126)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2152)

FAILURES!!!
Tests run: 1,  Failures: 2


INSTRUMENTATION_CODE: -1
2008/12/31 16:19:01 DEBUG cmd wait err: <nil>
2008/12/31 16:19:01 DEBUG idle for 500ms
2008/12/31 16:19:02 http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
2008/12/31 16:19:02 DEBUG program finished
2008/12/31 16:19:02 [INFO][github.com/openatx/atx-agent] main.go:1448: service uiautomator: stopservice com.github.uiautomator/.Service
2008/12/31 16:19:03 http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
2008/12/31 16:19:04 http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
2008/12/31 16:19:05 http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
2008/12/31 16:19:06 http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
2008/12/31 16:19:07 http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
2008/12/31 16:19:08 http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
2008/12/31 16:19:09 http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
2008/12/31 16:19:10 http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
```

## Versions (版本)
0.1.3

## Issue and steps to reproduce (复现步骤)
1. python -m uiautomator2 init
2. d = u2.connect("XXXX")

- 手機型號
Google Pixel 2

- 错误日志
```
>>> cmd.CommandWithTimeout("python -m uiautomator2 init")
[Cmd] python -m uiautomator2 init
'atx-agent output: 2008/12/31 16:23:09 [INFO][github.com/openatx/atx-agent] main.go:1397: Enter into daemon mode, listening on 127.0.0.1:7912\n'
>>> d = u2.connect("123456789")
Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
Starting new HTTP connection (1): 127.0.0.1
http://127.0.0.1:60024 "GET /version HTTP/1.1" 200 5
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
http://127.0.0.1:60024 "POST /shell HTTP/1.1" 200 239
http://127.0.0.1:60024 "DELETE /uiautomator HTTP/1.1" 200 7
http://127.0.0.1:60024 "POST /shell HTTP/1.1" 200 136
http://127.0.0.1:60024 "POST /uiautomator HTTP/1.1" 200 7
[2018-09-18 11:24:32] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:33] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:34] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:35] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:36] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:37] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:38] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:39] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:40] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:41] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:42] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:43] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:44] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:45] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:46] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:47] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:48] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:49] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:50] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
[2018-09-18 11:24:51] wait uiautomator is ready ...
http://127.0.0.1:60024 "GET /ping HTTP/1.1" 502 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uiautomator2\__init__.py", line 191, in connect
    return connect_usb(addr)
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uiautomator2\__init__.py", line 240, in connect_usb
    d.healthcheck()
  File "C:\Users\derekpchsieh\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uiautomator2\__init__.py", line 588, in healthcheck
    raise RuntimeError("Uiautomator started failed.")
RuntimeError: Uiautomator started failed.
```

## Additional Details （其他信息）

**Comment by derekhsieh** [comment]
剛嘗試在連接過程中...手動Launch uiautomator app...
有機會可以連接上
'''
[2018-09-18 17:15:07] uiautomator is starting ...
http://127.0.0.1:57267 "GET /ping HTTP/1.1" 502 0
[2018-09-18 17:15:08] uiautomator is starting ...
http://127.0.0.1:57267 "GET /ping HTTP/1.1" 502 0
[2018-09-18 17:15:09] uiautomator is starting ...
http://127.0.0.1:57267 "GET /ping HTTP/1.1" 200 24
http://127.0.0.1:57267 "POST /jsonrpc/0 HTTP/1.1" 200 214
http://127.0.0.1:57267 "POST /shell HTTP/1.1" 200 28792
http://127.0.0.1:57267 "POST /shell HTTP/1.1" 200 39
uiautomator back to normal
'''

**Comment by mingyuan-xia** [comment]
@derekhsieh 感谢启发
问题应该是这个：https://blog.csdn.net/pvpheroszw/article/details/77981553
待修

**Comment by codeskyblue** [comment]
最好提个pr，merge完之后马上可以发新版本了

**Comment by mingyuan-xia** [comment]
progress: https://github.com/openatx/android-uiautomator-server/commit/ed617038f3528342c771fbfb8662bf808d9f41ab

**Comment by mingyuan-xia** [comment]
https://github.com/openatx/android-uiautomator-server/releases/tag/1.1.6
