### ISSUE TITLE
打印信息错误

### ISSUE THREAD

**Issue by BugaoxingXXX** [openatx/uiautomator2#22]
链接上了设备但是运行`print (d.press('home')`的时候报错
``` batch
Traceback (most recent call last):
  File "C:\Users\Glority\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\Glority\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Glority\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Glority\Anaconda3\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Glority\Anaconda3\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Glority\Anaconda3\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Glority\Anaconda3\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Glority\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\Glority\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Glority\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Glority\Anaconda3\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Glority\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\Glority\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Glority\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Glority\Anaconda3\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Glority\Anaconda3\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Glority\Anaconda3\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Glority\Anaconda3\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Glority\Anaconda3\lib\site-packages\uiautomator2\__init__.py", line 791, in press
    return self.jsonrpc.pressKey(key)
  File "C:\Users\Glority\Anaconda3\lib\site-packages\uiautomator2\__init__.py", line 211, in __call__
    return self.server.jsonrpc_call(self.method, params, http_timeout)
  File "C:\Users\Glority\Anaconda3\lib\site-packages\uiautomator2\__init__.py", line 230, in jsonrpc_call
    data=data)
  File "C:\Users\Glority\Anaconda3\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Glority\Anaconda3\lib\site-packages\uiautomator2\__init__.py", line 154, in request
    resp = super(TimeoutRequestsSession, self).request(method, url, **kwargs)
  File "C:\Users\Glority\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Glority\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Glority\Anaconda3\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```
但是我这边并没有链接啊，我应该强制关掉哪个链接=。=

**Comment by BugaoxingXXX** [comment]
重新init了一下居然好了=。=
