### ISSUE TITLE
vivo手机，单台/多台手机做反复重启操作，重新连接手机概率性连接不上

### ISSUE THREAD

**Issue by fwdbupt** [openatx/uiautomator2#223]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```python
import os 
import  uiautomator2 as uu
import time
import threading
device_id = [设备id]

def reboot_and_check(device_num,l,aa):

    a=uu.connect_usb(device_num)
    time.sleep(15)
    if not a.agent_alive:
        print 'init again'
        a=uu.connect_usb(device_num)
        a.healthcheck()
    a.adb_shell('input keyevent 26')
    a.adb_shell('input swipe 500 1200 500 50')
    time.sleep(10)
    if not a.agent_alive:
        print 'init again'
        a=uu.connect_usb(device_num)
        a.healthcheck()
    time.sleep(5)
    a.adb_shell('am start -a android.settings.WIFI_SETTINGS')



    a.adb_shell('svc wifi enable')
    time.sleep(5)
    retry_time = 0
    while not a(resourceId=u'com.android.wifisettings:id/connected').exists:
        time.sleep(10)
        retry_time = retry_time + 1
        if retry_time > 5:
            a.screenshot("%s-fail.jpg"%device_num)
            print '*************%s cannot connect*****************'%device_num
            aa.write('%s*************%s cannot connect*****************\n'%(time.ctime(),device_num))
            device_id.remove(device_num)
            break  
    if retry_time == 6:
        raise Exception('cannot connect')
        a.adb_shell('input keyevent 26')
    else:
        pass
    a.adb_shell('svc wifi disable')
    time.sleep(1)



    a.adb_shell('svc wifi enable')
    #print 'enable...'
    time.sleep(5)
    retry_time = 0
    while not a(resourceId=u'com.android.wifisettings:id/connected').exists:
        time.sleep(10)
        retry_time = retry_time + 1
        if retry_time > 5:
            a.screenshot("%s-fail.jpg"%device_num)
            print '*************%s cannot connect*****************'%device_num
            aa.write('%s*************%s cannot connect*****************\n'%(time.ctime(),device_num))
            device_id.remove(device_num)
            break  
    if retry_time == 6:
        raise Exception('cannot connect')
        a.adb_shell('input keyevent 26')
    else:
        pass
    a.adb_shell('svc wifi disable')
    time.sleep(1)



    a.adb_shell('svc wifi enable')
    #print 'enable...'
    time.sleep(5)
    retry_time = 0
    while not a(resourceId=u'com.android.wifisettings:id/connected').exists:
        time.sleep(10)
        retry_time = retry_time + 1
        if retry_time > 5:
            a.screenshot("%s-fail.jpg"%device_num)
            print '*************%s cannot connect*****************'%device_num
            aa.write('%s*************%s cannot connect*****************\n'%(time.ctime(),device_num))
            device_id.remove(device_num)
            break
    if retry_time == 6:
        raise Exception('cannot connect')
        a.adb_shell('input keyevent 26')
    else:
        pass
    a.adb_shell('svc wifi disable')
    time.sleep(1)



    a.adb_shell('svc wifi enable')
    time.sleep(5)
    retry_time = 0
    while not a(resourceId=u'com.android.wifisettings:id/connected').exists:
        time.sleep(10)
        retry_time = retry_time + 1
        if retry_time > 5:
            a.screenshot("%s-fail.jpg"%device_num)
            print '*************%s cannot connect*****************'%device_num
            aa.write('%s*************%s cannot connect*****************\n'%(time.ctime(),device_num))
            device_id.remove(device_num)
            break  
    if retry_time == 6:
        raise Exception('cannot connect')
        a.adb_shell('input keyevent 26')
    else:
        pass
    a.adb_shell('svc wifi disable')
    time.sleep(1)



    a.adb_shell('svc wifi enable')
    time.sleep(5)
    retry_time = 0
    while not a(resourceId=u'com.android.wifisettings:id/connected').exists:
        time.sleep(10)
        retry_time = retry_time + 1
        if retry_time > 5:
            a.screenshot("%s-fail.jpg"%device_num)
            print '*************%s cannot connect*****************'%device_num
            aa.write('%s*************%s cannot connect*****************\n'%(time.ctime(),device_num))
            device_id.remove(device_num)
            break
    if retry_time == 6:
        raise Exception('cannot connect')
        a.adb_shell('input keyevent 26')
    else:
        try:
            a.adb_shell('reboot')
        except:
            pass
    time.sleep(60)



test_time = 1
while True:

    threads = []
    aa=open('test_result.txt','a+')
    aa.write('****%s test****\n'%test_time)
    print '...........begin to thread..........'
    for i in device_id:
        t = threading.Thread(target = reboot_and_check, args = (i,0,aa))
        threads.append(t)
    if len(threads) == 0:
    	break
    for i in threads:
        i.start()
    for i in threads:
        i.join()
    aa.close()
    test_time = test_time + 1


```

## Versions (版本)
Name: uiautomator2
Version: 0.1.3
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: c:\python27\lib\site-packages
Requires: requests, six, humanize, fire, docopt, progress, retry, whichcraft, pillow, lxml
Required-by:

## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快

- 手机型号?
VIVO手机，X23，或者NEXS，对于别的型号应该也有该问题。

- 错误日志?

单机跑：
ValueError: No JSON object could be decoded

多机一起跑：
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\My Documents\Desktop\reboot_check.py", line 14, in reboot_and_check
    a.adb_shell('input keyevent 26')
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 746, in adb_shell
    return self.shell(cmdline)[0]
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 722, in shell
    'timeout': str(timeout)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 270, in request
    "atx-agent is not running. Fix it with following steps.\n1. Plugin device into computer.\n2. Run command \"python -m uiautomator2 init\""
EnvironmentError: atx-agent is not running. Fix it with following steps.
1. Plugin device into computer.
2. Run command "python -m uiautomator2 init"

- 出错的代码片段?
a=uu.connect_usb(device_num)

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）
就是重启后，再进行connect，概率性提示json error或者atx不跑的错误，在脚本中有多次进行connect的尝试，但还是无法避免。感觉应该跟型号没关系。多次进行重启测试应该能复现到

**Comment by mingyuan-xia** [comment]
重新启动后需要 重新init，或者通过adb shell重新跑atx-agent

**Comment by codeskyblue** [comment]
难复现issue， 需要的时候再重新打开
