### ISSUE TITLE
atx-agent crashes on allwinner astar_d7

### ISSUE THREAD

**Issue by gamesguru** [openatx/uiautomator2#227]
Issue only affects one device out of 20.
init and connect() fail, device reboot is not solving issue.  allwinner astar_d7

```
__main__.py:284 - ERROR - Failure, unable to get result from http://localhost:%d/version
```
uiautomator2 version
```
Version: 0.1.4.dev45
```

atx log
```
2018/09/27 13:46:27 [INFO][github.com/openatx/atx-agent] main.go:1405: - - - - - - - - - - - - - - -
2018/09/27 13:46:27 [INFO][github.com/openatx/atx-agent] main.go:1406: daemon started
atx-agent version 0.4.5
Internet is not connected.2018/09/27 13:46:28 [INFO][github.com/openatx/atx-agent] main.go:1447: service uiautomator: startservice com.github.uiautomator/.Service
2018/09/27 13:46:29 DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
2018/09/27 13:46:29 DEBUG program pid: 1527
runtime: g34: leftover defer sp=0x12d4ae04 pc=0x233b2c
	defer 0x12d32140 sp=0x12d4ae04 pc=0x233b2c
	defer 0x12d32000 sp=0x12d4ae04 pc=0x2338f4
fatal error: traceback has leftover defers

runtime stack:
runtime.throw(0x5a50f1, 0x1d)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:619 +0x60
runtime.gentraceback(0xffffffff, 0xffffffff, 0x0, 0x12cec540, 0x0, 0x0, 0x7fffffff, 0x5bb0ec, 0x12cfbe58, 0x0, ...)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/traceback.go:575 +0x168c
runtime.copystack(0x12cec540, 0x1000, 0x1)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/stack.go:891 +0x1cc
runtime.newstack()
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/stack.go:1063 +0x280
runtime.morestack()
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/asm_arm.s:419 +0x64

goroutine 34 [copystack]:
runtime.slowdodiv(0xb5ed3bc8, 0x73a641da, 0x3b9aca00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/vlrt.go:237 +0x174 fp=0x12d4ab64 sp=0x12d4ab64 pc=0x61a28
runtime.dodiv(0xb5ed3bc8, 0x73a641da, 0x3b9aca00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/vlrt.go:198 +0x34 fp=0x12d4ab88 sp=0x12d4ab64 pc=0x61884
runtime.int64div(0x4a12c438, 0x8c59be25, 0x3b9aca00, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/vlrt.go:156 +0x15c fp=0x12d4abb4 sp=0x12d4ab88 pc=0x61678
time.Time.Add(0x4e0569c8, 0xbee355ad, 0x727c52d5, 0x0, 0x8be980, 0x4a12c438, 0x8c59be25, 0x0, 0x0, 0x0, ...)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/time/time.go:845 +0x40 fp=0x12d4abdc sp=0x12d4abb4 pc=0xa1304
time.Time.Sub(0x0, 0x0, 0x0, 0x0, 0x0, 0x4e0569c8, 0xbee355ad, 0x727c52d5, 0x0, 0x8be980, ...)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/time/time.go:888 +0x204 fp=0x12d4ac30 sp=0x12d4abdc pc=0xa1750
time.Until(0x0, 0x0, 0x0, 0x0, 0x0, 0x20948, 0x59e84)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/time/time.go:906 +0x3c fp=0x12d4ac78 sp=0x12d4ac30 pc=0xa18b0
internal/poll.setDeadlineImpl(0x12d3a050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x72, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/internal/poll/fd_poll_runtime.go:137 +0x2c fp=0x12d4acbc sp=0x12d4ac78 pc=0xaad74
internal/poll.(*FD).SetReadDeadline(0x12d3a050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x230344, 0x12d3e048)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/internal/poll/fd_poll_runtime.go:128 +0x30 fp=0x12d4ace4 sp=0x12d4acbc pc=0xaacd8
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/net/http/server.go:2795 +0x208

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x40077fc0, 0x72, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/netpoll.go:173 +0x44
internal/poll.(*pollDesc).wait(0x12b842e4, 0x72, 0xac800, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x8c
internal/poll.(*pollDesc).waitRead(0x12b842e4, 0xffffff00, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x2c
internal/poll.(*FD).Accept(0x12b842d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/internal/poll/fd_unix.go:372 +0x174

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/sigqueue.go:139 +0x130
os/signal.loop()
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.0
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/os/signal/signal_unix.go:28 +0x30

goroutine 17 [syscall]:
syscall.Syscall6(0x118, 0x1, 0x5f7, 0x12b2869c, 0x1000004, 0x0, 0x0, 0x0, 0x800000, 0x3f228)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/syscall/asm_linux_arm.s:48 +0x8
os.(*Process).blockUntilWaitable(0x12cd4060, 0x12c0d830, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/os/wait_waitid.go:31 +0x64
os.(*Process).wait(0x12cd4060, 0x12bc97d0, 0x12b287dc, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/os/exec_unix.go:22 +0x2c
os.(*Process).Wait(0x12cd4060, 0x0, 0x0, 0x32c5b8)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/os/exec.go:123 +0x1c
os/exec.(*Cmd).Wait(0x12cb4000, 0x32c624, 0x1)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/os/exec/exec.go:461 +0x40
os/exec.(*Cmd).Wait-fm(0x12c0d800, 0x12b287dc)
	/home/travis/gopath/src/github.com/openatx/atx-agent/cmdctrl/cmdctrl.go:228 +0x1c
github.com/openatx/atx-agent/cmdctrl.goFunc.func1(0x12cd0040, 0x12cb0078)
	/home/travis/gopath/src/github.com/openatx/atx-agent/cmdctrl/cmdctrl.go:34 +0x1c
created by github.com/openatx/atx-agent/cmdctrl.goFunc
	/home/travis/gopath/src/github.com/openatx/atx-agent/cmdctrl/cmdctrl.go:33 +0x48

goroutine 13 [select]:
github.com/openatx/atx-agent/cmdctrl.(*processKeeper).start.func1(0x12b7d180)
	/home/travis/gopath/src/github.com/openatx/atx-agent/cmdctrl/cmdctrl.go:229 +0x400
created by github.com/openatx/atx-agent/cmdctrl.(*processKeeper).start
	/home/travis/gopath/src/github.com/openatx/atx-agent/cmdctrl/cmdctrl.go:208 +0xd8

goroutine 14 [chan receive]:
main.(*Server).initHTTPServer.func17(0x12bc9d30)
	/home/travis/gopath/src/github.com/openatx/atx-agent/main.go:795 +0x74
created by main.(*Server).initHTTPServer
	/home/travis/gopath/src/github.com/openatx/atx-agent/main.go:794 +0x6c0

goroutine 15 [runnable, locked to thread]:
runtime.gopark(0x5bb234, 0x12d12130, 0x59612f, 0x9, 0x12b26016, 0x3)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/proc.go:291 +0xfc
runtime.goparkunlock(0x12d12130, 0x59612f, 0x9, 0x16, 0x3)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/proc.go:297 +0x44
runtime.chansend(0x12d12100, 0x12b29f90, 0x12b29f01, 0x63ff4, 0x8)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/chan.go:234 +0x284
runtime.chansend1(0x12d12100, 0x12b29f90)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/chan.go:125 +0x2c
runtime.ensureSigM.func1()
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/signal_unix.go:560 +0x134
runtime.goexit()
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/asm_arm.s:1015 +0x4

goroutine 33 [runnable]:
main.main.func3(0x12d0ad40, 0x12b20a0d, 0x12b0d078)
	/home/travis/gopath/src/github.com/openatx/atx-agent/main.go:1475
created by main.main
	/home/travis/gopath/src/github.com/openatx/atx-agent/main.go:1475 +0x1030
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.github.uiautomator.stub.Stub:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1mat!o
```

**Comment by mingyuan-xia** [comment]
I have suggested to build atx-agent go project with debug symbol on to help locate crash site.
Anyhow atx-agent crashes are rare. No idea for now.

**Comment by gamesguru** [comment]
it should be possible to install the debuggable client.  I'm not working in testing anymore so I can't help here

**Comment by codeskyblue** [comment]
这异常有点难懂
