### ISSUE TITLE
connect一直失败

### ISSUE THREAD

**Issue by flyfire100** [openatx/uiautomator2#246]
[2018-11-07 16:07:36] uiautomator is starting ...
[2018-11-07 16:07:37] uiautomator is starting ...
[2018-11-07 16:07:38] uiautomator is starting ...
[2018-11-07 16:07:39] uiautomator is starting ...
[2018-11-07 16:07:40] uiautomator is starting ...
[2018-11-07 16:07:41] uiautomator is starting ...
[2018-11-07 16:07:42] uiautomator is starting ...
[2018-11-07 16:07:43] uiautomator is starting ...
[2018-11-07 16:07:44] uiautomator is starting ...
[2018-11-07 16:07:45] uiautomator is starting ...
[2018-11-07 16:07:46] uiautomator is starting ...
[2018-11-07 16:07:47] uiautomator is starting ...
[2018-11-07 16:07:48] uiautomator is starting ...
[2018-11-07 16:07:49] uiautomator is starting ...
[2018-11-07 16:07:53] uiautomator is starting ...
[2018-11-07 16:07:54] uiautomator is starting ...
[2018-11-07 16:07:55] uiautomator is starting ...
Traceback (most recent call last):
  File "mytest.py", line 3, in <module>

**Comment by flyfire100** [comment]
分析到最后发现是http://127.0.0.1:7912/ping返回的是502，bad gateway

这个是怎么回事儿？

**Comment by mingyuan-xia** [comment]
不应该是 `127.0.0.1:7912` 是 `设备ip:7912`

**Comment by flyfire100** [comment]
你代码里写的也是127.0.0.1

--------------原始邮件--------------
发件人："Mingyuan Xia "<notifications@github.com>;
发送时间：2018年11月7日(星期三) 下午5:12
收件人："openatx/uiautomator2" <uiautomator2@noreply.github.com>;
抄送："flyfire "<flyfire@flyfire.net>;"Author "<author@noreply.github.com>;
主题：Re: [openatx/uiautomator2] connect一直失败 (#246)
-----------------------------------

 
不应该是 127.0.0.1:7912 是 设备ip:7912

**Comment by flyfire100** [comment]
确实映射了，代码中好像也映射了

--------------原始邮件--------------
发件人："Mingyuan Xia "<notifications@github.com>;
发送时间：2018年11月7日(星期三) 晚上10:23
收件人："openatx/uiautomator2" <uiautomator2@noreply.github.com>;
抄送："flyfire "<flyfire@flyfire.net>;"Author "<author@noreply.github.com>;
主题：Re: [openatx/uiautomator2] connect一直失败 (#246)
-----------------------------------

 
示例代码，除非你通过adb forward把设备的7912映射到了电脑的7912

**Comment by mingyuan-xia** [comment]
atxagent log有么

**Comment by flyfire100** [comment]
应该是手机的问题，昨天晚上自动升级了系统，今天本来想抓日志的，结果直接好了，汗！

**Comment by flyfire100** [comment]
> atxagent log有么

Time: 0.734
There were 2 failures:
1) testUIAutomatorStub(com.github.uiautomator.stub.Stub)
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.github.uiautomator.ACTION_START }
	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1784)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1825)
	at android.app.ContextImpl.startService(ContextImpl.java:1797)
	at com.github.uiautomator.stub.Stub.launchService(Stub.java:119)
	at com.github.uiautomator.stub.Stub.setUp(Stub.java:72)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2252)
2) testUIAutomatorStub(com.github.uiautomator.stub.Stub)
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.github.uiautomator.ACTION_STOP }
	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1784)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1825)
	at android.app.ContextImpl.startService(ContextImpl.java:1797)
	at com.github.uiautomator.stub.Stub.tearDown(Stub.java:126)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2252)

FAILURES!!!
Tests run: 1,  Failures: 2

**Comment by mingyuan-xia** [comment]
https://github.com/openatx/uiautomator2/issues/217
问题已知 感谢上报 进度见此issue
