### ISSUE TITLE
uiautomator2-0.1.5.dev5 华为手机连不上,0.1.4上连接正常

### ISSUE THREAD

**Issue by shixiujuan1203** [openatx/uiautomator2#252]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```
[2018-11-15 20:21:59] uiautomator is starting ...
[2018-11-15 20:22:00] uiautomator is starting ...
[2018-11-15 20:22:01] uiautomator is starting ...
[2018-11-15 20:22:03] uiautomator is starting ...
[2018-11-15 20:22:04] uiautomator is starting ...
[2018-11-15 20:22:05] uiautomator is starting ...
[2018-11-15 20:22:06] uiautomator is starting ...
[2018-11-15 20:22:07] uiautomator is starting ...
[2018-11-15 20:22:08] uiautomator is starting ...
[2018-11-15 20:22:09] uiautomator is starting ...
[2018-11-15 20:22:10] uiautomator is starting ...
[2018-11-15 20:22:11] uiautomator is starting ...
[2018-11-15 20:22:12] uiautomator is starting ...
[2018-11-15 20:22:14] uiautomator is starting ...
[2018-11-15 20:22:15] uiautomator is starting ...
[2018-11-15 20:22:16] uiautomator is starting ...
[2018-11-15 20:22:17] uiautomator is starting ...
[2018-11-15 20:22:18] uiautomator is starting ...
[2018-11-15 20:22:19] uiautomator is starting ...
[E 181115 20:22:20 web:1670] Uncaught exception POST /api/v1/connect (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='POST', uri='/api/v1/connect', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/weditor/__main__.py", line 242, in post
        d = u2.connect(device_url)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uiautomator2/__init__.py", line 205, in connect
        return connect_usb(addr)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uiautomator2/__init__.py", line 254, in connect_usb
        d.reset_uiautomator()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uiautomator2/__init__.py", line 653, in reset_uiautomator
        "Uiautomator started failed. Find solutions in https://github.com/openatx/uiautomator2/wiki/Common-issues"
    RuntimeError: Uiautomator started failed. Find solutions in https://github.com/openatx/uiautomator2/wiki/Common-issues

    During handling of the above exception, another exception occurred:
```

## Versions (版本)
通过`pip show uiautomator2`可以获取到

## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快
试了华为p9 华为p8都连接不上
命令行执行Python3 -w uiautomator2 init 提示success，但是weditor和执行case时候uiautomator2都连不上，提示信息为上面的log

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）

**Comment by mingyuan-xia** [comment]
提供atx-agent.log

**Comment by codeskyblue** [comment]
试试0.1.6
