### ISSUE TITLE
vivo 1606 (os 6.0.1) u2 init   连接不上

### ISSUE THREAD

**Issue by shixiujuan1203** [openatx/uiautomator2#256]
```
python3 -m uiautomator2 init
2018-11-25 20:06:47,291 - __main__.py:320 - INFO - Detect pluged devices: ['79BQADSSRGUXS']
2018-11-25 20:06:47,292 - __main__.py:336 - INFO - Device(79BQADSSRGUXS) initialing ...
2018-11-25 20:06:47,554 - __main__.py:133 - INFO - install minicap
2018-11-25 20:06:47,652 - __main__.py:140 - INFO - install minitouch
2018-11-25 20:06:49,071 - __main__.py:155 - INFO - app-uiautomator.apk(1.1.6) downloading ...
2018-11-25 20:06:49,072 - __main__.py:158 - INFO - app-uiautomator-test.apk downloading ...
2018-11-25 20:06:57,754 - __main__.py:219 - INFO - atx-agent(0.4.8) need to update
2018-11-25 20:06:57,754 - __main__.py:227 - INFO - atx-agent(0.4.9) is installing, please be patient
2018-11-25 20:06:58,648 - __main__.py:250 - INFO - launch atx-agent daemon
2018-11-25 20:06:59,233 - __main__.py:266 - INFO - atx-agent version: 0.4.8
atx-agent output: 2018/11/25 12:06:57 getgrop exec: "sh": executable file not found in $PATH
2018/11/25 12:06:57 [INFO][github.com/openatx/atx-agent] main.go:508: atx-agent listening on 10.1.63.27:7912
2018-11-25 20:07:00,150 - __main__.py:272 - INFO - success
```

## Versions (版本)
通过`pip show uiautomator2`可以获取到
pip3 show uiautomator2
Name: uiautomator2
Version: 0.1.6.dev1
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: requests, six, humanize, fire, docopt, progress, retry, whichcraft, logzero, pillow, lxml
Required-by: atx
## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快

- 手机型号?
vivo 1606 os：6.0.1
- 错误日志?

[I 181125 20:13:52 web:2162] 304 GET / (::1) 1.72ms
[I 181125 20:13:53 web:2162] 304 GET /api/v1/version (::1) 0.38ms
[2018-11-25 20:13:59] uiautomator is starting ...
[2018-11-25 20:14:00] uiautomator is starting ...
[2018-11-25 20:14:01] uiautomator is starting ...
[2018-11-25 20:14:02] uiautomator is starting ...
[2018-11-25 20:14:03] uiautomator is starting ...
[2018-11-25 20:14:04] uiautomator is starting ...
[2018-11-25 20:14:05] uiautomator is starting ...
[2018-11-25 20:14:06] uiautomator is starting ...
[2018-11-25 20:14:07] uiautomator is starting ...
[2018-11-25 20:14:08] uiautomator is starting ...
[2018-11-25 20:14:09] uiautomator is starting ...
[2018-11-25 20:14:10] uiautomator is starting ...
[2018-11-25 20:14:11] uiautomator is starting ...
[2018-11-25 20:14:12] uiautomator is starting ...
[2018-11-25 20:14:13] uiautomator is starting ...
[2018-11-25 20:14:15] uiautomator is starting ...
[2018-11-25 20:14:16] uiautomator is starting ...
[2018-11-25 20:14:17] uiautomator is starting ...
[2018-11-25 20:14:18] uiautomator is starting ...
[E 181125 20:14:19 web:1670] Uncaught exception POST /api/v1/connect (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='POST', uri='/api/v1/connect', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/weditor/__main__.py", line 243, in post
        d = u2.connect(device_url)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uiautomator2/__init__.py", line 205, in connect
        return connect_usb(addr)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uiautomator2/__init__.py", line 254, in connect_usb
        d.reset_uiautomator()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uiautomator2/__init__.py", line 653, in reset_uiautomator
        "Uiautomator started failed. Find solutions in https://github.com/openatx/uiautomator2/wiki/Common-issues"
    RuntimeError: Uiautomator started failed. Find solutions in https://github.com/openatx/uiautomator2/wiki/Common-issues

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/weditor/__main__.py", line 259, in post
        "description": traceback.format_exc().encode('utf-8'),
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tornado/web.py", line 746, in write
        chunk = escape.json_encode(chunk)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tornado/escape.py", line 81, in json_encode
        return json.dumps(value).replace("</", "<\\/")
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
        return _default_encoder.encode(obj)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
        return _iterencode(o, 0)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
        o.__class__.__name__)
    TypeError: Object of type 'bytes' is not JSON serializable
[E 181125 20:14:19 web:2162] 500 POST /api/v1/connect (::1) 21176.22ms

- 出错的代码片段?

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）

**Comment by mingyuan-xia** [comment]
手机上的atx-agent.log提供下

**Comment by hanjiefeng** [comment]
请问这个问题有解决吗？

python -m uiautomator2 init 10.97.190.152:8000
2018-11-27 17:10:53,470 - __main__.py:305 - INFO - atx-server addr 10.97.190.152:8000
2018-11-27 17:10:53,533 - __main__.py:326 - INFO - Detect pluged devices: [u'AKC0218326004138']
2018-11-27 17:10:53,535 - __main__.py:342 - INFO - Device(AKC0218326004138) initialing ...
2018-11-27 17:10:54,240 - __main__.py:133 - INFO - install minicap
2018-11-27 17:10:54,526 - __main__.py:140 - INFO - install minitouch
2018-11-27 17:10:55,140 - __main__.py:168 - INFO - apk(1.1.6) already installed, skip
2018-11-27 17:10:55,141 - __main__.py:349 - INFO - atx-agent is already running, force stop
2018-11-27 17:10:56,174 - __main__.py:213 - INFO - atx-agent(0.4.9) already installed, skip
2018-11-27 17:10:56,490 - __main__.py:250 - INFO - launch atx-agent daemon
2018-11-27 17:10:58,417 - __main__.py:272 - INFO - atx-agent version: 0.4.9
atx-agent output: 2018/11/27 09:10:59 getgrop exec: "sh": executable file not found in $PATH
2018/11/27 09:10:59 [INFO][github.com/openatx/atx-agent] main.go:508: atx-agent listening on 10.97.183.7:7912
2018-11-27 17:10:58,665 - __main__.py:278 - INFO - success

**Comment by codeskyblue** [comment]
最新版已修复，原因是PATH变量被错误的重写了
