### ISSUE TITLE
python -m uiautomator2 init --mirror报错502

### ISSUE THREAD

**Issue by cnhkzyy** [openatx/uiautomator2#270]
## Versions
0.1.7

## Issue and steps to reproduce 
python -m uiautomator2 init --mirror报错

- 手机型号?
荣耀畅玩4C(v5.0.1)， 荣耀8(v7.0)， 海马玩模拟器(v5.1.1)
- 错误日志?
```
2018-12-11 00:22:01,034 - __main__.py:327 - INFO - Detect pluged devices: ['JTG6T16307007427']
2018-12-11 00:22:01,035 - __main__.py:343 - INFO - Device(JTG6T16307007427) initialing ...
Traceback (most recent call last):
  File "D:\Program\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program\python34\lib\site-packages\uiautomator2\__main__.py", line 424, in <module>
    main()
  File "D:\Program\python34\lib\site-packages\uiautomator2\__main__.py", line 420, in main
    fire.Fire(MyFire)
  File "D:\Program\python34\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "D:\Program\python34\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "D:\Program\python34\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "D:\Program\python34\lib\site-packages\uiautomator2\__main__.py", line 331, in init
    ignore_apk_check)
  File "D:\Program\python34\lib\site-packages\uiautomator2\__main__.py", line 346, in _init_with_seria
    ins.install_minicap()
  File "D:\Program\python34\lib\site-packages\uiautomator2\__main__.py", line 129, in install_minicap
    path = cache_download(url)
  File "D:\Program\python34\lib\site-packages\uiautomator2\__main__.py", line 78, in cache_download
    raise Exception("status code", r.status_code)
Exception: ('status code', 502)
```
- 出错的代码片段?

## Additional Details 
之前一直是可以按照那两个apk包的，现在报错后，手机上无法安装

**Comment by cnhkzyy** [comment]
刚刚看到文档，mirror镜像网站让github给block了。。这不是一个问题
