### ISSUE TITLE
初始化不成功

### ISSUE THREAD

**Issue by shi819523756** [openatx/uiautomator2#271]
C:\Users\hero>python -m uiautomator2 init --mirror
Traceback (most recent call last):
  File "D:\Anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\lib\site-packages\uiautomator2\__main__.py", line 424, in <module>
    main()
  File "D:\Anaconda\lib\site-packages\uiautomator2\__main__.py", line 420, in main
    fire.Fire(MyFire)
  File "D:\Anaconda\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "D:\Anaconda\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "D:\Anaconda\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "D:\Anaconda\lib\site-packages\uiautomator2\__main__.py", line 317, in init
    sn for sn, _ in adbutils.Adb().devices(states=['device'])
  File "D:\Anaconda\lib\site-packages\uiautomator2\adbutils.py", line 34, in devices
    output = subprocess.check_output([self.adb_path(), 'devices'])
  File "D:\Anaconda\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "D:\Anaconda\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Anaconda\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda\lib\subprocess.py", line 1100, in _execute_child
    args = list2cmdline(args)
  File "D:\Anaconda\lib\subprocess.py", line 511, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable

**Comment by mingyuan-xia** [comment]
adb装了么
