### ISSUE TITLE
weditor链接不上手机

### ISSUE THREAD

**Issue by flyfire100** [openatx/uiautomator2#277]
使用 adb shell am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner查看发现下面的错误

java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@affdf52already registered!
        at android.os.Parcel.createException(Parcel.java:1961)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)

然后排查进程，发现不存在uiautomator的进程

**Comment by mingyuan-xia** [comment]
hierarchyViewer, Appium, maxim
