### ISSUE TITLE
无法指定单个设备

### ISSUE THREAD

**Issue by nostale** [openatx/uiautomator2#303]
```
指定设备报错，不指定不会报错
python -m uiautomator2 init --serial 192.168.3.39
```

## Versions (版本)
Version: 0.1.11.dev1
通过`pip show uiautomator2`可以获取到

## Issue and steps to reproduce (复现步骤)

[admin@localhost site-packages]$ python -m uiautomator2 init --serial 192.168.3.39
Namespace(agent_version='0.5.4', apk_version='1.1.7', reinstall=False, serial='192.168.3.39', server=None, subparser='init') init
2019-02-02 14:02:43,327 - __main__.py:364 - INFO - Device(192.168.3.39) initialing ...
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/admin/.local/lib/python2.7/site-packages/uiautomator2/__main__.py", line 451, in <module>
    main()
  File "/home/admin/.local/lib/python2.7/site-packages/uiautomator2/__main__.py", line 443, in main
    actions[args.subparser](args)
  File "/home/admin/.local/lib/python2.7/site-packages/uiautomator2/__main__.py", line 360, in cmd_init
    args.server, args.reinstall)
  File "/home/admin/.local/lib/python2.7/site-packages/uiautomator2/__main__.py", line 365, in _init_with_serial
    ins = Installer(serial)
  File "/home/admin/.local/lib/python2.7/site-packages/uiautomator2/__main__.py", line 96, in __init__
    self.sdk = self.getprop('ro.build.version.sdk')
  File "uiautomator2/adbutils.py", line 159, in getprop
    return self.shell('getprop', prop).strip()
  File "uiautomator2/adbutils.py", line 156, in shell
    return self._device.shell(" ".join(args))
AttributeError: 'NoneType' object has no attribute 'shell'

**Comment by codeskyblue** [comment]
原因应该是使用了 pure-python-adb 库的原因，感觉库很不稳定。计划先重新用命令行调用adb替换到该库

**Comment by codeskyblue** [comment]
开了一个分支  fix-adb 修复这个问题。需要点时间

**Comment by wogenhaosini** [comment]
同，我也发现这个问题了。

**Comment by codeskyblue** [comment]
已修复
