### ISSUE TITLE
uiautomator2 init 出现 FAIL 0014 错误

### ISSUE THREAD

**Issue by sltruman** [openatx/uiautomator2#305]
```
$ python -m uiautomator2 init
Namespace(agent_version='0.5.4', apk_version='1.1.7', reinstall=False, serial=None, server=None, subparser='init') init
[I 190219 22:10:11 __main__:355] Init device emulator-5554
2019-02-19 22:10:11,628 - __main__.py:364 - INFO - Device(emulator-5554) initialing ...
2019-02-19 22:10:11,645 - __main__.py:116 - INFO - skip install minicap on emulator
2019-02-19 22:10:11,646 - __main__.py:136 - INFO - install minitouch
2019-02-19 22:10:11,685 - __main__.py:164 - INFO - apk(1.1.7) already installed, skip
2019-02-19 22:10:11,697 - __main__.py:372 - INFO - atx-agent is already running, force stop
Traceback (most recent call last):
  File "C:\Users\SLTru\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\SLTru\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\SLTru\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__main__.py", line 447, in <module>
    main()
  File "C:\Users\SLTru\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__main__.py", line 439, in main
    actions[args.subparser](args)
  File "C:\Users\SLTru\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__main__.py", line 357, in cmd_init
    args.server, args.reinstall)
  File "C:\Users\SLTru\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__main__.py", line 377, in _init_with_serial
    if not ins.check_agent_installed(agent_version):
  File "C:\Users\SLTru\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\__main__.py", line 195, in check_agent_installed
    lport = self.forward_port(7912)
  File "C:\Users\SLTru\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\adbutils.py", line 147, in forward_port
    forwards = self.forward_list()
  File "C:\Users\SLTru\AppData\Local\Programs\Python\Python36\lib\site-packages\uiautomator2\adbutils.py", line 123, in forward_list
    result = self._device._execute_cmd(cmd)
  File "C:\Users\SLTru\AppData\Local\Programs\Python\Python36\lib\site-packages\adb\command\serial\__init__.py", line 9, in _execute_cmd
    conn.send(cmd)
  File "C:\Users\SLTru\AppData\Local\Programs\Python\Python36\lib\site-packages\adb\connection.py", line 77, in send
    return self._check_status()
  File "C:\Users\SLTru\AppData\Local\Programs\Python\Python36\lib\site-packages\adb\connection.py", line 83, in _check_status
    raise RuntimeError("ERROR: {} {}".format(repr(recv), error))
RuntimeError: ERROR: 'FAIL' 0014
```

**Comment by codeskyblue** [comment]
估计还是那个adb库的问题 @mingyuan-xia

**Comment by sltruman** [comment]
也许可以试试其他版本的adb，我的是雷电模拟器的adb。

**Comment by mingyuan-xia** [comment]
@Swind 来看看，我看是 `adb forward` 这个返回FAIL
https://stackoverflow.com/questions/5064304/how-can-i-forward-my-localhost-ip-address-to-an-android-emulator
是不是和emulator有关

**Comment by Swind** [comment]
剛剛我比對了一下 uiautomator2 的程式碼，發現他是死在 [adbutils.py] 內的 `forward_list` 裡面 (https://github.com/openatx/uiautomator2/blob/d94dcfd41f623e19b88e21f49fb228c9abf88c11/uiautomator2/adbutils.py#L108)

在這邊 uiautomator2 利用 

`result = self._device._execute_cmd(cmd)` 

執行了 

`host-serial:{serial}:list-forward".format(serial=self.serial)`

這個指令，然後回傳錯誤的部份是在 [pure-python-adb](https://github.com/Swind/pure-python-adb/blob/master/adb/connection.py#L77) 
這邊是在檢查指令送出之後， adb server 回傳這個指令是否有正確收到等，並不是指令執行的結果。
非常的單純，所以我想應該跟 `adb forward` 沒有關係？

而且前面的 shell 也可以正常執行，所以應該是能正確的連到該 device 沒有問題

而 `0014` 的 error code，如果我沒有追錯的話應該是 [ENOTDIR](https://android.googlesource.com/platform/system/core/+/master/adb/sysdeps/errno.cpp#44)
（這部份我還沒有很詳細的把 adb server 的程式碼追完）
這個在部份的 windows 用的程式碼的確會出現，但是我還不太清楚出現的原因。
但是我估計跟硬體環境比較有關系

Hi @sltruman  
Could you please provide me more details about the OS and emulator.

OS version:
adb version: ( the result of the command `adb version` )
android version:
and the result of the command `sdkmanager --list`

HAXM is enabled?:

Thanks

**Comment by sltruman** [comment]
@Swind 雷电模拟器+WIN10，在ui2的新版本出现之前，我一直运行正常。应该是最近的版本导致的。

**Comment by codeskyblue** [comment]
因为引入`pure-python-adb`引发的issue有点多，所以0.2.0版本移除了这个库的依赖，adb的协议相关的代码已经全部压缩到adbutils.py文件中
（Sorry about that,@Swind  等你的库再完善下，应该会再重新引入的）。
目前已知的问题有

1. python -m uiautomator2 init 不能指定serial了。错误原因记不太清了
2. 当前目录不能包含 adb.py 文件不然会报 from adb.client Import错误
3. socket Warning没有释放警告

@sltruman 你可以再测试一下最新版本是否还会出错

**Comment by Swind** [comment]
不會，是我這邊的問題，
我這邊一直沒有時間跟環境去處理 Windows 上的問題以及其他模擬器。
造成你們的 uiautomator2 不穩定真的很不好意思
如果我有修正完成你所提到的 1, 2, 3 之後再跟你們說。
感謝你們回報 issue
