### ISSUE TITLE
d.session()不认微视和爱奇艺

### ISSUE THREAD

**Issue by retrfy** [openatx/uiautomator2#306]
Traceback (most recent call last):
  File "D:/Project/Elegent/elegent/launch.py", line 14, in <module>
    weishi = d.session('com.tencent,weishi')
  File "D:\Python27\lib\site-packages\uiautomator2\__init__.py", line 1079, in session
    raise SessionBrokenError(pkg_name, resp.text)
uiautomator2.exceptions.SessionBrokenError: ('com.tencent,weishi', u'package not found\n')

**Comment by codeskyblue** [comment]
把其中的，换成.就好了
