### ISSUE TITLE
init提示uiautomator2.adbutils.AdbError: unknown host service

### ISSUE THREAD

**Issue by qq163xzq** [openatx/uiautomator2#314]
执行python -m uiautomator2 init后报错

最后提示uiautomator2.adbutils.AdbError: unknown host service

[D 190319 22:28:20 __main__:28] use cache directory: C:\Users\xzq\.uiautomator2
Namespace(serial=None, server=None, subparser='init') init
[I 190319 22:28:20 __main__:80] >>> Initial device AdbDevice(serial=emulator-5554)
[I 190319 22:28:20 __main__:162] Install minicap, minitouch
[D 190319 22:28:20 __main__:157] Push https://github.com/openatx/stf-binaries/raw/master/node_modules/minitouch-prebuilt/prebuilt/x86/bin/minitouch -> /data/local/tmp/minitouch:0755
[D 190319 22:28:20 __main__:157] Push https://github.com/openatx/stf-binaries/raw/master/node_modules/minicap-prebuilt/prebuilt/x86/lib/android-22/minicap.so -> /data/local/tmp/minicap.so:0755
[D 190319 22:28:20 __main__:157] Push https://github.com/openatx/stf-binaries/raw/master/node_modules/minicap-prebuilt/prebuilt/x86/bin/minicap -> /data/local/tmp/minicap:0755
[I 190319 22:28:21 __main__:168] Install com.github.uiautomator, com.github.uiautomator.test
[D 190319 22:28:21 __main__:90] Shell: ('pm', 'uninstall', 'com.github.uiautomator')
[D 190319 22:28:21 __main__:90] Shell: ('pm', 'uninstall', 'com.github.uiautomator.test')
[D 190319 22:28:22 __main__:157] Push https://github.com/openatx/android-uiautomator-server/releases/download/1.1.7/app-uiautomator.apk -> /data/local/tmp/app-uiautomator.apk:0644
[D 190319 22:28:22 __main__:90] Shell: ('pm', 'install', '-r', '-t', '/data/local/tmp/app-uiautomator.apk')
[D 190319 22:28:26 __main__:157] Push https://github.com/openatx/android-uiautomator-server/releases/download/1.1.7/app-uiautomator-test.apk -> /data/local/tmp/app-uiautomator-test.apk:0644
[D 190319 22:28:26 __main__:90] Shell: ('pm', 'install', '-r', '-t', '/data/local/tmp/app-uiautomator-test.apk')
[I 190319 22:28:29 __main__:175] Install atx-agent
[D 190319 22:28:29 __main__:90] Shell: ('getprop', 'ro.product.cpu.abilist')
[D 190319 22:28:29 __main__:90] Shell: ('getprop', 'ro.product.cpu.abilist')
[D 190319 22:28:29 __main__:157] Push https://github.com/openatx/atx-agent/releases/download/0.5.4/atx-agent_0.5.4_linux_386.tar.gz -> /data/local/tmp/atx-agent:0755
[D 190319 22:28:31 __main__:90] Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')
[D 190319 22:28:32 __main__:90] Shell: ('/data/local/tmp/atx-agent', 'server', '-d')
[I 190319 22:28:32 __main__:184] Check install
Traceback (most recent call last):
  File "C:\Users\xzq\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\xzq\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xzq\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 341, in <module>
    main()
  File "C:\Users\xzq\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 331, in main
    actions[args.subparser](args)
  File "C:\Users\xzq\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 284, in cmd_init
    init.install(args.server)
  File "C:\Users\xzq\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 185, in install
    self.check_atx_agent_version()
  File "<C:\Users\xzq\AppData\Local\Programs\Python\Python37\lib\site-packages\decorator.py:decorator-gen-10>", line 2, in check_atx_agent_version
  File "C:\Users\xzq\AppData\Local\Programs\Python\Python37\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "C:\Users\xzq\AppData\Local\Programs\Python\Python37\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\Users\xzq\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 193, in check_atx_agent_version
    port = self._device.forward_port(7912)
  File "C:\Users\xzq\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\adbutils.py", line 271, in forward_port
    for f in self._client.forward_list():
  File "C:\Users\xzq\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\adbutils.py", line 163, in forward_list
    c.check_okay()
  File "C:\Users\xzq\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\adbutils.py", line 120, in check_okay
    raise AdbError(self.read_string())
uiautomator2.adbutils.AdbError: unknown host service

**Comment by qq163xzq** [comment]
用的雷电模拟器新版本运行的

**Comment by codeskyblue** [comment]
对了 adb的版本提供下

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codeskyblue** [comment]
很头疼，复现不了。我用了手机，Genymotion模拟器，都OK

**Comment by qq163xzq** [comment]
雷电模拟器自带的adb，或者adbshell.com上下载的adb都试过，都不行

**Comment by codeskyblue** [comment]
精力不够，放弃支持了

**Comment by lilongsy** [comment]
可能是端口冲突了。设置了一下环境变量ANDROID_ADB_SERVER_PORT为7912就好了。
