### ISSUE TITLE
python -m uiautomator2 init 失败

### ISSUE THREAD

**Issue by retrfy** [openatx/uiautomator2#316]
E:\>python -m uiautomator2 init
[D 190320 11:24:41 __main__:28] use cache directory: C:\Users\Administrator\.uiautomator2
Namespace(serial=None, server=None, subparser='init') init
[I 190320 11:24:41 __main__:80] >>> Initial device AdbDevice(serial=c1b1c8709904)
[I 190320 11:24:42 __main__:162] Install minicap, minitouch
[D 190320 11:24:42 __main__:157] Push https://github.com/openatx/stf-binaries/raw/master/node_modules/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch -> /data/lo
cal/tmp/minitouch:0755
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\uiautomator2\__main__.py", line 341, in <module>
    main()
  File "C:\Python27\lib\site-packages\uiautomator2\__main__.py", line 331, in main
    actions[args.subparser](args)
  File "C:\Python27\lib\site-packages\uiautomator2\__main__.py", line 284, in cmd_init
    init.install(args.server)
  File "C:\Python27\lib\site-packages\uiautomator2\__main__.py", line 163, in install
    self.push_url(self.minitouch_url)
  File "C:\Python27\lib\site-packages\uiautomator2\__main__.py", line 158, in push_url
    self._device.sync.push(path, dest, mode=mode)
  File "C:\Python27\lib\site-packages\uiautomator2\adbutils.py", line 370, in push
    mtime = int(datetime.datetime.now().timestamp())
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

**Comment by BiteFoo** [comment]
今天更新了，一样的问题，不过我退回了能用的版本。我的环境是ubuntu18.0 python2.7

**Comment by codeskyblue** [comment]
已修复
