### ISSUE TITLE
Description/classname 無法點擊

### ISSUE THREAD

**Issue by Terrytao12345** [openatx/uiautomator2#319]
我的d2(description="White balance options").click() 這個動作在Pixel2上 不明原因一直點擊不了
今天更新後一直fail ,上一個版本可以
我用weditor 查過 
className=android.widget.ImageButton
description=White balance options
也有嘗試寫在d2(className="android.widget.ImageButton","description=White balance options").click 裡 但uiautomator 感覺有做動作  但就是打不開  我用手點擊是可以的 代表不是手機app自己的問題

所以log裡面到了d2(text="Sunny").click()  到了這一步找不到text=sunny
就fail了.因為White balance options 更本還沒點進去 但uiauto已經認為他做過了?
應該是今天update了 init/main/adbutis 檔造成的? 

```

code>
d2(description=u"Lock A.E. / A.F.").click()
	time.sleep(2)
	d2(description="White balance options").click()
	d.screen_on()
	d.press("home")
	time.sleep(1.5)
	#D1 開啟CAMERA
	d(text="Camera").click()
	d2(text="Sunny").click()

log>
C:\Users\terrytao>python3 "C:\ffmpeg\white_papaer\TPE test\B2F.py"
Traceback (most recent call last):
  File "C:\ffmpeg\white_papaer\TPE test\B2F.py", line 72, in <module>
    main()
  File "C:\ffmpeg\white_papaer\TPE test\B2F.py", line 68, in main
    basic2()
  File "C:\ffmpeg\white_papaer\TPE test\B2F.py", line 44, in basic2
    d2(text="Sunny").click()
  File "C:\Users\terrytao\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\session.py", line 39, in _inner
    return fn(self, *args, **kwargs)
  File "C:\Users\terrytao\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\session.py", line 745, in click
    self.must_wait(timeout=timeout)
  File "C:\Users\terrytao\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\session.py", line 930, in must_wait
    raise UiObjectNotFoundError({'code': -32002, 'method': 'wait'})
uiautomator2.exceptions.UiObjectNotFoundError: -32002 Client error: <> data: , method: None

## Versions (版本)
Version: 0.2.1

## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快

- 手机型号= Pixel 2
Pixel2 camera version = 6.0.21.xxxxxx(Google playstore update) 

- 错误日志?
- 出错的代码片段?

## Screenshots （相关截图）
能有尽量有
![Screenshot_20190321-060930](https://user-images.githubusercontent.com/48781691/54735787-11cfc800-4be3-11e9-9b34-222268d142b5.png)


## Additional Details （其他信息）

**Comment by Terrytao12345** [comment]
補充一下:
White balance options 這選項是在camera 裡的slowmotion video mode 下
隨然其他mode 也有  問題應該是可以leaverage

**Comment by codeskyblue** [comment]
你这个错误看起来跟 更新了init没什么关系

**Comment by Terrytao12345** [comment]
恩恩 請問該如何驗證這方面的錯誤呢~~?
因為突然不能使用 哪邊我可以提供log 或什麼之類的分析

**Comment by codeskyblue** [comment]
看你的日志是 `uiautomator2.exceptions.UiObjectNotFoundError:` 是不是app更新了

**Comment by Terrytao12345** [comment]
@codeskyblue  不好意思 請問uiautomator2.exceptions 這邊的版本 或 日誌 在哪邊查詢

**Comment by codeskyblue** [comment]
webview?
