### ISSUE TITLE
child_by_text 引起uiautomator2.exceptions.JsonRpcError

### ISSUE THREAD

**Issue by zylbj** [openatx/uiautomator2#322]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```
for i in d(className="android.support.v7.widget.RecyclerView").child_by_text("集***纳",
    allow_scroll_search=True,resourceId="com.****_project_name"):
发生异常: uiautomator2.exceptions.JsonRpcError
-32001 Jsonrpc error: <com.fasterxml.jackson.databind.JsonMappingException> data: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.github.uiautomator.stub.Selector: no String-argument constructor/factory method to deserialize from String value ('12ec3082-34e6-4c1c-a274-eedfc1639193')  
at [Source: N/A; line: -1, column: -1]   
at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1456)   
at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1012)   
at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:370)   
at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:315)   
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1282)   
at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:159)   at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)   
at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3770)   
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2165)   
at com.googlecode.jsonrpc4j.JsonRpcBasicServer.convertJsonToParameters(JsonRpcBasicServer.java:483)   at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:463)   
at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)   
at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)   
at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)   at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)   
at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)   
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)   
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)   
at java.lang.Thread.run(Thread.java:764) , method: count
  File "D:\****\appuntitled-1.py", line 55, in <module>
    allow_scroll_search=True,resourceId="com.***project_name"):
```

## Versions (版本)
Name: uiautomator2  
Version: 0.2.0
## Issue and steps to reproduce (复现步骤)
加allow_scroll_search滚动正常，也能根据关键词找到对应的信息，然后就抛出了错误。
不加allow_scroll_search，也会滚动查找，一样的报错。如果找不到会有其他报错，但是当找到的时候就是目前的错误
pc jdk：1.8.181

设备信息：  
android 8.0.0
内核：
3.18.71-14176914
{'currentPackageName': 'com.ccb.bluesearent', 'displayHeight': 1920, 'displayRotation': 0, 'displaySizeDpX': 360, 'displaySizeDpY': 640, 'displayWidth': 1080, 'productName': 'hero2qltezc', 'screenOn': True, 'sdkInt': 26, 'naturalOrientation': True}

## Additional Details （其他信息）

**Comment by codeskyblue** [comment]
你这个滚了多长的具体，滚了多久？

**Comment by zylbj** [comment]
如果不把child_by_text结果当成list 处理，不用for，当他是单数。不会有问题。
但是child是支持放在for i in 里面的，当成复数。
