### ISSUE TITLE
[兼容性]vivo部分机型无法获取元素

### ISSUE THREAD

**Issue by nekorice** [openatx/uiautomator2#330]
## Versions (版本)
Version: 0.1.9( 后续尝试更新到Version:0.2.2，也有同样的问题 )
## Issue and steps to reproduce (复现步骤)
以下两台手机，能够成功init，其他功能都正常。
可以用app_start,app_stop启动关闭应用。
但是无法执行click，获取元素报异常。

vivo Y67A  系统版本：6.0
vivo Y66 系统版本：6.0.1

用text或者ResourceId查找明显存在的元素都报UiObjectNotFoundError。

而同样代码和测试应用在oppo机器上运行正常。

目前暂时先抛弃vivo，用oppo机器了，希望大神有时间解决一下。

## Screenshots （相关截图）
能有尽量有

## Additional Details （其他信息）

**Comment by mingyuan-xia** [comment]
把相关selector code贴一下，还有那个页面调用下hierarchy dump (u2的)然后贴一下

**Comment by nekorice** [comment]
弄hierarchy的时候，才发现weditor也有执行功能，试了一下，这次报错信息和用u2跑的时候不一样。
查了一下算是定位到了真正的问题。

vivo这几台机器的开发者选项还有一个额外选项，允许“USB模拟点击”，打开就可以正常执行了。
目前貌似只在vivo y系列发现。

weditor上直接执行报以下错误：

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\weditor\__main__.py", line 298, in post
    ret = eval(code, {'d': d})
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\uiautomator2\session.py", line 39, in _inner
    return fn(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\uiautomator2\session.py", line 750, in click
    self.session.click(x, y)
  File "C:\Python27\lib\site-packages\uiautomator2\session.py", line 329, in click
    self._click(x, y)
  File "C:\Python27\lib\site-packages\uiautomator2\utils.py", line 39, in inner
    ret = fn(self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\uiautomator2\session.py", line 333, in _click
    self.jsonrpc.click(x, y)
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 369, in __call__
    params, http_timeout)
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 376, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 458, in jsonrpc_call
    raise err
JsonRpcError: -32001 Jsonrpc error: <java.lang.SecurityException> data: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
  at android.os.Parcel.readException(Parcel.java:1599)
  at android.os.Parcel.readException(Parcel.java:1552)
  at android.app.IUiAutomationConnection$Stub$Proxy.injectInputEvent(IUiAutomationConnection.java:273)
  at android.app.UiAutomation.injectInputEvent(UiAutomation.java:440)
  at android.support.test.uiautomator.InteractionController.injectEventSync(InteractionController.java:690)
  at android.support.test.uiautomator.InteractionController.touchDown(InteractionController.java:351)
  at android.support.test.uiautomator.InteractionController.clickNoSync(InteractionController.java:220)
  at android.support.test.uiautomator.UiDevice.click(UiDevice.java:557)
  at com.github.uiautomator.stub.AutomatorServiceImpl.click(AutomatorServiceImpl.java:160)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
  at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
  at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
  at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
  at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
  at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
  at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
  at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
  at java.lang.Thread.run(Thread.java:818)
, method: click
[Finished in 0.576s]

而如果是用u2跑只有这种出错信息：

  File "C:\Python27\lib\site-packages\uiautomator2\session.py", line 745, in cli
ck
    self.must_wait(timeout=timeout)
  File "C:\Python27\lib\site-packages\uiautomator2\session.py", line 930, in mus
t_wait
    raise UiObjectNotFoundError({'code': -32002, 'method': 'wait'})
UiObjectNotFoundError: -32002 Client error: <> data: , method: None

感觉原始错误信息是不是封装的太深了，导致看不到有效报错信息。

**Comment by mingyuan-xia** [comment]
棒 能给张vivo那个选项的截图么 我更新到文档上去 顺便把Appetizer里面检测也做了
感觉不封装的问题 是security exception被catch认为是没找到 内建的等待implicit wait出来 然后timeout 估计需要parse下jsonrpc异常内容来直接抛出

**Comment by wusuandahuanggua** [comment]
实际上小米的手机也有个"USB调试（安全选项）"需要打开。也是用于触摸屏幕的

**Comment by crifan** [comment]
@mingyuan-xia 其他安卓手机（最新安卓系统）中也有类似选项，比如我的是 小米9的 `USB调试（安全设置）`，描述是`允许通过USB调试修改权限或模拟点击`，如图：

![59C7EA81-B407-464A-9B97-2F4DDE921466](https://user-images.githubusercontent.com/2750682/69109330-66994a80-0ab2-11ea-97ca-47a6f45741d1.png)
