### ISSUE TITLE
connect_usb failed: uiautomator2.adbutils.AdbError: unknown host service

### ISSUE THREAD

**Issue by chengu** [openatx/uiautomator2#334]
Versions: 0.2.3.dev2

复现步骤：
usb两台手机连接一台电脑，连接时connect_usb("xxxx")出错，拿掉一台，则正常。两台同时连接，用connect_wifi("xx")也正常。

- 手机型号：oppo r7sm
IDE: pycharm
python: 3.6.5

截图：
![image](https://user-images.githubusercontent.com/5955326/56591440-4f2cd880-661b-11e9-9d28-a3a9d524a7d0.png)

**Comment by qing0404** [comment]
我也遇到了相同的问题，有的电脑上连2台手机就正常，有的电脑就不行

**Comment by codeskyblue** [comment]
估计是 1.0.40版本的adb不支持 `host:forward-list` 协议

**Comment by qing0404** [comment]
那就很奇怪啦，都是用的40版本的adb，我有看到另一个问题里【issues#308】有提到说是版本回退0.1.9就可以了，我这试了下安装一直报错，版本回退要如何操作啊？

**Comment by codeskyblue** [comment]
```
pip install -U --pre uiautomator2
```

我不确定是否修好了，因为我本地复现不了。有问题再反馈给我

**Comment by qing0404** [comment]
试了下，时好时坏，连了2台设备，执行python -m uiautomator2 init第一次还是报错，又执行了一次又好了，不知道后面还会不会再报错

**Comment by codeskyblue** [comment]
试试最新版是不是还这样？

**Comment by qing0404** [comment]
最新版本0.3.1，init之后还是报错：adbutils.errors.AdbError: unknown host service

**Comment by codeskyblue** [comment]
要不换台电脑试试？

**Comment by qing0404** [comment]
换过试了，另一台电脑也是不行

**Comment by codeskyblue** [comment]
你的adb是不是特殊定制的？

**Comment by qing0404** [comment]
不是啊，就是sdk里面的adb，40版本

**Comment by codeskyblue** [comment]
底层用的是这个库 https://github.com/openatx/adbutils 你看看有办法修复不，我复现不了你的问题

**Comment by qing0404** [comment]
uiautomator2我现在是0.3.1版本，我怎么安装低版本的啊，我想换低版本的试试

**Comment by rickidorina211** [comment]
Hello I need help with this issue Pleaseee. I cant find any solution at here :( please sir

**Comment by rickidorina211** [comment]
[W 211228 17:20:49 __init__:218] [pid:3228] atx-agent has something wrong, auto recovering
OKAY
[D 211228 17:20:49 __init__:322] [pid:3228] [emulator-5554] device emulator-5554 is online
FAILTraceback (most recent call last):

  File "c:\Users\Admin\Desktop\twitter\test.py", line 5, in <module>
    d = uiautomator2.connect("emulator-5554")
  File "C:\Program Files\Python310\lib\site-packages\uiautomator2\__init__.py", line 1914, in connect
    return connect_usb(addr)
  File "C:\Program Files\Python310\lib\site-packages\uiautomator2\__init__.py", line 1955, in connect_usb
    return Device(serial)
  File "C:\Program Files\Python310\lib\site-packages\uiautomator2\__init__.py", line 262, in __init__
    wlan_ip = self.wlan_ip
  File "C:\Program Files\Python310\lib\site-packages\uiautomator2\__init__.py", line 453, in wlan_ip
    ip = self.http.get("/wlan/ip").text.strip()
  File "C:\Program Files\Python310\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\uiautomator2\__init__.py", line 223, in request
    self.__client._prepare_atx_agent()
  File "C:\Program Files\Python310\lib\site-packages\uiautomator2\__init__.py", line 323, in _prepare_atx_agent
    version_url = self.path2url("/version")
  File "C:\Program Files\Python310\lib\site-packages\uiautomator2\__init__.py", line 306, in path2url
    return urlparse.urljoin(self._get_atx_agent_url(), path)
  File "C:\Program Files\Python310\lib\site-packages\uiautomator2\__init__.py", line 287, in _get_atx_agent_url
    lport = self._adb_device.forward_port(
  File "C:\Program Files\Python310\lib\site-packages\adbutils\__init__.py", line 610, in forward_port
    for f in self.forward_list():
  File "C:\Program Files\Python310\lib\site-packages\adbutils\__init__.py", line 392, in forward_list
    c.check_okay()
  File "C:\Program Files\Python310\lib\site-packages\adbutils\__init__.py", line 169, in check_okay
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError: unknown host service

**Comment by rickidorina211** [comment]
Anyone here can help me pleaseeeee

**Comment by fendoucg2019** [comment]
> 

step1:：adb kill-server
step2：adb start-server
step3：python -m uiautomator2 init

**Comment by onebits** [comment]
遇到同样的问题....也是排查了很久..
更新到最新的adb就好了... 貌似老板的不支持uiautomator2中某些方法.
也是阴差阳错的出错...哎
https://developer.android.com/studio/releases/platform-tools?hl=zh-cn

**Comment by Louis24** [comment]
pip install adbutils==2.2.1 this woks fine 4 me thx
