### ISSUE TITLE
android9.0 devices apk install errror

### ISSUE THREAD

**Issue by FatDing** [openatx/uiautomator2#335]
注，代码或者日志请使用[Markdown](http://wowubuntu.com/markdown/)语法，看完删掉

```
{'udid': 'P7C0218417000733-e4:a7:c5:ab:dc:94-BKL-AL20', 'version': '9', 'serial': 'P7C0218417000733', 'brand': 'HONOR', 'model': 'BKL-AL20', 'hwaddr': 'e4:a7:c5:ab:dc:94', 'port': 7912, 'sdk': 28, 'agentVersion': '0.5.5', 'display': {'width': 1080, 'height': 2160}, 'battery': {'acPowered': False, 'usbPowered': True, 'wirelessPowered': False, 'status': 5, 'health': 2, 'present': True, 'level': 100, 'scale': 100, 'voltage': 4333, 'temperature': 290, 'technology': 'Li-poly'}, 'memory': {'total': 5837840, 'around': '6 GB'}, 'cpu': {'cores': 7, 'hardware': ''}, 'owner': None, 'presenceChangedAt': '0001-01-01T00:00:00Z', 'usingBeganAt': '0001-01-01T00:00:00Z', 'product': None, 'provider': None}
10:47:13 id: 7
10:47:13 download initialing
10:47:14 downloading 45.4% [13.9M/30.6M]
10:47:15 downloading 93.2% [28.5M/30.6M]
Traceback (most recent call last):
  File "D:/Works/Python/Python36/Auto_Test/test1.py", line 74, in <module>
    d.app_install('http://192.168.14.207:8888/CChessGooglePlayQMXQ.apk',installing_callback=ccc)
  File "D:\Works\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 603, in app_install
10:47:16 download 100%
10:47:16 error install
    return self._wait_install_finished(id, installing_callback)
  File "D:\Works\Python\Python36\lib\site-packages\uiautomator2\__init__.py", line 658, in _wait_install_finished
    raise RuntimeError("error", jdata.get('error'))
RuntimeError: ('error', "avc:  denied  { read } for  scontext=u:r:system_server:s0 tcontext=u:object_r:sdcardfs:s0 tclass=file permissive=0\nSystem server has no access to read file context u:object_r:sdcardfs:s0 (from path /sdcard/tmp/3830abb91a639e023ae6c22d3369ff37.apk, context u:r:system_server:s0)\nError: Unable to open file: /sdcard/tmp/3830abb91a639e023ae6c22d3369ff37.apk\nConsider using a file under /data/local/tmp/\nError: Can't open file: /sdcard/tmp/3830abb91a639e023ae6c22d3369ff37.apk\n\nException occurred while executing:\njava.lang.IllegalArgumentException: Error: Can't open file: /sdcard/tmp/3830abb91a639e023ae6c22d3369ff37.apk\n\tat com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:350)\n\tat com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:929)\n\tat com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:166)\n\tat android.os.ShellCommand.exec(ShellCommand.java:103)\n\tat com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23384)\n\tat android.os.Binder.shellCommand(Binder.java:642)\n\tat android.os.Binder.onTransact(Binder.java:540)\n\tat android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2804)\n\tat com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4435)\n\tat com.android.server.pm.HwPackageManagerService.onTransact(HwPackageManagerService.java:994)\n\tat android.os.Binder.execTransact(Binder.java:739)\n: exit status 255")

```

## Versions (版本)
通过`pip show uiautomator2`可以获取到

## Issue and steps to reproduce (复现步骤)
系统升级到android9.0后，都出现这个问题。安装apk失败。

- 我们公司的其中三款手机pixel2、pixel xl、Honor_V10（只有这三款是9.0系统）
-
- d.app_install('http://192.168.14.207:8888/CChessGooglePlayQMXQ.apk')

## Screenshots （相关截图）
能有尽量有
![image](https://user-images.githubusercontent.com/35364370/56629471-05c2a480-6680-11e9-9ce5-502189b12335.png)

## Additional Details （其他信息）

**Comment by codeskyblue** [comment]
fixed.

**Comment by FatDing** [comment]
Cool,Tankyou.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
