### ISSUE TITLE
运行一段时间手机卡死

### ISSUE THREAD

**Issue by zjlwmz** [openatx/uiautomator2#341]
>- 手机截图
![15](https://user-images.githubusercontent.com/5568478/57219035-76c36e00-7029-11e9-8751-5cc07f9fe3d4.png)

**Comment by zjlwmz** [comment]
这个弹出的进度条是 uiautomator2 产生的么

**Comment by zjlwmz** [comment]
/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py:375: RuntimeWarning: uiautomator2 is not reponding, restart uiautomator2 automatically
  stacklevel=1)
Traceback (most recent call last):
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/zhangjialu/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Users/zhangjialu/anaconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Users/zhangjialu/anaconda3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/zhangjialu/anaconda3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 320, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.0.103', port=7912): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangjialu/MyProject/55App自动测试/share_python/GuangFa/05today_entrust/today_entrust_test_001.py", line 136, in <module>
    row_list= get_today_deal_list()
  File "/Users/zhangjialu/MyProject/55App自动测试/share_python/GuangFa/05today_entrust/today_entrust_test_001.py", line 122, in get_today_deal_list
    detail_info = get_delegation_details()
  File "/Users/zhangjialu/MyProject/55App自动测试/share_python/GuangFa/05today_entrust/today_entrust_test_001.py", line 101, in get_delegation_details
    count = len(detail_value_list)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/session.py", line 1012, in __len__
    return self.count
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/session.py", line 1009, in count
    return self.jsonrpc.count(self.selector)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 363, in __call__
    params, http_timeout)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 377, in jsonrpc_retry_call
    self.reset_uiautomator()
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 533, in reset_uiautomator
    self._reqsess.post(self.path2url('/uiautomator'))
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 185, in request
    method, url, **kwargs)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.0.103', port=7912): Read timed out. (read timeout=60)

**Comment by zjlwmz** [comment]
能不能不要重启呢，

**Comment by zjlwmz** [comment]
又测试了一次


[2019-05-06 21:36:38] uiautomator is starting ...
[2019-05-06 21:36:39] uiautomator is starting ...
[2019-05-06 21:36:40] uiautomator is starting ...
/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py:375: RuntimeWarning: uiautomator2 is not reponding, restart uiautomator2 automatically
  stacklevel=1)
[2019-05-06 21:36:49] uiautomator is starting ...
Traceback (most recent call last):
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 370, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 419, in jsonrpc_call
    (time.time() - request_start))
uiautomator2.exceptions.GatewayError: uiautomator2.GatewayError(gateway error, time used 0.8s)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangjialu/MyProject/55App自动测试/share_python/GuangFa/05today_entrust/today_entrust_test_001.py", line 137, in <module>
    row_list= get_today_deal_list()
  File "/Users/zhangjialu/MyProject/55App自动测试/share_python/GuangFa/05today_entrust/today_entrust_test_001.py", line 122, in get_today_deal_list
    detail_info = get_delegation_details()
  File "/Users/zhangjialu/MyProject/55App自动测试/share_python/GuangFa/05today_entrust/today_entrust_test_001.py", line 101, in get_delegation_details
    count = len(detail_value_list)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/session.py", line 1012, in __len__
    return self.count
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/session.py", line 1009, in count
    return self.jsonrpc.count(self.selector)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 363, in __call__
    params, http_timeout)
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 377, in jsonrpc_retry_call
    self.reset_uiautomator()
  File "/Users/zhangjialu/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 558, in reset_uiautomator
    "Uiautomator started failed. Find solutions in https://github.com/openatx/uiautomator2/wiki/Common-issues"
RuntimeError: Uiautomator started failed. Find solutions in https://github.com/openatx/uiautomator2/wiki/Common-issues

Process finished with exit code 1

**Comment by codeskyblue** [comment]
手机型号？代码？

**Comment by codeskyblue** [comment]
尽量提供详细的信息，这样提issue没有任何帮助

**Comment by zjlwmz** [comment]
嗯，对提交issue没有没有什么经验，以后会多注意
