### ISSUE TITLE
小米和华为手机Uiautomator started failed，很急啊，请帮忙看看到底是哪里出问题了

### ISSUE THREAD

**Issue by qing0404** [openatx/uiautomator2#361]
小米和华为手机都出现Uiautomator started failed

华为V10之前测试还是正常的，现在用也一样出现这个问题，连续换了3个手机试了都是一样的问题，

- 很急啊，请帮忙看看到底是哪里出问题了

[2019-06-06 00:24:04] wait uiautomator is ready ...
[2019-06-06 00:24:05] wait uiautomator is ready ...
[2019-06-06 00:24:06] wait uiautomator is ready ...
[2019-06-06 00:24:07] wait uiautomator is ready ...
[2019-06-06 00:24:08] wait uiautomator is ready ...
[2019-06-06 00:24:09] wait uiautomator is ready ...
[2019-06-06 00:24:10] wait uiautomator is ready ...
[2019-06-06 00:24:11] wait uiautomator is ready ...
[2019-06-06 00:24:12] wait uiautomator is ready ...
[2019-06-06 00:24:13] wait uiautomator is ready ...
[2019-06-06 00:24:14] wait uiautomator is ready ...
[2019-06-06 00:24:15] wait uiautomator is ready ...
[2019-06-06 00:24:16] wait uiautomator is ready ...
[2019-06-06 00:24:17] wait uiautomator is ready ...
[2019-06-06 00:24:18] wait uiautomator is ready ...
[2019-06-06 00:24:19] wait uiautomator is ready ...
[2019-06-06 00:24:20] wait uiautomator is ready ...
[2019-06-06 00:24:21] wait uiautomator is ready ...
[2019-06-06 00:24:22] wait uiautomator is ready ...
[2019-06-06 00:24:23] wait uiautomator is ready ...
Traceback (most recent call last):
  File "E:\python\py_projects\703_test\common\uitest.py", line 79, in run
    testMethod()
  File "E:\python\py_projects\703_test\case\case_watch.py", line 901, in test_device_104
    appCall = Position(app_sn)
  File "E:\python\py_projects\703_test\app\position.py", line 15, in __init__
    self.device = d.connect_usb(app_sn)
  File "D:\work\Python37\lib\site-packages\uiautomator2\__init__.py", line 270, in connect_usb
    d.healthcheck()
  File "D:\work\Python37\lib\site-packages\uiautomator2\__init__.py", line 618, in healthcheck
    raise RuntimeError("Uiautomator started failed.")
RuntimeError: Uiautomator started failed.

**Comment by qing0404** [comment]
2019/06/05 16:56:59 main.go:1377: Ignore SIGHUP
2019/06/05 16:56:59 main.go:1381: Kill server
2019/06/05 16:56:59 main.go:1384: wait previous server stopped
atx-agent version 0.3.6
Listen on http://192.168.31.72:7912
2019/06/05 16:57:01 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
2019/06/05 16:57:01 cmdctrl.go:27: DEBUG program pid: 14187
2019/06/05 16:57:01 main.go:794: rotation change received: 0
2019/06/05 16:57:01 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 1080x2160@800x800/0]
INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.github.uiautomator.stub.Stub:
INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS_CODE: 1
INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stack=java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.github.uiautomator.ACTION_STOP }
	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1784)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1825)
	at android.app.ContextImpl.startService(ContextImpl.java:1797)
	at com.github.uiautomator.stub.Stub.tearDown(Stub.java:126)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2252)

INSTRUMENTATION_STATUS: stream=
Error in testUIAutomatorStub(com.github.uiautomator.stub.Stub):
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.github.uiautomator.ACTION_STOP }
	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1784)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1825)
	at android.app.ContextImpl.startService(ContextImpl.java:1797)
	at com.github.uiautomator.stub.Stub.tearDown(Stub.java:126)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2252)

INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS_CODE: -2
INSTRUMENTATION_RESULT: stream=

Time: 0.905

**Comment by qing0404** [comment]
华为v10 现在的情况是刚开始能启动，测试的过程中Uiautomator started failed，只有就一直无法启动了

**Comment by codeskyblue** [comment]
`pip3 show uiautomator2` 我看看版本号

**Comment by qing0404** [comment]
Name: uiautomator2
Version: 0.1.3.dev40
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: d:\work\python37\lib\site-packages
Requires: requests, six, humanize, fire, docopt, progress, retry, whichcraft, pillow, lxml
Required-by:

**Comment by codeskyblue** [comment]
现在版本都 `0.2.3`了，你先升级下，然后重新init下

**Comment by qing0404** [comment]
我另一台电脑上是0.2.3，在那个上面也是这个问题

**Comment by codeskyblue** [comment]
型号写下，我看看能不能借到

**Comment by qing0404** [comment]
华为V10

**Comment by qing0404** [comment]
我那台PC现在版本已经是0.3.1了，现在init都失败了
[I 190620 10:29:45 __main__:172] Install minicap, minitouch
[D 190620 10:29:45 __main__:157] Push https://github.com/openatx/stf-binaries/ra
w/master/node_modules/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch -> /da
ta/local/tmp/minitouch:0755
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\urllib3\connection.py", line 159, in _new_
conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "D:\Python37\lib\site-packages\urllib3\util\connection.py", line 80, in c
reate_connection
    raise err
  File "D:\Python37\lib\site-packages\urllib3\util\connection.py", line 70, in c
reate_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没
有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in u
rlopen
    chunked=chunked)
  File "D:\Python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _
make_request
    self._validate_conn(conn)
  File "D:\Python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _
validate_conn
    conn.connect()
  File "D:\Python37\lib\site-packages\urllib3\connection.py", line 301, in conne
ct
    conn = self._new_conn()
  File "D:\Python37\lib\site-packages\urllib3\connection.py", line 168, in _new_
conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnecti
on object at 0x00000000044824E0>: Failed to establish a new connection: [WinErro
r 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in u
rlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\Python37\lib\site-packages\urllib3\util\retry.py", line 399, in incre
ment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubuserconten
t.com', port=443): Max retries exceeded with url: /openatx/stf-binaries/master/n
ode_modules/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-26/minicap.so (Cause
d by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0
x00000000044824E0>: Failed to establish a new connection: [WinError 10060] 由于
连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python37\lib\site-packages\uiautomator2\__main__.py", line 367, in <m
odule>
    main()
  File "D:\Python37\lib\site-packages\uiautomator2\__main__.py", line 357, in ma
in
    actions[args.subparser](args)
  File "D:\Python37\lib\site-packages\uiautomator2\__main__.py", line 302, in cm
d_init
    init.install(args.server)
  File "D:\Python37\lib\site-packages\uiautomator2\__main__.py", line 179, in in
stall
    self.push_url(url)
  File "D:\Python37\lib\site-packages\uiautomator2\__main__.py", line 149, in pu
sh_url
    path = cache_download(url, os.path.basename(url))
  File "D:\Python37\lib\site-packages\uiautomator2\__main__.py", line 68, in cac
he_download
    r = requests.get(url, stream=True, headers=headers)
  File "D:\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python37\lib\site-packages\requests\sessions.py", line 533, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "D:\Python37\lib\site-packages\requests\sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\Python37\lib\site-packages\requests\sessions.py", line 668, in <listc
omp>
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\Python37\lib\site-packages\requests\sessions.py", line 247, in resolv
e_redirects
    **adapter_kwargs
  File "D:\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercon
tent.com', port=443): Max retries exceeded with url: /openatx/stf-binaries/maste
r/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-26/minicap.so (Ca
used by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object a
t 0x00000000044824E0>: Failed to establish a new connection: [WinError 10060] 由
于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

C:\Users\test01>python -m uiautomator2 init
[D 190620 10:33:24 __main__:28] use cache directory: C:\Users\test01\.uiautomato
r2
Namespace(serial=None, server=None, subparser='init') init
[I 190620 10:33:24 __main__:88] >>> Initial device AdbDevice(serial=98895a344d4d
54554f)
[I 190620 10:33:25 __main__:172] Install minicap, minitouch
[D 190620 10:33:25 __main__:157] Push https://github.com/openatx/stf-binaries/ra
w/master/node_modules/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch -> /da
ta/local/tmp/minitouch:0755
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\urllib3\connection.py", line 159, in _new_
conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "D:\Python37\lib\site-packages\urllib3\util\connection.py", line 80, in c
reate_connection
    raise err
  File "D:\Python37\lib\site-packages\urllib3\util\connection.py", line 70, in c
reate_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没
有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in u
rlopen
    chunked=chunked)
  File "D:\Python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _
make_request
    self._validate_conn(conn)
  File "D:\Python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _
validate_conn
    conn.connect()
  File "D:\Python37\lib\site-packages\urllib3\connection.py", line 301, in conne
ct
    conn = self._new_conn()
  File "D:\Python37\lib\site-packages\urllib3\connection.py", line 168, in _new_
conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnecti
on object at 0x0000000004449DA0>: Failed to establish a new connection: [WinErro
r 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in u
rlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\Python37\lib\site-packages\urllib3\util\retry.py", line 399, in incre
ment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=44
3): Max retries exceeded with url: /openatx/stf-binaries/raw/master/node_modules
/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-26/minicap.so (Caused by NewCon
nectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004
449DA0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段
时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python37\lib\site-packages\uiautomator2\__main__.py", line 367, in <m
odule>
    main()
  File "D:\Python37\lib\site-packages\uiautomator2\__main__.py", line 357, in ma
in
    actions[args.subparser](args)
  File "D:\Python37\lib\site-packages\uiautomator2\__main__.py", line 302, in cm
d_init
    init.install(args.server)
  File "D:\Python37\lib\site-packages\uiautomator2\__main__.py", line 179, in in
stall
    self.push_url(url)
  File "D:\Python37\lib\site-packages\uiautomator2\__main__.py", line 149, in pu
sh_url
    path = cache_download(url, os.path.basename(url))
  File "D:\Python37\lib\site-packages\uiautomator2\__main__.py", line 68, in cac
he_download
    r = requests.get(url, stream=True, headers=headers)
  File "D:\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python37\lib\site-packages\requests\sessions.py", line 533, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "D:\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port
=443): Max retries exceeded with url: /openatx/stf-binaries/raw/master/node_modu
les/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-26/minicap.so (Caused by New
ConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000
004449DA0>: Failed to establish a new connection: [WinError 10060] 由于连接方在
一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by codeskyblue** [comment]
adb看起来不太稳定的样子

**Comment by qing0404** [comment]
我自己用的pc是0.1.3.dev40反而挺正常的

**Comment by codeskyblue** [comment]
0.1.3的adb是封装的adb命令，0.3.1直接使用socket协议跟adb server通信

**Comment by qing0404** [comment]
那这个怎么解决呢，换个adb？
