### ISSUE TITLE
指定 ANDROID_SERIAL 初始化 uiautomator2 失败

### ISSUE THREAD

**Issue by lvqier** [openatx/uiautomator2#370]
- 手机型号 
红米2 Android 5.1.1
- uiautomator2的版本号(`pip show uiautomator2`)
uiautomator2: 0.3.0
adbutils: 0.3.4
- 相关日志
```
$ python -m uiautomator2 init -s 86a53087
[D 190619 18:21:41 __main__:28] use cache directory: /Users/Workspace/.uiautomator2
Namespace(serial='875308797d32', server=None, subparser='init') init
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Workspace/script/pyenv/lib/python3.7/site-packages/uiautomator2/__main__.py", line 367, in <module>
    main()
  File "/Users/Workspace/script/pyenv/lib/python3.7/site-packages/uiautomator2/__main__.py", line 357, in main
    actions[args.subparser](args)
  File "/Users/Workspace/script/pyenv/lib/python3.7/site-packages/uiautomator2/__main__.py", line 295, in cmd_init
    device = adbutils.adb.device_with_serial(args.serial)
AttributeError: 'AdbClient' object has no attribute 'device_with_serial'
```
- 最好能附上可能复现问题的代码。
```
$ python -m uiautomator2 init -s 86a53087
```

**Comment by codeskyblue** [comment]
update uiautomator2 to 0.3.1

**Comment by hmonlinegit** [comment]
pip install --upgrade uiautomator2 adbutils
把这个更新，解决2个依赖库不兼容的问题
