### ISSUE TITLE
RuntimeError("error", jdata.get('error')) when trigger d.app_install()

### ISSUE THREAD

**Issue by troub1emaker-sys** [openatx/uiautomator2#372]
- 手机型号
Google Pixel 1

- uiautomator2的版本号(`pip show uiautomator2`)
Version: 0.2.3

- 手机截图
N/A

- 相关日志
```
12:34:06 id: 4
12:34:06 download initialing
12:34:07 download initialing
12:34:08 download 100%
12:34:08 error install
Traceback (most recent call last):
  File "C:\Users\username\Downloads\test.py", line 1027, in <module>
    d.app_install('https://drive.google.com/file/d/1_-Dx9XyPRGoDzDCEMOSFlA4wp29F9us8/view?usp=sharing')
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator2\__init__.py", line 626, in app_install
    return self._wait_install_finished(id, installing_callback)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator2\__init__.py", line 681, in _wait_install_finished
    raise RuntimeError("error", jdata.get('error'))
RuntimeError: ('error', 'Error: Failed to parse APK file: /data/local/tmp/782048cd90372bbfb776823991600367.apk\n\nException occurred while executing:\njava.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/782048cd90372bbfb776823991600367.apk\n\tat com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:471)\n\tat com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1060)\n\tat com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:169)\n\tat android.os.ShellCommand.exec(ShellCommand.java:104)\n\tat com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21661)\n\tat android.os.Binder.shellCommand(Binder.java:881)\n\tat android.os.Binder.onTransact(Binder.java:765)\n\tat android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4858)\n\tat com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4026)\n\tat android.os.Binder.execTransactInternal(Binder.java:1021)\n\tat android.os.Binder.execTransact(Binder.java:994)\nCaused by: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/782048cd90372bbfb776823991600367.apk\n\tat android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1594)\n\tat android.content.pm.PackageParser.parseApkLite(PackageParser.java:1579)\n\tat com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:464)\n\t... 10 more\n: exit status 255')
```

- 最好能附上可能复现问题的代码。
```
from uiautomator2 import connect
d = connect()
d.app_install('https://drive.google.com/file/d/1_-Dx9XyPRGoDzDCEMOSFlA4wp29F9us8/view?usp=sharing')
```

**Comment by codeskyblue** [comment]
下载地址不对。
