### ISSUE TITLE
指定ANDROID_SERIAL连接设备失败

### ISSUE THREAD

**Issue by lvqier** [openatx/uiautomator2#374]
- 手机型号
 Android 5.1.1
- uiautomator2的版本号(`pip show uiautomator2`)
adbutils==0.3.4
uiautomator2==0.3.1
- 手机截图
无
- 相关日志
无
- 最好能附上可能复现问题的代码。
```
>>> import uiautomator2 as u2
>>> d = u2.connect('87b3087a')
/Users/Workspace/pyenv/lib/python3.7/site-packages/uiautomator2/__init__.py:163: RuntimeWarning: backend atx-agent is not alive, start again ...
  RuntimeWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Workspace/pyenv/lib/python3.7/site-packages/uiautomator2/__init__.py", line 118, in connect
    return connect_usb(addr)
  File "/Users/Workspace/pyenv/lib/python3.7/site-packages/uiautomator2/__init__.py", line 165, in connect_usb
    device.shell("/data/local/tmp/atx-agent", "server", "-d")
TypeError: shell() takes from 2 to 3 positional arguments but 4 were given
```

**Comment by codeskyblue** [comment]
fix by sha:67c555bb624190a916dcb8f1b55bb637a725f3f3

**Comment by codeskyblue** [comment]
update uiautomator2 to 0.3.2
