### ISSUE TITLE
AttributerError:module 'uiautomator2' has no attribute 'connect'

### ISSUE THREAD

**Issue by vigiles** [openatx/uiautomator2#381]
- 手机型号：小米note3、MIUI9.5、Android7.1.1
- uiautomator2的版本号：0.3.3
- 报错情景：
1）手机安装Termux，在Termux内安装Python3及各种依赖，pip3安装uiautomator2。
2）在Termux内执行python3 my.py。
3）错位提示：AttributeError:module 'uiautomator2' has no attribute 'connect'。
- 相关代码：
import uiautomator2 as u2
d = u2.connect('192.168.1.104')
print(d.info)

**Comment by sltruman** [comment]
python环境有问题，没有环境变量。

**Comment by vigiles** [comment]
> python环境有问题，没有环境变量。
谢谢！python3和UiAutomator2安装后，在termux的shell里直接执行指令是正常的。我没太明白你说的哪个环境变量。

**Comment by vigiles** [comment]
> python环境有问题，没有环境变量。

谢谢！python3和UiAutomator2安装后，在termux的shell里直接执行指令是正常的。我没太明白你说的哪个环境变量。

**Comment by sltruman** [comment]
可能时Python库的环境变量。

**Comment by vigiles** [comment]
> 可能时Python库的环境变量。

 直接在termux内执行`python3`，进入python的shell，
然后执行一行一行的执行这3行代码：
【
import uiautomator2 as u2
d = u2.connect('192.168.1.104')
print(d.info)
】不报上面的错误了，但有别的错误：
“ /data/data/com.termux/files/usr/lib/python3.7/site-packages/uiautomator2/__init__.py:427:RuntimeWarning:uiautomator2 is not reponding,restart uiautomator2 automatically
” ，然后好像是在自动启动，最后：
“
$ python3
Python 3.7.3 (default, Jun 28 2019, 18:43:05)
[Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf6 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uiautomator2 as uu
>>> d=uu.connect('192.168.1.102')
>>> print(d.info)
Product-brand: Xiaomi
roduct-brand: Xiaomi
[2019-07-10 21:10:34] uiautomator is starting ...
[2019-07-10 21:10:35] uiautomator is starting ...
[2019-07-10 21:10:36] uiautomator is starting ...
[2019-07-10 21:10:37] uiautomator is starting ...
[2019-07-10 21:10:38] uiautomator is starting ...
[2019-07-10 21:10:39] uiautomator is starting ...
[2019-07-10 21:10:40] uiautomator is starting ...
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/uiautomator2/__init__.py", line 422, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/uiautomator2/__init__.py", line 472, in jsonrpc_call
    (time.time() - request_start))
uiautomator2.exceptions.GatewayError: uiautomator2.GatewayError(gateway error, time used 0.1s)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/uiautomator2/__init__.py", line 1232, in __getattr__
    return getattr(self._default_session, attr)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/uiautomator2/session.py", line 628, in info
    return self.jsonrpc.deviceInfo()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/uiautomator2/__init__.py", line 415, in __call__
    params, http_timeout)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/uiautomator2/__init__.py", line 429, in jsonrpc_retry_call
    self.reset_uiautomator()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/uiautomator2/__init__.py", line 630, in reset_uiautomator
    "Uiautomator started failed. Find solutions in https://github.com/openatx/uiautomator2/wiki/Common-issues"
RuntimeError: Uiautomator started failed. Find solutions in https://github.com/openatx/uiautomator2/wiki/Common-issues
”
只在TestHome上看到了相关的一个帖子，但是场景不同。

**Comment by sltruman** [comment]
似乎是模拟器与Pc无法联通

**Comment by vigiles** [comment]
> 似乎是模拟器与Pc无法联通

像开头说的，我这个场景和PC没有关系。Termux.apk是Android上的一个linux shell环境，python3、UiAutomator2等都是在这个termux内。
刚刚放入了arm版的adb文件测试，错误仍如上文，看来不是adb的问题。

**Comment by mingyuan-xia** [comment]
暂时没有计划测试或支持termux
