### ISSUE TITLE
atx-agent is not alive, start again ...

### ISSUE THREAD

**Issue by zy9096** [openatx/uiautomator2#384]
![image](https://user-images.githubusercontent.com/19945764/61165299-416b5d00-a551-11e9-9442-17bf0b72c23d.png)
![image](https://user-images.githubusercontent.com/19945764/61165314-5cd66800-a551-11e9-9b9f-0df6f02aea0e.png)
请问该怎么解决，需要打哪些log

**Comment by zy9096** [comment]
yfve_8q:/data/local/tmp $ ./atx-agent server
./atx-agent server
atx-agent version 0.6.0
Listen on http://172.20.30.3:7912
2019/07/11 21:56:44 [INFO][github.com/openatx/atx-agent] main.go:555: service ui
automator: startservice com.github.uiautomator/.Service
2019/07/11 21:56:44 DEBUG start args: [am instrument -w -r -e debug false -e cla
ss com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.
test.runner.AndroidJUnitRunner], env: []
2019/07/11 21:56:44 DEBUG program pid: 4509
onError: commandError=true message=INSTRUMENTATION_FAILED: com.github.uiautomato
r.test/android.support.test.runner.AndroidJUnitRunner
android.util.AndroidException: INSTRUMENTATION_FAILED: com.github.uiautomator.te
st/android.support.test.runner.AndroidJUnitRunner
        at com.android.commands.am.Instrument.run(Instrument.java:486)
        at com.android.commands.am.Am.runInstrument(Am.java:194)INSTRUMENTATION_
STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.github.
uiautomator.test/android.support.test.runner.AndroidJUnitRunner}

        at com.android.commands.am.Am.onRun(Am.java:80)INSTRUMENTATION_STATUS: i
d=ActivityManagerService

        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)INSTRUMEN
TATION_STATUS_CODE: -1

        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
2019/07/11 21:56:45 DEBUG cmd wait err: exit status 1
2019/07/11 21:56:45 DEBUG idle for 500ms
2019/07/11 21:56:45 DEBUG start args: [am instrument -w -r -e debug false -e cla
ss com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.
test.runner.AndroidJUnitRunner], env: []
2019/07/11 21:56:45 DEBUG program pid: 4525
onError: commandError=true message=INSTRUMENTATION_FAILED: com.github.uiautomato
r.test/android.support.test.runner.AndroidJUnitRunner
android.util.AndroidException: INSTRUMENTATION_FAILED: com.github.uiautomator.te
st/android.support.test.runner.AndroidJUnitRunnerINSTRUMENTATION_STATUS: Error=U
nable to find instrumentation info for: ComponentInfo{com.github.uiautomator.tes
t/android.support.test.runner.AndroidJUnitRunner}

INSTRUMENTATION_STATUS: id=ActivityManagerService
        at com.android.commands.am.Instrument.run(Instrument.java:486)INSTRUMENT
ATION_STATUS_CODE: -1

        at com.android.commands.am.Am.runInstrument(Am.java:194)
        at com.android.commands.am.Am.onRun(Am.java:80)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
2019/07/11 21:56:46 DEBUG cmd wait err: exit status 1
2019/07/11 21:56:46 DEBUG idle for 500ms
2019/07/11 21:56:46 DEBUG start args: [am instrument -w -r -e debug false -e cla
ss com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.
test.runner.AndroidJUnitRunner], env: []
2019/07/11 21:56:46 DEBUG program pid: 4535
onError: commandError=true message=INSTRUMENTATION_FAILED: com.github.uiautomato
r.test/android.support.test.runner.AndroidJUnitRunner
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: Component
Info{com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}
android.util.AndroidException: INSTRUMENTATION_FAILED: com.github.uiautomator.te
st/android.support.test.runner.AndroidJUnitRunner

INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS_CODE: -1 at com.android.commands.am.Instrument.run(Instru
ment.java:486)

        at com.android.commands.am.Am.runInstrument(Am.java:194)
        at com.android.commands.am.Am.onRun(Am.java:80)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
2019/07/11 21:56:47 DEBUG cmd wait err: exit status 1
2019/07/11 21:56:47 DEBUG idle for 500ms
2019/07/11 21:56:47 DEBUG start args: [am instrument -w -r -e debug false -e cla
ss com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.
test.runner.AndroidJUnitRunner], env: []
2019/07/11 21:56:47 DEBUG program pid: 4545
onError: commandError=true message=INSTRUMENTATION_FAILED: com.github.uiautomato
r.test/android.support.test.runner.AndroidJUnitRunner
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: Component
Info{com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}
android.util.AndroidException: INSTRUMENTATION_FAILED: com.github.uiautomator.te
st/android.support.test.runner.AndroidJUnitRunner

INSTRUMENTATION_STATUS: id=ActivityManagerService
        at com.android.commands.am.Instrument.run(Instrument.java:486)INSTRUMENT
ATION_STATUS_CODE: -1

        at com.android.commands.am.Am.runInstrument(Am.java:194)
        at com.android.commands.am.Am.onRun(Am.java:80)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
2019/07/11 21:56:48 DEBUG cmd wait err: exit status 1
2019/07/11 21:56:48 DEBUG idle for 500ms
2019/07/11 21:56:48 DEBUG program finished
2019/07/11 21:56:48 [INFO][github.com/openatx/atx-agent] main.go:560: service ui
automator: stopservice com.github.uiautomator/.Service

**Comment by zy9096** [comment]
Android 9，通过usb线连接的电脑

**Comment by zy9096** [comment]
问题已解决

**Comment by SLanXing** [comment]
你怎么解决的，我这边wifi连接的，一直都不行，但是别人又可以

**Comment by RunningIkkyu** [comment]
请问楼主怎么解决的啊

**Comment by codeskyblue** [comment]
他这个应该是少个apk没有安装吧，重新跑下`uiautomator2 init`就好了

**Comment by zy9096** [comment]
> 你怎么解决的，我这边wifi连接的，一直都不行，但是别人又可以

我的手机本地有个服务会禁用端口访问，导致PC跟uiautomator server无法通过127.0.0.1:port建立通信，后来我把服务删除就好了。
wifi连接的，先看下能不能ping通ip，能ping通的情况下，先启动atx，再用电脑试试访问127.0.0.1:7912这个地址，如果不能访问的话，可能你的设备也有端口的问题
