### ISSUE TITLE
d.dump_hierarchy()偶现500

### ISSUE THREAD

**Issue by chuckyLin** [openatx/uiautomator2#392]
- 手机型号：小米4 安卓6.0.1
- uiautomator2的版本号：0.3.3
- 相关日志
```
WARNING:root:request error: Post http://127.0.0.1:9008/jsonrpc/0: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

getRoot error: 500 Server Error: Internal Server Error for url: http://127.0.0.1:53170/dump/hierarchy
发现bug： can only concatenate str (not "HTTPError") to str

Traceback (most recent call last):
  File "start.py", line 59, in getRoot
    writeFile("xml/pageSource_"+deviceId+".xml", driver.dump_hierarchy())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sit
e-packages\uiautomator2\session.py", line 475, in dump_hierarchy
    res.raise_for_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sit
e-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url:
http://127.0.0.1:53170/dump/hierarchy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 868, in <module>
    main(driver)
  File "start.py", line 600, in main
    root = getRoot()
  File "start.py", line 67, in getRoot
    writeFile("获取元素超时出现了"+deviceId+".txt", '\n'+e, 'a')
TypeError: can only concatenate str (not "HTTPError") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 885, in <module>
    setDefaultSecure(secure)
NameError: name 'secure' is not defined
```
- 最好能附上可能复现问题的代码。
def writeFile(fileName, text, type='w'):
    with open(fileName, type, encoding='utf-8') as f:
        f.write(text)
# 多次执行d.dump_hierarchy()
writeFile("test.xml", d.dump_hierarchy())

**Comment by thlengane** [comment]
This is fixed on the latest update, you can close.

**Comment by codeskyblue** [comment]
atx-agent还需要修正下 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
