### ISSUE TITLE
wifi连接电视盒子init失败

### ISSUE THREAD

**Issue by SLanXing** [openatx/uiautomator2#398]
**Version**
Name: uiautomator2
Version: 0.3.3
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: g:\devlopment\python\python37\lib\site-packages
Requires: requests, six, humanize, fire, docopt, progress, retry, whichcraft, logzero, adbutils, pillow, lxml
Required-by:

**操作步骤**
wifi连接设备（电视盒子）
执行python -m uiautomator2 init

**结果日志**

G:\Code\PythonCode\android_performace>python -m uiautomator2 init
[D 190801 16:46:39 __main__:28] use cache directory: C:\Users\xxx\.uiautomator2
Namespace(serial=None, server=None, subparser='init') init
[I 190801 16:46:39 __main__:88] >>> Initial device AdbDevice(serial=192.168.3.5:5555)
[I 190801 16:46:39 __main__:172] Install minicap, minitouch
[D 190801 16:46:39 __main__:157] Push https://github.com/openatx/stf-binaries/raw/master/node_modules/minitouch-prebuilt/prebuilt/armeabi-v7a/bin/minitouch -> /data/local/tmp/minitouch:0755
[D 190801 16:46:39 __main__:157] Push https://github.com/openatx/stf-binaries/raw/master/node_modules/minicap-prebuilt/prebuilt/armeabi-v7a/lib/android-22/minicap.so -> /data/local/tmp/minicap.so:0755
[D 190801 16:46:39 __main__:157] Push https://github.com/openatx/stf-binaries/raw/master/node_modules/minicap-prebuilt/prebuilt/armeabi-v7a/bin/minicap -> /data/local/tmp/minicap:0755
[I 190801 16:46:40 __main__:182] Install com.github.uiautomator, com.github.uiautomator.test
[I 190801 16:46:40 __main__:191] Already installed com.github.uiautomator apks
[I 190801 16:46:40 __main__:193] Install atx-agent
[D 190801 16:46:41 __main__:157] Push https://github.com/openatx/atx-agent/releases/download/0.6.0/atx-agent_0.6.0_linux_armv7.tar.gz -> /data/local/tmp/atx-agent:0755
[D 190801 16:47:05 __main__:100] Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')
[D 190801 16:47:05 __main__:100] Shell: ('/data/local/tmp/atx-agent', 'server', '-d')
[I 190801 16:47:05 __main__:202] Check install
[D 190801 16:47:05 __main__:212] Forward: local:tcp:53583 -> remote:tcp:7912
[D 190801 16:47:06 __main__:212] Forward: local:tcp:53583 -> remote:tcp:7912
[D 190801 16:47:06 __main__:212] Forward: local:tcp:53583 -> remote:tcp:7912
[D 190801 16:47:07 __main__:212] Forward: local:tcp:53583 -> remote:tcp:7912
[D 190801 16:47:07 __main__:212] Forward: local:tcp:53583 -> remote:tcp:7912
[D 190801 16:47:08 __main__:212] Forward: local:tcp:53583 -> remote:tcp:7912
[D 190801 16:47:08 __main__:212] Forward: local:tcp:53583 -> remote:tcp:7912
[D 190801 16:47:09 __main__:212] Forward: local:tcp:53583 -> remote:tcp:7912
[D 190801 16:47:09 __main__:212] Forward: local:tcp:53583 -> remote:tcp:7912
[D 190801 16:47:10 __main__:212] Forward: local:tcp:53583 -> remote:tcp:7912
Traceback (most recent call last):
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "G:\Devlopment\Python\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "G:\Devlopment\Python\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "G:\Devlopment\Python\Python37\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Devlopment\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "G:\Devlopment\Python\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "G:\Devlopment\Python\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "G:\Devlopment\Python\Python37\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Devlopment\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "G:\Devlopment\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\Devlopment\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 367, in <module>
    main()
  File "G:\Devlopment\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 357, in main
    actions[args.subparser](args)
  File "G:\Devlopment\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 302, in cmd_init
    init.install(args.server)
  File "G:\Devlopment\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 203, in install
    self.check_atx_agent_version()
  File "<G:\Devlopment\Python\Python37\lib\site-packages\decorator.py:decorator-gen-10>", line 2, in check_atx_agent_version
  File "G:\Devlopment\Python\Python37\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "G:\Devlopment\Python\Python37\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "G:\Devlopment\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 213, in check_atx_agent_version
    response = requests.get("http://127.0.0.1:%d/version" % port).text
  File "G:\Devlopment\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "G:\Devlopment\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "G:\Devlopment\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "G:\Devlopment\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "G:\Devlopment\Python\Python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by SLanXing** [comment]
关键命令：adb shell /data/local/tmp/atx-agent server -d

*不执行此命令，脚本跑着一段时间后断开连接*
Traceback (most recent call last):
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "G:\Devlopment\Python\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "G:\Devlopment\Python\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "G:\Devlopment\Python\Python37\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Devlopment\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "G:\Devlopment\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "G:\Devlopment\Python\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "G:\Devlopment\Python\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "G:\Devlopment\Python\Python37\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Devlopment\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 229, in request
    method, url, **kwargs)
  File "G:\Devlopment\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "G:\Devlopment\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "G:\Devlopment\Python\Python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:/Code/PythonCode/android_performace/app_performance.py", line 644, in <module>
    my_test_func()
  File "G:/Code/PythonCode/android_performace/app_performance.py", line 591, in my_test_func
    test1.test()
  File "G:/Code/PythonCode/android_performace/app_performance.py", line 400, in test
    self.ergodic_button.ergodic_button()
  File "G:/Code/PythonCode/android_performace/app_performance.py", line 309, in ergodic_button
    toast = self.get_toast()
  File "G:/Code/PythonCode/android_performace/app_performance.py", line 243, in get_toast
    message = self.driver.toast.get_message(wait_time)
  File "G:\Devlopment\Python\Python37\lib\site-packages\uiautomator2\session.py", line 170, in get_message
    message = obj.jsonrpc.getLastToast(cache_timeout * 1000)
  File "G:\Devlopment\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 415, in __call__
    params, http_timeout)
  File "G:\Devlopment\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 422, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "G:\Devlopment\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 465, in jsonrpc_call
    data=data)
  File "G:\Devlopment\Python\Python37\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "G:\Devlopment\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 232, in request
    "atx-agent is not running. Fix it with following steps.\n1. Plugin device into computer.\n2. Run command \"python -m uiautomator2 init\""
OSError: atx-agent is not running. Fix it with following steps.
1. Plugin device into computer.
2. Run command "python -m uiautomator2 init"


*单独执行：adb shell /data/local/tmp/atx-agent server -d*
2019/08/01 18:04:52 [FATAL][github.com/openatx/atx-agent] main.go:385: Unale to run: open /sdcard/atx-agent.log: permission denied


有什么办法能解决吗？

**Comment by codeskyblue** [comment]
也就是说这个 /sdcard/下不能写文件喽？

**Comment by SLanXing** [comment]
> 也就是说这个 /sdcard/下不能写文件喽？

并不是，另一个人对同一个设备就可以。
我也成功过几次，，但大部分都失败了，也有中途断开的情况
