### ISSUE TITLE
测试过程中，多次出现returned non-zero exit status 1，导致测试终止，无法完整的跑完一轮测试

### ISSUE THREAD

**Issue by qing0404** [openatx/uiautomator2#401]
报错信息：
[2019-08-06 19:36:46] wait uiautomator is ready ...
[2019-08-06 19:36:47] wait uiautomator is ready ...
[2019-08-06 19:36:48] wait uiautomator is ready ...
[2019-08-06 19:36:49] wait uiautomator is ready ...
[2019-08-06 19:36:50] wait uiautomator is ready ...
[2019-08-06 19:36:51] wait uiautomator is ready ...
[2019-08-06 19:36:52] wait uiautomator is ready ...
uiautomator back to normal

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "d:\work\python37\lib\site-packages\uiautomator2\adbutils.py", line 55, in execute
INTERNALERROR>     cmdline, stderr=subprocess.STDOUT, shell=True).decode('utf-8')
INTERNALERROR>   File "d:\work\python37\lib\subprocess.py", line 376, in check_output
INTERNALERROR>     **kwargs).stdout
INTERNALERROR>   File "d:\work\python37\lib\subprocess.py", line 468, in run
INTERNALERROR>     output=stdout, stderr=stderr)
INTERNALERROR> subprocess.CalledProcessError: Command 'D:\work\Android\android-sdk-windows\platform-tools\adb.EXE -s 220b3c88 forward --list' returned non-zero exit status 1.

**Comment by codeskyblue** [comment]
这个问题，跟adbutils库有点关系，目前已经修复了。你更新uiautomator2到1.0.3再试试
