### ISSUE TITLE
uiautomator2 init fail due to lost minicap.so binary 

### ISSUE THREAD

**Issue by KimShaotester** [openatx/uiautomator2#402]
U:\>pip show uiautomator2
Name: uiautomator2
Version: 0.3.3

1. Use "python -m uiautomator2 init" to setup enviroment.
2. Find that minicap.so lost in android-29 folder as below information.

[D 190807 11:04:05 __main__:28] use cache directory: C:\Users\c_cjin\.uiautomator2
Namespace(serial=None, server=None, subparser='init') init
[I 190807 11:04:05 __main__:88] >>> Initial device AdbDevice(serial=294907ea)
[I 190807 11:04:06 __main__:172] Install minicap, minitouch
[Kminitouch |################################| 33.9K / 33.9K
[?25h[D 190807 11:04:09 __main__:157] Push https://github.com/openatx/stf-binaries/raw/master/node_modules/minitouch-prebuilt/prebuilt/arm64-v8a/bin/minitouch -> /data/local/tmp/minitouch:0755
Traceback (most recent call last):
  File "C:\Users\c_cjin\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\c_cjin\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\c_cjin\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 367, in <module>
    main()
  File "C:\Users\c_cjin\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 357, in main
    actions[args.subparser](args)
  File "C:\Users\c_cjin\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 302, in cmd_init
    init.install(args.server)
  File "C:\Users\c_cjin\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 179, in install
    self.push_url(url)
  File "C:\Users\c_cjin\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 149, in push_url
    path = cache_download(url, os.path.basename(url))
  File "C:\Users\c_cjin\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 70, in cache_download
    raise Exception(url, "status code", r.status_code)
Exception: ('https://github.com/openatx/stf-binaries/raw/master/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-29/minicap.so', 'status code', 404)

**Comment by codeskyblue** [comment]
fixed in 1.0.3
