### ISSUE TITLE
手机连接uiautomator2报错returned non-zero exit status 4294967179.

### ISSUE THREAD

**Issue by veast** [openatx/uiautomator2#424]
- 手机型号 
华为Y5 
- uiautomator2的版本号(`pip show uiautomator2`)
![image](https://user-images.githubusercontent.com/9658131/63687019-fde55d80-c835-11e9-9562-a49f07997661.png)
- 相关日志
<img width="866" alt="1" src="https://user-images.githubusercontent.com/9658131/63687217-8a901b80-c836-11e9-973c-92b3075ff1d9.png">

手机连接uiautomator2的时候报错，
Traceback (most recent call last):
  File "D:\scp\commons\python\bin\uiautomator2\adbutils.py", line 55, in execute
    cmdline, stderr=subprocess.STDOUT, shell=True).decode('utf-8')
  File "subprocess.py", line 389, in check_output
  File "subprocess.py", line 481, in run
subprocess.CalledProcessError: Command 'D:\scp\application\mobile-phone-tools\bin\platform-tools\adb.EXE -s VUY9K19226905968 shell PATH=$PATH:/data/local/tmp:/data/data/com.android/shell atx-agent server -d' returned non-zero exit status 4294967179.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\scp\commons\python\bin\uiautomator2\__init__.py", line 208, in connect
    return connect_usb(addr)
  File "D:\scp\commons\python\bin\uiautomator2\__init__.py", line 249, in connect_usb
    "atx-agent", "server", "-d")
  File "D:\scp\commons\python\bin\uiautomator2\adbutils.py", line 60, in execute
    'utf-8', errors='ignore'))
OSError: [Errno subprocess] D:\scp\application\mobile-phone-tools\bin\platform-tools\adb.EXE -s VUY9K19226905968 shell PATH=$PATH:/data/local/tmp:/data/data/com.android/shell atx-agent server -d: 'Segmentation fault \r\n'

**Comment by codeskyblue** [comment]
u2版本？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by veast** [comment]
0.3.3

**Comment by veast** [comment]
问题解决，发现atx-agent一直启动失败，尝试替换了一个atx-agent包，atx-agent在手机正常启动了
