### ISSUE TITLE
提示uiautomator2\__init__.py"内有SyntaxError: invalid syntax错误

### ISSUE THREAD

**Issue by scisMaster** [openatx/uiautomator2#428]
Traceback (most recent call last):
  File "d:/PythonWork/a.py", line 3, in <module>
    import uiautomator2 as u2
  File "D:\ProgramData\Anaconda2\lib\site-packages\uiautomator2\__init__.py", line 546
    def running(self) -> bool:
                      ^
SyntaxError: invalid syntax

用的是 VS code 编译器

**Comment by codeskyblue** [comment]
依赖Python3

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
