### ISSUE TITLE
小米8无法启动atx,原因是权限问题FOREGROUND_SERVICE

### ISSUE THREAD

**Issue by Enhinck** [openatx/uiautomator2#436]
- 小米8
- uiautomator2的版本号1.0.1
- 安卓9版本
- `java.lang.RuntimeException: Unable to create service com.github.uiautomator.Service: java.lang.SecurityException: Permission Denial: startForeground from pid=15166, uid=10290 requires android.permission.FOREGROUND_SERVICE
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3578)
	at android.app.ActivityThread.access$1400(ActivityThread.java:201)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6820)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=15166, uid=10290 requires android.permission.FOREGROUND_SERVICE
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5112)
	at android.app.Service.startForeground(Service.java:695)
	at com.github.uiautomator.Service.onCreate(Service.java:129)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3566)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:9650)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1232)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:907)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:21180)
	at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:10605)`

- 可以参考这个错误的解决方案 https://stackoverflow.com/questions/52382710/permission-denial-startforeground-requires-android-permission-foreground-servic

**Comment by codeskyblue** [comment]
印象中加过了，你把uiautomator2升级到最新版本，在重新init试试 最新的是1.2.4

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Enhinck** [comment]
> 印象中加过了，你把uiautomator2升级到最新版本，在重新init试试 最新的是1.2.4
> 
> Sent with [GitHawk](http://githawk.com)

嗯解决了，之前版本也是正常的，不知道升级了哪个版本异常了，感谢！
