### ISSUE TITLE
[版本1.2.4][d.xpath] requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:60354/dump/hierarchy

### ISSUE THREAD

**Issue by veast** [openatx/uiautomator2#437]
>>> d.xpath("//android.widget.Button[@text='OK']").exists
WARNING:root:request error: 404 page not found

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Env\Python\lib\site-packages\uiautomator2\xpath.py", line 320, in exists
    return len(self.all()) > 0
  File "D:\Env\Python\lib\site-packages\uiautomator2\xpath.py", line 307, in all
    xml_content = source or self._source or self._parent.dump_hierarchy()
  File "D:\Env\Python\lib\site-packages\uiautomator2\xpath.py", line 112, in dump_hierarchy
    self._last_source = self._d.dump_hierarchy()
  File "<D:\Env\Python\lib\site-packages\decorator.py:decorator-gen-8>", line 2, in dump_hierarchy
  File "D:\Env\Python\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "D:\Env\Python\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "D:\Env\Python\lib\site-packages\uiautomator2\session.py", line 507, in dump_hierarchy
    res.raise_for_status()
  File "D:\Env\Python\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:60354/dump/hierarchy

更新了1.2.4，手机也同步更新了android-uiautomator-server 2.0.2，atx-agent_0.6.2_linux_armv7，之前正常执行的命令抛出了异常。

荣耀8c，android 8.1

**Comment by codeskyblue** [comment]
看样子并没有升级的样子
