### ISSUE TITLE
项目中添加uiautomator2，生成的exe文件无法执行

### ISSUE THREAD

**Issue by GuangJieWang** [openatx/uiautomator2#442]
**python项目中添加uiautomator2，生成的exe文件启动时报错**

“Failed to execute script Operation”

**Comment by GuangJieWang** [comment]
错误信息为：
Traceback (most recent call last):
  File "Operation.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "d:\project_workspace\pythonworkspace\operationtool\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\uiautomator2\__init__.py", line 52, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "d:\project_workspace\pythonworkspace\operationtool\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\uiautomator2\init.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "d:\project_workspace\pythonworkspace\operationtool\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\uiautomator2\version.py", line 6, in <module>
  File "lib\site-packages\setuptools-39.0.1-py3.6.egg\pkg_resources\__init__.py", line 472, in get_distribution
  File "lib\site-packages\setuptools-39.0.1-py3.6.egg\pkg_resources\__init__.py", line 344, in get_provider
  File "lib\site-packages\setuptools-39.0.1-py3.6.egg\pkg_resources\__init__.py", line 892, in require
  File "lib\site-packages\setuptools-39.0.1-py3.6.egg\pkg_resources\__init__.py", line 778, in resolve
pkg_resources.DistributionNotFound: The 'uiautomator2' distribution was not found and is required by the application
[1464] Failed to execute script Operation

**Comment by mingyuan-xia** [comment]
打包脚本的事情，很清楚了
```
The 'uiautomator2' distribution was not found and is required by the application
```
项目没有打算支持这种用法，自己琢磨
