### ISSUE TITLE
atx-agent is running but timed out 

### ISSUE THREAD

**Issue by jihun-im** [openatx/uiautomator2#444]
*提Bug需要注意的事项*
I cannot run openatx with this device and this PC.
Both device and PC is working perfectly with other pair of PC and device.
I think there is something wrong with apks installed at runtime

Problem python code:
```
    try:
        d = u2.connect(device_id)
        log("d.healthcheck(): " + str(d.healthcheck()))
        log("d.device_info: " + str(d.device_info))
        log("d.info.get_result_info(): " + str(d.info))

    except RuntimeWarning as runtimeWarning:
        log("Runtime warning occurred from u2.connect() : " + str(runtimeWarning))
        exit(-1)
```

- 手机型号
`SM_G950N`
- uiautomator2的版本号(`pip show uiautomator2`)
```
13:23:26 + pip show uiautomator2
13:23:26 ---
13:23:26 Name: uiautomator2
13:23:26 Version: 0.1.7
```
- 手机截图
No screenshot
- 相关日志
```
13:23:26 show uiautomator2 version
13:23:26 + pip show uiautomator2
13:23:26 ---
13:23:26 Name: uiautomator2
13:23:26 Version: 0.1.7
13:23:26 Location: /home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages
13:23:26 Requires: requests, six, humanize, fire, docopt, progress, retry, whichcraft, logzero
13:23:26 + python3 smart_monkey_android.py 10.70.48.163:5554 jp.naver.line.android 100 135 600 False
13:23:27 application's pkg version is 9.17.0
13:23:27 2019-09-20 13:23:27,180 - __main__.py:343 - INFO - Device(10.70.48.163:5554) initialing ...
13:23:28 2019-09-20 13:23:28,084 - __main__.py:133 - INFO - install minicap
13:23:30 2019-09-20 13:23:30,052 - __main__.py:140 - INFO - install minitouch
13:23:30 2019-09-20 13:23:30,704 - __main__.py:168 - INFO - apk(1.1.7) already installed, skip
13:23:30 2019-09-20 13:23:30,705 - __main__.py:350 - INFO - atx-agent is already running, force stop
13:23:31 2019-09-20 13:23:31,705 - __main__.py:254 - INFO - launch atx-agent daemon
13:23:33 2019-09-20 13:23:33,938 - __main__.py:273 - INFO - atx-agent version: 0.4.9
13:23:34 2019-09-20 13:23:34,675 - __main__.py:279 - INFO - success
13:24:37 Traceback (most recent call last):
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/connectionpool.py", line 384, in _make_request
13:24:37 six.raise_from(e, None)
13:24:37 File "<string>", line 2, in raise_from
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/connectionpool.py", line 380, in _make_request
13:24:37 httplib_response = conn.getresponse()
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/http/client.py", line 1172, in getresponse
13:24:37 response.begin()
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/http/client.py", line 351, in begin
13:24:37 version, status, reason = self._read_status()
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/http/client.py", line 313, in _read_status
13:24:37 line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/socket.py", line 371, in readinto
13:24:37 return self._sock.recv_into(b)
13:24:37 socket.timeout: timed out
13:24:37

13:24:37 During handling of the above exception, another exception occurred:
13:24:37

13:24:37 Traceback (most recent call last):
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/requests/adapters.py", line 449, in send
13:24:37 timeout=timeout
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/connectionpool.py", line 638, in urlopen
13:24:37 _stacktrace=sys.exc_info()[2])
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/util/retry.py", line 367, in increment
13:24:37 raise six.reraise(type(error), error, _stacktrace)
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/packages/six.py", line 686, in reraise
13:24:37 raise value
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/connectionpool.py", line 600, in urlopen
13:24:37 chunked=chunked)
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/connectionpool.py", line 386, in _make_request
13:24:37 self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
13:24:37 raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
13:24:37 urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='10.70.48.163', port=5554): Read timed out. (read timeout=60)
13:24:37

13:24:37 During handling of the above exception, another exception occurred:
13:24:37

13:24:37 Traceback (most recent call last):
13:24:37 File "smart_monkey_android.py", line 1016, in <module>
13:24:37 log("d.healthcheck(): " + str(d.healthcheck()))
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/uiautomator2/__init__.py", line 664, in healthcheck
13:24:37 if not sh.is_screen_on():
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/uiautomator2/__init__.py", line 2367, in is_screen_on
13:24:37 output, _ = self.shell("dumpsys power")
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/uiautomator2/__init__.py", line 784, in shell
13:24:37 'timeout': str(timeout)
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/requests/sessions.py", line 581, in post
13:24:37 return self.request('POST', url, data=data, json=json, **kwargs)
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/uiautomator2/__init__.py", line 280, in request
13:24:37 method, url, **kwargs)
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/requests/sessions.py", line 533, in request
13:24:37 resp = self.send(prep, **send_kwargs)
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/requests/sessions.py", line 646, in send
13:24:37 r = adapter.send(request, **kwargs)
13:24:37 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/requests/adapters.py", line 529, in send
13:24:37 raise ReadTimeout(e, request=request)
13:24:37 requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.70.48.163', port=5554): Read timed out. (read timeout=60)
13:24:38 Build step 'Execute shell' marked build as failure
```
- 最好能附上可能复现问题的代码。

**Comment by codeskyblue** [comment]
感觉好像 `dumpsys power`这个命令卡住了

**Comment by jihunim** [comment]
Hello @codeskyblue, Thank you for the comment.
Here is my 'adb shell dumpsys power' result

```
 set@set-HP-EliteDesk-800-G1-TWR:~/jenkins/workspace$ adb -s 10.70.48.163:5553 shell dumpsys power
POWER MANAGER (dumpsys power)

Power Manager State:
  mDirty=0x0
  mWakefulness=Awake
  mWakefulnessChanging=false
  mIsPowered=false
  mPlugType=0
  mBatteryLevel=81
  mBatteryLevelCriticalLow=false
  mLastBatteryLevelCriticalLowTime=0
  mBatteryLevelWhenDreamStarted=81
  mDockState=0
  mStayOn=false
  mProximityPositive=false
  mBootCompleted=true
  mSystemReady=true
  mHalAutoSuspendModeEnabled=false
  mHalInteractiveModeEnabled=true
  mWakeLockSummary=0x1
  mUserActivitySummary=0x1
  mRequestWaitForNegativeProximity=false
  mSandmanScheduled=false
  mSandmanSummoned=false
  mLowPowerModeEnabled=false
  mUltraPowerSavingModeEnabled: false
  mEmergencyModeEnabled: false
  mAutoBrightnessScaleFactorFromSettings: 90
  mBatteryLevelLow=false
  mLightDeviceIdleMode=false
  mDeviceIdleMode=false
  mDeviceIdleWhitelist=[1000, 1001, 1201, 5002, 10001, 10005, 10024, 10032, 10037, 10039, 10048, 10051, 10059, 10060, 10063, 10077, 10080, 10082, 10087, 10095, 10099, 10127, 10135, 10155, 10158, 10169, 10182, 10187, 10188, 10190]
  mDeviceIdleTempWhitelist=[]
  mLastWakeTime=4867488 (206776 ms ago)
  mLastSleepTime=4808632 (265632 ms ago)
  mLastUserActivityTime=4942728 (131536 ms ago)
  mLastUserActivityTimeNoChangeLights=3295568 (1778696 ms ago)
  mLastInteractivePowerHintTime=4942728 (131536 ms ago)
  mLastScreenBrightnessBoostTime=0 (5074264 ms ago)
  mScreenBrightnessBoostInProgress=false
  mDisplayReady=true
  mHoldingWakeLockSuspendBlocker=true
  mHoldingDisplaySuspendBlocker=true

Settings and Configuration:
  mDecoupleHalAutoSuspendModeFromDisplayConfig=true
  mDecoupleHalInteractiveModeFromDisplayConfig=false
  mWakeUpWhenPluggedOrUnpluggedConfig=true
  mWakeUpWhenPluggedOrUnpluggedInTheaterModeConfig=false
  mTheaterModeEnabled=false
  mSuspendWhenScreenOffDueToProximityConfig=true
  mDreamsSupportedConfig=true
  mDreamsEnabledByDefaultConfig=false
  mDreamsActivatedOnSleepByDefaultConfig=false
  mDreamsActivatedOnDockByDefaultConfig=true
  mDreamsEnabledOnBatteryConfig=false
  mDreamsBatteryLevelMinimumWhenPoweredConfig=-1
  mDreamsBatteryLevelMinimumWhenNotPoweredConfig=15
  mDreamsBatteryLevelDrainCutoffConfig=5
  mDreamsEnabledSetting=false
  mDreamsActivateOnSleepSetting=true
  mDreamsActivateOnDockSetting=false
  mDozeAfterScreenOffConfig=true
  mLowPowerModeSetting=false
  mAutoLowPowerModeConfigured=false
  mAutoLowPowerModeSnoozing=false
  mLowBatteryTriggerLevel=0
  mMinimumScreenOffTimeoutConfig=3000
  mMaximumScreenDimDurationConfig=7000
  mMaximumScreenDimRatioConfig=0.20000005
  mScreenOffTimeoutSetting=600000
  mSleepTimeoutSetting=-1
  mMaximumScreenOffTimeoutFromDeviceAdmin=2147483647 (enforced=false)
  mStayOnWhilePluggedInSetting=0
  mScreenBrightnessSetting=0
  mScreenAutoBrightnessAdjustmentSetting=-1.0
  mScreenBrightnessModeSetting=1
  mScreenBrightnessOverrideFromWindowManager=-1
  mUserActivityTimeoutOverrideFromWindowManager=-1
  mUserInactiveOverrideFromWindowManager=false
  mTemporaryScreenBrightnessSettingOverride=-1
  mTemporaryScreenAutoBrightnessAdjustmentSettingOverride=NaN
  mDozeScreenStateOverrideFromDreamManager=4
  mDozeScreenBrightnessOverrideFromDreamManager=97
  mScreenBrightnessSettingMinimum=0
  mScreenBrightnessSettingMaximum=255
  mScreenBrightnessSettingDefault=128
  mDoubleTapWakeEnabled=false
  mLastUserActivitySummary: 1
  mIsCocktailBarCover: false
  mIsSupportedSensorHub: true
  mIsInPocketOrBagAvailable: false
  mLastWakeUpReason: 0
  mWakeUpPreventionForNotificationSetting: false
  mWakeUpPreventionPackagesForNotificationSetting: null
  mOutdoorModeSetting: false
  mIsSupportedLightSensor: true
  mTemporaryMarkerScreenBrightnessSettingOverride=-1
  mAutoBrightnessLowerLimit=-1
  mAutoBrightnessUpperLimit=-1
  mLastAutoBrightnessLimitTime=0
  mLastScreenBrightnessSettingChangedTime=0

  SecProductFeature_FRAMEWORK.SEC_PRODUCT_FEATURE_FRAMEWORK_ENABLE_SMART_STAY: true
  SecProductFeature_CAMERA.SEC_PRODUCT_FEATURE_CAMERA_DELAY_TIME_FOR_SMART_STAY: 2950
  USE_AUTO_BRIGHTNESS_DETAIL: false (mSCafeName:  mIsMocha: false upgradeLollipop: false SEC_FLOATING_FEATURE_SETTINGS_SUPPORT_AUTOMATIC_BRIGHTNESS_DETAIL: true)
  SEC_FEATURE_USE_GED_DOZE: true
  SEC_FEATURE_SEAMLESS_AOD: true
  mFeatureNotifyScreenOffTimeout: false

Sleep timeout: -1 ms
Screen off timeout: 600000 ms
Screen dim duration: 7000 ms
Screen dim duration override: -1 ms

Smart Stay:
  USE_SMART_STAY: true
  USE_PRE_SMART_STAY: false
  mSmartStayEnabledSetting: false
  SmartStayDelay: 2950
  mNextTimeoutForSmartStay: -1
  mPendingMessageSmartStay: false
  mPendingMessagePreSmartStay: false
  mFaceDetected: false
  mIsBadCurrentConsumptionDevice: true

UID states:
  UID 1000: 0
  UID 1001: 0
  UID 1002: 6
  UID 1027: 0
  UID 1037: 16
  UID 5003: 16
  UID 5004: 16
  UID 5006: 6
  UID 5009: 16
  UID 5012: 16
  UID 5013: 6
  UID 5018: 16
  UID u0a1: 16
  UID u0a3: 16
  UID u0a5: 0
  UID u0a6: 16
  UID u0a11: 0
  UID u0a13: 6
  UID u0a19: 10
  UID u0a20: 3
  UID u0a23: 16
  UID u0a24: 2
  UID u0a25: 3
  UID u0a28: 16
  UID u0a31: 16
  UID u0a36: 16
  UID u0a37: 16
  UID u0a39: 16
  UID u0a40: 16
  UID u0a43: 16
  UID u0a48: 6
  UID u0a53: 16
  UID u0a60: 10
  UID u0a67: 16
  UID u0a77: 10
  UID u0a83: 16
  UID u0a84: 2
  UID u0a97: 2
  UID u0a109: 16
  UID u0a127: 16
  UID u0a159: 13
  UID u0a160: 16
  UID u0a164: 16
  UID u0a167: 0
  UID u0a174: 7
  UID u0a187: 10
  UID u0a221: 4
  UID u0i0: 13

InputDeviceLightState:
  mTouchKeyOffTimeoutSetting: 1500
  mIsSipVisible: false
  mTouchKeyForceDisable: false
  mTouchKeyForceDisableOverrideFromSystemPowerSaveMode: false
  mInputDeviceEnabled: true
  mIsFolderType: false

UID states:
  UID 1000: 0
  UID 1001: 0
  UID 1002: 6
  UID 1027: 0
  UID 1037: 16
  UID 5003: 16
  UID 5004: 16
  UID 5006: 6
  UID 5009: 16
  UID 5012: 16
  UID 5013: 6
  UID 5018: 16
  UID u0a1: 16
  UID u0a3: 16
  UID u0a5: 0
  UID u0a6: 16
  UID u0a11: 0
  UID u0a13: 6
  UID u0a19: 10
  UID u0a20: 3
  UID u0a23: 16
  UID u0a24: 2
  UID u0a25: 3
  UID u0a28: 16
  UID u0a31: 16
  UID u0a36: 16
  UID u0a37: 16
  UID u0a39: 16
  UID u0a40: 16
  UID u0a43: 16
  UID u0a48: 6
  UID u0a53: 16
  UID u0a60: 10
  UID u0a67: 16
  UID u0a77: 10
  UID u0a83: 16
  UID u0a84: 2
  UID u0a97: 2
  UID u0a109: 16
  UID u0a127: 16
  UID u0a159: 13
  UID u0a160: 16
  UID u0a164: 16
  UID u0a167: 0
  UID u0a174: 7
  UID u0a187: 10
  UID u0a221: 4
  UID u0i0: 13

Clear Cover:
  mIsCoverClosed: false
  mlastUpdateCoverStateReason: isCoverClosedBySysfs called on closed = false
  mlastUpdateCoverStateTime: = -1 (5074267 ms ago)
  mFeatureCoverSysfs: true
  mIsCocktailBarCover: false
  mCoverType: 2 at -1 (5074267 ms ago)
  mlastUpdateCoverTypeReason: 

ALPM Mode:
  mIsAlpmMode: false
  mPendingForceUnblankDisplayState: -1

SEC_PRODUCT_FEATURE_COMMON_SUPPORT_COCKTAIL_FW: true

FTA mode: false
SEC_USE_FACTORY_BINARY: false

SEC_FEATURE_MARKER_TRACKER: true

SEC_FEATURE_USE_HBM_AT_MANUAL_MAX: true

UID states:
  UID 1000: 0
  UID 1001: 0
  UID 1002: 6
  UID 1027: 0
  UID 1037: 16
  UID 5003: 16
  UID 5004: 16
  UID 5006: 6
  UID 5009: 16
  UID 5012: 16
  UID 5013: 6
  UID 5018: 16
  UID u0a1: 16
  UID u0a3: 16
  UID u0a5: 0
  UID u0a6: 16
  UID u0a11: 0
  UID u0a13: 6
  UID u0a19: 10
  UID u0a20: 3
  UID u0a23: 16
  UID u0a24: 2
  UID u0a25: 3
  UID u0a28: 16
  UID u0a31: 16
  UID u0a36: 16
  UID u0a37: 16
  UID u0a39: 16
  UID u0a40: 16
  UID u0a43: 16
  UID u0a48: 6
  UID u0a53: 16
  UID u0a60: 10
  UID u0a67: 16
  UID u0a77: 10
  UID u0a83: 16
  UID u0a84: 2
  UID u0a97: 2
  UID u0a109: 16
  UID u0a127: 16
  UID u0a159: 13
  UID u0a160: 16
  UID u0a164: 16
  UID u0a167: 0
  UID u0a174: 7
  UID u0a187: 10
  UID u0a221: 4
  UID u0i0: 13

Wake Locks: size=1
  PARTIAL_WAKE_LOCK              'AudioIn' (uid=1041, pid=0, ws=WorkSource{10097}) (uid=1041, pid=0, ws=WorkSource{10097}, pkg=audioserver, elapsedTime=131355)

Suspend Blockers: size=5
  PowerManagerService.WakeLocks: ref count=1
  PowerManagerService.Display: ref count=1
  PowerManagerService.Dozing: ref count=0
  PowerManagerService.Broadcasts: ref count=0
  PowerManagerService.WirelessChargerDetector: ref count=0

Display Power: state=ON

Wireless Charger Detector State:
  mGravitySensor={Sensor name="Gravity Sensor", vendor="Samsung Electronics", version=3, type=9, maxRange=19.6133, resolution=5.9604645E-8, power=6.0, minDelay=10000}
  mPoweredWirelessly=false
  mAtRest=false
  mRestX=0.0, mRestY=0.0, mRestZ=0.0
  mDetectionInProgress=false
  mDetectionStartTime=0 (never)
  mMustUpdateRestPosition=false
  mTotalSamples=0
  mMovingSamples=0
  mFirstSampleX=0.0, mFirstSampleY=0.0, mFirstSampleZ=0.0
  mLastSampleX=0.0, mLastSampleY=0.0, mLastSampleZ=0.0


 ====================== beginning of PMS  log ======================
  Day       Time    Tid Debug     TAG            INFO
 ===================================================================
 ======================= end of PMS log ========================
 PMSLog Done !!! 
```

**Comment by codeskyblue** [comment]
Interesting, what kind of your phone

**Comment by jihunim** [comment]
It is GalaxyS8. I will factory reset and retry this

**Comment by jihunim** [comment]
I factory reset and run uiautomator2 python wrapper, but it fails again.
```
15:17:44 2019-09-24 15:17:44,891 - __main__.py:343 - INFO - Device(10.70.48.163:5551) initialing ...
15:17:45 2019-09-24 15:17:45,538 - __main__.py:133 - INFO - install minicap
15:17:47 2019-09-24 15:17:47,325 - __main__.py:140 - INFO - install minitouch
15:17:47 2019-09-24 15:17:47,950 - __main__.py:155 - INFO - app-uiautomator.apk(1.1.7) downloading ...
15:17:47 2019-09-24 15:17:47,951 - __main__.py:158 - INFO - app-uiautomator-test.apk downloading ...
15:17:56 2019-09-24 15:17:56,333 - __main__.py:350 - INFO - atx-agent is already running, force stop
15:17:56 2019-09-24 15:17:56,832 - __main__.py:227 - INFO - atx-agent(0.4.9) is installing, please be patient
15:18:12 2019-09-24 15:18:12,731 - __main__.py:254 - INFO - launch atx-agent daemon
15:18:13 2019-09-24 15:18:13,746 - __main__.py:273 - INFO - atx-agent version: 0.4.9
15:18:14 2019-09-24 15:18:14,270 - __main__.py:279 - INFO - success
15:18:17 Traceback (most recent call last):
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/connectionpool.py", line 600, in urlopen
15:18:17 chunked=chunked)
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/connectionpool.py", line 384, in _make_request
15:18:17 six.raise_from(e, None)
15:18:17 File "<string>", line 2, in raise_from
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/connectionpool.py", line 380, in _make_request
15:18:17 httplib_response = conn.getresponse()
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/http/client.py", line 1172, in getresponse
15:18:17 response.begin()
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/http/client.py", line 351, in begin
15:18:17 version, status, reason = self._read_status()
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/http/client.py", line 321, in _read_status
15:18:17 raise BadStatusLine(line)
15:18:17 http.client.BadStatusLine: ''
15:18:17

15:18:17 During handling of the above exception, another exception occurred:
15:18:17

15:18:17 Traceback (most recent call last):
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/requests/adapters.py", line 449, in send
15:18:17 timeout=timeout
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/connectionpool.py", line 638, in urlopen
15:18:17 _stacktrace=sys.exc_info()[2])
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/util/retry.py", line 367, in increment
15:18:17 raise six.reraise(type(error), error, _stacktrace)
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/packages/six.py", line 685, in reraise
15:18:17 raise value.with_traceback(tb)
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/connectionpool.py", line 600, in urlopen
15:18:17 chunked=chunked)
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/connectionpool.py", line 384, in _make_request
15:18:17 six.raise_from(e, None)
15:18:17 File "<string>", line 2, in raise_from
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/urllib3/connectionpool.py", line 380, in _make_request
15:18:17 httplib_response = conn.getresponse()
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/http/client.py", line 1172, in getresponse
15:18:17 response.begin()
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/http/client.py", line 351, in begin
15:18:17 version, status, reason = self._read_status()
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/http/client.py", line 321, in _read_status
15:18:17 raise BadStatusLine(line)
15:18:17 urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))
15:18:17

15:18:17 During handling of the above exception, another exception occurred:
15:18:17

15:18:17 Traceback (most recent call last):
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/uiautomator2/__init__.py", line 280, in request
15:18:17 method, url, **kwargs)
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/requests/sessions.py", line 533, in request
15:18:17 resp = self.send(prep, **send_kwargs)
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/requests/sessions.py", line 646, in send
15:18:17 r = adapter.send(request, **kwargs)
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/requests/adapters.py", line 498, in send
15:18:17 raise ConnectionError(err, request=request)
15:18:17 requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
15:18:17

15:18:17 During handling of the above exception, another exception occurred:
15:18:17

15:18:17 Traceback (most recent call last):
15:18:17 File "smart_monkey_android.py", line 1015, in <module>
15:18:17 log("d.healthcheck(): " + str(d.healthcheck()))
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/uiautomator2/__init__.py", line 664, in healthcheck
15:18:17 if not sh.is_screen_on():
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/uiautomator2/__init__.py", line 2367, in is_screen_on
15:18:17 output, _ = self.shell("dumpsys power")
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/uiautomator2/__init__.py", line 784, in shell
15:18:17 'timeout': str(timeout)
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/requests/sessions.py", line 581, in post
15:18:17 return self.request('POST', url, data=data, json=json, **kwargs)
15:18:17 File "/home/set/.pyenv/versions/3.4.1/lib/python3.4/site-packages/uiautomator2/__init__.py", line 283, in request
15:18:17 "atx-agent is not running. Fix it with following steps.\n1. Plugin device into computer.\n2. Run command \"python -m uiautomator2 init\""
15:18:17 OSError: atx-agent is not running. Fix it with following steps.
15:18:17 1. Plugin device into computer.
15:18:17 2. Run command "python -m uiautomator2 init"
15:18:17 Build step 'Execute shell' marked build as failure
15:18:17 Archiving artifacts
15:18:17 Started calculate disk usage of build
15:18:17 Finished Calculation of disk usage of build in 0 seconds
15:18:17 Started calculate disk usage of workspace
15:18:17 Finished Calculation of disk usage of workspace in 0 seconds
15:18:30 Finished: FAILURE
```

**Comment by jihunim** [comment]
I connected the device with 'ADB over WiFi'

**Comment by jihunim** [comment]
If I connect the device with ADB over usb cable, it works.
I think there is something with `ADB over Wifi` and `atx-agent`
