### ISSUE TITLE
python3.8: python -m weditor失效，出现

### ISSUE THREAD

**Issue by ThickBull** [openatx/uiautomator2#462]
异常场景: weditor version = 0.3.1  uiautomator2 version = 1.3.6  python version = 3.8.0
cmd中的异常log
C:\Users\MI>python -m weditor
listening on http://10.234.196.211:17310
Traceback (most recent call last):
  File "F:\python\Python3.8.0\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\python\Python3.8.0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\python\Python3.8.0\lib\site-packages\weditor\__main__.py", line 176, in <module>
    main()
  File "F:\python\Python3.8.0\lib\site-packages\weditor\__main__.py", line 172, in main
    run_web(args.debug, args.port, open_browser)
  File "F:\python\Python3.8.0\lib\site-packages\weditor\__main__.py", line 114, in run_web
    application.listen(port)
  File "F:\python\Python3.8.0\lib\site-packages\tornado\web.py", line 2112, in listen
    server.listen(port, address)
  File "F:\python\Python3.8.0\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "F:\python\Python3.8.0\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "F:\python\Python3.8.0\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "F:\python\Python3.8.0\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "F:\python\Python3.8.0\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

**Comment by DENGXIANSHENG** [comment]
3.8有问题的 换成py3.6就好了

**Comment by codeskyblue** [comment]
估计tornado没兼容python 3.8

**Comment by Sanmejie** [comment]
俺也出现了  Python 3.9.0
`listening on http://192.168.31.127:17310
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\weditor\__main__.py", line 255, in <module>
    main()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\weditor\__main__.py", line 251, in main
    run_web(args.debug, args.port, open_browser, args.force_quit)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\weditor\__main__.py", line 181, in run_web
    application.listen(port)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError

C:\Users\Administrator>
C:\Users\Administrator>
C:\Users\Administrator>
C:\Users\Administrator>python -m weditor
listening on http://192.168.31.127:17310
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\weditor\__main__.py", line 255, in <module>
    main()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\weditor\__main__.py", line 251, in main
    run_web(args.debug, args.port, open_browser, args.force_quit)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\weditor\__main__.py", line 181, in run_web
    application.listen(port)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError`

**Comment by codeskyblue** [comment]
@Sanmejie weditor 0.6.3 你试试？

**Comment by Sanmejie** [comment]
@codeskyblue  升级后可以调起浏览器了，但还有500错误（我在尝试看看是不是环境问题导致的）。
操作步骤：
1.数据线连接安卓设备
2.adb tcpip 5555
3.python -m weditor
4.在浏览器页面上面输入 设备:5555  点击 Connect
在windows dos看到下面的信息:（已经验证  设备:5555是adb命令可以正常执行）
[E 201231 12:56:44 web:1789] Uncaught exception GET /api/v2/devices/android%3A192.168.1.16%3A5555/hierarchy (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/api/v2/devices/android%3A192.168.1.16%3A5555/hierarchy', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\weditor\web\handlers\page.py", line 94, in get
        self.write(d.dump_hierarchy2())
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\weditor\web\device.py", line 39, in dump_hierarchy2
        current = self._d.app_current()
      File "<decorator-gen-14>", line 2, in app_current
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\retry\api.py", line 73, in retry_decorator
        return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\retry\api.py", line 33, in __retry_internal
        return f()
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 1261, in app_current
        m = _focusedRE.search(self.shell(['dumpsys', 'window', 'windows'])[0])
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 390, in shell
        raise RuntimeError(
    RuntimeError: ('device agent responds with an error code 504', '[Fiddler] SendRequest() failed: System.Net.Sockets.SocketException 你的主机中的软件中止了一个已建立的连接。                                                                                                                                                                                                                                                                                                                                                                                                                                         ')
[E 201231 12:56:44 web:2239] 500 GET /api/v2/devices/android%3A192.168.1.16%3A5555/hierarchy (::1) 8145.94ms
[I 201231 12:56:47 page:204] Serial: android:192.168.1.16:5555
[E 201231 12:56:54 web:1789] Uncaught exception GET /api/v1/devices/android%3A192.168.1.16%3A5555/screenshot (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/api/v1/devices/android%3A192.168.1.16%3A5555/screenshot', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 862, in screenshot
        return Image.open(buff).convert("RGB")
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 2943, in open
        raise UnidentifiedImageError(
    PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000024C799FD310>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\weditor\web\handlers\page.py", line 208, in get
        d.screenshot().convert("RGB").save(buffer, format='JPEG')
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\weditor\web\device.py", line 33, in screenshot
        return self._d.screenshot()
      File "<decorator-gen-10>", line 2, in screenshot
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\retry\api.py", line 73, in retry_decorator
        return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\retry\api.py", line 33, in __retry_internal
        return f()
      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uiautomator2\__init__.py", line 867, in screenshot
        if d.settings['fallback_to_blank_screenshot']:
    NameError: name 'd' is not defined
[E 201231 12:56:54 web:2239] 500 GET /api/v1/devices/android%3A192.168.1.16%3A5555/screenshot (::1) 6799.97ms
![image](https://user-images.githubusercontent.com/40269911/103395252-4dddde00-4b68-11eb-8747-4805252f3fdd.png)
