### ISSUE TITLE
红米2A 上 uiautomator 有时无法启动

### ISSUE THREAD

**Issue by stevenjoy2013** [openatx/uiautomator2#469]
- 手机型号： 红米2A
- uiautomator2的版本号(`pip show uiautomator2`): 1.3.4
- 手机截图
- 相关日志

atx-agent.log

There was 1 failure:
1) testUIAutomatorStub(com.github.uiautomator.stub.Stub)
java.net.BindException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.IoBridge.bind(IoBridge.java:99)
        at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132)
        at java.net.ServerSocket.bind(ServerSocket.java:335)
        at java.net.ServerSocket.bind(ServerSocket.java:295)
        at fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:1761)
        at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.Posix.bind(Native Method)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:56)
        at libcore.io.IoBridge.bind(IoBridge.java:97)
        ... 5 more

FAILURES!!!
Tests run: 1,  Failures: 1

- 最好能附上可能复现问题的代码。

**Comment by stevenjoy2013** [comment]
重启手机后才好

**Comment by stevenjoy2013** [comment]
第一处出现这个错误的日志：

127.0.0.1 - - [31/Oct/2019:14:05:16 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 90
127.0.0.1 - - [31/Oct/2019:14:05:18 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 223
127.0.0.1 - - [31/Oct/2019:14:05:18 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:18 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 304
127.0.0.1 - - [31/Oct/2019:14:05:18 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:19 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 90
127.0.0.1 - - [31/Oct/2019:14:05:20 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:20 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:21 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 298
127.0.0.1 - - [31/Oct/2019:14:05:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 87
127.0.0.1 - - [31/Oct/2019:14:05:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 304
127.0.0.1 - - [31/Oct/2019:14:05:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:24 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:24 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 88
127.0.0.1 - - [31/Oct/2019:14:05:25 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:25 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 88
127.0.0.1 - - [31/Oct/2019:14:05:26 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 90
127.0.0.1 - - [31/Oct/2019:14:05:28 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:28 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 90
127.0.0.1 - - [31/Oct/2019:14:05:29 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:29 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 90
127.0.0.1 - - [31/Oct/2019:14:05:30 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:30 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 90
127.0.0.1 - - [31/Oct/2019:14:05:30 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 88
127.0.0.1 - - [31/Oct/2019:14:05:31 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 90
127.0.0.1 - - [31/Oct/2019:14:05:31 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:31 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 90
127.0.0.1 - - [31/Oct/2019:14:05:32 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:33 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 90
127.0.0.1 - - [31/Oct/2019:14:05:33 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:33 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 90
127.0.0.1 - - [31/Oct/2019:14:05:34 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:34 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:37 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:05:37 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 289
127.0.0.1 - - [31/Oct/2019:14:05:40 +0800] "POST /info/battery HTTP/1.1" 200 7
2019/10/31 14:08:37 [1;34m[Info] main.go:599 uiautomator has not activity for 3 minutes, closed
[0m2019/10/31 14:08:37 cmdctrl.go:27: DEBUG program finished
2019/10/31 14:08:37 [1;34m[Info] main.go:590 service uiautomator: stopservice com.github.uiautomator/.Service
[0m2019/10/31 14:10:40 httpserver.go:389: startservice com.github.uiautomator/.Service
127.0.0.1 - - [31/Oct/2019:14:10:41 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [31/Oct/2019:14:10:41 +0800] "POST /info/wifi HTTP/1.1" 404 19
2019/10/31 14:10:41 httpserver.go:418: rotation change received: 180
127.0.0.1 - - [31/Oct/2019:14:10:41 +0800] "POST /info/wifi HTTP/1.1" 404 19
2019/10/31 14:10:41 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 720x1280@800x800/180]
127.0.0.1 - - [31/Oct/2019:14:10:41 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [31/Oct/2019:14:10:41 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [31/Oct/2019:14:10:41 +0800] "POST /info/rotation HTTP/1.1" 200 16
127.0.0.1 - - [31/Oct/2019:14:15:21 +0800] "GET /version HTTP/1.1" 200 5
127.0.0.1 - - [31/Oct/2019:14:15:21 +0800] "GET /ping HTTP/1.1" 200 24
127.0.0.1 - - [31/Oct/2019:14:15:21 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 555
127.0.0.1 - - [31/Oct/2019:14:15:21 +0800] "GET /version HTTP/1.1" 200 5
127.0.0.1 - - [31/Oct/2019:14:15:21 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
2019/10/31 14:15:22 [1;34m[Info] main.go:539 - - - - - - - - - - - - - - -[0m
2019/10/31 14:15:22 [1;34m[Info] main.go:540 daemon started[0m
atx-agent version 0.7.2
Listen on http://192.168.1.2:7912
2019/10/31 14:15:22 [1;35m[Fatal] main.go:555 listen tcp :7912: bind: address already in use[0m
127.0.0.1 - - [31/Oct/2019:14:15:21 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 88
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 87
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 87
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:22 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:23 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 146
127.0.0.1 - - [31/Oct/2019:14:15:23 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:25 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [31/Oct/2019:14:15:25 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 580
127.0.0.1 - - [31/Oct/2019:14:15:28 +0800] "POST /shell HTTP/1.1" 200 47
2019/10/31 14:15:28 [1;34m[Info] main.go:584 service uiautomator: startservice com.github.uiautomator/.Service
[0m127.0.0.1 - - [31/Oct/2019:14:15:28 +0800] "POST /uiautomator HTTP/1.1" 200 20
2019/10/31 14:15:28 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
127.0.0.1 - - [31/Oct/2019:14:15:28 +0800] "GET /uiautomator HTTP/1.1" 200 16
2019/10/31 14:15:28 cmdctrl.go:27: DEBUG program pid: 2686
127.0.0.1 - - [31/Oct/2019:14:15:28 +0800] "GET /ping HTTP/1.1" 200 24
127.0.0.1 - - [31/Oct/2019:14:15:28 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 555
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.github.uiautomator.stub.Stub:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1
127.0.0.1 - - [31/Oct/2019:14:15:29 +0800] "GET /uiautomator HTTP/1.1" 200 16
127.0.0.1 - - [31/Oct/2019:14:15:29 +0800] "GET /ping HTTP/1.1" 200 24
127.0.0.1 - - [31/Oct/2019:14:15:29 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 555
127.0.0.1 - - [31/Oct/2019:14:15:31 +0800] "GET /uiautomator HTTP/1.1" 200 16
127.0.0.1 - - [31/Oct/2019:14:15:31 +0800] "GET /ping HTTP/1.1" 200 24
127.0.0.1 - - [31/Oct/2019:14:15:31 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 555
127.0.0.1 - - [31/Oct/2019:14:15:32 +0800] "GET /uiautomator HTTP/1.1" 200 16
127.0.0.1 - - [31/Oct/2019:14:15:32 +0800] "GET /ping HTTP/1.1" 200 24
127.0.0.1 - - [31/Oct/2019:14:15:32 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 555
127.0.0.1 - - [31/Oct/2019:14:15:33 +0800] "GET /uiautomator HTTP/1.1" 200 16
127.0.0.1 - - [31/Oct/2019:14:15:33 +0800] "GET /ping HTTP/1.1" 200 24
127.0.0.1 - - [31/Oct/2019:14:15:33 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 555
127.0.0.1 - - [31/Oct/2019:14:15:34 +0800] "GET /uiautomator HTTP/1.1" 200 16
127.0.0.1 - - [31/Oct/2019:14:15:34 +0800] "GET /ping HTTP/1.1" 200 24
127.0.0.1 - - [31/Oct/2019:14:15:34 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 555
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
Error in testUIAutomatorStub(com.github.uiautomator.stub.Stub):
java.net.BindException: bind failed: EADDRINUSE (Address already in use)
	at libcore.io.IoBridge.bind(IoBridge.java:99)
	at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132)
	at java.net.ServerSocket.bind(ServerSocket.java:335)
	at java.net.ServerSocket.bind(ServerSocket.java:295)
	at fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:1761)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
	at libcore.io.Posix.bind(Native Method)
	at libcore.io.ForwardingOs.bind(ForwardingOs.java:56)
	at libcore.io.IoBridge.bind(IoBridge.java:97)
	... 5 more

INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
INSTRUMENTATION_STATUS: stack=java.net.BindException: bind failed: EADDRINUSE (Address already in use)
	at libcore.io.IoBridge.bind(IoBridge.java:99)
	at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132)
	at java.net.ServerSocket.bind(ServerSocket.java:335)
	at java.net.ServerSocket.bind(ServerSocket.java:295)
	at fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:1761)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
	at libcore.io.Posix.bind(Native Method)
	at libcore.io.ForwardingOs.bind(ForwardingOs.java:56)
	at libcore.io.IoBridge.bind(IoBridge.java:97)
	... 5 more

**Comment by codeskyblue** [comment]
升级升级uiautomator2试试
