### ISSUE TITLE
long_click()出现错误

### ISSUE THREAD

**Issue by trimQiu** [openatx/uiautomator2#470]
* pip show uiautomator2 的结果：
Name: uiautomator2
Version: 2.0.0
Summary: Python Wrapper for Google Android UiAutomator2 test tool
Home-page: https://github.com/openatx/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: d:\python\lib\site-packages
Requires: six, requests, humanize, whichcraft, logzero, progress, retry, adbutils, Deprecated, Pillow, lxml
Required-by: weditor
* 代码：
```
>>> d=u2.connect()
>>> d(text="Calendar").long_click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\lib\site-packages\uiautomator2\session.py", line 878, in long_click
    return self.session.long_click(x, y, duration)
  File "D:\Python\lib\site-packages\uiautomator2\session.py", line 391, in long_click
    return self._long_click(x, y, duration)
  File "D:\Python\lib\site-packages\uiautomator2\utils.py", line 54, in inner
    ret = fn(self, *args, **kwargs)
  File "D:\Python\lib\site-packages\uiautomator2\session.py", line 395, in _long_click
    self.touch.down(x, y)
  File "D:\Python\lib\site-packages\uiautomator2\session.py", line 349, in down
    obj.jsonrpc.injectInputEvent(ACTION_DOWN, x, y, 0)
  File "D:\Python\lib\site-packages\uiautomator2\__init__.py", line 440, in __call__
    params, http_timeout)
  File "<decorator-gen-12>", line 2, in jsonrpc_retry_call
  File "D:\Python\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "D:\Python\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "D:\Python\lib\site-packages\uiautomator2\__init__.py", line 457, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "D:\Python\lib\site-packages\uiautomator2\__init__.py", line 542, in jsonrpc_call
    raise err
uiautomator2.exceptions.JsonRpcError: -32601 Method not found: <Method not found> data: , method: injectInputEvent
```

**Comment by yaming116** [comment]
是否可以使用drag代替long click事件？

**Comment by yaming116** [comment]
@codeskyblue     https://github.com/openatx/uiautomator2/blob/baed1f639fd6b62f715fb958684bdf0ce97bc364/uiautomator2/session.py#L383

今天我测试了一下，使用 swip可以触发长按事件，测试局部代码如下：
```java
mDevice.swipe(rect.centerX(), rect.centerY(), rect.centerX(), rect.centerY(), 200);
```

u2 对应实现代码是否可行：

```python
def long_click(self, x, y, duration=None):
        '''long click at arbitrary coordinates.
        Args:
            duration (float): seconds of pressed
        '''
        if not duration:
            duration = 0.2
        duration = duration * 1000
        x, y = self.pos_rel2abs(x, y)
        return self. _swipe(x, y, x, y, duration)
```

**Comment by crifan** [comment]
对于 @yaming116 的答案进行补充：

也就是，把原先代码：

```python
    return self._long_click(x, y, duration)
```

改为
```python
    durationInMs = duration * 1000
    return self. _swipe(x, y, x, y, durationInMs)
```

结论：经过自己实测是**可行**的。

注：

1. swipe的单位是毫秒ms
    * 如果不小心传入秒（比如1.5），还会报错
2. 关于用swipe替代 long_click的解释，详见[UiAutomator 2.0 Click 事件分析及长按方法实现 · TesterHome](https://testerhome.com/topics/11029)

**Comment by codeskyblue** [comment]
Already fixed. in 2.4.0
