### ISSUE TITLE
double_click报错

### ISSUE THREAD

**Issue by hylhyl323323** [openatx/uiautomator2#474]
- 手机型号：米6 android9
- uiautomator2的版本号：2.0.1.dev4
- 相关日志
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/AtxLibrary/Test/atx_test1.py", line 5, in <module>
    d.double_click(288,929)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uiautomator2/session.py", line 378, in double_click
    self.touch.down(x, y)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uiautomator2/session.py", line 349, in down
    obj.jsonrpc.injectInputEvent(ACTION_DOWN, x, y, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uiautomator2/__init__.py", line 440, in __call__
    params, http_timeout)
  File "</Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/decorator.py:decorator-gen-12>", line 2, in jsonrpc_retry_call
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uiautomator2/__init__.py", line 457, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uiautomator2/__init__.py", line 542, in jsonrpc_call
    raise err
uiautomator2.exceptions.JsonRpcError: -32601 Method not found: <Method not found> data: , method: injectInputEvent`

测试代码:
import uiautomator2 as u2
d = u2.connect('85666ac6')
d.double_click(288,929)

**Comment by codeskyblue** [comment]
已修复。
