### ISSUE TITLE
获取toast消息报错

### ISSUE THREAD

**Issue by lkhzzqgydx** [openatx/uiautomator2#478]
Name: uiautomator2
Version: 2.0.1.dev11

代码：
        d = u2.connect_usb('5503700044')
       sess = d.session("com.sgcc.pda.mdrh")
       time.sleep(10)
       sess(text="登录").click()
       message = sess.toast.get_message()
       print(message)
报错信息：
Traceback (most recent call last):
  File "F:/pythonScript/atx.py", line 9, in <module>
    message = sess.toast.get_message()
  File "D:\appiumTest\Python\lib\site-packages\uiautomator2\session.py", line 196, in get_message
    message = obj.jsonrpc.getLastToast(cache_timeout * 1000)
  File "D:\appiumTest\Python\lib\site-packages\uiautomator2\__init__.py", line 439, in __call__
    return self.server.jsonrpc_retry_call(jsonrpc_url, self.method,
  File "<D:\appiumTest\Python\lib\site-packages\decorator.py:decorator-gen-12>", line 2, in jsonrpc_retry_call
  File "D:\appiumTest\Python\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "D:\appiumTest\Python\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "D:\appiumTest\Python\lib\site-packages\uiautomator2\__init__.py", line 457, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "D:\appiumTest\Python\lib\site-packages\uiautomator2\__init__.py", line 542, in jsonrpc_call
    raise err
uiautomator2.exceptions.JsonRpcError: -32601 Method not found: <Method not found> data: , method: getLastToast

**Comment by lkhzzqgydx** [comment]
一看到暂时不支持了

**Comment by codeskyblue** [comment]
鄙人想了想，还是切换回到2.0比较好一点。虽然经常的重启，但是总比功能缺失墙一点。2.1.0版本，发布的时候，就重新支持下
