### ISSUE TITLE
2.0版本初始化总是失败

### ISSUE THREAD

**Issue by 406722575** [openatx/uiautomator2#480]
- 手机型号 
华为8A   
系统版本号：安卓9
- uiautomator2的版本号(2.0.1.dev11)
- 手机截图
- 相关日志
(atx_env) C:\Users\Administrator\Desktop\atx_ui2>python -m uiautomator2 init
[D 191113 16:27:25 init:109] Initial device AdbDevice(serial=RMSNW19808002065)
[I 191113 16:27:25 init:277] Install minicap, minitouch
[D 191113 16:27:25 init:48] Use cached assets: C:\Users\Administrator\.uiautomator2\028124b3b0b14f68ba32e32663e2a7cf4bbfda095754
0389d39e1d3c\minitouch
[D 191113 16:27:25 init:186] Push to /data/local/tmp/minitouch:0755
[D 191113 16:27:25 init:48] Use cached assets: C:\Users\Administrator\.uiautomator2\7197af5446923552cd9fd05d4311c84c6637614194e9
143b80c519fd\minicap.so
[D 191113 16:27:25 init:186] Push to /data/local/tmp/minicap.so:0755
[D 191113 16:27:25 init:48] Use cached assets: C:\Users\Administrator\.uiautomator2\eeeef31fcbb49e1d498476b4ba4f8135e27bf1263677
8615f2849908\minicap
[D 191113 16:27:25 init:186] Push to /data/local/tmp/minicap:0755
[D 191113 16:27:26 init:48] Use cached assets: C:\Users\Administrator\.uiautomator2\6edef50a02af79ddf2217874d1ce621d4a847d6762dc
86c10d5811a0\bundle.jar
[D 191113 16:27:26 init:186] Push to /data/local/tmp/bundle.jar:0644
[D 191113 16:27:26 init:48] Use cached assets: C:\Users\Administrator\.uiautomator2\42a21461fa2b0031646c206175ef315ae8a142421a76
75e219336bca\uiautomator-stub.jar
[D 191113 16:27:26 init:186] Push to /data/local/tmp/uiautomator-stub.jar:0644
[I 191113 16:27:26 init:295] Already installed com.github.uiautomator apks
[D 191113 16:27:27 init:214] Real version: [0, 7, 4], Expect version: [0, 7, 4]
[I 191113 16:27:27 init:300] Check install
[D 191113 16:27:27 init:310] Forward: local:tcp:64220 -> remote:tcp:7912
[D 191113 16:27:27 init:310] Forward: local:tcp:64220 -> remote:tcp:7912
[D 191113 16:27:28 init:310] Forward: local:tcp:64220 -> remote:tcp:7912
[D 191113 16:27:28 init:310] Forward: local:tcp:64220 -> remote:tcp:7912
[D 191113 16:27:29 init:310] Forward: local:tcp:64220 -> remote:tcp:7912
[D 191113 16:27:29 init:310] Forward: local:tcp:64220 -> remote:tcp:7912
[D 191113 16:27:30 init:310] Forward: local:tcp:64220 -> remote:tcp:7912
[D 191113 16:27:30 init:310] Forward: local:tcp:64220 -> remote:tcp:7912
[D 191113 16:27:31 init:310] Forward: local:tcp:64220 -> remote:tcp:7912
[D 191113 16:27:31 init:310] Forward: local:tcp:64220 -> remote:tcp:7912
Traceback (most recent call last):
  File "D:\atx_env\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\atx_env\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\atx_env\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "d:\python3.6\Lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "d:\python3.6\Lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "d:\python3.6\Lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "d:\python3.6\Lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\atx_env\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\atx_env\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\atx_env\lib\site-packages\urllib3\util\retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\atx_env\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\atx_env\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\atx_env\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\atx_env\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "d:\python3.6\Lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "d:\python3.6\Lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "d:\python3.6\Lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "d:\python3.6\Lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None
, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python3.6\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python3.6\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\atx_env\lib\site-packages\uiautomator2\__main__.py", line 229, in <module>
    main()
  File "D:\atx_env\lib\site-packages\uiautomator2\__main__.py", line 219, in main

- 最好能附上可能复现问题的代码。

**Comment by lau8889** [comment]
华为20pro也不行，手机中看atx-agent.log，报的operation not permitted，你的问题解决了没

**Comment by 406722575** [comment]
升级最新版本解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lau8889"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月16日(星期一) 上午8:42
收件人:&nbsp;"openatx/uiautomator2"<uiautomator2@noreply.github.com&gt;;
抄送:&nbsp;"Nic"<406722575@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [openatx/uiautomator2] 2.0版本初始化总是失败 (#480)




华为20pro也不行，手机中看atx-agent.log，报的operation not permitted，你的问题解决了没

**Comment by codeskyblue** [comment]
之前有个bug，忘记启动atx-agent了。已修复。多谢反馈
