### ISSUE TITLE
python -m uiautomator2 init 出現失敗 已解決

### ISSUE THREAD

**Issue by kobojp** [openatx/uiautomator2#483]
使用模擬器：雷電模擬器3.76版，android5.1.1

有正確的安裝ATX-Agent，之後顯示錯誤，且使用weditor無法連上雷電模擬器
是我設定出了什麼問題

-----------------------------------

原本是在Visual Studio Code 啟動 uiautomator2 這樣會發生錯誤
另外開啟一個Command Prompt以系統管理員執行,啟動uiautomator2  可解決
```
[D 191115 23:37:41 init:109] Initial device AdbDevice(serial=127.0.0.1:5555)
[I 191115 23:37:41 init:277] Install minicap, minitouch
[D 191115 23:37:41 init:48] Use cached assets: C:\Users\love\.uiautomator2\383030fa57087cbc4edca315ef01dac9fe671d3304263fb5f6016c6c\minitouch
[D 191115 23:37:41 init:186] Push to /data/local/tmp/minitouch:0755
[I 191115 23:37:41 init:281] abi:x86 seems to be android emulator, skip install minicap
[D 191115 23:37:41 init:48] Use cached assets: C:\Users\love\.uiautomator2\6edef50a02af79ddf2217874d1ce621d4a847d6762dc86c10d5811a0\bundle.jar
[D 191115 23:37:41 init:186] Push to /data/local/tmp/bundle.jar:0644
[D 191115 23:37:41 init:48] Use cached assets: C:\Users\love\.uiautomator2\42a21461fa2b0031646c206175ef315ae8a142421a7675e219336bca\uiautomator-stub.jar
[D 191115 23:37:41 init:186] Push to /data/local/tmp/uiautomator-stub.jar:0644
[I 191115 23:37:41 init:295] Already installed com.github.uiautomator apks
[D 191115 23:37:41 init:214] Real version: [0, 7, 4], Expect version: [0, 7, 4]
[I 191115 23:37:41 init:300] Check install
Traceback (most recent call last):
  File "C:\Users\love\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\love\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\love\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator2\__main__.py", line 229, in <module>
    main()
  File "C:\Users\love\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator2\__main__.py", line 219, in main
    actions[args.subparser](args)
  File "C:\Users\love\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator2\__main__.py", line 34, in cmd_init
    init.install(args.server)
  File "C:\Users\love\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator2\init.py", line 301, in install
    self.check_atx_agent_version()
  File "<C:\Users\love\AppData\Local\Programs\Python\Python37-32\lib\site-packages\decorator.py:decorator-gen-4>", line 2, in check_atx_agent_version
  File "C:\Users\love\AppData\Local\Programs\Python\Python37-32\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "C:\Users\love\AppData\Local\Programs\Python\Python37-32\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\Users\love\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator2\init.py", line 309, in check_atx_agent_version
    port = self._device.forward_port(7912)
  File "C:\Users\love\AppData\Local\Programs\Python\Python37-32\lib\site-packages\adbutils\__init__.py", line 383, in forward_port
    for f in self.forward_list():
  File "C:\Users\love\AppData\Local\Programs\Python\Python37-32\lib\site-packages\adbutils\__init__.py", line 224, in forward_list
    c.check_okay()
  File "C:\Users\love\AppData\Local\Programs\Python\Python37-32\lib\site-packages\adbutils\__init__.py", line 137, in check_okay
    raise AdbError(self.read_string())
adbutils.errors.AdbError: unknown host service
```

**Comment by afuz777** [comment]
@codeskyblue 
Hi, 這問題我查過後發現應該是無法找到對應的 Port 才會發生這問題。

1. 確認 **ANDROID_ADB_SERVER_PORT** 預設 **Port** 是多少 ( **_Default 5037_** )
2. 執行 ```python -m uiautomator2 init``` 取得 **self._device.forward_port()** 的值是多少, 可以看到下列資訊所設置的是 7912  Port，**透過這兩點便可以得知是無法連上正確的 ADB Server Port** 

```
$ python -m uiautomator2 init
[I 200916 12:06:08 init:155] uiautomator2 version: 2.11.3
[I 200916 12:06:09 init:377] Check atx-agent version
Traceback (most recent call last):
  ........
  File "C:\Users\Zhang\AppData\Local\Programs\Python\Python38-32\lib\site-packages\uiautomator2\init.py", line 389, in check_atx_agent_version
    port = self._device.forward_port(7912)
  ........
adbutils.errors.AdbError: unknown host service
```

解決方式：
```shell
# 將 ADB Server Port 修改成 7912
$ export ANDROID_ADB_SERVER_PORT=7912

# Restart ADB Server
$ adb kill-server | adb start-server

# 再次執行 uiautomator2 init
$ python -m uiautomator2 init
```
