### ISSUE TITLE
初始化的时候安装minicap.so碰到ssl error 怎么破呢

### ISSUE THREAD

**Issue by samuelchen2015** [openatx/uiautomator2#49]
samueldeiMac:jingpin vip$ python -m uiautomator2 init
2018-02-27 21:52:35,393 - __main__.py:250 - INFO - Device(3207da40) initialing ...
2018-02-27 21:52:35,746 - __main__.py:106 - DEBUG - install minicap.so
2018-02-27 21:52:35,747 - __main__.py:108 - INFO - https://github.com/codeskyblue/stf-binaries/raw/master/node_modules/minicap-prebuilt/prebuilt/armeabi-v7a/lib/android-23/minicap.so
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/uiautomator2/__main__.py", line 310, in <module>
    main()
  File "/Library/Python/2.7/site-packages/uiautomator2/__main__.py", line 306, in main
    fire.Fire(MyFire)
  File "/Library/Python/2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/Library/Python/2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/Library/Python/2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/Library/Python/2.7/site-packages/uiautomator2/__main__.py", line 253, in init
    ins.install_minicap()
  File "/Library/Python/2.7/site-packages/uiautomator2/__main__.py", line 109, in install_minicap
    path = cache_download(url)
  File "/Library/Python/2.7/site-packages/uiautomator2/__main__.py", line 70, in cache_download
    r = requests.get(url, stream=True)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /codeskyblue/stf-binaries/raw/master/node_modules/minicap-prebuilt/prebuilt/armeabi-v7a/lib/android-23/minicap.so (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))

**Comment by HeartIsBeat** [comment]
我用python2.7.5的好像碰到过这个问题，换个python3.6或python2.7.12就没问题了。

**Comment by mingyuan-xia** [comment]
这个也不完全是SSL的问题，和G-F-W有关，python版本更没多大关系，我们会考虑把这个so文件本地化或者放个稳定点地方

**Comment by codeskyblue** [comment]
Try `pip install -U pyopenssl`

Refs: https://github.com/requests/requests/issues/4246

**Comment by ym994561723** [comment]
这个问题 搞了我两天，最后通过抓包，请教大牛  找到了原因，是你本地的tsl协议版本过低，最低需要1.2版本的，我是1.1的，请求是 被拒了，最后的解决办法就是装个虚拟机，配上uiautomator2的环境，然后从那边对移动设备进行初始化，希望对你有帮助

**Comment by codeskyblue** [comment]
Ref: https://github.com/openatx/atx-server/issues/4

添加两个依赖
```
pyOpenSSL == 0.13
ndg-httpsclient == 0.3.2
```

**Comment by q88535448** [comment]
pyOpenSSL == 0.13 一定要安装这个版本吗？？？ 安装的时候一直提示
OpenSSL/crypto/x509.h:17:10: fatal error: 'openssl/ssl.h' file not found
    #include <openssl/ssl.h>
             ^~~~~~~~~~~~~~~
    1 error generated.
    error: command 'cc' failed with exit status 1

**Comment by q88535448** [comment]
我遇到了该问题，我用pycharm执行init命令就可以成功，直接在命令行执行python -m uiautomator2 init就失败报ssl错误。

**Comment by UtopiaHXM** [comment]
Try pip install -U pyopenssl  升级pyopenssl版本可行
