### ISSUE TITLE
adb自动断开没有回连

### ISSUE THREAD

**Issue by cd159** [openatx/uiautomator2#494]
atx总是自己断掉,连上的时候抓取界面元素有些小卡页抓不到

- 手机华为p20
- uiautomator2的版本号(`Version: 2.0.1.dev7`)
- 手机截图
- 
-

**Comment by cd159** [comment]
INSTRUMENTATION_STATUS: stream=
Error in testUIAutomatorStub(com.github.uiautomator.stub.Stub):
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@55a525dalready registered!
	at android.os.Parcel.createException(Parcel.java:1961)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.IUiAutomationConnection$Stub$Proxy.connect(IUiAutomationConnection.java:255)
	at android.app.UiAutomation.connect(UiAutomation.java:238)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2223)
	at android.support.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at android.support.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at android.support.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at android.support.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at com.github.uiautomator.stub.Stub.launchService(Stub.java:106)
	at com.github.uiautomator.stub.Stub.setUp(Stub.java:72)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:76)
	at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2252)

INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS_CODE: -2
127.0.0.1 - - [02/Dec/2019:20:29:01 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [02/Dec/2019:20:29:01 +0800] "POST /info/wifi HTTP/1.1" 404 19
2019/12/02 20:29:01 httpserver.go:521: rotation change received: 0
127.0.0.1 - - [02/Dec/2019:20:29:01 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [02/Dec/2019:20:29:01 +0800] "POST /info/wifi HTTP/1.1" 404 19
2019/12/02 20:29:01 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 1080x2244@800x800/0]
127.0.0.1 - - [02/Dec/2019:20:29:01 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [02/Dec/2019:20:29:01 +0800] "POST /info/rotation HTTP/1.1" 200 14
2019/12/02 20:29:01 httpserver.go:521: rotation change received: 0
127.0.0.1 - - [02/Dec/2019:20:29:01 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [02/Dec/2019:20:29:01 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [02/Dec/2019:20:29:01 +0800] "POST /info/wifi HTTP/1.1" 404 19
2019/12/02 20:29:01 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 1080x2244@800x800/0]
127.0.0.1 - - [02/Dec/2019:20:29:01 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [02/Dec/2019:20:29:01 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [02/Dec/2019:20:29:01 +0800] "POST /info/rotation HTTP/1.1" 200 14
INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0
2019/12/02 20:29:01 cmdctrl.go:27: DEBUG cmd wait err: <nil>
2019/12/02 20:29:01 cmdctrl.go:27: DEBUG idle for 500ms
2019/12/02 20:29:02 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
2019/12/02 20:29:02 cmdctrl.go:27: DEBUG program pid: 15636
INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.github.uiautomator.stub.Stub:
INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS_CODE: 1
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@50b6732already registered!
	at android.os.Parcel.createException(Parcel.java:1961)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:409)
	at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:399)
	at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:97)
	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:62)
	at android.os.Binder.execTransact(Binder.java:739)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accessibility.UiAutomationManager.registerUiTestAutomationServiceLocked(Landroid/os/IBinder;Landroid/accessibilityservice/IAccessibilityServiceClient;Landroid/content/Context;Landroid/accessibilityservice/AccessibilityServiceInfo;ILandroid/os/Handler;Ljava/lang/Object;Lcom/android/server/accessibility/AccessibilityManagerService$SecurityPolicy;Lcom/android/server/accessibility/AbstractAccessibilityServiceConnection$SystemSupport;Lcom/android/server/wm/WindowManagerInternal;Lcom/android/server/accessibility/GlobalActionPerformer;I)V(libmapleservices.so:7015097)
	at com.android.server.accessibility.AccessibilityManagerService.registerUiTestAutomationService(Landroid/os/IBinder;Landroid/accessibilityservice/IAccessibilityServiceClient;Landroid/accessibilityservice/AccessibilityServiceInfo;I)V(libmapleservices.so:7143181)
	at android.view.accessibility.IAccessibilityManager$Stub.onTransact(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z(libmapleframework.so:5436573)
	at android.os.Binder.execTransact(IJJI)Z(libmapleframework.so:6089041)

INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stack=java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@50b6732already registered!
	at android.os.Parcel.createException(Parcel.java:1961)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.IUiAutomationConnection$Stub$Proxy.connect(IUiAutomationConnection.java:255)
	at android.app.UiAutomation.connect(UiAutomation.java:238)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2223)
	at android.support.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at android.support.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at android.support.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at android.support.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at com.github.uiautomator.stub.Stub.launchService(Stub.java:106)
	at com.github.uiautomator.stub.Stub.setUp(Stub.java:72)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:76)
	at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2252)

INSTRUMENTATION_STATUS: stream=
Error in testUIAutomatorStub(com.github.uiautomator.stub.Stub):
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@50b6732already registered!
	at android.os.Parcel.createException(Parcel.java:1961)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.IUiAutomationConnection$Stub$Proxy.connect(IUiAutomationConnection.java:255)
	at android.app.UiAutomation.connect(UiAutomation.java:238)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2223)
	at android.support.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at android.support.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at android.support.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at android.support.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at com.github.uiautomator.stub.Stub.launchService(Stub.java:106)
	at com.github.uiautomator.stub.Stub.setUp(Stub.java:72)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:76)
	at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2252)

INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS_CODE: -2
127.0.0.1 - - [02/Dec/2019:20:29:03 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [02/Dec/2019:20:29:03 +0800] "POST /info/wifi HTTP/1.1" 404 19
2019/12/02 20:29:03 httpserver.go:521: rotation change received: 0
127.0.0.1 - - [02/Dec/2019:20:29:03 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [02/Dec/2019:20:29:03 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [02/Dec/2019:20:29:03 +0800] "POST /info/battery HTTP/1.1" 200 7
2019/12/02 20:29:03 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 1080x2244@800x800/0]
127.0.0.1 - - [02/Dec/2019:20:29:03 +0800] "POST /info/rotation HTTP/1.1" 200 14
2019/12/02 20:29:03 httpserver.go:521: rotation change received: 0
127.0.0.1 - - [02/Dec/2019:20:29:03 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [02/Dec/2019:20:29:03 +0800] "POST /info/wifi HTTP/1.1" 404 19
2019/12/02 20:29:03 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 1080x2244@800x800/0]
127.0.0.1 - - [02/Dec/2019:20:29:03 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [02/Dec/2019:20:29:03 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [02/Dec/2019:20:29:03 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [02/Dec/2019:20:29:03 +0800] "POST /info/rotation HTTP/1.1" 200 14
INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0
2019/12/02 20:29:03 cmdctrl.go:27: DEBUG cmd wait err: <nil>
2019/12/02 20:29:03 cmdctrl.go:27: DEBUG idle for 500ms
2019/12/02 20:29:04 cmdctrl.go:27: DEBUG program finished
2019/12/02 20:29:04 [Info] main.go:586 service uiautomator: stopservice com.github.uiautomator/.Service
127.0.0.1 - - [02/Dec/2019:20:29:33 +0800] "GET /screenshot/0 HTTP/1.1" 200 551947
127.0.0.1 - - [02/Dec/2019:20:29:34 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 19201
127.0.0.1 - - [02/Dec/2019:20:29:36 +0800] "GET /screenshot/0 HTTP/1.1" 200 551911
127.0.0.1 - - [02/Dec/2019:20:29:36 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 19201
127.0.0.1 - - [02/Dec/2019:20:29:46 +0800] "GET /screenshot/0 HTTP/1.1" 200 117045
127.0.0.1 - - [02/Dec/2019:20:29:46 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 2076
127.0.0.1 - - [02/Dec/2019:20:29:58 +0800] "GET /screenshot/0 HTTP/1.1" 200 73137
127.0.0.1 - - [02/Dec/2019:20:29:58 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 12092
127.0.0.1 - - [02/Dec/2019:20:30:10 +0800] "GET /screenshot/0 HTTP/1.1" 200 73178
127.0.0.1 - - [02/Dec/2019:20:30:10 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 12092
2019/12/02 20:33:10 [Info] main.go:595 uiautomator has not activity for 3 minutes, closed
2019/12/02 20:33:10 cmdctrl.go:27: DEBUG program finished
2019/12/02 20:34:03 httpserver.go:492: startservice com.github.uiautomator/.Service

**Comment by codeskyblue** [comment]
升级到2.2.0试试

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cd159** [comment]
我已经升到2.2.0了但是运行用例１－２个小时左右adb会自动断开，然后也没有会连导致剩下的用例失败
手机：huawei p20
atx-agent.log上的部分log
127.0.0.1 - - [03/Dec/2019:20:04:46 +0800] "POST /shell HTTP/1.1" 200 47
2019/12/03 20:04:46 ^[[1;34m[Info] main.go:580 service uiautomator: startservice com.github.uiautomator/.Service
^[[0m127.0.0.1 - - [03/Dec/2019:20:04:46 +0800] "POST /services/uiautomator HTTP/1.1" 200 48
127.0.0.1 - - [03/Dec/2019:20:04:46 +0800] "GET /packages/com.github.uiautomator/info HTTP/1.1" 200 190
127.0.0.1 - - [03/Dec/2019:20:04:46 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [03/Dec/2019:20:04:46 +0800] "POST /info/wifi HTTP/1.1" 404 19
2019/12/03 20:04:46 httpserver.go:536: rotation change received: 0
127.0.0.1 - - [03/Dec/2019:20:04:46 +0800] "POST /info/wifi HTTP/1.1" 404 19
2019/12/03 20:04:46 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 1080x2244@800x800/0]
127.0.0.1 - - [03/Dec/2019:20:04:46 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [03/Dec/2019:20:04:46 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [03/Dec/2019:20:04:46 +0800] "POST /shell HTTP/1.1" 200 172
127.0.0.1 - - [03/Dec/2019:20:04:46 +0800] "GET /services/uiautomator HTTP/1.1" 200 31
127.0.0.1 - - [03/Dec/2019:20:04:46 +0800] "POST /info/rotation HTTP/1.1" 200 14
2019/12/03 20:04:46 reverseproxy.go:442: http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
127.0.0.1 - - [03/Dec/2019:20:04:46 +0800] "POST /jsonrpc/0 HTTP/1.1" 502 0
INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.github.uiautomator.stub.Stub:
INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS_CODE: 1
127.0.0.1 - - [03/Dec/2019:20:04:46 +0800] "GET /uiautomator HTTP/1.1" 200 16
127.0.0.1 - - [03/Dec/2019:20:04:47 +0800] "GET /services/uiautomator HTTP/1.1" 200 31
2019/12/03 20:04:47 reverseproxy.go:442: http: proxy error: dial tcp 127.0.0.1:9008: connect: connection refused
127.0.0.1 - - [03/Dec/2019:20:04:47 +0800] "POST /jsonrpc/0 HTTP/1.1" 502 0
127.0.0.1 - - [03/Dec/2019:20:04:48 +0800] "GET /services/uiautomator HTTP/1.1" 200 31
127.0.0.1 - - [03/Dec/2019:20:04:48 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 213
127.0.0.1 - - [03/Dec/2019:20:04:48 +0800] "POST /shell HTTP/1.1" 200 32172
127.0.0.1 - - [03/Dec/2019:20:04:48 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [03/Dec/2019:20:04:48 +0800] "GET /packages/com.xiaomi.xiaoailite/info HTTP/1.1" 200 219
127.0.0.1 - - [03/Dec/2019:20:04:49 +0800] "POST /shell HTTP/1.1" 200 189
127.0.0.1 - - [03/Dec/2019:20:04:51 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [03/Dec/2019:20:04:51 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [03/Dec/2019:20:04:51 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 292
127.0.0.1 - - [03/Dec/2019:20:04:52 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [03/Dec/2019:20:04:54 +0800] "GET /screenshot/0 HTTP/1.1" 200 117654
127.0.0.1 - - [03/Dec/2019:20:04:54 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 88
127.0.0.1 - - [03/Dec/2019:20:04:55 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [03/Dec/2019:20:04:55 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 291
127.0.0.1 - - [03/Dec/2019:20:04:55 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [03/Dec/2019:20:04:57 +0800] "GET /screenshot/0 HTTP/1.1" 200 117654
127.0.0.1 - - [03/Dec/2019:20:04:55 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [03/Dec/2019:20:04:55 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 291
127.0.0.1 - - [03/Dec/2019:20:04:55 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [03/Dec/2019:20:04:57 +0800] "GET /screenshot/0 HTTP/1.1" 200 117654
127.0.0.1 - - [03/Dec/2019:20:04:57 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 90
127.0.0.1 - - [03/Dec/2019:20:05:07 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [03/Dec/2019:20:05:12 +0800] "POST /jsonrpc/0 HTTP/1.1" 200 89
127.0.0.1 - - [03/Dec/2019:20:05:21 +0800] "GET /screenshot/0 HTTP/1.1" 200 552389
2019/12/03 20:08:12 ^[[1;34m[Info] main.go:595 uiautomator has not activity for 3 minutes, closed
^[[0m2019/12/03 20:08:12 cmdctrl.go:27: DEBUG program finished
2019/12/03 20:08:12 ^[[1;34m[Info] main.go:586 service uiautomator: stopservice com.github.uiautomator/.Service
^[[0m2019/12/03 20:09:46 httpserver.go:507: startservice com.github.uiautomator/.Service
127.0.0.1 - - [03/Dec/2019:20:11:14 +0800] "GET /uiautomator HTTP/1.1" 200 17
2019/12/03 20:11:16 ^[[1;34m[Info] main.go:580 service uiautomator: startservice com.github.uiautomator/.Service
^[[0m127.0.0.1 - - [03/Dec/2019:20:11:16 +0800] "POST /uiautomator HTTP/1.1" 200 20
2019/12/03 20:11:16 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
2019/12/03 20:11:16 cmdctrl.go:27: DEBUG program pid: 26226
2019/12/03 20:11:16 httpserver.go:536: rotation change received: 0
127.0.0.1 - - [03/Dec/2019:20:11:16 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [03/Dec/2019:20:11:16 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [03/Dec/2019:20:11:16 +0800] "POST /info/wifi HTTP/1.1" 404 19
2019/12/03 20:11:16 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 1080x2244@800x800/0]
127.0.0.1 - - [03/Dec/2019:20:11:16 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [03/Dec/2019:20:11:16 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [03/Dec/2019:20:11:16 +0800] "POST /info/rotation HTTP/1.1" 200 14
INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.github.uiautomator.stub.Stub:
INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS_CODE: 1
2019/12/03 20:11:18 httpserver.go:536: rotation change received: 0
2019/12/03 20:11:18 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 1080x2244@800x800/0]
127.0.0.1 - - [03/Dec/2019:20:11:18 +0800] "POST /info/rotation HTTP/1.1" 200 14
127.0.0.1 - - [03/Dec/2019:20:11:18 +0800] "GET /uiautomator HTTP/1.1" 200 16
127.0.0.1 - - [03/Dec/2019:20:11:18 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [03/Dec/2019:20:11:18 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [03/Dec/2019:20:11:18 +0800] "POST /info/wifi HTTP/1.1" 404 19
127.0.0.1 - - [03/Dec/2019:20:11:18 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [03/Dec/2019:20:11:18 +0800] "POST /info/battery HTTP/1.1" 200 7
2019/12/03 20:11:19 ^[[1;34m[Info] main.go:580 service uiautomator: startservice com.github.uiautomator/.Service
^[[0m127.0.0.1 - - [03/Dec/2019:20:11:19 +0800] "POST /uiautomator HTTP/1.1" 200 15
127.0.0.1 - - [03/Dec/2019:20:14:00 +0800] "GET /uiautomator HTTP/1.1" 200 16
2019/12/03 20:14:01 ^[[1;34m[Info] main.go:580 service uiautomator: startservice com.github.uiautomator/.Service
^[[0m127.0.0.1 - - [03/Dec/2019:20:14:01 +0800] "POST /uiautomator HTTP/1.1" 200 15
127.0.0.1 - - [03/Dec/2019:20:16:13 +0800] "POST /info/battery HTTP/1.1" 200 7
127.0.0.1 - - [03/Dec/2019:20:16:44 +0800] "POST /info/battery HTTP/1.1" 200 7
2019/12/03 20:17:01 ^[[1;34m[Info] main.go:595 uiautomator has not activity for 3 minutes, closed
^[[0m2019/12/03 20:17:01 cmdctrl.go:27: DEBUG program finished
2019/12/03 20:17:01 ^[[1;34m[Info] main.go:586 service uiautomator: stopservice com.github.uiautomator/.Service
^[[0m

以下是用例运行时报的错
Traceback (most recent call last):
  File "/home/chendan/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/chendan/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/chendan/.local/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/home/chendan/.local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: : Failed to establish a new connection: [Errno 111] Connection refused
麻烦帮我看一下

**Comment by AllenLuosong** [comment]
Connection refused的报错我这边之前也出现过是因为电脑关机，导致本地电脑端脚本停止运行，你看你的是不是也是这个情况。

**Comment by cd159** [comment]
我的不是呢！就是自己跑着跑着就断开，电脑没有关机

**Comment by codeskyblue** [comment]
换个adb试试呢

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cd159** [comment]
我换了一个adb还是会出现运行到一半就断开的现象，我观察了一下adb 5037的端口状态好像出问题的时候5037都处于CLOSE_WAIT的状态．不知道是不是这个原因啊？

**Comment by JdiChen** [comment]
华为是不是有自动关闭后台应用的功能？可以跟开发沟通一下
