### ISSUE TITLE
安卓模拟器 d.clipboard 获取剪切板数据报错

### ISSUE THREAD

**Issue by BruceLee569** [openatx/uiautomator2#500]
- 手机型号：逍遥安卓模拟器 DUK-AL20
- uiautomator2版本号：2.3.3
- 错误日志（ipython环境，获取剪切板数据时报错）：
```python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] on win32
>>> import uiautomator2 as u2
>>> d = u2.connect()
>>> print(d.clipboard)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\development\Python\Envs\spider\lib\site-packages\uiautomator2\__init__.py", line 1440, in __getattr__
    return getattr(self._default_session, attr)
  File "C:\development\Python\Envs\spider\lib\site-packages\uiautomator2\session.py", line 585, in clipboard
    return self.jsonrpc.getClipboard()
  File "C:\development\Python\Envs\spider\lib\site-packages\uiautomator2\__init__.py", line 488, in __call__
    params, http_timeout)
  File "<C:\development\Python\Envs\spider\lib\site-packages\decorator.py:decorator-gen-12>", line 2, in jsonrpc_retry_call
  File "C:\development\Python\Envs\spider\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "C:\development\Python\Envs\spider\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\development\Python\Envs\spider\lib\site-packages\uiautomator2\__init__.py", line 505, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "C:\development\Python\Envs\spider\lib\site-packages\uiautomator2\__init__.py", line 590, in jsonrpc_call
    raise err
uiautomator2.exceptions.JsonRpcError: -32601 Method not found: <method not found> data: , method: getClipboard
```

**Comment by codeskyblue** [comment]
2.4.0已修复

**Comment by alx-xlx** [comment]
![](https://i.imgur.com/XQiE0tY.png)

This doesn't work, I have tried copying text to the clipboard but doesn't give any output "None"
