### ISSUE TITLE
python -m uiautomator2 init时报错adbutils.errors.AdbError

### ISSUE THREAD

**Issue by stephenlee622** [openatx/uiautomator2#505]

**Comment by stephenlee622** [comment]
D:\>python -m uiautomator2 init
[I 191225 19:08:03 init:110] uiautomator2 version: 2.3.4
[I 191225 19:08:03 init:291] Install minicap, minitouch
[D 191225 19:08:03 init:48] Use cached assets: C:\Users\.uiautomator2\40b57fb8db0d9cc9349fd77248111576dad7e945698260536c6594fc\minitouch
[D 191225 19:08:03 init:187] Push to /data/local/tmp/minitouch:0755
[D 191225 19:08:03 init:48] Use cached assets: C:\Users\.uiautomator2\dda98df4432cfaee0233cd4c0157be330c23130b89528b13025535c0\minicap.so
[D 191225 19:08:03 init:187] Push to /data/local/tmp/minicap.so:0755
[D 191225 19:08:03 init:48] Use cached assets: C:\Users\.uiautomator2\995d216c5453e782fa10efde5cfbd9456f74e56efb361ff47e69876c\minicap
[D 191225 19:08:03 init:187] Push to /data/local/tmp/minicap:0755
[D 191225 19:08:04 init:208] signature: 71f2c9ff
[I 191225 19:08:04 init:309] Already installed com.github.uiautomator apks
[D 191225 19:08:04 init:228] Real version: [0, 8, 0], Expect version: [0, 8, 0]
[D 191225 19:08:04 init:113] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d')
[I 191225 19:08:04 init:316] Check atx-agent version
Traceback (most recent call last):
  File "d:\python\python3.7.4\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\tools\python\python3.7.4\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Envs\android_runner\lib\site-packages\uiautomator2\__main__.py", line 239, in <module>
    main()
  File "C:\Users\Envs\android_runner\lib\site-packages\uiautomator2\__main__.py", line 229, in main
    actions[args.subparser](args)
  File "C:\Users\Envs\android_runner\lib\site-packages\uiautomator2\__main__.py", line 34, in cmd_init
    init.install(args.server)
  File "C:\Users\Envs\android_runner\lib\site-packages\uiautomator2\init.py", line 317, in install
    self.check_atx_agent_version()
  File "<C:\Users\Envs\android_runner\lib\site-packages\decorator.py:decorator-gen-4>", line 2, in check_atx_agent_version
  File "C:\Users\Envs\android_runner\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "C:\Users\Envs\android_runner\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\Users\Envs\android_runner\lib\site-packages\uiautomator2\init.py", line 325, in check_atx_agent_version
    port = self._device.forward_port(7912)
  File "C:\Users\Envs\android_runner\lib\site-packages\adbutils\__init__.py", line 446, in forward_port
    self._client.forward(self._serial, "tcp:" + str(local_port), remote)
  File "C:\Users\android_runner\lib\site-packages\adbutils\__init__.py", line 303, in forward
    c.check_okay()
  File "C:\Users\Envs\android_runner\lib\site-packages\adbutils\__init__.py", line 146, in check_okay
    raise AdbError(self.read_string())
adbutils.errors.AdbError

**Comment by codeskyblue** [comment]
当前adb版本多少，试着升级一下试试呢？

**Comment by stephenlee622** [comment]
Version 29.0.5-5949299

**Comment by stephenlee622** [comment]
用其他电脑尝试试了以后成功了

**Comment by a6a18** [comment]
我也有遇到類似的問題，發生的步驟如下：

在windows 10 命令列輸入 adb reboot，這時候程序似乎卡在這裡
等待機器重開完後，再開另一個命令列，使用python -m uiautomator2 init

就會發生adbutils.errors.AdbError: closed

似乎是系統程序沒有停止adb reboot，所以卡住python -m uiautomator2 init的執行。

adb版本：30.0.3-6597393
adbutils：0.7.1
uiautomator2：2.5.7
