### ISSUE TITLE
截图概率性失败

### ISSUE THREAD

**Issue by qingqingcaoyuanlin** [openatx/uiautomator2#510]
手机：荣耀V9，分辨率2560*1440，Android 9.0
uiautomator2 Version: 2.4.2

问题描述：
一开始用命令行截图概率性提示异常，用d.srceenshot()命令截图概率性出现截图内容全黑，试多几次后就正常了。不过截屏显示的内容是1920*1080，超出的部分显示黑色。用荣耀V20没有出现此类问题。
![screenshot](https://user-images.githubusercontent.com/8575159/71637857-2a006780-2c8a-11ea-9b80-50a874815d31.jpg)

`
D:\data\mess>uiautomator2 screenshot screenshot.jpg
[I 200101 11:02:37 init:129] uiautomator2 version: 2.4.2
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\PIL\JpegImagePlugin.py", line 628, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\Scripts\uiautomator2-script.py", line 11, in <module>
    load_entry_point('uiautomator2==2.4.2', 'console_scripts', 'uiautomator2')()
  File "c:\python37\lib\site-packages\uiautomator2\__main__.py", line 229, in main
    actions[args.subparser](args)
  File "c:\python37\lib\site-packages\uiautomator2\__main__.py", line 46, in cmd_screenshot
    d.screenshot().save(args.filename)
  File "c:\python37\lib\site-packages\PIL\Image.py", line 2088, in save
    save_handler(self, fp, filename)
  File "c:\python37\lib\site-packages\PIL\JpegImagePlugin.py", line 630, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode RGBA as JPEG
`

**Comment by codeskyblue** [comment]
黑边的问题，貌似需要到设置（显示设置）里面调整一下就好了。报的那个错误，应该是个bug

**Comment by codeskyblue** [comment]
报的那个错误，原因是用minicap截图失败了，转用screencap截图，然后格式是png的，所以pillow读取的时候有个alpha通道。需要用convert转化成rgb格式。2.4.4版本中已修复

**Comment by qingqingcaoyuanlin** [comment]
uiautomator2 version: 2.5.7验证已解决

**Comment by qingqingcaoyuanlin** [comment]
抱歉，拿错手机来验证，还是会有黑边问题

**Comment by qingqingcaoyuanlin** [comment]
抱歉，拿错手机来验证，还是会有黑边问题

**Comment by codeskyblue** [comment]
fixed
