### ISSUE TITLE
d.pull功能异常

### ISSUE THREAD

**Issue by qingqingcaoyuanlin** [openatx/uiautomator2#517]
uiautomator2 version: 2.5.1

d.pull('/data/data/com.xxx.h.os06/databases/H-OS06_DB.db','123.db')
d.pull异常问题应该很容易复现，肯定是版本的问题，将u2降级了就正常了，对比了pull的代码，版本前后是有改动过的。

`C:\Python37\python.exe F:/1-code/qingqingcaoyuanlin/HOS06/OS/test.py
Traceback (most recent call last):
  File "F:/1-code/qingqingcaoyuanlin/HOS06/OS/test.py", line 16, in <module>
    d.pull('/data/data/com.gvs.h.os06/databases/H-OS06_DB.db','123.db')
  File "C:\Python37\lib\site-packages\uiautomator2\__init__.py", line 1370, in pull
    r = requests.get(pathname, stream=True)
  File "C:\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Python37\lib\site-packages\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "C:\Python37\lib\site-packages\requests\models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/raw/data/data/com.xxx.h.os06/databases/H-OS06_DB.db': No schema supplied. Perhaps you meant http:///raw/data/data/com.xxx.h.os06/databases/H-OS06_DB.db?

Process finished with exit code 1`

**Comment by codeskyblue** [comment]
use d.adb_device.sync.pull instead
