### ISSUE TITLE
直接代码中init device报错

### ISSUE THREAD

**Issue by treeleave** [openatx/uiautomator2#519]
- uiautomator2的版本号  2.4.3.dev3
- Android版本：Android 8.1
- 出错代码：uiautomator2.connect_usb()
分析原因应该是datetime.datetime.fromtimestamp(mtime)，mtime为0导致的
直接使用python -m uiautomator2 init没问题，但目前需求是想在代码中init uiautomator2
[I 200118 13:44:46 init:129] uiautomator2 version: 2.4.3.dev3
Traceback (most recent call last):
  File "D:/00-Dev/06-Python/demo/Vivo/hello.py", line 4, in <module>
    init = uiautomator2.connect_usb(serial_no)
  File "D:\Python36\lib\site-packages\uiautomator2\__init__.py", line 173, in connect_usb
    if not initer.check_install():
  File "D:\Python36\lib\site-packages\uiautomator2\init.py", line 256, in check_install
    if d.sync.stat("/data/local/tmp/atx-agent").size == 0:
  File "D:\Python36\lib\site-packages\adbutils\__init__.py", line 480, in stat
    return FileInfo(mode, size, datetime.datetime.fromtimestamp(mtime),
OSError: [Errno 22] Invalid argument

**Comment by Gaoyongxian666** [comment]
更新库版本就好了
