### ISSUE TITLE
miui9设备端crash

### ISSUE THREAD

**Issue by smartguo** [openatx/uiautomator2#52]
手机型号为MI 6，MIUI 9.2系统，Android版本7.1.1，报错信息如下：
```
>>> import uiautomator2 as ui2
>>> d = ui2.connect('192.168.0.104')
>>> d.info
/home/smartguo/lib/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py:325: RuntimeWarning: uiautomator2 is down, restart.
  warnings.warn("uiautomator2 is down, restart.", RuntimeWarning, stacklevel=1)
Traceback (most recent call last):
  File "/home/smartguo/lib/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 323, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "/home/.../anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 351, in jsonrpc_call
    raise GatewayError(res, "gateway error, time used %.1fs" % (time.time() - request_start))
uiautomator2.GatewayError: uiautomator2.GatewayError(gateway error, time used 0.1s)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 771, in __getattr__
    return getattr(self._default_session, attr)
  File "/home/..../anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 1152, in info
    return self.jsonrpc.deviceInfo()
  File "/home/.../anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 316, in __call__
    return self.server.jsonrpc_retry_call(jsonrpc_url, self.method, params, http_timeout)
  File "/home/smartguo/lib/anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 327, in jsonrpc_retry_call
    self.healthcheck(unlock=False)
  File "/home/.../anaconda3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 430, in healthcheck
    raise RuntimeError("Uiautomator started failed.")
RuntimeError: Uiautomator started failed.
```

**Comment by codeskyblue** [comment]
重新init 下

**Comment by smartguo** [comment]
允许了啊，该开的权限均已开启，允许USB安装，USB调试等等。另一个python的uiautomator项目可以控制，这个总是设备端程序崩溃。

**Comment by mingyuan-xia** [comment]
有没有用其他的测试框架，比如xiaocong/uiautomator等基于uiautomator系列的框架

**Comment by yazhli** [comment]
請問這個問題解決了嘛？我在安卓S上也發現了這個問題
