### ISSUE TITLE
uiautomator2.exceptions.JsonRpcError: -32001 Jsonrpc error: <java.lang.SecurityException> data: java.lang.Secu rityException: Injecting to another application requires INJECT_EVENTS permission

### ISSUE THREAD

**Issue by janksenhu** [openatx/uiautomator2#520]
product is: Xiaomi, os version: 9，手机型号：小米8，MIUI：11.0.3

E:\uiautomator_nearby>python wifi.py
Traceback (most recent call last):
  File "wifi.py", line 27, in <module>
    driver.press("enter")
  File "D:\Python38\lib\site-packages\uiautomator2\session.py", line 546, in press
    return self.jsonrpc.pressKey(key)
  File "D:\Python38\lib\site-packages\uiautomator2\__init__.py", line 544, in __call__
    return self.server.jsonrpc_retry_call(self.method, params,
  File "D:\Python38\lib\site-packages\uiautomator2\__init__.py", line 551, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "D:\Python38\lib\site-packages\uiautomator2\__init__.py", line 643, in jsonrpc_call
    raise err
uiautomator2.exceptions.JsonRpcError: -32001 Jsonrpc error: <java.lang.SecurityException> data: java.lang.Secu
rityException: Injecting to another application requires INJECT_EVENTS permission
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.app.IUiAutomationConnection$Stub$Proxy.injectInputEvent(IUiAutomationConnection.java:292)
        at android.app.UiAutomation.injectInputEvent(UiAutomation.java:516)
        at android.support.test.uiautomator.InteractionController.injectEventSync(InteractionController.java:6
90)
        at android.support.test.uiautomator.InteractionController.sendKey(InteractionController.java:587)
        at android.support.test.uiautomator.UiDevice.pressKeyCode(UiDevice.java:461)
        at android.support.test.uiautomator.UiDevice.pressEnter(UiDevice.java:448)
        at com.github.uiautomator.stub.AutomatorServiceImpl.pressKey(AutomatorServiceImpl.java:539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
        at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
        at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)
, method: pressKey

**Comment by codeskyblue** [comment]
把开发者选项中的，模拟点击打开就好了

**Comment by crifan** [comment]
开启 `设置`->`开发者选项`->`USB调试（安全设置）  允许通过USB调试修改权限或模拟点击`

如图：

![59C7EA81-B407-464A-9B97-2F4DDE921466](https://user-images.githubusercontent.com/2750682/74634326-94b82480-519e-11ea-8f0c-274f113c6c93.png)

即可解决问题。
