### ISSUE TITLE
执行d.dump_hierarchy() 获取hierarchy报错

### ISSUE THREAD

**Issue by sixsixzhu** [openatx/uiautomator2#522]
**看完请删掉该内容**

*提Bug需要注意的事项*

请务必提供详细的信息，能够复现你的问题，否则很难帮你解决。没用的Issue会被打上`Invalid`标签。

- 手机型号
- uiautomator2的版本号(`pip show uiautomator2`)  使用仓库中的最新版本
- 手机截图
- 相关日志
- 最好能附上可能复现问题的代码。

代码： 
import uiautomator2 as u2

d = u2.connect()

d.xpath('//*[@resource-id="com.netease.cloudmusic:id/b2y"]/android.widget.LinearLayout[1]/androidx.appcompat.app.ActionBar-Tab[1]').click()

报错：
E:\zhl>python3 test2.py
Traceback (most recent call last):
  File "test2.py", line 5, in <module>
    d.xpath('//*[@resource-id="com.netease.cloudmusic:id/b2y"]/android.widget.LinearLayout[1]/androidx.appcompat.app.ActionBar-Tab[1]').click()
  File "C:\python3\lib\site-packages\uiautomator2\xpath.py", line 503, in click
    el.click()
  File "C:\python3\lib\site-packages\uiautomator2\xpath.py", line 557, in click
    self._parent.send_click(x, y)
  File "C:\python3\lib\site-packages\uiautomator2\xpath.py", line 193, in send_click
    self._d.click(x, y)
  File "C:\python3\lib\site-packages\uiautomator2\session.py", line 382, in click
    self._click(x, y)
  File "C:\python3\lib\site-packages\uiautomator2\utils.py", line 56, in inner
    ret = fn(self, *args, **kwargs)
  File "C:\python3\lib\site-packages\uiautomator2\session.py", line 386, in _click
    self.jsonrpc.click(x, y)
  File "C:\python3\lib\site-packages\uiautomator2\__init__.py", line 547, in __call__
    http_timeout)
  File "C:\python3\lib\site-packages\uiautomator2\__init__.py", line 553, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "C:\python3\lib\site-packages\uiautomator2\__init__.py", line 645, in jsonrpc_call
    raise err
uiautomator2.exceptions.JsonRpcError: -32001 Jsonrpc error: <java.lang.SecurityException> data: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
        at android.os.Parcel.readException(Parcel.java:1683)
        at android.os.Parcel.readException(Parcel.java:1636)
        at android.app.IUiAutomationConnection$Stub$Proxy.injectInputEvent(IUiAutomationConnection.java:276)
        at android.app.UiAutomation.injectInputEvent(UiAutomation.java:501)
        at android.support.test.uiautomator.InteractionController.injectEventSync(InteractionController.java:690)
        at android.support.test.uiautomator.InteractionController.touchDown(InteractionController.java:351)
        at android.support.test.uiautomator.InteractionController.clickNoSync(InteractionController.java:220)
        at android.support.test.uiautomator.UiDevice.click(UiDevice.java:557)
        at com.github.uiautomator.stub.AutomatorServiceImpl.click(AutomatorServiceImpl.java:199)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
        at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
        at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:760)
, method: click

**Comment by sixsixzhu** [comment]
uiautomator2**

**Comment by crifan** [comment]
看你错误是
`aise err
uiautomator2.exceptions.JsonRpcError: -32001 Jsonrpc error: <java.lang.SecurityException> data: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission`

-》也是**INJECT_EVENTS**的问题

详见：
Duplicate of #520
