### ISSUE TITLE
Exception in thread watcher

### ISSUE THREAD

**Issue by thlengane** [openatx/uiautomator2#524]
***提Bug需要注意的事项***
Getting an exception when a watcher has been detected a text to be watched or when I execute d.watcher.run(). 

if I run the line below while I an on the screen with text 'now', it does click successfully but if I run d.watcher.start(), it crashes.
d.watcher("test_watcher").when("//*[contains(@text , 'now')]").call(watcher_contains_click(d, 'contains(@text', 'now'))

**- 手机型号**  
Phone: HUAWEI Mate 10 Pro
Model: BLA-L29
Build Number: BLA-L29 8.0.0.144(C185)
Android Version: 8.0.0

**- uiautomator2的版本号(`pip show uiautomator2`)**
Name: uiautomator2
Version: 2.5.6
Summary: Python Wrapper for Google Android UiAutomator2 test tool
Home-page: https://github.com/openatx/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: c:\python\lib\site-packages
Requires: six, requests, humanize, whichcraft, logzero, progress, retry, adbutils, Deprecated, Pillow, lxml
Required-by: weditor

**- 手机截图**
![image](https://user-images.githubusercontent.com/7370719/74922993-b997dc00-53d8-11ea-92b2-95d0d86d5ba0.png)

- 相关日志
Exception in thread watcher:
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\lib\site-packages\uiautomator2\watcher.py", line 88, in _watch_forever
    triggered = self.run()
  File "C:\Python\lib\site-packages\uiautomator2\watcher.py", line 95, in run
    self._run_watchers(source=source)
  File "C:\Python\lib\site-packages\uiautomator2\watcher.py", line 119, in _run_watchers
    st = inspect.signature(cb)
  File "C:\Python\lib\inspect.py", line 3083, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "C:\Python\lib\inspect.py", line 2833, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "C:\Python\lib\inspect.py", line 2208, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: None is not a callable object 

**- 最好能附上可能复现问题的代码。**
import uiautomator2 as object_device
d = object_device.connect_usb()

def watcher_contains_click(d : object_device, xpath : str, item : str):
&nbsp;&nbsp;&nbsp;&nbsp;if REGISTER_WATCHERS == False :
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;d.xpath("//*[" + xpath + ", '" + item + "')]").click()

REGISTER_WATCHERS = True
d.watcher("test_watcher").when("//*[contains(@text , 'now')]").call(watcher_contains_click(d, 'contains(@text', 'now'))
REGISTER_WATCHERS = False

d.watcher.start()

**Comment by thlengane** [comment]
Got it working, I had to put in **_lambda  d :_** before I call my method.

**Comment by thlengane** [comment]
Got it working, I had to put in lambda d : before I call my method.
