### ISSUE TITLE
反复经常异常FATAL EXCEPTION: Instr: android.support.test.runner.AndroidJUnitRunner

### ISSUE THREAD

**Issue by qing0404** [openatx/uiautomator2#525]
02-28 04:01:38.529  1622  1636 E AndroidRuntime: FATAL EXCEPTION: Instr: android.support.test.runner.AndroidJUnitRunner
02-28 04:01:38.529  1622  1636 E AndroidRuntime: Process: com.github.uiautomator, PID: 1622
02-28 04:01:38.529  1622  1636 E AndroidRuntime: java.lang.IllegalStateException: UiAutomation not connected!
02-28 04:01:38.529  1622  1636 E AndroidRuntime: 	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:719)
02-28 04:01:38.529  1622  1636 E AndroidRuntime: 	at android.app.UiAutomation.disconnect(UiAutomation.java:254)
02-28 04:01:38.529  1622  1636 E AndroidRuntime: 	at android.app.Instrumentation.finish(Instrumentation.java:205)
02-28 04:01:38.529  1622  1636 E AndroidRuntime: 	at android.support.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:351)
02-28 04:01:38.529  1622  1636 E AndroidRuntime: 	at android.support.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:404)
02-28 04:01:38.529  1622  1636 E AndroidRuntime: 	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:393)
02-28 04:01:38.529  1622  1636 E AndroidRuntime: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1756)

设备是个手表，mini版的android手机
- uiautomator2的版本号：1.3.7.dev6
其他log：
02-28 04:02:07.039  2061  2076 E AndroidRuntime: FATAL EXCEPTION: Instr: android.support.test.runner.AndroidJUnitRunner
02-28 04:02:07.039  2061  2076 E AndroidRuntime: Process: com.github.uiautomator, PID: 2061
02-28 04:02:07.039  2061  2076 E AndroidRuntime: java.lang.IllegalStateException: Cannot call disconnect() while connecting!
02-28 04:02:07.039  2061  2076 E AndroidRuntime: 	at android.app.UiAutomation.disconnect(UiAutomation.java:251)
02-28 04:02:07.039  2061  2076 E AndroidRuntime: 	at android.app.Instrumentation.finish(Instrumentation.java:205)
02-28 04:02:07.039  2061  2076 E AndroidRuntime: 	at android.support.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:351)
02-28 04:02:07.039  2061  2076 E AndroidRuntime: 	at android.support.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:404)
02-28 04:02:07.039  2061  2076 E AndroidRuntime: 	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:393)
02-28 04:02:07.039  2061  2076 E AndroidRuntime: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1756)

**Comment by sashuangyibing** [comment]
我也经常遇到了，在原生Android Q上
