### ISSUE TITLE
restart-uiautomator since Http read-timeout

### ISSUE THREAD

**Issue by 1098880928aa** [openatx/uiautomator2#539]
- 手机型号：小米Note、OPPO R9TM 、OPPO R7SM

- uiautomator2的版本号：Name: uiautomator2      Version: 2.7.1

- 错误描述：
   使用一段时间后会出现以下错误，开始也怀疑是网络问题。
   但发现在重启程序，重新使用u2.connect(ip)建立链接，又可以正常使用
   还有一个现象就是，发生此错误时，设置的Watch监听好像还可以正常响应，不清楚这是什么原因造成的
- 相关日志：
[D 200419 20:33:45 __init__:774] restart-uiautomator since "Http read-timeout: HTTPConnectionPool(host='192.168.2.11', port=7912): Read timed out. (read timeout=60)"
[D 200419 20:38:22 __init__:774] restart-uiautomator since "Http read-timeout: HTTPConnectionPool(host='192.168.2.11', port=7912): Read timed out. (read timeout=60)"
Exception in thread watcher:
Traceback (most recent call last):
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Program Files (x86)\Python\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "D:\Program Files (x86)\Python\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "D:\Program Files (x86)\Python\Python37\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Program Files (x86)\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
    raise value
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\urllib3\connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\urllib3\connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.2.11', port=7912): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\Program Files (x86)\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\uiautomator2\watcher.py", line 93, in _watch_forever
    triggered = self.run()
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\uiautomator2\watcher.py", line 105, in run
    return self._run_watchers(source=source)
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\uiautomator2\watcher.py", line 112, in _run_watchers
    source = source or self._dump_hierarchy()
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\uiautomator2\watcher.py", line 41, in _dump_hierarchy
    return self._d.dump_hierarchy()
  File "<decorator-gen-10>", line 2, in dump_hierarchy
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\uiautomator2\session.py", line 528, in dump_hierarchy
    content = self.jsonrpc.dumpWindowHierarchy(compressed, None)
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\uiautomator2\__init__.py", line 547, in __call__
    http_timeout)
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\uiautomator2\__init__.py", line 580, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\uiautomator2\__init__.py", line 601, in jsonrpc_call
    data=data)
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\uiautomator2\__init__.py", line 406, in _request
    return self._reqsess.request(method, self.path2url(url), **kwargs)
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\uiautomator2\__init__.py", line 228, in request
    self).request(method, url, **kwargs)
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "D:\projects\PyCharm\projects\venv\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.2.11', port=7912): Read timed out. (read timeout=60)

**Comment by mingyuan-xia** [comment]
logcat
