### ISSUE TITLE
android 7.1.1 设备上无法点击中文文本（vivo X20）

### ISSUE THREAD

**Issue by jiguanghover** [openatx/uiautomator2#55]
操作：
d(text=u"数码家电").click()
错误信息：

Traceback (most recent call last):
  File "C:\Python\Python35\lib\site-packages\weditor\__main__.py", line 297, in post
    ret = eval(code, {'d': d})
  File "<string>", line 1, in <module>
  File "C:\Python\Python35\lib\site-packages\uiautomator2\__init__.py", line 1194, in inner
    return fn(self, *args, **kwargs)
  File "C:\Python\Python35\lib\site-packages\uiautomator2\__init__.py", line 1237, in click
    self.session.click(x, y)
  File "C:\Python\Python35\lib\site-packages\uiautomator2\__init__.py", line 972, in click
    ret = self.jsonrpc.click(x, y)
  File "C:\Python\Python35\lib\site-packages\uiautomator2\__init__.py", line 322, in __call__
    return self.server.jsonrpc_retry_call(jsonrpc_url, self.method, params, http_timeout)
  File "C:\Python\Python35\lib\site-packages\uiautomator2\__init__.py", line 329, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "C:\Python\Python35\lib\site-packages\uiautomator2\__init__.py", line 373, in jsonrpc_call
    raise err
uiautomator2.JsonRpcError: -32001 Server error: java.lang.SecurityException <Injecting to another application requires INJECT_EVENTS permission>
[Finished in 1.085s]

**Comment by codeskyblue** [comment]
手机禁用了 uiautomator的功能，看看开发者选项里面有没有什么选项没有设置好的

**Comment by he902** [comment]
开发者选项里面有个"USB调试（安全模式）允许模拟点击“。
我的小米2SC就是要打开那个选项才不报SecurityException.
