### ISSUE TITLE
米9在使用watcher时失败，报错如下

### ISSUE THREAD

**Issue by ant0x00** [openatx/uiautomator2#555]
**看完请删掉该内容**

*提Bug需要注意的事项*

请务必提供详细的信息，能够复现你的问题，否则很难帮你解决。没用的Issue会被打上`Invalid`标签。

- 手机型号: 米9
- uiautomator2的版本号(`pip show uiautomator2`) 2.7.2

- 日志:
[I 200605 15:57:18 watcher:123] XPath(hook:install): ['继续安装']
[W 200605 15:57:18 watcher:141] watchers exception: -32001 Jsonrpc error: <java.lang.SecurityException> data: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
    	at android.os.Parcel.createException(Parcel.java:1950)
    	at android.os.Parcel.readException(Parcel.java:1918)
    	at android.os.Parcel.readException(Parcel.java:1868)
    	at android.app.IUiAutomationConnection$Stub$Proxy.injectInputEvent(IUiAutomationConnection.java:292)
    	at android.app.UiAutomation.injectInputEvent(UiAutomation.java:516)
    	at com.github.uiautomator.stub.TouchController.injectEventSync(TouchController.java:38)
    	at com.github.uiautomator.stub.TouchController.touchDown(TouchController.java:47)
    	at com.github.uiautomator.stub.AutomatorServiceImpl.click(AutomatorServiceImpl.java:206)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
    	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
    	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
    	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
    	at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
    	at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
    	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
    	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
    	at java.lang.Thread.run(Thread.java:764)
    , method: click

**Comment by ant0x00** [comment]
我的代码：
        watch_keys = ["继续安装", "完成", "始终允许", "同意", "ALLOW"]  #关键字
        for key in watch_keys:
            self.driver.watcher('install').when(key).click()

可能涉及到的代码：watcher.py
    def click(self):
        def _inner_click(selector):
            selector.get_last_match().click()
        self.call(_inner_click)

**Comment by mingyuan-xia** [comment]
`Injecting to another application requires INJECT_EVENTS permission` 你自己搜一下这个错误
