### ISSUE TITLE
get_text()方法概率性异常。

### ISSUE THREAD

**Issue by qingqingcaoyuanlin** [openatx/uiautomator2#562]
uiautomator版本不好确定，因为自己增加了一些功能（应该是uiautomator2大改之前的版本）。
在init时显示的一些版本号信息：
[I 200619 17:48:32 init:257] package com.github.uiautomator version 1.1.7, latest 2.3.1
[I 200619 17:48:32 init:363] Install com.github.uiautomator, com.github.uiautomator.test 2.3.1

问题描述：我的用例中有两次调用get_text()，在第二次调用出现异常，重新运行脚本，功能正常。
出现概率：1次

**以下是异常日志：**
C:\Python37\lib\site-packages\uiautomator2\__init__.py:570: RuntimeWarning: uiautomator2 raise exception -32001 Jsonrpc error: <java.lang.NullPointerException> data: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.support.test.uiautomator.UiObject2.getText()' on a null object reference
	at com.github.uiautomator.stub.AutomatorServiceImpl.getText(AutomatorServiceImpl.java:674)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
	at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
	at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:818)
, method: getText, and run code again
  stacklevel=1)
Traceback (most recent call last):
  File "G:\1-code\qingqingcaoyuanlin\XXX\XXX\IS\test_IS_Called.py", line 507, in test_Monitor_Next
    self.show_device_No()
  File "G:\1-code\qingqingcaoyuanlin\XXX\XXX\IS\test_IS_Called.py", line 106, in show_device_No
    device = self.IS.d(**UI_Calling['设备']).get_text()
  File "C:\Python37\lib\site-packages\uiautomator2\session.py", line 1059, in get_text
    return self.jsonrpc.getText(self.selector)
  File "C:\Python37\lib\site-packages\uiautomator2\__init__.py", line 547, in __call__
    http_timeout)
  File "C:\Python37\lib\site-packages\uiautomator2\__init__.py", line 580, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "C:\Python37\lib\site-packages\uiautomator2\__init__.py", line 645, in jsonrpc_call
    raise err
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error: <android.support.test.uiautomator.UiObjectNotFoundException> data: UiSelector[RESOURCE_ID=com.xxx.xxx:id/tv_from_type], method: getText

**Comment by mingyuan-xia** [comment]
1. 异常是没找到元素，和get_text没关系，和元素定位有关，没上下文没法调试
2. 1.x早就不维护了，atxagent和uiautomator2-server也已经迭代很多了

**Comment by codeskyblue** [comment]
@mingyuan-xia 看日志就是用的最新版

**Comment by qingqingcaoyuanlin** [comment]
u2版本是版本大改之前的版本，版本号约为2.8。这个问题感觉可能是atx-agent或者app端的问题。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;shengxiang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月24日(星期三) 上午10:26
收件人:&nbsp;&quot;openatx/uiautomator2&quot;<uiautomator2@noreply.github.com&gt;;
抄送:&nbsp;&quot;qingqingcaoyuanlin&quot;<1451368913@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [openatx/uiautomator2] get_text()方法概率性异常 (#562)
