### ISSUE TITLE
无法通过package启动app: no such file or directory

### ISSUE THREAD

**Issue by darrenxyli** [openatx/uiautomator2#565]
无法通过package启动app

- Google Pixel XL
- uiautomator2的版本号:2.9.6
- 代码:

`
d.app_start('com.appatomic.vpnhub')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 1316, in app_start
    info = self.app_info(package_name)
  File "/workspace/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 1460, in app_info
    raise BaseError(resp.get('description', 'unknown'))
uiautomator2.exceptions.BaseError: stat /data/app/com.appatomic.vpnhub-d3kmp3Wod8qpTtwoJJmYKA==/base.apk
package:/data/app/com.appatomic.vpnhub-d3kmp3Wod8qpTtwoJJmYKA==/split_config.arm64_v8a.apk
package:/data/app/com.appatomic.vpnhub-d3kmp3Wod8qpTtwoJJmYKA==/split_config.en.apk
package:/data/app/com.appatomic.vpnhub-d3kmp3Wod8qpTtwoJJmYKA==/split_config.xxxhdpi.apk: no such file or directory
`

**Comment by codeskyblue** [comment]
你先这样启动吧，你这个app，程序解析不了。。

```
d.app_start("xxxxx", use_monkey=True)
```

**Comment by darrenxyli** [comment]
谢谢！然后还有一个issue是UIAUTOMATOR在这个device上启动不了，闪退

**Comment by darrenxyli** [comment]
```
[D 200623 19:54:29 __init__:595] kill process(ps): uiautomator
[D 200623 19:54:30 __init__:614] uiautomator-v2 is starting ... left: 40.0s
[D 200623 19:54:31 __init__:614] uiautomator-v2 is starting ... left: 39.0s
[D 200623 19:54:32 __init__:614] uiautomator-v2 is starting ... left: 38.0s
[D 200623 19:54:33 __init__:614] uiautomator-v2 is starting ... left: 36.9s
[D 200623 19:54:34 __init__:614] uiautomator-v2 is starting ... left: 35.9s
[D 200623 19:54:35 __init__:614] uiautomator-v2 is starting ... left: 34.9s
[I 200623 19:54:37 __init__:567] restart-uiautomator since "uiautomator2.GatewayError(gateway error, time used 0.0s)"
[D 200623 19:54:37 __init__:595] kill process(ps): uiautomator
[D 200623 19:54:37 __init__:649] grant permissions
[D 200623 19:54:38 __init__:614] uiautomator-v2 is starting ... left: 40.0s
[D 200623 19:54:39 __init__:614] uiautomator-v2 is starting ... left: 39.0s
[D 200623 19:54:40 __init__:614] uiautomator-v2 is starting ... left: 38.0s
[D 200623 19:54:41 __init__:614] uiautomator-v2 is starting ... left: 36.9s
[D 200623 19:54:42 __init__:614] uiautomator-v2 is starting ... left: 35.9s
Traceback (most recent call last):
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 438, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 475, in _jsonrpc_call
    (time.time() - request_start))
uiautomator2.exceptions.GatewayError: uiautomator2.GatewayError(gateway error, time used 0.0s)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/xpath.py", line 546, in click
    el = self.get(timeout=timeout)
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/xpath.py", line 474, in get
    if not self.wait(timeout or self._global_timeout):
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/xpath.py", line 510, in wait
    if self.exists:
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/xpath.py", line 459, in exists
    return len(self.all()) > 0
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/xpath.py", line 410, in all
    xml_content = source or self._source or self._parent.dump_hierarchy()
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/xpath.py", line 176, in dump_hierarchy
    self._last_source = self._d.dump_hierarchy()
  File "<decorator-gen-12>", line 2, in dump_hierarchy
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 883, in dump_hierarchy
    content = self.jsonrpc.dumpWindowHierarchy(compressed, None)
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 432, in __call__
    http_timeout)
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 442, in _jsonrpc_retry_call
    self.reset_uiautomator(str(e)) # uiautomator可能出问题了，强制重启一下
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 586, in reset_uiautomator
    depth=depth + 1)
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 586, in reset_uiautomator
    depth=depth + 1)
  File "/Users/darrenxyli/Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 563, in reset_uiautomator
    "adb shell am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner",
OSError: [Errno Uiautomator started failed.] uiautomator2.GatewayError(gateway error, time used 0.0s): 'https://github.com/openatx/uiautomator2/wiki/Common-issues'
```

**Comment by utiq** [comment]
> ```
> [D 200623 19:54:29 __init__:595] kill process(ps): uiautomator
> [D 200623 19:54:30 __init__:614] uiautomator-v2 is starting ... left: 40.0s
> [D 200623 19:54:31 __init__:614] uiautomator-v2 is starting ... left: 39.0s
> [D 200623 19:54:32 __init__:614] uiautomator-v2 is starting ... left: 38.0s
> [D 200623 19:54:33 __init__:614] uiautomator-v2 is starting ... left: 36.9s
> [D 200623 19:54:34 __init__:614] uiautomator-v2 is starting ... left: 35.9s
> [D 200623 19:54:35 __init__:614] uiautomator-v2 is starting ... left: 34.9s
> [I 200623 19:54:37 __init__:567] restart-uiautomator since "uiautomator2.GatewayError(gateway error, time used 0.0s)"
> [D 200623 19:54:37 __init__:595] kill process(ps): uiautomator
> [D 200623 19:54:37 __init__:649] grant permissions
> [D 200623 19:54:38 __init__:614] uiautomator-v2 is starting ... left: 40.0s
> [D 200623 19:54:39 __init__:614] uiautomator-v2 is starting ... left: 39.0s
> [D 200623 19:54:40 __init__:614] uiautomator-v2 is starting ... left: 38.0s
> [D 200623 19:54:41 __init__:614] uiautomator-v2 is starting ... left: 36.9s
> [D 200623 19:54:42 __init__:614] uiautomator-v2 is starting ... left: 35.9s
> Traceback (most recent call last):
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 438, in _jsonrpc_retry_call
>     return self._jsonrpc_call(*args, **kwargs)
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 475, in _jsonrpc_call
>     (time.time() - request_start))
> uiautomator2.exceptions.GatewayError: uiautomator2.GatewayError(gateway error, time used 0.0s)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/xpath.py", line 546, in click
>     el = self.get(timeout=timeout)
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/xpath.py", line 474, in get
>     if not self.wait(timeout or self._global_timeout):
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/xpath.py", line 510, in wait
>     if self.exists:
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/xpath.py", line 459, in exists
>     return len(self.all()) > 0
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/xpath.py", line 410, in all
>     xml_content = source or self._source or self._parent.dump_hierarchy()
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/xpath.py", line 176, in dump_hierarchy
>     self._last_source = self._d.dump_hierarchy()
>   File "<decorator-gen-12>", line 2, in dump_hierarchy
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
>     logger)
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
>     return f()
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 883, in dump_hierarchy
>     content = self.jsonrpc.dumpWindowHierarchy(compressed, None)
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages//__init__.py", line 432, in __call__
>     http_timeout)
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 442, in _jsonrpc_retry_call
>     self.reset_uiautomator(str(e)) # uiautomator可能出问题了，强制重启一下
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 586, in reset_uiautomator
>     depth=depth + 1)
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 586, in reset_uiautomator
>     depth=depth + 1)
>   File "/Users//Projects/playground/atxserver2-android-provider/venv/lib/python3.6/site-packages/uiautomator2/__init__.py", line 563, in reset_uiautomator
>     "adb shell am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner",
> OSError: [Errno Uiautomator started failed.] uiautomator2.GatewayError(gateway error, time used 0.0s): 'https://github.com/openatx/uiautomator2/wiki/Common-issues'
> ```

I have the same error, how did you solve it?
