### ISSUE TITLE
watcher使用报错

### ISSUE THREAD

**Issue by Hello-Linux** [openatx/uiautomator2#567]
/root/PycharmProjects/phone/venv/bin/python /root/PycharmProjects/phone/control.py
```
Exception in thread watcher:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PycharmProjects/phone/venv/lib/python3.7/site-packages/uiautomator2/watcher.py", line 93, in _watch_forever
    triggered = self.run()
  File "/root/PycharmProjects/phone/venv/lib/python3.7/site-packages/uiautomator2/watcher.py", line 105, in run
    return self._run_watchers(source=source)
  File "/root/PycharmProjects/phone/venv/lib/python3.7/site-packages/uiautomator2/watcher.py", line 118, in _run_watchers
    if not last_selector.exists:
  File "/root/PycharmProjects/phone/venv/lib/python3.7/site-packages/uiautomator2/xpath.py", line 459, in exists
    return len(self.all()) > 0
  File "/root/PycharmProjects/phone/venv/lib/python3.7/site-packages/uiautomator2/xpath.py", line 425, in all
    root = etree.fromstring(str2bytes(xml_content))
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 259
lxml.etree.XMLSyntaxError: Excessive depth in document: 256 use XML_PARSE_HUGE option, line 259, column 515
```

**Comment by yaming116** [comment]
请提供详细一些信息

**Comment by Hello-Linux** [comment]
报错只有这些了，在哪里还能看更详细的？

**Comment by yaming116** [comment]
自己的demo代码和页面结构
