### ISSUE TITLE
为什么toast.show()不能使用，toast.get_message()正常使用

### ISSUE THREAD

**Issue by power76** [openatx/uiautomator2#586]
调用toast.show()完全没反应，但toast.get_message()可正常截获toast!

- 手机型号
Nubia Z11, android 9.0, nubia UI 7.0
- uiautomator2的版本号(`pip show uiautomator2`)
2.11.2
- 手机截图
- 相关日志
- 最好能附上可能复现问题的代码。
    d.toast.show("Hello world")
    message = d.toast.get_message()
    print(message)

**Comment by Brioal** [comment]
我也是一样不能显示toast

**Comment by YaoLiMuMu** [comment]
我的也是, d.toast.show("Hello world", 10.0), 手机界面什么东西都没有.
手机型号: oneplus 5T
设备系统: android 9
uiautomator2版本: 2.16.13

**Comment by Hiraly-wang** [comment]
我也是，报错了
`F:\code\U2AppTest\venv\Scripts\python.exe F:\code\U2AppTest\u2_app_test\page\acct_list.py 
[D 231109 14:42:03 __init__:661] [pid:37108] [emulator-5554] kill process(ps): uiautomator
Traceback (most recent call last):
  File "F:\code\U2AppTest\venv\lib\site-packages\uiautomator2\__init__.py", line 486, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "F:\code\U2AppTest\venv\lib\site-packages\uiautomator2\__init__.py", line 519, in _jsonrpc_call
    raise GatewayError(
uiautomator2.exceptions.GatewayError: (<Response [502]>, 'gateway error, time used 0.0s')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\code\U2AppTest\u2_app_test\page\acct_list.py", line 385, in <module>
    message = d.toast.get_message()
  File "F:\code\U2AppTest\venv\lib\site-packages\uiautomator2\__init__.py", line 1287, in get_message
    message = obj.jsonrpc.getLastToast(cache_timeout * 1000)
  File "F:\code\U2AppTest\venv\lib\site-packages\uiautomator2\__init__.py", line 479, in __call__
    return self.server._jsonrpc_retry_call(self.method, params,
  File "F:\code\U2AppTest\venv\lib\site-packages\uiautomator2\__init__.py", line 488, in _jsonrpc_retry_call
    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下
  File "F:\code\U2AppTest\venv\lib\site-packages\uiautomator2\__init__.py", line 640, in reset_uiautomator
    ok = self._force_reset_uiautomator_v2(
  File "F:\code\U2AppTest\venv\lib\site-packages\uiautomator2\__init__.py", line 667, in _force_reset_uiautomator_v2
    if self._is_apk_required():
  File "F:\code\U2AppTest\venv\lib\site-packages\uiautomator2\__init__.py", line 711, in _is_apk_required
    if self._package_version("com.github.uiautomator.test") is None:
  File "F:\code\U2AppTest\venv\lib\site-packages\uiautomator2\__init__.py", line 735, in _package_version
    return packaging.version.parse(m.group('name') if m else "")
  File "F:\code\U2AppTest\venv\lib\site-packages\packaging\version.py", line 52, in parse
    return Version(version)
  File "F:\code\U2AppTest\venv\lib\site-packages\packaging\version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''

Process finished with exit code 1
`

**Comment by codeskyblue** [comment]
toast show 的最新版已经移除。不再提供支持
