### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by jiajiajiajiajiajiajiajia** [openatx/uiautomator2#6]
Hi , 
I download this uiautomator2-master.zip and install it in windows7, but I meet an error by using "pip install -e .":
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "d:\uiautomator\uiautomator2\.eggs\pbr-3.1.1-py2.7.egg\pbr\core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "d:\uiautomator\uiautomator2\.eggs\pbr-3.1.1-py2.7.egg\pbr\util.py", line 249, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "d:\uiautomator\uiautomator2\.eggs\pbr-3.1.1-py2.7.egg\pbr\hooks\__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "d:\uiautomator\uiautomator2\.eggs\pbr-3.1.1-py2.7.egg\pbr\hooks\base.py", line 27, in run
        self.hook()
      File "d:\uiautomator\uiautomator2\.eggs\pbr-3.1.1-py2.7.egg\pbr\hooks\metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "d:\uiautomator\uiautomator2\.eggs\pbr-3.1.1-py2.7.egg\pbr\packaging.py", line 755, in get_version
        name=package_name))
    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's a
e that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project
mator2 was given, but was not able to be found.
    error in setup command: Error parsing D:\Uiautomator\uiautomator2\setup.cfg: Exception: Versioning for this project requ
 an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package
up.cfg and the argument given to pbr.version.VersionInfo. Project name uiautomator2 was given, but was not able to be found.

How I can resolve it ? thanks~

**Comment by codeskyblue** [comment]
使用git clone下代码，不要直接点击网页上的下载

**Comment by wogenhaosini** [comment]
env : 
Python 2.7.10 
pip 18.1 from /Library/Python/2.7/site-packages/pip (python 2.7)

git clone 下来运行 ` pip install -e uiautomator2`

`Command "python setup.py egg_info" failed with error code 1 in /Users/bin/Downloads/uiautomator2/`

 这种怎么办，求解。
