### ISSUE TITLE
用电脑连接手机和手机上直接连都有问题，只能偶尔连接上去。

### ISSUE THREAD

**Issue by swanv** [openatx/uiautomator2#60]
好像是手机上服务器有问题，但agent已经打开了呀

/data/user/0/org.qpython.qpy/files/bin/qpython3-android5.sh "/storage/emulated/0/qpython/scripts3/demo.py" && exit
0/qpython/scripts3/demo.py" && exit      <
This is console module
Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection    raise err
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/data/user/0/org.qpython.qpy/files/lib/python36.zip/http/client.py", line 1239, in request
  File "/data/user/0/org.qpython.qpy/files/lib/python36.zip/http/client.py", line 1285, in _send_request
  File "/data/user/0/org.qpython.qpy/files/lib/python36.zip/http/client.py", line 1234, in endheaders
  File "/data/user/0/org.qpython.qpy/files/lib/python36.zip/http/client.py", line 1026, in _send_output
  File "/data/user/0/org.qpython.qpy/files/lib/python36.zip/http/client.py", line 964, in send
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xe9344d70>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=7912): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xe9344d70>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/emulated/0/qpython/scripts3/demo.py", line 12, in <module>
    r = requests.get(url)
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/data/user/0/org.qpython.qpy/files/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=7912): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xe9344d70>: Failed to establish a new connection: [Errno 111] Connection refused',))
1|heroqltechn:/ $

**Comment by codeskyblue** [comment]
Ip应该写 127.0.0.1

**Comment by swanv** [comment]
都尝试过了，包括局域网地址

raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=7912): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xef744950>: Failed to establish a new connection: [Errno 111] Connection refused',))

我的手机是三星s7 系统是android 7.0

**Comment by codeskyblue** [comment]
你代码怎么写的

**Comment by codeskyblue** [comment]
暂时关掉了，有问题再Reopen
