### ISSUE TITLE
left(),right(),down(),up()性能问题

### ISSUE THREAD

**Issue by 350050183** [openatx/uiautomator2#623]
left(),right(),down(),up()性能是不是有问题？要分析比较久才有结果。

**Comment by codeskyblue** [comment]
是的，性能非常差 在2020年11月26日 16:17，swingcoder 写道： 

left(),right(),down(),up()性能是不是有问题？要分析比较久才有结果。



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/openatx/uiautomator2/issues/623",

"url": "https://github.com/openatx/uiautomator2/issues/623",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by AnyiAi** [comment]
使用left(),right(),down(),up()方法报错，频率比较高
Traceback (most recent call last):

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()

  File "/opt/auth_test/tel_test/pzdf_tc/pzdf_oriental_vision/test_oriental_vieion_setting.py", line 4471, in test_seven_meeting_five_split
    self.assert_mcp_place_out(self.convoke_d, self.participantA_number)

  File "/opt/auth_test/tel_test/pzdf_tc/pzdf_oriental_vision/oriental_vision_base.py", line 848, in assert_mcp_place_out
    pr = self.exists_mcp_participants_place_out(d, name)

  File "/opt/auth_test/tel_test/pzdf_tc/pzdf_oriental_vision/oriental_vision_base.py", line 738, in exists_mcp_participants_place_out
    right(resourceId="com.android.pzPhone:id/btn_metting_mcu_activity_item_kicking", text="请出").exists()

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uiautomator2/_selector.py", line 461, in right
    return self.__view_beside(onrightof, **kwargs)

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uiautomator2/_selector.py", line 487, in __view_beside
    for ui in UiObject(self.session, Selector(**kwargs)):

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uiautomator2/_selector.py", line 439, in __iter__
    obj, length = self, self.count

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uiautomator2/_selector.py", line 433, in count
    return self.jsonrpc.count(self.selector)

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uiautomator2/__init__.py", line 436, in __call__
    http_timeout)

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uiautomator2/__init__.py", line 442, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uiautomator2/__init__.py", line 514, in _jsonrpc_call
    raise err

uiautomator2.exceptions.JSONRPCError: -32001 Jsonrpc error: <java.lang.StackOverflowError> data: java.lang.StackOverflowError: stack size 1041KB
	at java.util.ArrayList.<init>(ArrayList.java:190)
	at android.view.accessibility.AccessibilityNodeInfo.init(AccessibilityNodeInfo.java:3457)
	at android.view.accessibility.AccessibilityNodeInfo.obtain(AccessibilityNodeInfo.java:3143)
	at android.view.accessibility.AccessibilityCache.getNode(AccessibilityCache.java:228)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:325)
	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:976)
	at android.support.test.uiautomator.QueryController.findNodeRegularRecursive(QueryController.java:338)
	at android.support.test.uiautomator.QueryController.findNodeRegularRecursive(QueryController.java:354)
	at android.support.test.uiautomator.QueryController.findNodeRegularRecursive(QueryController.java:354)
	at android.support.test.uiautomator.QueryController.findNodeRegularRecursive(QueryController.java:354)
	at android.support.test.uiautomator.QueryController.findNodeRegularRecursive(QueryController.java:354)
	at android.support.test.uiautomator.QueryController.findNodeRegularRecursive(QueryController.java:354)
	at android.support.test.uiautomator.QueryController.findNodeRegularRecursive(QueryController.java:354)
	at android.support.test.uiautomator.QueryController.findNodeRegularRecursive(QueryController.java:354)
