### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by ChaseWindWu** [openatx/uiautomator2#630]
使用”for view in d(text="Add new")“时报错

File "/opt/auth_test/tel_test/base_operation.py", line 67, in get_instance
    for i in range(0, len(ele_list)):

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uiautomator2/_selector.py", line 436, in __len__
    return self.count

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uiautomator2/_selector.py", line 433, in count
    return self.jsonrpc.count(self.selector)

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uiautomator2/__init__.py", line 436, in __call__
    http_timeout)

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uiautomator2/__init__.py", line 442, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)

  File "/root/.pyenv/versions/3.7.2/lib/python3.7/site-packages/uiautomator2/__init__.py", line 514, in _jsonrpc_call
    raise err
uiautomator2.exceptions.JSONRPCError: -32001 Jsonrpc error: <java.lang.StackOverflowError> data: java.lang.StackOverflowError: stack size 1041KB
	at java.util.AbstractList.<init>(AbstractList.java:76)
	at java.util.ArrayList.<init>(ArrayList.java:190)
	at android.view.accessibility.AccessibilityNodeInfo.init(AccessibilityNodeInfo.java:3457)
	at android.view.accessibility.AccessibilityNodeInfo.obtain(AccessibilityNodeInfo.java:3143)
	at android.view.accessibility.AccessibilityCache.getNode(AccessibilityCache.java:228)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:325)
	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:976)
	at android.support.test.uiautomator.QueryController.findNodeRegularRecursive(QueryController.java:338)
	at android.support.test.uiautomator.QueryController.findNodeRegularRecursive(QueryController.java:354)
	at android.support.test.uiautomator.QueryController.findNodeRegularRecursive(QueryController.java:354)
	at android.support.test.uiautomator.QueryController.findNodeRegularRecursive(QueryController.java:354)
	at android.support.test.uiautomator.QueryController.findNodeRegularRecursive(QueryController.java:354)

**Comment by codeskyblue** [comment]
底层框架已升级
