### ISSUE TITLE
init 时 报错不能连接 http://127.0.0.1:43667/version

### ISSUE THREAD

**Issue by jlff** [openatx/uiautomator2#631]
- 手机型号
- uiautomator2的版本号(`pip show uiautomator2`)
Name: uiautomator2
Version: 2.12.1
Summary: Python Wrapper for Google Android UiAutomator2 test tool
Home-page: https://github.com/openatx/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location:Requires: requests, Pillow, adbutils, packaging, whichcraft, Deprecated, lxml, retry, progress, six, cached-property, logzero
Required-by: weditor

- 手机截图
- 相关日志
uiautomator2 init
[I 201221 18:15:12 init:155] uiautomator2 version: 2.12.1
[I 201221 18:15:12 init:352] Install minicap, minitouch
[[D 201221 18:15:12 init:250] apk-debug package-info: {'version_name': '2.3.1', 'version_code': '2003001', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2020, 12, 17, 14, 49, 24), 'last_update_time': datetime.datetime(2020, 12, 17, 14, 49, 24), 'signature': '8376b3fb], past signatures:['}
[D 201221 18:15:12 init:251] apk-debug-test package-info: {'version_name': '', 'version_code': '', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2020, 12, 17, 14, 49, 24), 'last_update_time': datetime.datetime(2020, 12, 17, 14, 49, 24), 'signature': '8376b3fb], past signatures:['}
[I 201221 18:15:12 init:370] Already installed com.github.uiautomator apks
[D 201221 18:15:12 init:291] Real version: [0, 9, 5], Expect version: [0, 9, 5]
[D 201221 18:15:12 init:162] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d')
[I 201221 18:15:12 init:377] Check atx-agent version
[D 201221 18:15:12 init:390] Forward: local:tcp:43667 -> remote:tcp:7912
[D 201221 18:15:12 init:393] atx-agent version <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
    <html><head>
    <meta type="copyright" content="Copyright (C) 1996-2016 The Squid Software Foundation and contributors">
    <meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8">
    <title>ERROR: The requested URL could not be retrieved</title>
    <style type="text/css"></style>
    </head><body id=ERR_CONNECT_FAIL>
    <div id="titles">
    <h1>ERROR</h1>
    <h2>The requested URL could not be retrieved</h2>
    </div>
    <hr>
    
    <div id="content">
    <p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:43667/version">http://127.0.0.1:43667/version</a></p>
    
    <blockquote id="error">
    <p><b>Connection to 127.0.0.1 failed.</b></p>
    </blockquote>
    
    <p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>
    
    <p>The remote host or network may be down. Please try the request again.</p>
    
 
    
    <br>
    </div>
    
    <hr>
    <div id="footer">
    <p>Generated Mon, 21 Dec 2020 10:15:12 GMT by p-bj-squid-01 (squid/3.5.20)</p>
    
    </div>
    </body></html>
Successfully init AdbDevice(serial=1234567)

- 最好能附上可能复现问题的代码。

**Comment by jlff** [comment]
<style type="text/css"></style>
    </head><body id=ERR_CONNECT_FAIL>
    <div id="titles">
    <h1>ERROR</h1>
    <h2>The requested URL could not be retrieved</h2>
    </div>
    <hr>
    
    <div id="content">
    <p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:43667/version">http://127.0.0.1:43667/version</a></p>
    
    <blockquote id="error">
    <p><b>Connection to 127.0.0.1 failed.</b></p>
    </blockquote>
    
    <p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>
    
    <p>The remote host or network may be down. Please try the request again.</p>
    
    <p>Your cache administrator is <a href="mailto:help@nio.com?subject=CacheErrorInfo%20-%20ERR_CONNECT_FAIL&amp;body=CacheHost%3A%20p-bj-squid-01%0D%0AErrPage%3A%20ERR_CONNECT_FAIL%0D%0AErr%3A%20(111)%20Connection%20refused%0D%0ATimeStamp%3A%20Mon,%2021%20Dec%202020%2010%3A15%3A12%20GMT%0D%0A%0D%0AClientIP%3A%2010.111.154.176%0D%0AServerIP%3A%20127.0.0.1%0D%0A%0D%0AHTTP%20Request%3A%0D%0AGET%20%2Fversion%20HTTP%2F1.1%0AUser-Agent%3A%20python-requests%2F2.23.0%0D%0AAccept-Encoding%3A%20gzip,%20deflate%0D%0AAccept%3A%20*%2F*%0D%0AConnection%3A%20keep-alive%0D%0AHost%3A%20127.0.0.1%3A43667%0D%0A%0D%0A%0D%0A">help@nio.com</a>.</p>
    
    <br>
    </div>
    
    <hr>
    <div id="footer">
    <p>Generated Mon, 21 Dec 2020 10:15:12 GMT by p-bj-squid-01 (squid/3.5.20)</p>
    
    </div>

**Comment by jlff** [comment]
>>> d.info
18:31:48.787 $ curl -X POST -d '{"jsonrpc": "2.0", "id": "8148b3488eb10ab1001fc93fddcd99eb", "method": "deviceInfo", "params": {}}' 'http://127.0.0.1:42785/jsonrpc/0'
18:31:48.802 Response (14 ms) >>>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2016 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"></style>
</head><body id=ERR_CONNECT_FAIL>
<div id="titles">
<h1>ERROR</h1>
<h2>The requested URL could not be retrieved</h2>
</div>
<hr>

<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:42785/jsonrpc/0">http://127.0.0.1:42785/jsonrpc/0</a></p>

<blockquote id="error">
<p><b>Connection to 127.0.0.1 failed.</b></p>
</blockquote>

<p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>

<p>The remote host or network may be down. Please try the request again.</p>

<p>Your cache administrator is <a href="mailto:help@nio.com?subject=CacheErrorInfo%20-%20ERR_CONNECT_FAIL&amp;body=CacheHost%3A%20p-bj-squid-02%0D%0AErrPage%3A%20ERR_CONNECT_FAIL%0D%0AErr%3A%20(111)%20Connection%20refused%0D%0ATimeStamp%3A%20Mon,%2021%20Dec%202020%2010%3A31%3A48%20GMT%0D%0A%0D%0AClientIP%3A%2010.111.154.176%0D%0AServerIP%3A%20127.0.0.1%0D%0A%0D%0AHTTP%20Request%3A%0D%0APOST%20%2Fjsonrpc%2F0%20HTTP%2F1.1%0AUser-Agent%3A%20python-requests%2F2.23.0%0D%0AAccept-Encoding%3A%20gzip,%20deflate%0D%0AAccept%3A%20*%2F*%0D%0AConnection%3A%20keep-alive%0D%0AContent-Type%3A%20application%2Fjson%0D%0AContent-Length%3A%2098%0D%0AHost%3A%20127.0.0.1%3A42785%0D%0A%0D%0A%0D%0A">help@nio.com</a>.</p>

<br>
</div>

<hr>
<div id="footer">
<p>Generated Mon, 21 Dec 2020 10:31:48 GMT by p-bj-squid-02 (squid/3.5.20)</p>

</div>
</body></html>
<<< END
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nio/.miniconda2/envs/sanity/lib/python3.6/site-packages/uiautomator2/__init__.py", line 404, in info
    return self.jsonrpc.deviceInfo(http_timeout=10)
  File "/home/nio/.miniconda2/envs/sanity/lib/python3.6/site-packages/uiautomator2/__init__.py", line 436, in __call__
    http_timeout)
  File "/home/nio/.miniconda2/envs/sanity/lib/python3.6/site-packages/uiautomator2/__init__.py", line 442, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/home/nio/.miniconda2/envs/sanity/lib/python3.6/site-packages/uiautomator2/__init__.py", line 484, in _jsonrpc_call
    "HTTP Return code is not 200", res.text)
uiautomator2.exceptions.BaseError: ('{"jsonrpc": "2.0", "id": "8148b3488eb10ab1001fc93fddcd99eb", "method": "deviceInfo", "params": {}}', 503, '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html><head>\n<meta type="copyright" content="Copyright (C) 1996-2016 The Squid Software Foundation and contributors">\n<meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8">\n<title>ERROR: The requested URL could not be retrieved</title>\n<style type="text/css"></style>\n</head><body id=ERR_CONNECT_FAIL>\n<div id="titles">\n<h1>ERROR</h1>\n<h2>The requested URL could not be retrieved</h2>\n</div>\n<hr>\n\n<div id="content">\n<p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:42785/jsonrpc/0">http://127.0.0.1:42785/jsonrpc/0</a></p>\n\n<blockquote id="error">\n<p><b>Connection to 127.0.0.1 failed.</b></p>\n</blockquote>\n\n<p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>\n\n<p>The remote host or network may be down. Please try the request again.</p>\n\n<p>Your cache administrator is <a href="mailto:help@nio.com?subject=CacheErrorInfo%20-%20ERR_CONNECT_FAIL&amp;body=CacheHost%3A%20p-bj-squid-02%0D%0AErrPage%3A%20ERR_CONNECT_FAIL%0D%0AErr%3A%20(111)%20Connection%20refused%0D%0ATimeStamp%3A%20Mon,%2021%20Dec%202020%2010%3A31%3A48%20GMT%0D%0A%0D%0AClientIP%3A%2010.111.154.176%0D%0AServerIP%3A%20127.0.0.1%0D%0A%0D%0AHTTP%20Request%3A%0D%0APOST%20%2Fjsonrpc%2F0%20HTTP%2F1.1%0AUser-Agent%3A%20python-requests%2F2.23.0%0D%0AAccept-Encoding%3A%20gzip,%20deflate%0D%0AAccept%3A%20*%2F*%0D%0AConnection%3A%20keep-alive%0D%0AContent-Type%3A%20application%2Fjson%0D%0AContent-Length%3A%2098%0D%0AHost%3A%20127.0.0.1%3A42785%0D%0A%0D%0A%0D%0A">help@nio.com</a>.</p>\n\n<br>\n</div>\n\n<hr>\n<div id="footer">\n<p>Generated Mon, 21 Dec 2020 10:31:48 GMT by p-bj-squid-02 (squid/3.5.20)</p>\n\n</div>\n</body></html>\n', 'HTTP Return code is not 200', '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html><head>\n<meta type="copyright" content="Copyright (C) 1996-2016 The Squid Software Foundation and contributors">\n<meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8">\n<title>ERROR: The requested URL could not be retrieved</title>\n<style type="text/css"></style>\n</head><body id=ERR_CONNECT_FAIL>\n<div id="titles">\n<h1>ERROR</h1>\n<h2>The requested URL could not be retrieved</h2>\n</div>\n<hr>\n\n<div id="content">\n<p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:42785/jsonrpc/0">http://127.0.0.1:42785/jsonrpc/0</a></p>\n\n<blockquote id="error">\n<p><b>Connection to 127.0.0.1 failed.</b></p>\n</blockquote>\n\n<p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>\n\n<p>The remote host or network may be down. Please try the request again.</p>\n\n<p>Your cache administrator is <a href="mailto:help@nio.com?subject=CacheErrorInfo%20-%20ERR_CONNECT_FAIL&amp;body=CacheHost%3A%20p-bj-squid-02%0D%0AErrPage%3A%20ERR_CONNECT_FAIL%0D%0AErr%3A%20(111)%20Connection%20refused%0D%0ATimeStamp%3A%20Mon,%2021%20Dec%202020%2010%3A31%3A48%20GMT%0D%0A%0D%0AClientIP%3A%2010.111.154.176%0D%0AServerIP%3A%20127.0.0.1%0D%0A%0D%0AHTTP%20Request%3A%0D%0APOST%20%2Fjsonrpc%2F0%20HTTP%2F1.1%0AUser-Agent%3A%20python-requests%2F2.23.0%0D%0AAccept-Encoding%3A%20gzip,%20deflate%0D%0AAccept%3A%20*%2F*%0D%0AConnection%3A%20keep-alive%0D%0AContent-Type%3A%20application%2Fjson%0D%0AContent-Length%3A%2098%0D%0AHost%3A%20127.0.0.1%3A42785%0D%0A%0D%0A%0D%0A">help@nio.com</a>.</p>\n\n<br>\n</div>\n\n<hr>\n<div id="footer">\n<p>Generated Mon, 21 Dec 2020 10:31:48 GMT by p-bj-squid-02 (squid/3.5.20)</p>\n\n</div>\n</body></html>\n')

**Comment by jlff** [comment]
adb shell 进android  , 从7912端口是可以得到的， 问题在 adb Forward: local:tcp:43667 -> remote:tcp:7912
# curl http://127.0.0.1:7912/version                                                                                                                                                        
0.6.0

**Comment by jlff** [comment]
我这台机器 curl 127.0.0.1:44495/version 报错连不上
在浏览器里输入127.0.0.1:44495/version 可以连上

**Comment by jlff** [comment]
原来是设置了代理服务器导致 127.0.0.1 访问报错。在.bashrc 里将代理服务器的变量注释掉就好了。
