### ISSUE TITLE
d.info 报错 503 http://127.0.0.1:42785/jsonrpc/0

### ISSUE THREAD

**Issue by jlff** [openatx/uiautomator2#632]
**看完请删掉该内容**

*提Bug需要注意的事项*

请务必提供详细的信息，能够复现你的问题，否则很难帮你解决。没用的Issue会被打上`Invalid`标签。

- 手机型号
- uiautomator2的版本号(`pip show uiautomator2`)
pip show uiautomator2
Name: uiautomator2
Version: 2.12.1
Summary: Python Wrapper for Google Android UiAutomator2 test tool
Home-page: https://github.com/openatx/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location:
Requires: retry, lxml, Deprecated, adbutils, packaging, cached-property, requests, progress, Pillow, whichcraft, six, logzero
Required-by: weditor

- 手机截图
- 相关日志
- >>> d.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nio/.miniconda2/envs/sanity/lib/python3.6/site-packages/uiautomator2/__init__.py", line 404, in info
    return self.jsonrpc.deviceInfo(http_timeout=10)
  File "/home/nio/.miniconda2/envs/sanity/lib/python3.6/site-packages/uiautomator2/__init__.py", line 436, in __call__
    http_timeout)
  File "/home/nio/.miniconda2/envs/sanity/lib/python3.6/site-packages/uiautomator2/__init__.py", line 442, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/home/nio/.miniconda2/envs/sanity/lib/python3.6/site-packages/uiautomator2/__init__.py", line 484, in _jsonrpc_call
    "HTTP Return code is not 200", res.text)
uiautomator2.exceptions.BaseError: ('{"jsonrpc": "2.0", "id": "86de3c1b1c41dec46514d06c3c42b5e4", "method": "deviceInfo", "params": {}}', 503, '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<h-tml><head>\n<meta type="copyright" content="Copyright (C) 1996-2016 The Squid Software Foundation and contributors">\n<meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8">\n<title>ERROR: The requested URL could not be retrieved</title>\n<style type="text/css"></style>\n</head><body id=ERR_CONNECT_FAIL>\n<div id="titles">\n<h1>ERROR</h1>\n<h2>The requested URL could not be retrieved</h2>\n</div>\n<hr>\n\n<div id="content">\n<p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:42785/jsonrpc/0">http://127.0.0.1:42785/jsonrpc/0</a></p>\n\n<blockquote id="error">\n<p><b>Connection to 127.0.0.1 failed.</b></p>\n</blockquote>\n\n<p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>\n\np>Generated Mon, 21 Dec 2020 10:40:31 GMT by p-bj-squid-01 (squid/3.5.20)</p>\n\n</div>\n</body></html>\n', 'HTTP Return code is not 200', '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html><head>\n<meta type="copyright" content="Copyright (C) 1996-2016 The Squid Software Foundation and contributors">\n<meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8">\n<title>ERROR: The requested URL could not be retrieved</title>\n<style type="text/css"></style>\n</head><body id=ERR_CONNECT_FAIL>\n<div id="titles">\n<h1>ERROR</h1>\n<h2>The requested URL could not be retrieved</h2>\n</div>\n<hr>\n\n<div id="content">\n<p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:42785/jsonrpc/0">http://127.0.0.1:42785/jsonrpc/0</a></p>\n\n<blockquote id="error">\n\n</div>\n</body></html>\n')

- 最好能附上可能复现问题的代码。

**Comment by jlff** [comment]
原来是设置了代理服务器导致 127.0.0.1 访问报错。在.bashrc 里将代理服务器的变量注释掉就好了。
