### ISSUE TITLE
FastInputIME started failed

### ISSUE THREAD

**Issue by qugo9955** [openatx/uiautomator2#640]
手机之前是正常的，后面把项目中的atx-agent卸载了，单独安装了git上atx-agent项目中的安装包，就出现这个问题

Traceback (most recent call last):
  File "E:\PyWorkSpace\wu-apptest\Public\Decorator.py", line 69, in wrapper
    ret = func(*args, **kwargs)
  File "E:\PyWorkSpace\wu-apptest\PageObject\YouZuYun\houseManage.py", line 36, in search
    self.d.send_action('search')
  File "D:\Python36\lib\site-packages\uiautomator2\__init__.py", line 1636, in send_action
    self.wait_fastinput_ime()
  File "D:\Python36\lib\site-packages\uiautomator2\__init__.py", line 1685, in wait_fastinput_ime
    raise EnvironmentError("FastInputIME started failed")
OSError: FastInputIME started failed

**Comment by qugo9955** [comment]
重复提了
