### ISSUE TITLE
ATX Agent crashes after d.toast.show

### ISSUE THREAD

**Issue by thlengane** [openatx/uiautomator2#647]
Bug
ATX Agent crashes every time I execute d.toast.show("Hello world", 1.0).

Details:
See the execution and how many times the process restarts. Other commands works well without crashing the Agent

- Phone model: Samsung Galaxy A50, SM-A505F/DS
- uiautomator2: Version: 2.12.1
- Code and Logs
                >>> d.toast.show("Hello world", 1.0)
                [D 210118 16:02:59 __init__:600] kill process(ps): uiautomator
                [D 210118 16:03:01 __init__:619] uiautomator-v2 is starting ... left: 40.0s
                [D 210118 16:03:02 __init__:619] uiautomator-v2 is starting ... left: 39.0s
                [D 210118 16:03:03 __init__:619] uiautomator-v2 is starting ... left: 38.0s
                [D 210118 16:03:04 __init__:619] uiautomator-v2 is starting ... left: 36.9s
                [D 210118 16:03:05 __init__:619] uiautomator-v2 is starting ... left: 35.9s
                [D 210118 16:03:06 __init__:619] uiautomator-v2 is starting ... left: 34.9s
                [D 210118 16:03:07 __init__:619] uiautomator-v2 is starting ... left: 33.9s
                [I 210118 16:03:07 __init__:583] uiautomator back to normal
                True
                >>> d.toast.show("Hello world", 1.0)
                [W 210118 16:32:52 __init__:203] atx-agent has something wrong, auto recovering
                [D 210118 16:32:52 __init__:287] device R58M70675WB is online
                [I 210118 16:32:53 init:155] uiautomator2 version: 2.12.1
                [D 210118 16:32:54 __init__:600] kill process(ps): uiautomator
                [D 210118 16:32:55 __init__:619] uiautomator-v2 is starting ... left: 40.0s
                [D 210118 16:32:56 __init__:619] uiautomator-v2 is starting ... left: 39.0s
                [D 210118 16:32:57 __init__:619] uiautomator-v2 is starting ... left: 38.0s
                [I 210118 16:32:57 __init__:583] uiautomator back to normal
                True
                >>> d.toast.show("Hello world", 1.0)
                [D 210118 16:32:59 __init__:600] kill process(ps): uiautomator
                [D 210118 16:33:00 __init__:619] uiautomator-v2 is starting ... left: 40.0s
                [D 210118 16:33:01 __init__:619] uiautomator-v2 is starting ... left: 39.0s
                [D 210118 16:33:02 __init__:619] uiautomator-v2 is starting ... left: 38.0s
                [I 210118 16:33:02 __init__:583] uiautomator back to normal
                True
                >>> d.toast.show("Hello world", 1.0)
                True
                >>> d.toast.show("Hello world", 1.0)
                [D 210118 16:33:08 __init__:600] kill process(ps): uiautomator
                [D 210118 16:33:09 __init__:619] uiautomator-v2 is starting ... left: 40.0s
                [D 210118 16:33:10 __init__:619] uiautomator-v2 is starting ... left: 39.0s
                [D 210118 16:33:11 __init__:619] uiautomator-v2 is starting ... left: 38.0s
                [I 210118 16:33:11 __init__:583] uiautomator back to normal

**Comment by mingyuan-xia** [comment]
need `adb logcat` logs at the crash moment

**Comment by thlengane** [comment]
> need `adb logcat` logs at the crash moment

[logcat.zip](https://github.com/openatx/uiautomator2/files/6647498/logcat.zip)

Here is the logcat attached.

**Comment by mingyuan-xia** [comment]
Related crash: need more checks at https://github.com/openatx/android-uiautomator-server/blob/master/app/src/main/java/com/github/uiautomator/ToastHelper.java#L54
Thanks for reporting
```
06-14 11:51:41.028 30021 30021 D AndroidRuntime: Shutting down VM
06-14 11:51:41.031 30021 30021 E AndroidRuntime: FATAL EXCEPTION: main
06-14 11:51:41.031 30021 30021 E AndroidRuntime: Process: com.github.uiautomator, PID: 30021
06-14 11:51:41.031 30021 30021 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
06-14 11:51:41.031 30021 30021 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1457)
06-14 11:51:41.031 30021 30021 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:469)
06-14 11:51:41.031 30021 30021 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:114)
06-14 11:51:41.031 30021 30021 E AndroidRuntime: 	at com.github.uiautomator.ToastHelper.show(ToastHelper.java:54)
06-14 11:51:41.031 30021 30021 E AndroidRuntime: 	at com.github.uiautomator.stub.AutomatorServiceImpl$3.run(AutomatorServiceImpl.java:170)
06-14 11:51:41.031 30021 30021 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
06-14 11:51:41.031 30021 30021 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-14 11:51:41.031 30021 30021 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
06-14 11:51:41.031 30021 30021 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8506)
06-14 11:51:41.031 30021 30021 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-14 11:51:41.031 30021 30021 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
06-14 11:51:41.031 30021 30021 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
06-14 11:51:41.048 30021 30021 E MonitoringInstr: Exception encountered by: Thread[main,5,main]. Dumping thread state to outputs and pining for the fjords.
06-14 11:51:41.048 30021 30021 E MonitoringInstr: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
06-14 11:51:41.048 30021 30021 E MonitoringInstr: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1457)
06-14 11:51:41.048 30021 30021 E MonitoringInstr: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:469)
06-14 11:51:41.048 30021 30021 E MonitoringInstr: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:114)
06-14 11:51:41.048 30021 30021 E MonitoringInstr: 	at com.github.uiautomator.ToastHelper.show(ToastHelper.java:54)
06-14 11:51:41.048 30021 30021 E MonitoringInstr: 	at com.github.uiautomator.stub.AutomatorServiceImpl$3.run(AutomatorServiceImpl.java:170)
06-14 11:51:41.048 30021 30021 E MonitoringInstr: 	at android.os.Handler.handleCallback(Handler.java:938)
06-14 11:51:41.048 30021 30021 E MonitoringInstr: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-14 11:51:41.048 30021 30021 E MonitoringInstr: 	at android.os.Looper.loop(Looper.java:246)
06-14 11:51:41.048 30021 30021 E MonitoringInstr: 	at android.app.ActivityThread.main(ActivityThread.java:8506)
06-14 11:51:41.048 30021 30021 E MonitoringInstr: 	at java.lang.reflect.Method.invoke(Native Method)
06-14 11:51:41.048 30021 30021 E MonitoringInstr: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
06-14 11:51:41.048 30021 30021 E MonitoringInstr: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:   Thread[InstrumentationConnectionThread,5,main]
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     android.os.MessageQueue.nativePollOnce(Native Method)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     android.os.MessageQueue.next(MessageQueue.java:335)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     android.os.Looper.loop(Looper.java:206)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     android.os.HandlerThread.run(HandlerThread.java:67)
06-14 11:51:41.062 30021 30021 E THREAD_STATE: 
06-14 11:51:41.062 30021 30021 E THREAD_STATE:   Thread[Timer-0,5,main]
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.lang.Object.wait(Native Method)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.lang.Object.wait(Object.java:442)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.lang.Object.wait(Object.java:568)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.util.TimerThread.mainLoop(Timer.java:533)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.util.TimerThread.run(Timer.java:512)
06-14 11:51:41.062 30021 30021 E THREAD_STATE: 
06-14 11:51:41.062 30021 30021 E THREAD_STATE:   Thread[NanoHttpd Request Processor (#3),5,main]
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.net.SocketInputStream.socketRead0(Native Method)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.net.SocketInputStream.read(SocketInputStream.java:176)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.net.SocketInputStream.read(SocketInputStream.java:144)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.io.BufferedInputStream.read1(BufferedInputStream.java:288)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.io.BufferedInputStream.read(BufferedInputStream.java:347)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:881)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.lang.Thread.run(Thread.java:923)
06-14 11:51:41.062 30021 30021 E THREAD_STATE: 
06-14 11:51:41.062 30021 30021 E THREAD_STATE:   Thread[main,5,main]
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     dalvik.system.VMStack.getThreadStackTrace(Native Method)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.lang.Thread.getStackTrace(Thread.java:1736)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.lang.Thread.getAllStackTraces(Thread.java:1812)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     android.support.test.runner.MonitoringInstrumentation.getThreadState(MonitoringInstrumentation.java:636)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     android.support.test.runner.MonitoringInstrumentation.dumpThreadStateToOutputs(MonitoringInstrumentation.java:631)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     android.support.test.runner.MonitoringInstrumentation.onException(MonitoringInstrumentation.java:625)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     android.support.test.runner.AndroidJUnitRunner.onException(AndroidJUnitRunner.java:518)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     android.support.test.runner.MonitoringInstrumentation$3.uncaughtException(MonitoringInstrumentation.java:261)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
06-14 11:51:41.062 30021 30021 E THREAD_STATE: 
06-14 11:51:41.062 30021 30021 E THREAD_STATE:   Thread[NanoHttpd Main Listener,5,main]
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     libcore.io.Linux.poll(Native Method)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     libcore.io.ForwardingOs.poll(ForwardingOs.java:168)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     libcore.io.BlockGuardOs.poll(BlockGuardOs.java:263)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     libcore.io.ForwardingOs.poll(ForwardingOs.java:168)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     android.system.Os.poll(Os.java:430)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     libcore.io.IoBridge.poll(IoBridge.java:676)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.net.PlainSocketImpl.socketAccept(PlainSocketImpl.java:194)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:451)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.net.ServerSocket.implAccept(ServerSocket.java:547)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.net.ServerSocket.accept(ServerSocket.java:515)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:1769)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.lang.Thread.run(Thread.java:923)
06-14 11:51:41.062 30021 30021 E THREAD_STATE: 
06-14 11:51:41.062 30021 30021 E THREAD_STATE:   Thread[Instr: android.support.test.runner.AndroidJUnitRunner,5,main]
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.lang.Thread.sleep(Native Method)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.lang.Thread.sleep(Thread.java:442)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.lang.Thread.sleep(Thread.java:358)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     com.github.uiautomator.stub.Stub.testUIAutomatorStub(Stub.java:145)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     java.lang.reflect.Method.invoke(Native Method)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
06-14 11:51:41.062 30021 30021 E THREAD_STATE:     org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     org.junit.runners.ParentRunner.run(ParentRunner.java:363)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     org.junit.runners.Suite.runChild(Suite.java:128)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     org.junit.runners.Suite.runChild(Suite.java:27)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     org.junit.runners.ParentRunner.run(ParentRunner.java:363)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     org.junit.runner.JUnitCore.run(JUnitCore.java:137)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     org.junit.runner.JUnitCore.run(JUnitCore.java:115)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2218)
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[FinalizerWatchdogDaemon,5,system]
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Thread.sleep(Native Method)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Thread.sleep(Thread.java:442)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Thread.sleep(Thread.java:358)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Daemons$FinalizerWatchdogDaemon.sleepForNanos(Daemons.java:390)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:419)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:325)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Daemons$Daemon.run(Daemons.java:139)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Thread.run(Thread.java:923)
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[HeapTaskDaemon,5,system]
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[Jit thread pool worker thread 0,5,system]
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[Binder:30021_1,5,main]
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[FinalizerDaemon,5,system]
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Object.wait(Native Method)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Object.wait(Object.java:442)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:273)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Daemons$Daemon.run(Daemons.java:139)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Thread.run(Thread.java:923)
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[Binder:30021_3,5,main]
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[RenderThread,7,main]
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[UiAutomation,5,main]
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     android.os.MessageQueue.nativePollOnce(Native Method)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     android.os.MessageQueue.next(MessageQueue.java:335)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     android.os.Looper.loop(Looper.java:206)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     android.os.HandlerThread.run(HandlerThread.java:67)
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[Signal Catcher,10,system]
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[Profile Saver,5,system]
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[Binder:30021_4,5,main]
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[ReferenceQueueDaemon,5,system]
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Object.wait(Native Method)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Object.wait(Object.java:442)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Object.wait(Object.java:568)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:217)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Daemons$Daemon.run(Daemons.java:139)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Thread.run(Thread.java:923)
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[NanoHttpd Request Processor (#2),5,main]
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.net.SocketInputStream.socketRead0(Native Method)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.net.SocketInputStream.read(SocketInputStream.java:176)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.net.SocketInputStream.read(SocketInputStream.java:144)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.io.BufferedInputStream.read1(BufferedInputStream.java:288)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.io.BufferedInputStream.read(BufferedInputStream.java:347)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:881)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
06-14 11:51:41.063 30021 30021 E THREAD_STATE:     java.lang.Thread.run(Thread.java:923)
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
06-14 11:51:41.063 30021 30021 E THREAD_STATE:   Thread[Binder:30021_2,5,main]
06-14 11:51:41.063 30021 30021 E THREAD_STATE: 
```
