### ISSUE TITLE
cannot import name 'compare_ssim' from 'skimage.measure

### ISSUE THREAD

**Issue by xzkzdx** [openatx/uiautomator2#648]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 1593, in __getattr__
    return getattr(self._default_session, attr)
  File "C:\Python\Python37\lib\site-packages\uiautomator2\utils.py", line 46, in inner
    _cached_values[key] = ret = fn(*args, **kwargs)
  File "C:\Python\Python37\lib\site-packages\uiautomator2\session.py", line 93, in widget
    from uiautomator2.widget import Widget
  File "C:\Python\Python37\lib\site-packages\uiautomator2\widget.py", line 16, in <module>
    import uiautomator2.image as uim
  File "C:\Python\Python37\lib\site-packages\uiautomator2\image.py", line 14, in <module>
    import findit
  File "C:\Python\Python37\lib\site-packages\findit\__init__.py", line 1, in <module>
    from findit.core import FindIt
  File "C:\Python\Python37\lib\site-packages\findit\core.py", line 11, in <module>
    from findit.engine import engine_dict, FindItEngineResponse, FindItEngine
  File "C:\Python\Python37\lib\site-packages\findit\engine\__init__.py", line 4, in <module>
    from findit.engine.sim import SimEngine
  File "C:\Python\Python37\lib\site-packages\findit\engine\sim.py", line 3, in <module>
    from skimage.measure import compare_ssim
ImportError: cannot import name 'compare_ssim' from 'skimage.measure' (C:\Python\Python37\lib\site-packages\skimage\measure\__init__.py)

**Comment by xzkzdx** [comment]
uiautomator2 No module named 'findit'

**Comment by mingyuan-xia** [comment]
https://github.com/openatx/uiautomator2/issues/639
