### ISSUE TITLE
截图匹配报findit is not defined

### ISSUE THREAD

**Issue by zycfcn** [openatx/uiautomator2#655]
使用代码:
d = u2.connect()
d.image.click('test.jpg', timeout=20.0)

版本号:
uiautomator2-2.12.2-py3.6
windows10 系统
安卓系统使用模拟器

报如下错误:
Traceback (most recent call last):
  File "D:/Documents/pyperjects/xx/main.py", line 43, in <module>
    d.image.click('test.jpg', timeout=20.0)
  File "D:\Documents\pyperjects\xx\venv\lib\site-packages\uiautomator2\image.py", line 295, in click
    res = self.wait(imdata, timeout=timeout)
  File "D:\Documents\pyperjects\xx\venv\lib\site-packages\uiautomator2\image.py", line 287, in wait
    m = self.__wait(imdata, timeout=timeout, threshold=threshold)
  File "D:\Documents\pyperjects\xx\venv\lib\site-packages\uiautomator2\image.py", line 275, in __wait
    m = self.match(imdata)
  File "D:\Documents\pyperjects\xx\venv\lib\site-packages\uiautomator2\image.py", line 253, in match
    fi = findit.FindIt(engine=['template'],
NameError: name 'findit' is not defined

**Comment by fanlion** [comment]
代码里有一行被注释掉了，#import findiit

**Comment by miyouzi** [comment]
所以是出于什么目的不解除注释？源码还是保持着注释 https://github.com/openatx/uiautomator2/blob/1d338c0d0bc6a7d3717c721fb9ee02f816be4a41/uiautomator2/image.py#L16

**Comment by Sanmejie** [comment]
> 所以是出于什么目的不解除注释？源码还是保持着注释
> 
> https://github.com/openatx/uiautomator2/blob/1d338c0d0bc6a7d3717c721fb9ee02f816be4a41/uiautomator2/image.py#L16

我也遇到了， 同问！
