### ISSUE TITLE
uiautomator connect失败

### ISSUE THREAD

**Issue by pxrgod** [openatx/uiautomator2#656]
- 手机型号 荣耀10
- uiautomator2的版本号(2.12.2)
- 手机截图
- 无
- 相关日志
[W 210208 17:26:02 __init__:203] atx-agent has something wrong, auto recovering
[D 210208 17:26:02 __init__:287] device RPG0219215004872 is online
[I 210208 17:26:02 init:155] uiautomator2 version: 2.12.2
Traceback (most recent call last):
  File "E:\pyCode\venv\lib\site-packages\urllib3\connectionpool.py", line 598, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "E:\pyCode\venv\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "E:\pyCode\venv\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "E:\python 3.9.0\Lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "E:\python 3.9.0\Lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "E:\python 3.9.0\Lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by mingyuan-xia** [comment]
logcat
