### ISSUE TITLE
d=connect_usb("......")连接远程设备，d.info 获取设备信息失败

### ISSUE THREAD

**Issue by RonChu-01** [openatx/uiautomator2#658]
- 概述
使用uiautomator2连接远程设备（atxserver2设备管理平台上面的设备），执行d.info获取设备信息失败，报错；

- 手机型号 OPPO Find X2，android版本11
- uiautomator2的版本号 2.12.2
- 截图
![image](https://user-images.githubusercontent.com/26916485/108826552-6239d680-75ff-11eb-963f-eadc0633335c.png)
- 报错代码。
```
try:
        # 获取占用设备信息
        ret = request_api("/api/v1/user/devices/" + udid)
        source = ret['device']['source']
        pprint(source)

        # 运行测试
        adb_remote_addr = source['remoteConnectAddress']
        subprocess.run(['adb', 'connect', adb_remote_addr])
        time.sleep(1)
        d = u2.connect_usb(adb_remote_addr)
        print(d.info)


    finally:
        # 释放设备
        ret = request_api("/api/v1/user/devices/" + udid, method="delete")
        print(ret)

```
- 报错日志
```
connected to 192.168.198.13:20034
/Users/ron/workspace/ATXTask/venv/lib/python3.7/site-packages/uiautomator2/__init__.py:151: UserWarning: 404 page not found

  warnings.warn(res.text)
Traceback (most recent call last):
  File "/Users/ron/workspace/ATXTask/venv/lib/python3.7/site-packages/uiautomator2/__init__.py", line 442, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "/Users/ron/workspace/ATXTask/venv/lib/python3.7/site-packages/uiautomator2/__init__.py", line 479, in _jsonrpc_call
    (time.time() - request_start))
uiautomator2.exceptions.GatewayError: uiautomator2.GatewayError(gateway error, time used 0.0s)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ron/workspace/ATXTask/main.py", line 100, in <module>
    print(d.info)
  File "/Users/ron/workspace/ATXTask/venv/lib/python3.7/site-packages/uiautomator2/__init__.py", line 404, in info
    return self.jsonrpc.deviceInfo(http_timeout=10)
  File "/Users/ron/workspace/ATXTask/venv/lib/python3.7/site-packages/uiautomator2/__init__.py", line 436, in __call__
    http_timeout)
  File "/Users/ron/workspace/ATXTask/venv/lib/python3.7/site-packages/uiautomator2/__init__.py", line 446, in _jsonrpc_retry_call
    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下
  File "/Users/ron/workspace/ATXTask/venv/lib/python3.7/site-packages/uiautomator2/__init__.py", line 581, in reset_uiautomator
    launch_test_app=depth > 0)  # uiautomator 2.0
  File "/Users/ron/workspace/ATXTask/venv/lib/python3.7/site-packages/uiautomator2/__init__.py", line 598, in _force_reset_uiautomator_v2
    self.uiautomator.stop()
  File "/Users/ron/workspace/ATXTask/venv/lib/python3.7/site-packages/uiautomator2/__init__.py", line 170, in stop
    self._raise_for_status(res)
  File "/Users/ron/workspace/ATXTask/venv/lib/python3.7/site-packages/uiautomator2/__init__.py", line 152, in _raise_for_status
    res.raise_for_status()
  File "/Users/ron/workspace/ATXTask/venv/lib/python3.7/site-packages/uiautomator2/__init__.py", line 125, in raise_for_status
    raise requests.HTTPError(_self.status_code, _self.text)
requests.exceptions.HTTPError: [Errno 404] 404 page not found

```

**Comment by RonChu-01** [comment]
目前找了个临时方案解决，通过ip连接设备时，先重新初始化uiautomator2 init，暂时解决该问题
