### ISSUE TITLE
ATXAgent缺少armv9编译版本

### ISSUE THREAD

**Issue by Supermanboyang** [openatx/uiautomator2#667]
- 手机型号  高通内部机
- uiautomator2的版本号 2.14.1
- 手机截图  手机界面正常 
- 相关日志
C:\Users\xiaogu>python -m uiautomator2 init
[I 210401 18:32:21 init:154] uiautomator2 version: 2.14.2.dev1
[I 210401 18:32:21 init:346] Install minicap, minitouch
[D 210401 18:32:21 init:59] Use cached assets: C:\Users\xiaogu\.uiautomator2\cache\minitouch-f7a806902f\minitouch
[D 210401 18:32:21 init:231] Push to /data/local/tmp/minitouch:0755
[D 210401 18:32:21 init:59] Use cached assets: C:\Users\xiaogu\.uiautomator2\cache\minicap.so-f4deedd88f\minicap.so
[D 210401 18:32:21 init:231] Push to /data/local/tmp/minicap.so:0755
[D 210401 18:32:21 init:59] Use cached assets: C:\Users\xiaogu\.uiautomator2\cache\minicap-4ad740a772\minicap
[D 210401 18:32:21 init:231] Push to /data/local/tmp/minicap:0755
[D 210401 18:32:21 init:249] apk-debug package-info: {'version_name': '2.3.3', 'version_code': '2003003', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2021, 3, 18, 23, 0, 23), 'last_update_time': datetime.datetime(2021, 3, 18, 23, 0, 23), 'signature': 'ae17cd86], past signatures:['}
[D 210401 18:32:21 init:250] apk-debug-test package-info: {'version_name': '', 'version_code': '', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2021, 3, 18, 23, 0, 23), 'last_update_time': datetime.datetime(2021, 3, 18, 23, 0, 23), 'signature': 'ae17cd86], past signatures:['}
[I 210401 18:32:21 init:364] Already installed com.github.uiautomator apks
[I 210401 18:32:21 init:338] Install atx-agent 0.10.0
[D 210401 18:32:21 init:59] Use cached assets: C:\Users\xiaogu\.uiautomator2\cache\atx-agent_0.10.0_linux_armv7.tar.gz-cf3333ae7b\atx-agent_0.10.0_linux_armv7.tar.gz
[D 210401 18:32:21 init:231] Push to /data/local/tmp/atx-agent:0755
[D 210401 18:32:21 init:161] Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')
[D 210401 18:32:21 init:161] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr', '127.0.0.1:7912')
[I 210401 18:32:21 init:371] Check atx-agent version
[D 210401 18:32:21 init:384] Forward: local:tcp:62891 -> remote:tcp:7912
[D 210401 18:32:21 init:384] Forward: local:tcp:62891 -> remote:tcp:7912
[D 210401 18:32:22 init:384] Forward: local:tcp:62891 -> remote:tcp:7912
[D 210401 18:32:22 init:384] Forward: local:tcp:62891 -> remote:tcp:7912
[D 210401 18:32:23 init:384] Forward: local:tcp:62891 -> remote:tcp:7912
[D 210401 18:32:23 init:384] Forward: local:tcp:62891 -> remote:tcp:7912
[D 210401 18:32:24 init:384] Forward: local:tcp:62891 -> remote:tcp:7912
[D 210401 18:32:24 init:384] Forward: local:tcp:62891 -> remote:tcp:7912
[D 210401 18:32:25 init:384] Forward: local:tcp:62891 -> remote:tcp:7912
[D 210401 18:32:25 init:384] Forward: local:tcp:62891 -> remote:tcp:7912
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Program Files\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Program Files\Python36\lib\site-packages\urllib3\util\retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Program Files\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python36\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Python36\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\lib\site-packages\uiautomator2\__main__.py", line 245, in <module>
    main()
  File "C:\Program Files\Python36\lib\site-packages\uiautomator2\__main__.py", line 235, in main
    actions[args.subparser](args)
  File "C:\Program Files\Python36\lib\site-packages\uiautomator2\__main__.py", line 34, in cmd_init
    init.install()
  File "C:\Program Files\Python36\lib\site-packages\uiautomator2\init.py", line 372, in install
    self.check_atx_agent_version()
  File "<decorator-gen-8>", line 2, in check_atx_agent_version
  File "C:\Program Files\Python36\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "C:\Program Files\Python36\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\Program Files\Python36\lib\site-packages\uiautomator2\init.py", line 386, in check_atx_agent_version
    port).text.strip()
  File "C:\Program Files\Python36\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

后面我读了你们的wiki 检查了 ATX的工作状态没有正常launch

![image](https://user-images.githubusercontent.com/18500971/113646453-70c5e400-96bb-11eb-871a-f91eb87e31c4.png)

这个会报没有发现浮点运算单元导致ATX不能正常运行  需要修改编译选项

我现在只能定位问题到这里了， 这个issue 会block 我们的测试， 麻烦帮忙指导下， 需要的信息我会update 给你

非常感谢！

**Comment by trigeek** [comment]
我已经编译好了可以用于arm-v9的atx-agent。如果你是qcom同事，请comment你的名字，我会发给你。 @Supermanboyang

**Comment by mingyuan-xia** [comment]
我们希望能将atxagent 在armv9的compile options贡献给社区，谢谢

**Comment by moongkool** [comment]
s

**Comment by moongkool** [comment]
any solution?
every 1h I got this problem

**Comment by trigeek** [comment]
@mingyuan-xia @moongkool please use ARM-V5 compile options to compile a atx-agent. It will works fine on ARMv9 devices also.
