### ISSUE TITLE
app_install 错误

### ISSUE THREAD

**Issue by suqingyue738** [openatx/uiautomator2#690]
```
[D 210616 11:10:19 __init__:1304] pm install -rt /data/local/tmp/_tmp.apk
Traceback (most recent call last):
  File "G:/ck/Playback/App_Playback/tests/adb2u2.py", line 9, in <module>
    d.app_install(url)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\uiautomator2\__init__.py", line 1307, in app_install
    raise RuntimeError(ret.output, ret.exit_code)
RuntimeError: ('Error: Failed to parse APK file: /data/local/tmp/_tmp.apk\n\nException occurred while executing:\njava.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/_tmp.apk\n\tat com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:338)\n\tat com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:906)\n\tat com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:158)\n\tat android.os.ShellCommand.exec(ShellCommand.java:103)\n\tat com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21262)\n\tat android.os.Binder.shellCommand(Binder.java:634)\n\tat android.os.Binder.onTransact(Binder.java:532)\n\tat android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2796)\n\tat com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3858)\n\tat android.os.Binder.execTransact(Binder.java:731)\nCaused by: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/_tmp.apk\n\tat android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1582)\n\tat android.content.pm.PackageParser.parseApkLite(PackageParser.java:1567)\n\tat com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:331)\n\t... 9 more\n', 255)
```

**Comment by mingyuan-xia** [comment]
Failed to parse APK file:

**Comment by mingyuan-xia** [comment]
使用Issue模板上报问题
