### ISSUE TITLE
夜神模拟器无法初始化成功

### ISSUE THREAD

**Issue by Hedilict** [openatx/uiautomator2#692]
- 手机型号：夜神模拟器 7.0.1.2
- uiautomator2的版本号(`pip show uiautomator2`): 2.16.0
- 手机截图
- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)
- @Administrator ➜ XXQG python -m uiautomator2 init
[I 210618 20:06:16 init:156] uiautomator2 version: 2.16.0
[I 210618 20:06:16 init:351] Install minicap, minitouch
[D 210618 20:06:16 init:59] Use cached assets: C:\Users\Administrator\.uiautomator2\cache\minitouch-1e3ccbf4fa\minitouch
[D 210618 20:06:16 init:237] Push to /data/local/tmp/minitouch:0755
[I 210618 20:06:16 init:354] abi:x86 not supported well, skip install minicap
[D 210618 20:06:16 init:255] apk-debug package-info: {'package_name': 'com.github.uiautomator', 'version_name': '2.3.3', 'version_code': '2003003', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2021, 6, 18, 19, 58, 36), 'last_update_time': datetime.datetime(2021, 6, 18, 19, 58, 36), 'signature': 'ae17cd86'}
[D 210618 20:06:16 init:256] apk-debug-test package-info: None
[I 210618 20:06:16 init:364] Install com.github.uiautomator, com.github.uiautomator.test 2.3.3
[D 210618 20:06:16 init:167] Shell: ('pm', 'uninstall', 'com.github.uiautomator')
[D 210618 20:06:16 init:167] Shell: ('pm', 'uninstall', 'com.github.uiautomator.test')
[D 210618 20:06:17 init:59] Use cached assets: C:\Users\Administrator\.uiautomator2\cache\app-uiautomator.apk-d3f17174fb\app-uiautomator.apk
[D 210618 20:06:17 init:237] Push to /data/local/tmp/app-uiautomator.apk:0644
[D 210618 20:06:17 init:167] Shell: ('pm', 'install', '-r', '-t', '/data/local/tmp/app-uiautomator.apk')
[I 210618 20:06:18 init:336] - app-uiautomator.apk installed
[D 210618 20:06:18 init:59] Use cached assets: C:\Users\Administrator\.uiautomator2\cache\app-uiautomator-test.apk-652bf9e13c\app-uiautomator-test.apk
[D 210618 20:06:18 init:237] Push to /data/local/tmp/app-uiautomator-test.apk:0644
[W 210618 20:06:18 api:40] [WinError 10054] 远程主机强迫关闭了一个现有的连接。, retrying in 0 seconds...
[D 210618 20:06:18 init:59] Use cached assets: C:\Users\Administrator\.uiautomator2\cache\app-uiautomator-test.apk-652bf9e13c\app-uiautomator-test.apk
[D 210618 20:06:18 init:237] Push to /data/local/tmp/app-uiautomator-test.apk:0644
adb server is out of date.  killing...
* daemon started successfully *
Traceback (most recent call last):
  File "D:\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\lib\site-packages\uiautomator2\__main__.py", line 289, in <module>
    main()
  File "D:\anaconda3\lib\site-packages\uiautomator2\__main__.py", line 279, in main
    actions[args.subparser](args)
  File "D:\anaconda3\lib\site-packages\uiautomator2\__main__.py", line 36, in cmd_init
    init.install()
  File "D:\anaconda3\lib\site-packages\uiautomator2\init.py", line 367, in install
    self._install_uiautomator_apks()
  File "D:\anaconda3\lib\site-packages\uiautomator2\init.py", line 326, in _install_uiautomator_apks
    path = self.push_url(url, mode=0o644)
  File "D:\anaconda3\lib\site-packages\decorator.py", line 231, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\anaconda3\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "D:\anaconda3\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "D:\anaconda3\lib\site-packages\uiautomator2\init.py", line 238, in push_url
    self._device.sync.push(path, dest, mode=mode)
  File "D:\anaconda3\lib\site-packages\adbutils\__init__.py", line 698, in push
    with self._prepare_sync(path, "SEND") as c:
  File "D:\anaconda3\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\anaconda3\lib\site-packages\adbutils\__init__.py", line 656, in _prepare_sync
    c.check_okay()
  File "D:\anaconda3\lib\site-packages\adbutils\__init__.py", line 168, in check_okay
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError: device not found
- 最好能附上可能复现问题的代码。

**Comment by Hedilict** [comment]
已解决，adb版本的问题。采用夜神模拟器自带d额adb就可以了。
