### ISSUE TITLE
python -m uiautomator2 init 安装失败，麻烦看下多谢（未解决）

### ISSUE THREAD

**Issue by yanghuo662** [openatx/uiautomator2#70]
## Versions (版本)
Name: uiautomator2
Version: 0.1.1.dev26
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: d:\python\lib\site-packages
Requires: requests, six, humanize, fire, progress, retry

## Issue and steps to reproduce (复现步骤)
执行python -m uiautomator2 init 报错如下：
c:\>python -m uiautomator2 init
2018-03-24 11:14:32,821 - __main__.py:268 - INFO - Detect pluged devices: ['32e0c01a']
2018-03-24 11:14:32,822 - __main__.py:284 - INFO - Device(32e0c01a) initialing ...
2018-03-24 11:14:33,366 - __main__.py:113 - INFO - install minicap
2018-03-24 11:14:33,728 - __main__.py:120 - INFO - install minitouch
2018-03-24 11:14:35,173 - __main__.py:143 - INFO - app-uiautomator.apk(1.0.12) installing ...
2018-03-24 11:14:36,302 - __main__.py:148 - INFO - app-uiautomator-test.apk installing ...
2018-03-24 11:14:37,307 - __main__.py:175 - INFO - atx-agent(0.2.1) already installed, skip
Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python\lib\site-packages\uiautomator2\__main__.py", line 345, in <module>
    main()
  File "D:\python\lib\site-packages\uiautomator2\__main__.py", line 341, in main
    fire.Fire(MyFire)
  File "D:\python\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "D:\python\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "D:\python\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "D:\python\lib\site-packages\uiautomator2\__main__.py", line 271, in init
    agent_version, reinstall)
  File "D:\python\lib\site-packages\uiautomator2\__main__.py", line 291, in init_with_serial
    ins.check_apk_installed(apk_version)
  File "D:\python\lib\site-packages\uiautomator2\__main__.py", line 162, in check_apk_installed
    % (apk_version, pkg_info['version_name']))
OSError: package com.github.uiautomator version expect "1.0.12" got "None"

c:\>python -muiautomator2 init --verbose
2018-03-24 11:17:51,122 - __main__.py:268 - INFO - Detect pluged devices: ['32e0c01a']
2018-03-24 11:17:51,123 - __main__.py:284 - INFO - Device(32e0c01a) initialing ...
2018-03-24 11:17:51,544 - __main__.py:109 - DEBUG - install minicap.so
2018-03-24 11:17:51,544 - __main__.py:70 - DEBUG - file 'minicap.so' cached before
2018-03-24 11:17:51,708 - __main__.py:113 - INFO - install minicap
2018-03-24 11:17:51,708 - __main__.py:70 - DEBUG - file 'minicap' cached before
2018-03-24 11:17:52,286 - __main__.py:120 - INFO - install minitouch
2018-03-24 11:17:52,287 - __main__.py:70 - DEBUG - file 'minitouch' cached before
2018-03-24 11:17:52,830 - __main__.py:140 - DEBUG - uninstall old apks
2018-03-24 11:17:53,834 - __main__.py:143 - INFO - app-uiautomator.apk(1.0.12) installing ...
2018-03-24 11:17:53,835 - __main__.py:70 - DEBUG - file 'app-uiautomator.apk' cached before
2018-03-24 11:17:55,575 - __main__.py:146 - DEBUG - app-uiautomator.apk installed
2018-03-24 11:17:55,575 - __main__.py:148 - INFO - app-uiautomator-test.apk installing ...
2018-03-24 11:17:55,584 - __main__.py:70 - DEBUG - file 'app-uiautomator-test.apk' cached before
2018-03-24 11:17:56,601 - __main__.py:151 - DEBUG - app-uiautomator-test.apk installed
2018-03-24 11:17:56,709 - __main__.py:175 - INFO - atx-agent(0.2.1) already installed, skip
Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python\lib\site-packages\uiautomator2\__main__.py", line 345, in <module>
    main()
  File "D:\python\lib\site-packages\uiautomator2\__main__.py", line 341, in main
    fire.Fire(MyFire)
  File "D:\python\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "D:\python\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "D:\python\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "D:\python\lib\site-packages\uiautomator2\__main__.py", line 271, in init
    agent_version, reinstall)
  File "D:\python\lib\site-packages\uiautomator2\__main__.py", line 291, in init_with_serial
    ins.check_apk_installed(apk_version)
  File "D:\python\lib\site-packages\uiautomator2\__main__.py", line 162, in check_apk_installed
    % (apk_version, pkg_info['version_name']))
OSError: package com.github.uiautomator version expect "1.0.12" got "None"

**其他信息：**
手机：ZTE 天机axon 7s
python：3.6
win10
android 6.0.1

**Comment by yanghuo662** [comment]
刚发现和#53的问题一样，但是我在手机上没有找到安装包，是 app-uiautomator-test.apk 和app-uiautomator.apk 这2吗，手机这块比较小白

**Comment by yanghuo662** [comment]
我重新init后，操作提示：
C:\Users\defaultuser0>python -m weditor
listen port 17310
[I 180324 13:41:55 web:2106] 304 GET /api/v1/version (::1) 0.99ms
[I 180324 13:41:57 web:2106] 200 POST /api/v1/connect (::1) 78.23ms
[I 180324 13:42:00 web:2106] 200 POST /api/v1/devices/f3d76c48-f131-466a-8927-4004b9055251/exec (::1) 1037.76ms
SN f3d76c48-f131-466a-8927-4004b9055251
[E 180324 13:42:02 web:1621] Uncaught exception GET /api/v1/devices/f3d76c48-f131-466a-8927-4004b9055251/screenshot (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/api/v1/devices/f3d76c48-f131-466a-8927-4004b9055251/screenshot', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "D:\python\lib\site-packages\tornado\web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "D:\python\lib\site-packages\weditor\__main__.py", line 133, in get
        d.screenshot().convert("RGB").save(buffer, format='JPEG')
      File "<decorator-gen-2>", line 2, in screenshot
      File "D:\python\lib\site-packages\retry\api.py", line 74, in retry_decorator
        logger)
      File "D:\python\lib\site-packages\retry\api.py", line 33, in __retry_internal
        return f()
      File "D:\python\lib\site-packages\uiautomator2\__init__.py", line 1083, in screenshot
        from PIL import Image
    ModuleNotFoundError: No module named 'PIL'
[E 180324 13:42:02 web:2106] 500 GET /api/v1/devices/f3d76c48-f131-466a-8927-4004b9055251/screenshot (::1) 879.34ms

**Comment by codeskyblue** [comment]
奥，再安装一个pillow库

**Comment by yanghuo662** [comment]
多谢，已解决
