### ISSUE TITLE
Android 12 下兼容性出现问题，运行一段时间后会无法连接

### ISSUE THREAD

**Issue by icegourd** [openatx/uiautomator2#763]
之前测试代码运行都很正常，手机升级为Android12后，运行测试代码刚开始还正常，但是很短时间内就会出现异常，无法重新连接上。
出现错误代码如下：

[E 211013 13:13:24 web:2250] 500 GET /api/v2/devices/android%AAAAAAAA/hierarchy (::1) 425.75ms
[I 211013 13:17:07 page:297] Serial: AAAAAAAA
[I 211013 13:17:13 web:2250] 200 GET /api/v1/devices/android%AAAAAAAA/screenshot (::1) 5580.32ms
[W 211013 13:17:13 __init__:471] [pid:3964] jsonrpc call got: -32001 Jsonrpc error: <java.lang.NullPointerException> data: java.lang.NullPointerException: Attempt to read from field 'int android.accessibilityservice.AccessibilityServiceInfo.flags' on a null object reference
        at androidx.test.uiautomator.UiDevice.setCompressedLayoutHeirarchy(UiDevice.java:234)
        at com.github.uiautomator.stub.AutomatorServiceImpl.dumpWindowHierarchy(AutomatorServiceImpl.java:295)
        at com.github.uiautomator.stub.AutomatorServiceImpl.dumpWindowHierarchy(AutomatorServiceImpl.java:284)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
        at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
        at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
        at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:920)
    , method: dumpWindowHierarchy

我怀疑是uiautomater服务出了问题，因为如果手动在 ATX APP中点击“停止UIAUTOMATOR”按钮后，这时候运行测试代码，获得的错误信息是一样的

- 手机型号
Nokia X10（Android 12）

- uiautomator2的版本号(`pip show uiautomator2`)
Version: 2.16.7

- 手机截图

- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)

![Screenshot_20211013-140309](https://user-images.githubusercontent.com/8433789/137076968-3d074b8e-f69d-44ad-9a7f-15363f238911.png)
[atx-agent.daemon.log](https://github.com/openatx/uiautomator2/files/7335368/atx-agent.daemon.log)
[atx-agent.log](https://github.com/openatx/uiautomator2/files/7335369/atx-agent.log)

**Comment by icegourd** [comment]
问题已经找到了，我的测试代码在main()入口的第一动作就是调用"python -m uiautomator2 init"进行初始化，Android12之前的版本都没有问题，现在Android12执行这个动作之后uiautomator服务就停止了（ d.uiautomator.running()返回false）
现在的做法是移除这个动作，因为在之前的版中这个就是非必须的

NOTE：
运行python3 -m uiautomator2 init安装包含httprpc服务的apk到手机+atx-agent, minicap, minitouch （在过去的版本中，这一步是必须执行的，但是从1.3.0之后的版本，当运行python代码u2.connect()时就会自动推送这些文件了）

**Comment by zhaojunPanda** [comment]
请问有解决方案了吗？

**Comment by killaragorn** [comment]
+1

**Comment by chrisjansky** [comment]
Did you find a fix for this? Happens to me also 😢
