### ISSUE TITLE
uiautomator2连接真机报错：您的主机中的软件中止了一个已建立的连接

### ISSUE THREAD

**Issue by GBwuka** [openatx/uiautomator2#77]
python -m uiautomator2 init成功之后通过serial number连接真机
d = u2.connect('X2P5T15827000029')
print(d.info)报错

Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in u
rlopen
    chunked=chunked)
  File "D:\Python36\lib\site-packages\urllib3\connectionpool.py", line 357, in _
make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Python36\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "D:\Python36\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
ConnectionAbortedError: [WinError 10053] 您的主机中的软件中止了一个已建立的连接
。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "D:\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in u
rlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\Python36\lib\site-packages\urllib3\util\retry.py", line 357, in incre
ment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\Python36\lib\site-packages\urllib3\packages\six.py", line 685, in rer
aise
    raise value.with_traceback(tb)
  File "D:\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in u
rlopen
    chunked=chunked)
  File "D:\Python36\lib\site-packages\urllib3\connectionpool.py", line 357, in _
make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Python36\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "D:\Python36\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError
(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uiauto2_test.py", line 4, in <module>
    print(d.info)
  File "D:\Python36\lib\site-packages\uiautomator2\__init__.py", line 830, in __
getattr__
    return getattr(self._default_session, attr)
  File "D:\Python36\lib\site-packages\uiautomator2\__init__.py", line 1242, in i
nfo
    return self.jsonrpc.deviceInfo()
  File "D:\Python36\lib\site-packages\uiautomator2\__init__.py", line 322, in __
call__
    return self.server.jsonrpc_retry_call(jsonrpc_url, self.method, params, http
_timeout)
  File "D:\Python36\lib\site-packages\uiautomator2\__init__.py", line 329, in js
onrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "D:\Python36\lib\site-packages\uiautomator2\__init__.py", line 352, in js
onrpc_call
    data=data)
  File "D:\Python36\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\Python36\lib\site-packages\uiautomator2\__init__.py", line 210, in re
quest
    resp = super(TimeoutRequestsSession, self).request(method, url, **kwargs)
  File "D:\Python36\lib\site-packages\requests\sessions.py", line 508, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "D:\Python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python36\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedEr
ror(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None))

**Comment by codeskyblue** [comment]
没有init?

**Comment by GBwuka** [comment]
init 过了

**Comment by codeskyblue** [comment]
加群问吧，欢迎加入atx+uiautomator2，群号码：499563266
