### ISSUE TITLE
在windows上安装报错，应该是编码方式不对导致的，是否，可以修改下？

### ISSUE THREAD

**Issue by flyfire100** [openatx/uiautomator2#79]
使用pip部署时候报下面的错误，原因是我Python安装的路径带有中文，且系统编码是GBK的，导致编码方式不对造成的，是否可以修改下安装脚本，使之兼容？
Collecting uiautomator2
  Using cached uiautomator2-0.1.1.dev31.tar.gz
Exception:
Traceback (most recent call last):
  File "d:\安装程序\1-安装包\python\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 5: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\安装程序\1-安装包\python\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\安装程序\1-安装包\python\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "d:\安装程序\1-安装包\python\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "d:\安装程序\1-安装包\python\lib\site-packages\pip\req\req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "d:\安装程序\1-安装包\python\lib\site-packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "d:\安装程序\1-安装包\python\lib\site-packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "d:\安装程序\1-安装包\python\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "d:\安装程序\1-安装包\python\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 5: invalid start byte

**Comment by flyfire100** [comment]
https://www.cnblogs.com/ironbear/p/7879166.html
按照上面的方式解决了
