### ISSUE TITLE
8.0系统N5X手机连接WEditor失败

### ISSUE THREAD

**Issue by q88535448** [openatx/uiautomator2#80]
```
➜  ~ python2 -m weditor
listen port 17310
[I 180411 16:04:17 web:2063] 304 GET /api/v1/version (::1) 1.61ms
[W 180411 16:04:20 web:2063] 404 POST /api/v1/devices//exec (::1) 1.01ms
SN -
[E 180411 16:04:29 web:1590] Uncaught exception GET /api/v1/devices/-/screenshot (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/api/v1/devices/-/screenshot', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://atx.open.netease.com', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:17310', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6', 'Connection': 'keep-alive', 'Referer': 'http://atx.open.netease.com/'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python2.7/site-packages/weditor/__main__.py", line 134, in get
        d.screenshot().convert("RGB").save(buffer, format='JPEG')
    AttributeError: 'NoneType' object has no attribute 'screenshot'
[E 180411 16:04:29 web:2063] 500 GET /api/v1/devices/-/screenshot (::1) 2.73ms

```

## Versions (版本)
`Name: uiautomator2
Version: 0.1.1.dev32
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: /Library/Python/2.7/site-packages
Requires: retry, six, progress, humanize, fire, requests`

## Issue and steps to reproduce (复现步骤)
描述的越详细，issue修复的越快

- 8.0系统N5X

**Comment by codeskyblue** [comment]
先点击导航栏的Connect

**Comment by q88535448** [comment]
好像是我没有成功安装uia apk，现在搞定了。但是stf的机器还是不能直接用uia2或者WEditor啊

**Comment by codeskyblue** [comment]
你先重新提个issue
