### ISSUE TITLE
AttributeError: 'Device' object has no attribute '_logger'. Did you mean: 'logger'?

### ISSUE THREAD

**Issue by Xander-97** [openatx/uiautomator2#815]
1. 使用ip地址改会报错
![image](https://user-images.githubusercontent.com/60773912/173238245-4b737c2e-8fb9-42ee-a0f2-19fb04bf40fb.png)

2. 反过来使用serial就不会报错
![image](https://user-images.githubusercontent.com/60773912/173238327-787d2c71-10f6-4bb9-ad89-de7a1622a00d.png)

不知道是什么原因
就用了这一行代码做测试,我反复试了很多次
`d.swipe(756, 1647, 540, 372, duration=.1)`

- 手机型号
手机相关信息:
`info: {'udid': 'ee37d044-1c:48:ce:36:a3:a3-OPPO_R9s', 'version': '7.1.1', 'serial': 'ee37d044', 'brand': 'OPPO', 'model': 'OPPO R9s', 'hwaddr': '1c:48:ce:36:a3:a3', 'sdk': 25, 'agentVersion': '0.10.0', 'display': {'width': 1080, 'height': 1920}, 'battery': {'acPowered': False, 'usbPowered': True, 'wirelessPowered': False, 'status': 2, 'health': 2, 'present': True, 'level': 44, 'scale': 100, 'voltage': 3828, 'temperature': 326, 'technology': 'Li-ion'}, 'memory': {'total': 3680892, 'around': '4 GB'}, 'cpu': {'cores': 8, 'hardware': 'Qualcomm Technologies, Inc MSM8953'}, 'arch': '', 'owner': None, 'presenceChangedAt': '0001-01-01T00:00:00Z', 'usingBeganAt': '0001-01-01T00:00:00Z', 'product': None, 'provider': None}`

- uiautomator2的版本号(`pip show uiautomator2`)
![image](https://user-images.githubusercontent.com/60773912/173238517-be595875-9015-42d2-b7f2-bce4546a92fd.png)
- 手机截图
![183ac9a5-71d5-4191-b2a1-e7959fcfb63a](https://user-images.githubusercontent.com/60773912/173238678-0f80b3ea-a227-4079-826c-69a70a59e74a.jpg)

**Comment by Xander-97** [comment]
- 重复步骤依然有:
    补上：
![image](https://user-images.githubusercontent.com/60773912/173254051-db05c995-0e4e-4c5e-9f8d-8c308871b595.png)
```python
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.4.0

Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
import uiautomator2 as u2
d = u2.connect('192.168.1.4')
d.drag(756, 1647, 540, 372, duration=.08)

Traceback (most recent call last):
  File "C:\Users\Summer\apps\Python310\lib\site-packages\uiautomator2\__init__.py", line 487, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "C:\Users\Summer\apps\Python310\lib\site-packages\uiautomator2\__init__.py", line 519, in _jsonrpc_call
    raise GatewayError(
uiautomator2.exceptions.GatewayError: uiautomator2.GatewayError(gateway error, time used 0.1s)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Summer\apps\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-93ddd308c69f>", line 1, in <cell line: 1>
    d.drag(756, 1647, 540, 372, duration=.08)
  File "C:\Users\Summer\apps\Python310\lib\site-packages\uiautomator2\__init__.py", line 1150, in drag
    return self.jsonrpc.drag(sx, sy, ex, ey, int(duration * 200))
  File "C:\Users\Summer\apps\Python310\lib\site-packages\uiautomator2\__init__.py", line 480, in __call__
    return self.server._jsonrpc_retry_call(self.method, params,
  File "C:\Users\Summer\apps\Python310\lib\site-packages\uiautomator2\__init__.py", line 489, in _jsonrpc_retry_call
    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下
  File "C:\Users\Summer\apps\Python310\lib\site-packages\uiautomator2\__init__.py", line 616, in reset_uiautomator
    with self._filelock:
AttributeError: 'Device' object has no attribute '_filelock'
```
```python
d.swipe(756, 1647, 540, 372, duration=1)
Traceback (most recent call last):
  File "C:\Users\Summer\apps\Python310\lib\site-packages\uiautomator2\__init__.py", line 487, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "C:\Users\Summer\apps\Python310\lib\site-packages\uiautomator2\__init__.py", line 519, in _jsonrpc_call
    raise GatewayError(
uiautomator2.exceptions.GatewayError: uiautomator2.GatewayError(gateway error, time used 0.0s)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Summer\apps\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-ffd1e7133306>", line 1, in <cell line: 1>
    d.swipe(756, 1647, 540, 372, duration=1)
  File "C:\Users\Summer\apps\Python310\lib\site-packages\uiautomator2\__init__.py", line 1124, in swipe
    return self.jsonrpc.swipe(fx, fy, tx, ty, steps)
  File "C:\Users\Summer\apps\Python310\lib\site-packages\uiautomator2\__init__.py", line 480, in __call__
    return self.server._jsonrpc_retry_call(self.method, params,
  File "C:\Users\Summer\apps\Python310\lib\site-packages\uiautomator2\__init__.py", line 489, in _jsonrpc_retry_call
    self.reset_uiautomator(str(e))  # uiautomator可能出问题了，强制重启一下
  File "C:\Users\Summer\apps\Python310\lib\site-packages\uiautomator2\__init__.py", line 616, in reset_uiautomator
    with self._filelock:
AttributeError: 'Device' object has no attribute '_filelock'
```
```python
d.device_info()
Traceback (most recent call last):
  File "C:\Users\Summer\apps\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-3090b79a7cdd>", line 1, in <cell line: 1>
    d.device_info()
TypeError: 'dict' object is not callable
d.device_info
Out[8]: 
{'udid': 'ee37d044-1c:48:ce:36:a3:a3-OPPO_R9s',
 'version': '7.1.1',
 'serial': 'ee37d044',
 'brand': 'OPPO',
 'model': 'OPPO R9s',
 'hwaddr': '1c:48:ce:36:a3:a3',
 'sdk': 25,
 'agentVersion': '0.10.0',
 'display': {'width': 1080, 'height': 1920},
 'battery': {'acPowered': False,
  'usbPowered': True,
  'wirelessPowered': False,
  'status': 2,
  'health': 2,
  'present': True,
  'level': 2,
  'scale': 100,
  'voltage': 3597,
  'temperature': 330,
  'technology': 'Li-ion'},
 'memory': {'total': 3680892, 'around': '4 GB'},
 'cpu': {'cores': 8, 'hardware': 'Qualcomm Technologies, Inc MSM8953'},
 'arch': '',
 'owner': None,
 'presenceChangedAt': '0001-01-01T00:00:00Z',
 'usingBeganAt': '0001-01-01T00:00:00Z',
 'product': None,
 'provider': None}

```

**Comment by codeskyblue** [comment]
Haha, you found a bug. fixed in 2.16.16.

默认情况下手机上运行的atx-agent并不会监听所有的端口。需要先数据线连接上手机，然后运行 `uiautomator2 init --addr :7912` 才行。

然后断开数据线，然后就是可以用代码 `d = u2.connect("192.168.xxx")` 这种方法连接了

**Comment by Xander-97** [comment]
> 
我是使用这个命令重启 

> agx-agent

`adb shell "chmod 755 /data/local/tmp/atx-agent && data/local/tmp/atx-agent version && /data/local/tmp/atx-agent server -d"`
