### ISSUE TITLE
使用uiautomator可以正常连接测试，使用uiautomator2无法做任何操作

### ISSUE THREAD

**Issue by nickyang86** [openatx/uiautomator2#82]
同一台手机(meizu 魅蓝 note2)，使用uiautomator可以正常连接测试，使用uiautomator2无法做任何操作，直接报错

```
执行出错代码：（execute fail）
import uiautomator2 as u2
d = u2.connect_usb('81CEBM925UNQ')
print d.device_info()  #换成其他方法也是一样错误

执行正常代码：（execute success）
from uiautomator import Device
d = Device('81CEBM925UNQ')
print d.info()
```

##Versions (版本)
Version: 0.1.1.dev32

##出错信息
Traceback (most recent call last):
  File "E:\uitest.py", line 7, in <module>
    print d.device_info()
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 765, in device_info
    self.__devinfo = self._reqsess.get(self.path2url('/info')).json()
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\uiautomator2\__init__.py", line 210, in request
    resp = super(TimeoutRequestsSession, self).request(method, url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(10054, ''))

**Comment by codeskyblue** [comment]
需要init操作才行，我等下加个提示吧

**Comment by nickyang86** [comment]
我明白了，我没有执行这个python -m uiautomator2 init， 谢了
