### ISSUE TITLE
图像匹配报错：NameError: name 'findit' is not defined

### ISSUE THREAD

**Issue by shifengboy** [openatx/uiautomator2#848]
执行图像匹配代码时报如下错误：
代码：
```python
imdata = "home.jpg" # 也可以是URL, PIL.Image或OpenCV打开的图像
d.image.match(imdata)
d.image.click(imdata, timeout=20.0)
```

保存信息：
Traceback (most recent call last):
  File "/Users/chenshifeng/MyCode/www.py", line 374, in <module>
    d.image.match(imdata)
  File "/usr/local/lib/python3.9/site-packages/uiautomator2/image.py", line 253, in match
    fi = findit.FindIt(engine=['template'],
NameError: name 'findit' is not defined

Process finished with exit code 1

**Comment by codeskyblue** [comment]
图像功能不在维护
