### ISSUE TITLE
图像匹配报错

### ISSUE THREAD

**Issue by 1450687719** [openatx/uiautomator2#854]
执行以下代码报错：
    imdata = '7.png' # 也可以是URL, PIL.Image或OpenCV打开的图像
    d.image.match('7.png')

报错内容为：
Traceback (most recent call last):
  File "C:\Users\Ms.zhang\AppData\Local\Programs\Python\Python38\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/pythonProject2/自动同花顺/open.py", line 15, in <module>
    d.image.click(imdata, timeout=20.0)
  File "D:\pythonProject2\venv\lib\site-packages\cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "D:\pythonProject2\venv\lib\site-packages\uiautomator2\__init__.py", line 1840, in image
    from uiautomator2 import image as _image
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\uiautomator2\image.py", line 16, in <module>
    import findit
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\findit\__init__.py", line 1, in <module>
    from findit.core import FindIt
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\findit\core.py", line 11, in <module>
    from findit.engine import engine_dict, FindItEngineResponse, FindItEngine
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\findit\engine\__init__.py", line 1, in <module>
    from findit.engine.feature import FeatureEngine
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\findit\engine\feature.py", line 7, in <module>
    from sklearn.cluster import KMeans
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\sklearn\__init__.py", line 64, in <module>
    from .base import clone
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\sklearn\base.py", line 13, in <module>
    from .utils.fixes import signature
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\sklearn\utils\__init__.py", line 14, in <module>
    from . import _joblib
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\sklearn\utils\_joblib.py", line 22, in <module>
    from ..externals import joblib
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\sklearn\externals\joblib\__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\sklearn\externals\joblib\parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\sklearn\externals\joblib\executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\sklearn\externals\joblib\externals\loky\__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\sklearn\externals\joblib\externals\loky\backend\reduction.py", line 125, in <module>
    from sklearn.externals.joblib.externals import cloudpickle  # noqa: F401
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "D:\新建文件夹\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\pythonProject2\venv\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py", line 167, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "D:\pythonProject2\venv\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py", line 148, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)

**Comment by gleke** [comment]
你这是识别验证码？

**Comment by codeskyblue** [comment]
图片匹配从lib中移除，需要搞验证码可以试试 dddocr
