### ISSUE TITLE
-32001 Jsonrpc error: <java.lang.StackOverflowError> data: java.lang.StackOverflowError: stack size 1039KB

### ISSUE THREAD

**Issue by winniewang0813** [openatx/uiautomator2#856]
执行几次就报错
![image](https://user-images.githubusercontent.com/88882151/207767856-40c33c29-eb91-4628-a04e-6d4dc3316fd0.png)

- 手机型号
OnelPlus 9 (Android 12)

- uiautomator2的版本号(`pip show uiautomator2`)
Name: uiautomator2
Version: 2.16.21
Summary: Python Wrapper for Google Android UiAutomator2 test tool
Home-page: https://github.com/openatx/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: c:\users\cnwiwan14\appdata\local\programs\python\python37\lib\site-packages
Requires: adbutils, cached-property, Deprecated, filelock, logzero, lxml, packaging, Pillow, progress, requests, retry, six, whichcraft
Required-by: weditor

- 手机截图
手机设置：
![image](https://user-images.githubusercontent.com/88882151/207768092-9bf9dec4-015e-47fa-9cbe-ba5f68a853c3.png)

- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)
at java.lang.Thread.run(Thread.java:920)
, method: exist

- 最好能附上可能复现问题的代码。
- def wait_for_exists_by_resourceId(self,locator,timeout):
        """
            # Wait for the object (wait until the ui object appears) which has *selectors* within the given timeout. 
            # wait Settings appear in 3s, same as .wait(3)  
            # Return bool: true if the object *appear* in the given timeout. Else return false.
        """
        print("the locator is",locator)
        time.sleep(timeout)
        return self.u(resourceId=locator).exists
        #return self.u(resourceId=locator).wait(timeout) 

def wait_for_exists_by_xpath(self,locator,timeout):
        """
            # Wait for the object which has *selectors* within the given timeout.

            # Return true if the object *appear* in the given timeout. Else return false.
        """
        print("the xpath is",locator)
        #return self.u.xpath(locator).wait(timeout)
        time.sleep(timeout)
        return self.u.xpath(locator).exists

if __name__=='__main__':
    apk = 'com.abb.welcome'
    test=AndroidAppTool()
    test.connect_device('300140e3')

    for i in range (1,100):
        test.start_application(apk)
        time.sleep(5)
        el = apk+':id/layout_cancel'
        result = test.wait_for_exists_by_resourceId(el,3)
        print (result)
        time.sleep(5)
        result = test.wait_for_exists_by_xpath('//*[@resource-id="com.abb.welcome:id/chk_eula"]',3)
        print (result)
        time.sleep(5)
        #test.stop_application(apk)
        test.stop_all_application()

**Comment by winniewang0813** [comment]
ATX版本：0.10.0

**Comment by winniewang0813** [comment]
Logcat 
[OnelPlus 9 (Android 12)_logcat_20221215.txt](https://github.com/openatx/uiautomator2/files/10233576/OnelPlus.9.Android.12._logcat_20221215.txt)

**Comment by winniewang0813** [comment]
12-15 11:50:06.543 22820 24125 W System.err: java.lang.StackOverflowError: stack size 1039KB
12-15 11:50:06.548 22820 24125 W System.err: 	at android.util.SparseArray.get(SparseArray.java:134)
12-15 11:50:06.548 22820 24125 W System.err: 	at android.util.SparseArray.get(SparseArray.java:125)
12-15 11:50:06.548 22820 24125 W System.err: 	at android.view.accessibility.AccessibilityInteractionClient.getConnection(AccessibilityInteractionClient.java:204)
12-15 11:50:06.548 22820 24125 W System.err: 	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:465)
12-15 11:50:06.548 22820 24125 W System.err: 	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:1121)

**Comment by Ffmydy** [comment]
uiautomator2.exceptions.JSONRPCError: -32001 Jsonrpc error: <java.lang.StackOverflowError> data: java.lang.StackOverflowError: stack size 1039KB
	at java.nio.CharBuffer.limit(CharBuffer.java:876)
	at java.nio.Buffer.<init>(Buffer.java:213)
	at java.nio.CharBuffer.<init>(CharBuffer.java:141)
	at java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:58)
	at java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:54)
	at java.nio.CharBuffer.wrap(CharBuffer.java:210)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:265)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at com.android.org.kxml2.io.KXmlSerializer.flushBuffer(KXmlSerializer.java:80)
	at com.android.org.kxml2.io.KXmlSerializer.append(KXmlSerializer.java:61)
	at com.android.org.kxml2.io.KXmlSerializer.append(KXmlSerializer.java:75)
	at com.android.org.kxml2.io.KXmlSerializer.startTag(KXmlSerializer.java:406)
	at com.github.uiautomator.stub.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:88)
	at com.github.uiautomator.stub.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:117)
	at com.github.uiautomator.stub.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:117)
	at com.github.uiautomator.stub.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:117)
	at com.github.uiautomator.stub.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:117)
	at com.github.uiautomator.stub.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:117)
	at com.github.uiautomator.stub.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:117)
	at com.github.uiautomator.stub.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:117)
	at com.github.uiautomator.stub.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:117)
	at com.github.uiautomator.stub.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:117)
还是有这个问题啊

**Comment by codeskyblue** [comment]
麻烦附上具体的复现步骤，不然就算知道有这个问题也没法修啊

**Comment by codeskyblue** [comment]
it should fixed now( I guess)
