### ISSUE TITLE
init 执行报错 nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by AceCcream** [openatx/uiautomator2#86]
python -m uiautomator2 init执行后报错

```
2018-04-18 18:54:00,796 - __main__.py:269 - INFO - Detect pluged devices: [u'HT53TYJ11305']
2018-04-18 18:54:00,796 - __main__.py:286 - INFO - Device(HT53TYJ11305) initialing ...
2018-04-18 18:54:00,970 - __main__.py:109 - DEBUG - install minicap.so
2018-04-18 18:54:00,971 - __main__.py:70 - DEBUG - file 'minicap.so' cached before
2018-04-18 18:54:01,002 - __main__.py:113 - INFO - install minicap
2018-04-18 18:54:01,003 - __main__.py:70 - DEBUG - file 'minicap' cached before
2018-04-18 18:54:01,442 - __main__.py:120 - INFO - install minitouch
2018-04-18 18:54:01,442 - __main__.py:70 - DEBUG - file 'minitouch' cached before
2018-04-18 18:54:01,629 - __main__.py:137 - INFO - apk(1.0.12) already installed, skip
2018-04-18 18:54:01,669 - __main__.py:175 - INFO - atx-agent(0.3.0) already installed, skip
2018-04-18 18:54:01,784 - __main__.py:212 - INFO - launch atx-agent daemon
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/uiautomator2/__main__.py", line 352, in <module>
    main()
  File "/Library/Python/2.7/site-packages/uiautomator2/__main__.py", line 348, in main
    fire.Fire(MyFire)
  File "/Library/Python/2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/Library/Python/2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/Library/Python/2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/Library/Python/2.7/site-packages/uiautomator2/__main__.py", line 273, in init
    ignore_apk_check)
  File "/Library/Python/2.7/site-packages/uiautomator2/__main__.py", line 295, in _init_with_serial
    ins.launch_and_check()
  File "/Library/Python/2.7/site-packages/uiautomator2/__main__.py", line 218, in launch_and_check
    lport = self.forward_port(7912)
  File "/Library/Python/2.7/site-packages/uiautomator2/adbutils.py", line 79, in forward_port
    free_port = find_free_port()
  File "/Library/Python/2.7/site-packages/uiautomator2/adbutils.py", line 14, in find_free_port
    s.bind(('localhost', 0))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by AceCcream** [comment]
sorry  locahost被我删掉了
