### ISSUE TITLE
测试过程抛异常UiObjectNotFoundError: -32002 Server error: android.support.test.uiautomator.UiObjectNotFoundException

### ISSUE THREAD

**Issue by dingronghui** [openatx/uiautomator2#87]
## source code:
print("\t\t是否有首页提示图片！")
        if driver(className="android.widget.ImageView", packageName="com.tydic.phone.tray",
                  instance=10).exists:
            driver(className="android.widget.ImageView", packageName="com.tydic.phone.tray",
                  instance=10).click()
            print("\t\t点击首页提示图片操作成功！")
        else:
            # fout.write("\t\tError-签约弹窗操作！"+'\n')
            print("\t\t无首页提示图片")
        time.sleep(3)

## Versions (版本)
Name: uiautomator2
Version: 0.0.3.dev22
Summary: Python Wrapper for Android UiAutomator2 test tool
Home-page: https://github.com/codeskyblue/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: /Users/dingronghui/uiautomator2
Requires: requests, six, humanize, fire, progress, retry
You are using pip version 9.0.1, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

- 手机型号
小米 6 MIUI 9

## 抛出异常
Traceback (most recent call last):
  File "A.py", line 117, in test_new
    S.tips()
  File "/Users/dingronghui/svn/DialTest/Trunk/20180227/B.py", line 1596, in tips
    self.cases()
  File "/Users/dingronghui/svn/DialTest/Trunk/20180227/B.py", line 1719, in cases
    self.xiaoxiceshi()                      #消息测试
  File "/Users/dingronghui/svn/DialTest/Trunk/20180227/B.py", line 825, in xiaoxiceshi
    self.chushihuaqidongqianyue()  # 初始化登录-启动-签约更新
  File "/Users/dingronghui/svn/DialTest/Trunk/20180227/B.py", line 428, in chushihuaqidongqianyue
    self.chushihuajiemian()  # 初始化欢迎登录界面
  File "/Users/dingronghui/svn/DialTest/Trunk/20180227/B.py", line 321, in chushihuajiemian
    instance=10).click()
  File "/Users/dingronghui/uiautomator2/uiautomator2/__init__.py", line 985, in click
    return self.tap()
  File "/Users/dingronghui/uiautomator2/uiautomator2/__init__.py", line 938, in inner
    return fn(self, *args, **kwargs)
  File "/Users/dingronghui/uiautomator2/uiautomator2/__init__.py", line 969, in tap
    self.click_nowait()
  File "/Users/dingronghui/uiautomator2/uiautomator2/__init__.py", line 978, in click_nowait
    self.jsonrpc.click(self.selector)
  File "/Users/dingronghui/uiautomator2/uiautomator2/__init__.py", line 231, in __call__
    return self.server.jsonrpc_call(self.method, params, http_timeout)
  File "/Users/dingronghui/uiautomator2/uiautomator2/__init__.py", line 265, in jsonrpc_call
    raise err
UiObjectNotFoundError: -32002 Server error: android.support.test.uiautomator.UiObjectNotFoundException <UiSelector[CLASS=android.widget.ImageView, INSTANCE=10, PACKAGE NAME=com.tydic.phone.tray]>

**Comment by codeskyblue** [comment]
正常错误，元素没有找到

**Comment by dingronghui** [comment]
嗯，可能我的被测试方需求比较特殊：

**Comment by dingronghui** [comment]
嗯，可能我的被测试方需求比较特殊：

**Comment by dingronghui** [comment]
嗯，可能我的被测试方需求比较特殊：

**Comment by dingronghui** [comment]
明白您的意思，可能我的被测试方需求比较特殊：
由server下发需要运行的计划任务和测试用例，按照规定的计划运行测试用例，如：每天的8点，10点跑指定的测试用例。所以我不得不只写一个用例(比如叫test_A)，里面用white循环里面包含所有的测试用例，待测试任务到达执行时间启动。但这样会导致test_A里面只要一个用例抛出异常(如上面提的未找到元素)就会停止整个用例(test_A)，所以我不得不用try-catch来处理。不知道有没有好的办法能够满足这样的需求，谢

**Comment by codeskyblue** [comment]
不抛出异常的方法可以用 `d(text="Settings").click_exists(timeout=10)` 这种
