### ISSUE TITLE
Problems with stability of connection of a large number of devices. 

### ISSUE THREAD

**Issue by af652030** [openatx/uiautomator2#900]
Problems with stability of connection of a large number of devices. 

I have several mobile devices and the code on uiautomator2 which worked fine. But with increasing number of devices I catch a strange error after which something happens with adb server. 
After which: 
1) device gets offline status
2) Log code says "device offline". 
3) A window "Allow usb debugging" pops up on the device, which tells about re-authorization of the device for the adb server. Although adb server works and some other devices work stably. (It's always different devices. Sometimes it turns off device 1,2,3, sometimes 3,2,5, etc.) 
4) If you use the command "adb reconnect offline" then the device can be used again and its status changes.

I have some assumptions: 
1) Devices are often rebooted via "adb shell reboot" command. Perhaps when rebooting the script cannot connect to the application and a conflict occurs, so it restarts the server.

2) Problem in ports. A large number of devices require more ports and when rebooting the device as if it gets a new port. Maybe there are not enough ports and uiautomator restarts adb. 

I've been studying the documentation for a couple days but can't find the reason. If you have any ideas or thoughts why the adb server might be restarting, it would be appreciated. 

ERROR: 
ConnectionError : ('Connection aborted.',
 RemoteDisconnected('Remote end closed connection without response'))
 
 
![image_2023-07-15_12-26-21](https://github.com/openatx/uiautomator2/assets/139620205/629a61a0-1289-4d91-9b30-745514a47c0e)

**Comment by af652030** [comment]
* daemon not running; starting now at tcp:5037
could not read ok from ADB Server
* failed to start daemon
error: cannot connect to daemon
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Program Files (x86)\python3.9\lib\http\client.py", line 1371, in getresponse
    response.begin()
  File "D:\Program Files (x86)\python3.9\lib\http\client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "D:\Program Files (x86)\python3.9\lib\http\client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Program Files (x86)\python3.9\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\adapters.py", line 429, in send
    resp = conn.urlopen(
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 648, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Program Files (x86)\python3.9\lib\http\client.py", line 1371, in getresponse
    response.begin()
  File "D:\Program Files (x86)\python3.9\lib\http\client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "D:\Program Files (x86)\python3.9\lib\http\client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Program Files (x86)\python3.9\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 203, in request
    return super().request(method, url, **kwargs)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 119, in request
    resp = super(TimeoutRequestsSession,
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\adapters.py", line 489, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\tt_bot3\reg.py", line 750, in reg
    assert self._reg()
  File "C:\Users\Admin\PycharmProjects\tt_bot3\reg.py", line 703, in _reg
    self._click_next('email')
  File "C:\Users\Admin\PycharmProjects\tt_bot3\reg.py", line 363, in _click_next
    result = self._wait_for_loading(screen)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\reg.py", line 352, in _wait_for_loading
    if condition:
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\utils.py", line 105, in __bool__
    return self.__nonzero__()
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\utils.py", line 101, in __nonzero__
    return self.uiobject.jsonrpc.exist(self.uiobject.selector)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 479, in __call__
    return self.server._jsonrpc_retry_call(self.method, params,
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 486, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 513, in _jsonrpc_call
    res = self.http.post("/jsonrpc/0",
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\sessions.py", line 569, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 210, in request
    self.__client._is_agent_alive():
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 586, in _is_agent_alive
    return bool(self._get_agent_version())
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 570, in _get_agent_version
    url = self.path2url("/version")
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 301, in path2url
    return urlparse.urljoin(self._get_atx_agent_url(), path)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 282, in _get_atx_agent_url
    lport = self._adb_device.forward_port(
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\adbutils\_device.py", line 248, in forward_port
    self.forward("tcp:" + str(local_port), remote)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\adbutils\_device.py", line 238, in forward
    self.open_transport(":".join(args))
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\adbutils\_device.py", line 89, in open_transport
    c.check_okay()
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\adbutils\_adb.py", line 134, in check_okay
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError
  File "C:\Users\Admin\PycharmProjects\tt_bot3\runner\main.py", line 45, in <module>
    run(arg1)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\runner\main.py", line 27, in run
    result = m.reg()
  File "C:\Users\Admin\PycharmProjects\tt_bot3\reg.py", line 771, in reg
    traceback.print_stack()
AdbError :

Почта отменена!
[W 230715 13:02:53 __init__:218] [pid:3356] atx-agent has something wrong, auto recovering
[I 230715 13:02:53 __init__:357] [pid:3356] [XXX] wait-for-device, time left(3.0s)
[I 230715 13:02:54 __init__:357] [pid:3356] [XXX] wait-for-device, time left(2.0s)
[I 230715 13:02:55 __init__:357] [pid:3356] [XXX] wait-for-device, time left(1.0s)
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Program Files (x86)\python3.9\lib\http\client.py", line 1371, in getresponse
    response.begin()
  File "D:\Program Files (x86)\python3.9\lib\http\client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "D:\Program Files (x86)\python3.9\lib\http\client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Program Files (x86)\python3.9\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\adapters.py", line 429, in send
    resp = conn.urlopen(
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 648, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Program Files (x86)\python3.9\lib\http\client.py", line 1371, in getresponse
    response.begin()
  File "D:\Program Files (x86)\python3.9\lib\http\client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "D:\Program Files (x86)\python3.9\lib\http\client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Program Files (x86)\python3.9\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 203, in request
    return super().request(method, url, **kwargs)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 119, in request
    resp = super(TimeoutRequestsSession,
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\sessions.py", line 522, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\sessions.py", line 642, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\adapters.py", line 489, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\tt_bot3\reg.py", line 750, in reg
    assert self._reg()
  File "C:\Users\Admin\PycharmProjects\tt_bot3\reg.py", line 703, in _reg
    self._click_next('email')
  File "C:\Users\Admin\PycharmProjects\tt_bot3\reg.py", line 363, in _click_next
    result = self._wait_for_loading(screen)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\reg.py", line 352, in _wait_for_loading
    if condition:
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\utils.py", line 105, in __bool__
    return self.__nonzero__()
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\utils.py", line 101, in __nonzero__
    return self.uiobject.jsonrpc.exist(self.uiobject.selector)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 479, in __call__
    return self.server._jsonrpc_retry_call(self.method, params,
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 486, in _jsonrpc_retry_call
    return self._jsonrpc_call(*args, **kwargs)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 513, in _jsonrpc_call
    res = self.http.post("/jsonrpc/0",
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\sessions.py", line 569, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 210, in request
    self.__client._is_agent_alive():
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 586, in _is_agent_alive
    return bool(self._get_agent_version())
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 570, in _get_agent_version
    url = self.path2url("/version")
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 301, in path2url
    return urlparse.urljoin(self._get_atx_agent_url(), path)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 282, in _get_atx_agent_url
    lport = self._adb_device.forward_port(
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\adbutils\_device.py", line 248, in forward_port
    self.forward("tcp:" + str(local_port), remote)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\adbutils\_device.py", line 238, in forward
    self.open_transport(":".join(args))
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\adbutils\_device.py", line 89, in open_transport
    c.check_okay()
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\adbutils\_adb.py", line 134, in check_okay
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\tt_bot3\runner\main.py", line 45, in <module>
    run(arg1)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\runner\main.py", line 27, in run
    result = m.reg()
  File "C:\Users\Admin\PycharmProjects\tt_bot3\reg.py", line 779, in reg
    self.insert_account(error=error)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\reg.py", line 585, in insert_account
    'language': self.d.shell('getprop persist.sys.locale').output.strip().split('-')[1],
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 432, in shell
    ret = self.http.post("/shell", data=data, timeout=timeout+10)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\requests\sessions.py", line 569, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 223, in request
    self.__client._prepare_atx_agent()
  File "C:\Users\Admin\PycharmProjects\tt_bot3\venv\lib\site-packages\uiautomator2\__init__.py", line 316, in _prepare_atx_agent
    raise RuntimeError("USB device %s is offline" % self._serial)
RuntimeError: USB device XXX is offline

P.S. Changed the serial number of the device

**Comment by af652030** [comment]
I think it's the ports. 
I have 5,000 ports open on the adb.exe process.

Can you tell me where the error might be?

**Comment by af652030** [comment]
Any Ideas why so many adb ports? 
![image](https://github.com/openatx/uiautomator2/assets/139620205/1a42181d-2523-42b6-81c0-1171bb94dfea)

Total 5200

**Comment by codeskyblue** [comment]
try the lastest uiautomator2 >= 3.2.0, close for now, reopen it if still exist
