### ISSUE TITLE
weditor problem

### ISSUE THREAD

**Issue by reloging** [openatx/uiautomator2#916]
As soon as I press dump I get an error:

[E 231011 21:20:24 web:1871] Uncaught exception GET /api/v2/devices/AndroidADB%3A1B19293410EA2MJY/hierarchy (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/api/v2/devices/AndroidADB%3A1B19293410EA2MJY/hierarchy', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\adm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tornado\web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\adm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\weditor\web\handlers\page.py", line 97, in get
        self.write(d.dump_hierarchy2())
                   ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\adm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\weditor\web\device.py", line 44, in dump_hierarchy2
        page_xml = self._d.dump_hierarchy()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\adm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\adbutils\_device.py", line 1152, in dump_hierarchy
        raise AdbError("uiautomator dump failed", output)
    adbutils.errors.AdbError: ('uiautomator dump failed', 'Killed')
[E 231011 21:20:24 web:2344] 500 GET /api/v2/devices/AndroidADB%3A1B19293410EA2MJY/hierarchy (::1) 498.03ms

**Comment by reloging** [comment]
reinstalled all possible components, what could be the problem?

**Comment by codeskyblue** [comment]
Please use https://uiauto.dev instead. thanks
