### ISSUE TITLE
Healthcheck Error

### ISSUE THREAD

**Issue by utiq** [openatx/uiautomator2#919]
When I run `uiautomator2 healthcheck` I get this error
```
[D 231021 06:17:59 __init__:661] [pid:8484] [localhost:5555] kill process(ps): uiautomator
[D 231021 06:18:02 __init__:392] [pid:8484] [localhost:5555] Install app-uiautomator.apk
[D 231021 06:18:04 __init__:392] [pid:8484] [localhost:5555] Install app-uiautomator-test.apk
[D 231021 06:18:06 __init__:682] [pid:8484] [localhost:5555] uiautomator-v2 is starting ... left: 40.0s
[D 231021 06:18:07 __init__:682] [pid:8484] [localhost:5555] uiautomator-v2 is starting ... left: 39.0s
[D 231021 06:18:08 __init__:682] [pid:8484] [localhost:5555] uiautomator-v2 is starting ... left: 37.9s
[D 231021 06:18:09 __init__:682] [pid:8484] [localhost:5555] uiautomator-v2 is starting ... left: 36.9s
[I 231021 06:18:10 __init__:626] [pid:8484] [localhost:5555] restart-uiautomator since "healthcheck"
[D 231021 06:18:10 __init__:661] [pid:8484] [localhost:5555] kill process(ps): uiautomator
[D 231021 06:18:13 __init__:392] [pid:8484] [localhost:5555] Install app-uiautomator.apk
[D 231021 06:18:14 __init__:392] [pid:8484] [localhost:5555] Install app-uiautomator-test.apk
[D 231021 06:18:16 __init__:738] [pid:8484] [localhost:5555] grant permissions
[D 231021 06:18:20 __init__:682] [pid:8484] [localhost:5555] uiautomator-v2 is starting ... left: 40.0s
[D 231021 06:18:21 __init__:682] [pid:8484] [localhost:5555] uiautomator-v2 is starting ... left: 39.0s
[D 231021 06:18:22 __init__:682] [pid:8484] [localhost:5555] uiautomator-v2 is starting ... left: 37.9s
[D 231021 06:18:23 __init__:682] [pid:8484] [localhost:5555] uiautomator-v2 is starting ... left: 36.9s
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/uiautomator2", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/uiautomator2/__main__.py", line 279, in main
    actions[args.subparser](args)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/uiautomator2/__main__.py", line 77, in cmd_healthcheck
    d.healthcheck()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/wrapt/wrappers.py", line 669, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/deprecated/classic.py", line 285, in wrapper_function
    return wrapped_(*args_, **kwargs_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/uiautomator2/__init__.py", line 1628, in healthcheck
    self.reset_uiautomator("healthcheck")
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/uiautomator2/__init__.py", line 651, in reset_uiautomator
    return self.reset_uiautomator(reason=reason,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/uiautomator2/__init__.py", line 651, in reset_uiautomator
    return self.reset_uiautomator(reason=reason,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/uiautomator2/__init__.py", line 618, in reset_uiautomator
    raise EnvironmentError(
OSError: [Errno Uiautomator started failed.] healthcheck: 'https://github.com/openatx/uiautomator2/wiki/Common-issues'
```

If I do `uiautomator2 doctor`, I get this

```
[D 231021 06:19:07 __main__:105] sdk:25 abi:arm64-v8a
CHECK atx-agent
[D 231021 06:19:07 init:295] Real version: [0, 10, 0], Expect version: [0, 10, 0]
[D 231021 06:19:07 init:359] Forward: local:tcp:47948 -> remote:tcp:7912
[D 231021 06:19:07 init:362] atx-agent version 0.10.0
[D 231021 06:19:07 init:365] device wlan ip: 192.168.4.100
	GOOD: atx-agent version 0.10.0
CHECK uiautomator-apks
[D 231021 06:19:07 init:256] apk-debug package-info: None
[D 231021 06:19:07 init:257] apk-debug-test package-info: None
	FAIL
[W 231021 06:19:07 __main__:120] apk is invalid
==> FAIL <==
```

**看完请删掉该内容**
*提Bug需要注意的事项*

请务必提供详细的信息，能够复现你的问题，否则很难帮你解决。没用的Issue将自动被机器人打上`Invalid`标签并且自动关闭！！。

- 手机型号
 Android 11
- uiautomator2的版本号(`pip show uiautomator2`)
2.16.14 I downgraded because the latest version was having the same problem
- 手机截图
- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)
- 最好能附上可能复现问题的代码。

**Comment by codeskyblue** [comment]
healthcheck removed on 3.x
