### ISSUE TITLE
执行print(d.info)提示adbutils.errors.AdbError: cannot bind listener: cannot bind to 127.0.0.1:60941: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 (10048)

### ISSUE THREAD

**Issue by NewFoolish** [openatx/uiautomator2#968]
已在Issues中检索，未见相同错误
**- 手机型号**
 三星Galaxy 22  

**android版本：**
 android 13

**- uiautomator2的版本号**
 Name: uiautomator2
**Version: 3.0.11**
Summary: uiautomator for android device
Home-page: https://github.com/openatx/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: /home/yangwang/.local/lib/python3.10/site-packages
Requires: adbutils, Deprecated, lxml, Pillow, requests, retry
Required-by:

**- 源码脚本如下（在wsl2下执行，Python版本 3.10.12）**
```python
#!/usr/bin/python

import uiautomator2 as u2

def test_simple():
    d = u2.connect('my-serial') # my phone’s device id
    print(d.info)

if __name__ == "__main__":
    test_simple()
```

**- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)**
Traceback (most recent call last):
  File "/mnt/e/workspace/Python/uitest/./uitest.py", line 12, in <module>
    test_simple()
  File "/mnt/e/workspace/Python/uitest/./uitest.py", line 8, in test_simple
    print(d.info)
  File "/home/yangwang/.local/lib/python3.10/site-packages/uiautomator2/__init__.py", line 1040, in info
    _info = super().info
  File "/home/yangwang/.local/lib/python3.10/site-packages/uiautomator2/__init__.py", line 139, in info
    return self.jsonrpc.deviceInfo(http_timeout=10)
  File "/home/yangwang/.local/lib/python3.10/site-packages/uiautomator2/__init__.py", line 179, in __call__
    return self.server.jsonrpc_call(self.method, params, http_timeout)
  File "/home/yangwang/.local/lib/python3.10/site-packages/uiautomator2/core.py", line 274, in jsonrpc_call
    return _jsonrpc_call(self._dev, method, params, timeout, self._debug)
  File "/home/yangwang/.local/lib/python3.10/site-packages/uiautomator2/core.py", line 122, in _jsonrpc_call
    r = _http_request(dev, "POST", "/jsonrpc/0", payload, timeout=timeout, print_request=print_request)
  File "/home/yangwang/.local/lib/python3.10/site-packages/uiautomator2/core.py", line 89, in _http_request
    lport = dev.forward_port(9008)
  File "/home/yangwang/.local/lib/python3.10/site-packages/adbutils/_device.py", line 262, in forward_port
    self.forward("tcp:" + str(local_port), remote)
  File "/home/yangwang/.local/lib/python3.10/site-packages/adbutils/_device.py", line 244, in forward
    c.check_okay() # this OKAY means message was received
  File "/home/yangwang/.local/lib/python3.10/site-packages/adbutils/_adb.py", line 147, in check_okay
    raise AdbError(self.read_string_block())
**adbutils.errors.AdbError: cannot bind listener: cannot bind to 127.0.0.1:60941: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 (10048)**

**Comment by codeskyblue** [comment]
可以稳定复现吗

**Comment by NewFoolish** [comment]
> 可以稳定复现吗

目前在我在wsl2下是可以稳定复现的

另外我在cmd端执行就是正常的（Python 3.11.1）
输出如下：
{'currentPackageName': 'com.tencent.mm', 'displayHeight': 2340, 'displayRotation': 0, 'displaySizeDpX': 411, 'displaySizeDpY': 891, 'displayWidth': 1080, 'productName': 'g0qzcx', 'screenOn': True, 'sdkInt': 34, 'naturalOrientation': True}

**Comment by NewFoolish** [comment]
> > 可以稳定复现吗
> 
> 目前在我在wsl2下是可以稳定复现的
> 
> 另外我在cmd端执行就是正常的（Python 3.11.1） 输出如下： {'currentPackageName': 'com.tencent.mm', 'displayHeight': 2340, 'displayRotation': 0, 'displaySizeDpX': 411, 'displaySizeDpY': 891, 'displayWidth': 1080, 'productName': 'g0qzcx', 'screenOn': True, 'sdkInt': 34, 'naturalOrientation': True}

我怀疑可能是adb环境的问题，在wsl2下我是通过软链接的形式使用windows下的adb环境。这个问题先关闭吧，目前在windows下是可正常执行的

**Comment by codeskyblue** [comment]
OK， 如何有新的发现可以在reopen一下

**Comment by tmmdh** [comment]
我在windows上调用uiautomator2.connect_usb遇到了同样的问题，报错信息如下，大概率复现，复现概率约60%

Traceback (most recent call last):
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\autotest\lockstatus.py", line 18, in <module>
    from automan import automan
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\autotest\automan.py", line 332, in <module>
    automan = AutoMan()
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\autotest\automan.py", line 42, in __init__
    self.devices = u2.connect_usb(android.devices.serial)
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\python3.10.0\lib\site-packages\uiautomator2\__init__.py", line 1119, in connect_usb
    return Device(serial)
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\python3.10.0\lib\site-packages\uiautomator2\__init__.py", line 69, in __init__
    BasicUiautomatorServer.__init__(self, self._dev)
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\python3.10.0\lib\site-packages\uiautomator2\core.py", line 170, in __init__
    self.start_uiautomator()
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\python3.10.0\lib\site-packages\uiautomator2\core.py", line 193, in start_uiautomator
    if not self._check_alive():
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\python3.10.0\lib\site-packages\uiautomator2\core.py", line 249, in _check_alive
    response = _http_request(self._dev, "GET", "/ping")
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\python3.10.0\lib\site-packages\uiautomator2\core.py", line 91, in _http_request
    lport = dev.forward_port(9008)
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\python3.10.0\lib\site-packages\adbutils\_device.py", line 252, in forward_port
    self.forward("tcp:" + str(local_port), remote)
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\python3.10.0\lib\site-packages\adbutils\_device.py", line 238, in forward
    self._client.forward(self._serial, local, remote, norebind)
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\python3.10.0\lib\site-packages\adbutils\_adb.py", line 365, in forward
    c.check_okay()
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\python3.10.0\lib\site-packages\adbutils\_adb.py", line 151, in check_okay
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError: cannot bind listener: cannot bind to 127.0.0.1:64718: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 (10048)
Exception ignored in: <function AutoMan.__del__ at 0x000001C1AB6DB9A0>
Traceback (most recent call last):
  File "D:\work\pycharm\PerformanceTools_v1.0\tools\autotest\automan.py", line 51, in __del__
    if self.devices:
AttributeError: 'AutoMan' object has no attribute 'devices'
请按任意键继续. .

uiautomator2版本信息如下
pip show uiautomator2
Name: uiautomator2
Version: 3.2.8
Summary: uiautomator for android device
Home-page: https://github.com/openatx/uiautomator2
Author: codeskyblue
Author-email: codeskyblue@gmail.com
License: MIT
Location: d:\python\python310\lib\site-packages
Requires: adbutils, lxml, Pillow, requests, retry
Required-by:


adb版本
Android Debug Bridge version 1.0.41
Version 29.0.6-6198805
Installed as D:\Tools\android-sdk-windows\platform-tools\adb.exe

安卓版本：
15.0

python版本：
3.10.0
