### ISSUE TITLE
d.clipboard报错

### ISSUE THREAD

**Issue by dongdongzld** [openatx/uiautomator2#995]
- 手机型号
MI6X   MIUI12.0.2
- uiautomator2的版本号(`pip show uiautomator2`)
3.1.0
- 手机截图
- 
- 相关日志(Python控制台错误信息, adb logcat完整信息, atxagent.log日志)
06/24/2024 17:25:03 main.py [func:collectData()] [line:147] ERROR Traceback (most recent call last):
  File "productRobot/main.py", line 144, in collectData
    collectProduct(d, filePath, productList, sheet, workbook)
  File "productRobot/main.py", line 228, in collectProduct
    goodsLink = d.clipboard
                ^^^^^^^^^^^
  File "productRobot/.venv/lib/python3.12/site-packages/uiautomator2/__init__.py", line 562, in clipboard
    return super().clipboard
           ^^^^^^^^^^^^^^^^^
  File "productRobot/.venv/lib/python3.12/site-packages/uiautomator2/_input.py", line 36, in clipboard
    return base64.b64decode(result.data).decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/base64.py", line 83, in b64decode
    s = _bytes_from_decode_data(s)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
- 最好能附上可能复现问题的代码。
d.set_input_ime(True)
print(d.clipboard)

不是所有的设备都有这个问题，有的设备有时有问题，有时候没有问题，很奇怪～

**Comment by dongdongzld** [comment]
先在一个输入框唤起输入法，再进到另一个界面去点复制，可必现此问题；如果没有别的界面获得过焦点，则可正常使用

**Comment by codeskyblue** [comment]
目前的剪贴板是通过输入法来监听的，你换成别的输入法，就获取不到剪贴板的内容了

**Comment by codeskyblue** [comment]
fixed in 3.2.0 现在监听剪贴板转移到了u2-service里面了
